-- KO-LESSON-004: Indonesian translations for published lessons
-- DO NOT execute directly; review and apply via Conductor.

UPDATE public.lessons
SET
    summary_id = 'Uang adalah alat yang membuat perdagangan, menabung, dan perencanaan jadi mungkin.',
    concept_body_id = 'Uang adalah apa saja yang umum diterima orang sebagai pembayaran barang dan jasa. Dalam kehidupan sehari-hari, uang punya tiga peran. Pertama, sebagai alat tukar: alih-alih menukar mie ayammu langsung dengan charger ponsel, kamu pakai rupiah. Kedua, sebagai penyimpan nilai: uang memungkinkanmu menabung hari ini dan berbelanja besok. Ketiga, sebagai satuan hitung: uang memberi harga pada semua barang sehingga kamu bisa membandingkan nilai dengan cepat.',
    why_this_matters_id = 'Kalau kamu tidak paham apa itu uang sebenarnya, setiap keputusan finansial terasa seperti sihir atau keberuntungan. Begitu kamu melihat uang sebagai alat, kamu bisa mulai menggunakannya dengan sengaja.',
    common_mistake_id = 'Berpikir uang hanya berupa uang tunai. Dompet digital, saldo bank, dan bahkan beberapa investasi juga termasuk bentuk uang karena bisa ditukar dengan barang dan jasa.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah yang merupakan contoh uang berfungsi sebagai alat tukar?", "options": ["Menyimpan emas di rumah", "Membayar mie ayam dengan rupiah", "Mencatat harga barang", "Meminjam uang ke bank"], "answer": "Membayar mie ayam dengan rupiah", "explanation": "Alat tukar berarti uang digunakan untuk membeli barang dan jasa."}, {"type": "true_false", "question": "Saldo GoPay dan OVO termasuk bentuk uang karena bisa digunakan untuk bertransaksi.", "answer": true, "explanation": "Uang tidak harus berbentuk kertas atau logam; saldo digital yang diterima sebagai pembayaran juga termasuk uang."}, {"type": "fill_blank", "question": "Fungsi uang yang memungkinkan kita membandingkan harga berbagai barang disebut ____.", "answer": "satuan hitung", "explanation": "Satuan hitung memberi nilai pada barang sehingga mudah dibandingkan."}]'::jsonb
WHERE id = '4b1fbc13-6d5a-42c4-8162-33f541e2ffb4'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Inflasi berarti jumlah uang yang sama bisa membeli lebih sedikit seiring waktu.',
    concept_body_id = 'Inflasi adalah kenaikan harga perlahan di seluruh ekonomi. Ketika inflasi 5%, semangkuk mie ayam Rp 10.000 bisa jadi Rp 10.500 tahun depan. Uangmu masih terlihat sama, tapi daya belinya mengecil. Inflasi biasanya disebabkan oleh terlalu banyak uang mengejar barang yang terlalu sedikit, biaya produksi naik, atau nilai tukar mata uang melemah.',
    why_this_matters_id = 'Inflasi adalah alasan mengapa menyimpan semua uang di celengan selama sepuluh tahun berisiko. Meski jumlahnya tidak berubah, barang yang bisa dibelinya berubah.',
    common_mistake_id = 'Berpikir inflasi berarti setiap harga naik dalam jumlah yang sama. Ada harga yang naik lebih cepat dari yang lain; inflasi adalah ukuran rata-rata.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang terjadi pada daya beli uang saat inflasi naik?", "options": ["Daya beli naik", "Daya beli turun", "Daya beli tetap", "Daya beli menjadi nol"], "answer": "Daya beli turun", "explanation": "Inflasi membuat harga naik, sehingga uang yang sama membeli lebih sedikit barang."}, {"type": "true_false", "question": "Inflasi berarti setiap harga naik dalam jumlah yang sama persis.", "answer": false, "explanation": "Inflasi adalah rata-rata kenaikan harga; beberapa barang naik lebih cepat dari yang lain."}, {"type": "fill_blank", "question": "Bank Indonesia menargetkan inflasi sekitar ____ persen per tahun.", "answer": "2,5", "explanation": "Target inflasi BI adalah sekitar 2,5% plus minus 1%."}]'::jsonb
WHERE id = '27385c2e-0485-49a4-9830-4bc5b37caf9b'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Bunga adalah harga menggunakan uang dari waktu ke waktu — baik yang kamu dapatkan maupun yang kamu bayar.',
    concept_body_id = 'Bunga punya dua sisi. Saat menabung, bank membayar kamu bunga karena meminjam uangmu. Saat berhutang, kamu membayar bunga karena memakai uang orang lain. Bunga sederhana dihitung hanya dari jumlah pokok. Bunga majemuk dihitung dari pokok ditambah bunga yang sudah ditambahkan sebelumnya, sehingga pertumbuhannya semakin cepat dari waktu ke waktu.',
    why_this_matters_id = 'Bunga menjelaskan mengapa utang bisa tumbuh cepat dan mengapa menabung lebih awal mengalahkan menabung nanti. Ini adalah salah satu konsep paling kuat dalam keuangan pribadi.',
    common_mistake_id = 'Mengabaikan bahwa bunga bekerja melawanmu saat berhutang. Biaya kartu kredit 2% per bulan terdengar kecil, tapi kalau majemuk bisa jauh lebih besar dari 24% per tahun.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Apa perbedaan bunga sederhana dan bunga majemuk?", "options": ["Bunga sederhana dihitung dari pokok saja; bunga majemuk dihitung dari pokok ditambah bunga sebelumnya", "Bunga sederhana selalu lebih besar", "Bunga majemuk hanya untuk utang", "Tidak ada perbedaan"], "answer": "Bunga sederhana dihitung dari pokok saja; bunga majemuk dihitung dari pokok ditambah bunga sebelumnya", "explanation": "Bunga majemuk menghasilkan bunga dari bunga sebelumnya, sehingga pertumbuhannya semakin cepat."}, {"type": "true_false", "question": "Bunga selalu menguntungkan karena membuat uang tumbuh.", "answer": false, "explanation": "Bunga menguntungkan saat menabung, tapi merugikan saat berhutang."}, {"type": "fill_blank", "question": "Bunga adalah harga menggunakan ____ dari waktu ke waktu.", "answer": "uang", "explanation": "Bunga adalah biaya atau imbalan atas penggunaan uang dalam periode tertentu."}]'::jsonb
WHERE id = '7c4e8674-b299-44ec-bd0a-97902cb0191e'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Pendapatan adalah uang yang masuk. Kekayaan adalah uang yang tersisa dan tumbuh.',
    concept_body_id = 'Pendapatan adalah apa yang kamu dapatkan dari gaji, uang saku, kerja lepas, atau bisnis. Kekayaan adalah apa yang kamu miliki dikurangi apa yang kamu hutang. Seseorang bisa pendapatannya tinggi tapi kekayaannya rendah jika menghabiskan semuanya. Seseorang bisa pendapatannya sederhana tapi kekayaannya tumbuh jika rajin menabung dan berinvestasi.',
    why_this_matters_id = 'Banyak anak muda bermimpi gaji tinggi, tetapi kekayaan yang menciptakan kebebasan nyata. Kamu tidak bisa pensiun dari pendapatan saja; kamu butuh kekayaan yang terakumulasi.',
    common_mistake_id = 'Menilai kesuksesan hanya dari penghasilan bulanan. Gaya hidup mencolok yang dibiayai utang justru kebalikan dari kekayaan.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah pernyataan yang benar tentang pendapatan dan kekayaan?", "options": ["Pendapatan tinggi selalu berarti kekayaan tinggi", "Kekayaan dihitung dari aset dikurangi utang", "Kekayaan hanya untuk orang kaya", "Pendapatan dan kekayaan adalah hal yang sama"], "answer": "Kekayaan dihitung dari aset dikurangi utang", "explanation": "Kekayaan adalah stok kepemilikan bersih, bukan hanya aliran masuk bulanan."}, {"type": "true_false", "question": "Seseorang dengan gaji kecil bisa memiliki kekayaan lebih besar dari orang bergaji tinggi jika dia rajin menabung.", "answer": true, "explanation": "Kekayaan tergantung seberapa banyak yang disimpan dan tumbuh, bukan hanya berapa yang dihasilkan."}, {"type": "fill_blank", "question": "Pendapatan adalah uang yang ____; kekayaan adalah uang yang tersisa dan tumbuh.", "answer": "masuk", "explanation": "Pendapatan adalah aliran masuk, sedangkan kekayaan adalah akumulasi bersih dari waktu ke waktu."}]'::jsonb
WHERE id = 'dc40a9ae-8a7d-4558-bac4-b11f4903d125'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Aset memasukkan uang ke kantongmu. Liabilitas mengeluarkan uang dari kantongmu.',
    concept_body_id = 'Aset adalah sesuatu yang memiliki atau menghasilkan nilai: tabungan, investasi, keterampilan produktif, atau bahkan motor yang membantumu mencari nafkah. Liabilitas adalah sesuatu yang menghabiskan uangmu: utang, barang mewah yang dibeli kredit, atau langganan yang tidak kamu pakai. Barang yang sama bisa jadi aset atau liabilitas tergantung cara kamu menggunakannya.',
    why_this_matters_id = 'Perbedaan ini adalah fondasi anggaran dan berinvestasi. Sebelum membeli sesuatu, tanyakan: barang ini akan membuatku menghasilkan uang atau mengeluarkan uang dari waktu ke waktu?',
    common_mistake_id = 'Secara otomatis menyebut rumah utama atau mobil sebagai aset. Jika barang itu menghabiskan lebih banyak uang daripada yang dihasilkannya, ia berperilaku seperti liabilitas di neraca keuangan pribadimu.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Sebelum membeli barang mahal, pertanyaan apa yang membantumu membedakan aset dan liabilitas?", "options": ["Apakah ini lagi tren di media sosial?", "Barang ini akan membuatku menghasilkan atau mengeluarkan uang dari waktu ke waktu?", "Apakah warnanya favoritku?", "Apakah temanku sudah membelinya?"], "answer": "Barang ini akan membuatku menghasilkan atau mengeluarkan uang dari waktu ke waktu?", "explanation": "Aset memasukkan uang atau menambah nilai; liabilitas mengeluarkan uang."}, {"type": "true_false", "question": "Barang yang sama bisa menjadi aset untuk satu orang dan liabilitas untuk orang lain.", "answer": true, "explanation": "Penggunaan menentukan apakah barang menghasilkan atau menghabiskan uang."}, {"type": "fill_blank", "question": "Aset adalah sesuatu yang memasukkan uang ke kantong; liabilitas mengeluarkan uang dari ____.", "answer": "kantong", "explanation": "Aset menghasilkan nilai, sementara liabilitas menghabiskan uang."}]'::jsonb
WHERE id = 'a3931a80-6ba5-4da6-8755-fe43b904f587'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Risiko adalah kemungkinan sesuatu yang buruk terjadi pada uangmu.',
    concept_body_id = 'Risiko adalah kemungkinan kehilangan uang atau mendapatkan return lebih rendah dari yang diharapkan. Setiap pilihan finansial punya risiko. Menyimpan uang tunai di bawah kasur berisiko dicuri dan tergerus inflasi. Menaruh uang di deposito berisiko return rendah. Berinvestasi di saham berisiko harga turun. Tidak ada pilihan yang bebas risiko; yang ada hanya risiko yang berbeda jenis.',
    why_this_matters_id = 'Memahami risiko menghentikanmu dari mengejar investasi ''aman'' yang tidak ada. Risiko juga membantumu memilih risiko yang masih bisa kamu terima.',
    common_mistake_id = 'Berpikir risiko hanya berarti kehilangan semuanya. Risiko juga mencakup kehilangan daya beli, melewatkan peluang, atau tidak bisa mengakses uang saat dibutuhkan.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah pernyataan yang benar tentang risiko finansial?", "options": ["Semua risiko bisa dihilangkan sepenuhnya", "Return tinggi biasanya berarti risiko tinggi", "Risiko hanya ada di pasar saham", "Menyimpan uang tunai tidak punya risiko"], "answer": "Return tinggi biasanya berarti risiko tinggi", "explanation": "Risiko dan return biasanya terkait; return tinggi umumnya datang dengan risiko lebih besar."}, {"type": "true_false", "question": "Menyimpan semua uang tunai di bawah kasur sepenuhnya bebas risiko.", "answer": false, "explanation": "Uang tunai menghadapi risiko pencurian dan inflasi yang menggerus daya beli."}, {"type": "fill_blank", "question": "Risiko adalah kemungkinan hasil yang lebih buruk dari yang ____.", "answer": "diharapkan", "explanation": "Risiko berarti hasil aktual bisa lebih buruk dari ekspektasi kita."}]'::jsonb
WHERE id = '56cea7b7-aeca-45f4-bc43-faa571967b35'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Return adalah keuntungan atau kerugian yang kamu dapat dari tabungan atau investasi.',
    concept_body_id = 'Return adalah uang yang kamu hasilkan atau hilangkan dari uangmu. Jika kamu menaruh Rp 1.000.000 ke sesuatu dan kemudian nilainya Rp 1.100.000, returnmu Rp 100.000 atau 10%. Return bisa berasal dari bunga, dividen, kenaikan harga, atau keuntungan bisnis. Potensi return yang lebih tinggi biasanya datang dengan risiko yang lebih tinggi.',
    why_this_matters_id = 'Return adalah apa yang mengubah menabung menjadi berinvestasi. Tanpa memahami return, kamu tidak bisa membandingkan deposito, obligasi, dan saham.',
    common_mistake_id = 'Mengharapkan return tinggi tanpa risiko. Jika seseorang menjanjikan return tinggi dan risiko rendah, itu biasanya penipuan.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang dimaksud dengan return dalam keuangan?", "options": ["Jumlah uang yang diinvestasikan", "Keuntungan atau kerugian dari uang yang diinvestasikan", "Jenis rekening bank", "Pengembalian pajak dari pemerintah"], "answer": "Keuntungan atau kerugian dari uang yang diinvestasikan", "explanation": "Return mengukur seberapa banyak uang bertambah atau berkurang relatif terhadap modal."}, {"type": "true_false", "question": "Janji return tinggi, terjamin, dan tanpa risiko adalah sinyal investasi yang aman.", "answer": false, "explanation": "Kombinasi return tinggi, terjamin, dan tanpa risiko adalah tanda klasik penipuan."}, {"type": "fill_blank", "question": "Jika kamu menginvestasikan Rp 1.000.000 dan nilainya menjadi Rp 1.100.000, returnmu adalah ____ persen.", "answer": "10", "explanation": "Keuntungan Rp 100.000 dari Rp 1.000.000 berarti return 10%."}]'::jsonb
WHERE id = 'b4837816-751f-43fe-bd64-e048c80956f7'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Menabung melindungi uang sekarang. Berinvestasi menumbuhkan uang untuk nanti.',
    concept_body_id = 'Menabung adalah menyimpan uang di tempat aman agar bisa segera dipakai. Berinvestasi adalah menaruh uang ke sesuatu yang nilainya bisa tumbuh dalam jangka lebih panjang. Menabung untuk dana darurat dan tujuan jangka pendek. Berinvestasi untuk tujuan bertahun-tahun, seperti pendidikan, bisnis, atau pensiun. Kamu butuh keduanya.',
    why_this_matters_id = 'Banyak pemula mengira harus memilih antara menabung dan berinvestasi. Pada kenyataannya, kamu menabung dulu untuk stabilitas, lalu berinvestasi dengan uang yang tidak akan segera dibutuhkan.',
    common_mistake_id = 'Berinvestasi dengan uang yang mungkin dibutuhkan bulan depan. Investasi bisa turun jangka pendek; tabungan seharusnya tidak.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Tujuan mana yang paling cocok untuk berinvestasi daripada menabung?", "options": ["Dana darurat", "Belanja bulanan", "Pensiun dalam 20 tahun", "Perbaikan motor mendesak"], "answer": "Pensiun dalam 20 tahun", "explanation": "Investasi untuk tujuan jangka panjang; menabung untuk kebutuhan jangka pendek dan darurat."}, {"type": "true_false", "question": "Kamu harus memiliki dana darurat sebelum mulai berinvestasi.", "answer": true, "explanation": "Dana darurat memberi stabilitas sebelum kamu menanggung risiko investasi jangka panjang."}, {"type": "fill_blank", "question": "Menabung melindungi uang ____; berinvestasi menumbuhkannya untuk nanti.", "answer": "sekarang", "explanation": "Tabungan untuk kebutuhan dekat dan darurat; investasi untuk pertumbuhan jangka panjang."}]'::jsonb
WHERE id = '2d4141af-7b5e-4390-9ac8-1644810351ed'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Dana darurat adalah uang yang disimpan aman untuk masalah tak terduga.',
    concept_body_id = 'Dana darurat adalah uang tunai yang bisa diakses cepat ketika hidup memberi kejutan: ponsel rusak, tagihan medis, kehilangan pekerjaan, atau kebutuhan keluarga. Target umum adalah 3–6 bulan pengeluaran penting, tapi bahkan Rp 1.000.000 lebih baik daripada tidak ada. Dana ini harus aman, mudah diambil, dan terpisah dari uang belanja harian.',
    why_this_matters_id = 'Dana darurat adalah jaring pengaman finansial pertama. Dana ini mengubah krisis menjadi ketidaknyamanan.',
    common_mistake_id = 'Menyimpan dana darurat di investasi berisiko. Jika investasi turun saat uang dibutuhkan, dana itu gagal menjalankan fungsinya.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Dana darurat sebaiknya digunakan untuk ...", "options": ["Membeli ponsel terbaru", "Kebutuhan tak terduga seperti perbaikan motor atau tagihan medis", "Investasi di saham", "Liburan mendadak"], "answer": "Kebutuhan tak terduga seperti perbaikan motor atau tagihan medis", "explanation": "Dana darurat untuk kebutuhan mendesak, bukan keinginan atau investasi."}, {"type": "true_false", "question": "Dana darurat sebaiknya disimpan di instrumen yang mudah diakses dan aman.", "answer": true, "explanation": "Dana darurat harus cepat diambil dan tidak berisiko turun nilainya saat dibutuhkan."}, {"type": "fill_blank", "question": "Target umum dana darurat adalah ____ hingga enam bulan pengeluaran penting.", "answer": "tiga", "explanation": "Dana darurat yang umum disarankan mencakup 3–6 bulan pengeluaran esensial."}]'::jsonb
WHERE id = '3a9943bd-08ff-4af5-8d58-6102f4d3b560'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Kebutuhan adalah hal esensial. Keinginan adalah hal yang menyenangkan tapi bisa ditunda.',
    concept_body_id = 'Kebutuhan adalah sesuatu yang harus kamu miliki untuk hidup dan berfungsi: makanan, tempat tinggal, pakaian dasar, transportasi ke sekolah atau kerja. Keinginan adalah sesuatu yang kamu sukai tapi bisa hidup tanpanya: ponsel terbaru, sepatu branded, streaming premium, atau boba tambahan. Garisnya bersifat pribadi, tapi jujur tentang perbedaannya adalah langkah pertama membuat anggaran.',
    why_this_matters_id = 'Setiap pertarungan anggaran sebenarnya adalah keputusan kebutuhan vs keinginan. Menguasai istilah ini memberimu kendali atas pengeluaranmu.',
    common_mistake_id = 'Membiarkan iklan memutuskan apa yang kamu butuhkan. Pemasaran berusaha mengubah keinginan menjadi kebutuhan; hanya kamu yang bisa menarik garis sendiri.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah yang termasuk kebutuhan dibandingkan keinginan?", "options": ["Ponsel flagship terbaru", "Makan siang harian", "Tiket konser", "Sepatu branded"], "answer": "Makan siang harian", "explanation": "Makanan untuk bertahan hidup dan berfungsi adalah kebutuhan, bukan keinginan."}, {"type": "true_false", "question": "Keinginan selalu buruk dan harus dihindari sepenuhnya.", "answer": false, "explanation": "Keinginan tidak selalu buruk; yang penting adalah membedakannya dari kebutuhan dan mengatur anggaran."}, {"type": "fill_blank", "question": "Kebutuhan adalah hal yang harus dimiliki untuk hidup dan berfungsi; keinginan adalah hal yang ____ tapi bisa ditunda.", "answer": "menyenangkan", "explanation": "Keinginan membuat hidup lebih nyaman, tapi tidak harus dipenuhi segera."}]'::jsonb
WHERE id = '03d3f2be-5d3c-43c2-96fd-47915765fe11'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Utang adalah uang yang kamu pinjam dan harus dikembalikan, biasanya dengan biaya tambahan.',
    concept_body_id = 'Utang terjadi ketika kamu meminjam uang dan berjanji mengembalikannya nanti. Pemberi pinjaman biasanya mengenakan bunga atau biaya untuk pinjamannya. Beberapa utang bisa berguna, seperti pinjaman pendidikan yang meningkatkan daya jual kerjamu. Beberapa utang berbahaya, seperti pay-later untuk barang yang cepat turun nilainya. Pertanyaan kuncinya: berapa suku bunganya, bisakah kamu membayar cicilannya, dan apakah utang itu membantumu menghasilkan lebih banyak atau hanya untuk konsumsi?',
    why_this_matters_id = 'Utang tidak selalu buruk, tapi selalu punya biaya. Memahami bunga dan tujuan membantumu menghindari jebakan utang.',
    common_mistake_id = 'Berpikir pembayaran minimum membuat utang terjangkau. Pembayaran minimum memanjangkan utang dan menggandakan total bunga.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang membuat utang konsumen menjadi jebakan?", "options": ["Bunga atau denda yang tumbuh lebih cepat dari pendapatan", "Utang selalu diberikan tanpa bunga", "Utang hanya untuk orang dewasa", "Utang otomatis hilang setelah setahun"], "answer": "Bunga atau denda yang tumbuh lebih cepat dari pendapatan", "explanation": "Utang menjadi jebakan ketika biayanya bertambah lebih cepat dari kemampuan membayar."}, {"type": "true_false", "question": "Membayar hanya minimum dari utang kartu kredit membuat total bunga menjadi lebih kecil.", "answer": false, "explanation": "Pembayaran minimum memanjangkan utang dan meningkatkan total bunga yang dibayar."}, {"type": "fill_blank", "question": "Utang adalah uang yang dipinjam dan harus ____ nanti, biasanya dengan biaya tambahan.", "answer": "dikembalikan", "explanation": "Peminjam berjanji mengembalikan pokok ditambah bunga atau biaya."}]'::jsonb
WHERE id = 'ef7550a9-2ae9-4820-83bc-3f79f9308dec'::uuid;

UPDATE public.lessons
SET
    summary_id = 'Jika terdengar terlalu bagus untuk jadi kenyataan, biasanya memang begitu.',
    concept_body_id = 'Penipuan sering menjanjikan return tinggi terjamin dengan risiko kecil atau nol, menekanmu untuk cepat memutuskan, memintamu mengajak teman, atau berpura-pura dari lembaga pemerintah atau perusahaan terkenal. Investasi nyata tidak bisa menjanjikan return tetap tinggi karena pasar bergerak. Regulator nyata tidak akan pernah meminta password atau OTP-mu.',
    why_this_matters_id = 'Kesadaran penipuan melindungi uang dan teman-temanmu. Sebagian besar kerugian finansial di kalangan anak muda Indonesia berasal dari skema yang terlihat jelas setelah kejadian.',
    common_mistake_id = 'Berpikir kamu terlalu pintar untuk ditipu. Penipu menyesuaikan diri untuk menipu orang berpendidikan juga; pertahanannya adalah memeriksa izin dan melambat.',
    quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah yang merupakan tanda penipuan investasi?", "options": ["Return tinggi terjamin tanpa risiko", "Produk terdaftar di OJK", "Informasi lengkap tentang risiko", "Bisa menarik uang kapan saja"], "answer": "Return tinggi terjamin tanpa risiko", "explanation": "Return tinggi terjamin adalah tanda klasik penipuan investasi."}, {"type": "true_false", "question": "Regulator seperti OJK boleh meminta password atau OTP-mu untuk verifikasi.", "answer": false, "explanation": "Regulator dan bank resmi tidak akan meminta password atau OTP."}, {"type": "fill_blank", "question": "Jika sesuatu terdengar terlalu bagus untuk jadi kenyataan, biasanya memang ____.", "answer": "begitu", "explanation": "Janji yang terlalu muluk adalah salah satu tanda utama penipuan."}]'::jsonb
WHERE id = '1e4ffcbe-1980-4704-ae01-0f7097e3622f'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa arti ''bayar diri sendiri dulu''?", "options": ["Belanja dulu, sisanya ditabung", "Transfer uang ke tabungan sebelum membelanjakan uang lainnya", "Membayar utang setelah berbelanja", "Meminta gaji lebih awal"], "answer": "Transfer uang ke tabungan sebelum membelanjakan uang lainnya", "explanation": "Bayar diri sendiri dulu berarti menyisihkan tabungan begitu gaji atau uang masuk, bukan menunggu sisa."}, {"type": "true_false", "question": "Menabung di akhir bulan setelah berbelanja biasanya lebih efektif daripada menabung di awal.", "answer": false, "explanation": "Di akhir bulan sering tidak ada sisa karena pengeluaran sudah habis duluan."}, {"type": "fill_blank", "question": "Cara paling mudah menerapkan bayar diri sendiri dulu adalah mengatur transfer ____ ke tabungan.", "answer": "otomatis", "explanation": "Transfer otomatis memastikan tabungan terpisah sebelum uang bisa dibelanjakan."}]'::jsonb
WHERE id = '4459f7da-6806-42f6-8f4e-e08a64572013'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah yang termasuk jebakan pengeluaran?", "options": ["Membuat anggaran harian", "Flash sale dengan timer membuatmu membeli barang yang tidak direncanakan", "Menabung di awal bulan", "Mencatat pengeluaran"], "answer": "Flash sale dengan timer membuatmu membeli barang yang tidak direncanakan", "explanation": "Flash sale menciptakan urgensi palsu yang mendorong pembelian impulsif."}, {"type": "true_false", "question": "Belanja kecil harian seperti kopi atau snack tidak berpengaruh besar pada anggaran.", "answer": false, "explanation": "Pengeluaran kecil yang sering dilakukan bisa menumpuk dan memakan anggaran besar."}, {"type": "fill_blank", "question": "Trik seperti countdown timer dan stok terbatas memanfaatkan rasa ____ untuk mendorong pembelian.", "answer": "terburu-buru", "explanation": "Penjual sering memakai urgensi palsu agar konsumen membeli tanpa berpikir panjang."}]'::jsonb
WHERE id = '52996b7e-6991-48c6-80c9-a77f063ffb58'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa PayLater, pinjol, dan kartu kredit bisa menjadi jebakan?", "options": ["Mereka selalu gratis", "Bunga atau denda bisa tumbuh lebih cepat dari pendapatan", "Tidak bisa dipakai untuk belanja online", "Hanya tersedia untuk orang tua"], "answer": "Bunga atau denda bisa tumbuh lebih cepat dari pendapatan", "explanation": "Kemudahan berutang menyembunyikan biaya tinggi yang bisa melarutkan keuangan."}, {"type": "true_false", "question": "Pinjol dengan bunga tinggi aman asalkan pembayaran pertama dilakukan tepat waktu.", "answer": false, "explanation": "Bunga tinggi tetap membebani, bahkan jika pembayaran awal tepat waktu."}, {"type": "fill_blank", "question": "Utang menjadi jebakan ketika biaya bunga atau denda tumbuh lebih ____ daripada pendapatan.", "answer": "cepat", "explanation": "Jika biaya utang melampaui kemampuan bayar, utang akan semakin membesar."}]'::jsonb
WHERE id = '28a29281-a749-4779-bc3d-86709daaf05e'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang membuat tujuan keuangan menjadi baik?", "options": ["Sifatnya abstrak dan tidak punya batas waktu", "Spesifik, punya jumlah target, dan punya tenggat waktu", "Hanya berupa keinginan saja", "Tidak perlu ditulis"], "answer": "Spesifik, punya jumlah target, dan punya tenggat waktu", "explanation": "Tujuan yang jelas lebih mudah diukur dan dicapai."}, {"type": "true_false", "question": "Menabung tanpa target jumlah dan waktu biasanya lebih efektif daripada menabung dengan tujuan jelas.", "answer": false, "explanation": "Tanpa target, motivasi dan ukuran keberhasilan menjadi kabur."}, {"type": "fill_blank", "question": "Contoh tujuan keuangan yang baik: menabung Rp 5.000.000 untuk laptop pada ____.", "answer": "Desember", "explanation": "Tujuan yang baik memiliki jumlah dan tenggat waktu yang jelas."}]'::jsonb
WHERE id = '045ca6a9-1c3b-4827-8891-9e4aab0b483b'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa janji return tinggi terjamin tanpa risiko mencurigakan?", "options": ["Karena semua investasi pasti aman", "Karena return dan risiko biasanya terkait", "Karena OJK melarang semua investasi", "Karena bank selalu menjanjikan return tinggi"], "answer": "Karena return dan risiko biasanya terkait", "explanation": "Investasi nyata tidak bisa menjanjikan return tinggi tanpa risiko."}, {"type": "true_false", "question": "Tekanan untuk segera memutuskan dan mengajak teman adalah tanda investasi yang sah.", "answer": false, "explanation": "Tekanan dan sistem ajak-teman adalah tanda umum penipuan."}, {"type": "fill_blank", "question": "Kalau terdengar terlalu bagus untuk jadi kenyataan, kemungkinan itu adalah ____.", "answer": "penipuan", "explanation": "Janji muluk adalah tanda klasik skema tidak jujur."}]'::jsonb
WHERE id = 'f1c2b35a-e186-4096-8ac2-ebe55791cc04'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa penting memeriksa izin OJK sebelum berinvestasi?", "options": ["Agar return lebih tinggi", "Produk berizin lebih aman dan dilindungi; produk tidak berizin ilegal", "OJK menjamin keuntungan", "Karena semua produk tanpa izin pasti menguntungkan"], "answer": "Produk berizin lebih aman dan dilindungi; produk tidak berizin ilegal", "explanation": "OJK mengawasi produk keuangan berizin; produk di luar daftar tidak memiliki perlindungan."}, {"type": "true_false", "question": "Jika produk tidak terdaftar di situs OJK, uangmu masih tetap aman karena perusahaan pasti jujur.", "answer": false, "explanation": "Produk tidak berizin tidak punya perlindungan jika terjadi masalah."}, {"type": "fill_blank", "question": "OJK adalah singkatan dari Otoritas ____ Keuangan.", "answer": "Jasa", "explanation": "OJK mengawasi lembaga jasa keuangan di Indonesia."}]'::jsonb
WHERE id = 'c2349ee3-966a-4bb5-92ad-6aa7e604d2a3'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa tujuan utama serangan phishing?", "options": ["Memberikan hadiah gratis", "Mencuri data pribadi, password, atau OTP", "Meningkatkan literasi keuangan", "Menawarkan pekerjaan"], "answer": "Mencuri data pribadi, password, atau OTP", "explanation": "Phishing memaksa atau menipu korban agar memberikan informasi sensitif."}, {"type": "true_false", "question": "Bank resmi akan meminta OTP-mu melalui telepon atau chat untuk keamanan akun.", "answer": false, "explanation": "Bank dan regulator resmi tidak meminta password atau OTP."}, {"type": "fill_blank", "question": "Social engineering memanipulasi orang secara ____ untuk mendapatkan informasi atau uang.", "answer": "emosional", "explanation": "Penipu sering memanfaatkan rasa takut, terburu-buru, atau percaya untuk menipu korban."}]'::jsonb
WHERE id = '1f322f3d-4cdd-4d12-95b9-2b69a0c0a5b1'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa perbedaan utama bisnis MLM sah dan skema piramida?", "options": ["MLM sah menghasilkan uang dari penjualan produk; piramida dari perekrutan", "Tidak ada perbedaan", "Piramida selalu legal", "MLM sah tidak menjual produk"], "answer": "MLM sah menghasilkan uang dari penjualan produk; piramida dari perekrutan", "explanation": "Fokus pada perekrutan daripada penjualan produk adalah tanda piramida."}, {"type": "true_false", "question": "Skema piramida bisa bertahan selamanya selama terus ada anggota baru.", "answer": false, "explanation": "Piramida akan runtuh ketika perekrutan melambat karena tidak cukup orang baru."}, {"type": "fill_blank", "question": "Bisnis sah menghasilkan uang dari ____ nyata, bukan hanya dari biaya perekrutan.", "answer": "pelanggan", "explanation": "Jika penghasilan utama berasal dari perekrutan, itu bukan bisnis nyata."}]'::jsonb
WHERE id = 'd457210e-a32b-4f0a-93ad-3deb39ba7d09'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa bunga majemuk bisa tumbuh lebih cepat dari bunga sederhana?", "options": ["Karena menghitung bunga dari bunga sebelumnya", "Karena tidak ada risiko", "Karena bank menambahkan uang gratis", "Karena pajak lebih kecil"], "answer": "Karena menghitung bunga dari bunga sebelumnya", "explanation": "Bunga majemuk menghasilkan bunga dari pokok dan bunga yang sudah terkumpul."}, {"type": "true_false", "question": "Dua faktor paling penting dalam bunga majemuk adalah waktu dan suku bunga.", "answer": true, "explanation": "Semakin lama waktu dan semakin tinggi suku bunga, efek salju bunga majemuk semakin besar."}, {"type": "fill_blank", "question": "Bunga majemuk menciptakan efek ____ yang membuat uang tumbuh semakin cepat dari waktu ke waktu.", "answer": "salju", "explanation": "Seperti bola salju, bunga majemuk semakin membesar seiring berjalannya waktu."}]'::jsonb
WHERE id = '3f4ca16e-72f4-455c-bdcd-3182ba3167a8'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Kapan uang sebaiknya disimpan di bank daripada diinvestasikan?", "options": ["Untuk dana darurat dan kebutuhan jangka pendek", "Untuk tujuan pensiun 30 tahun lagi", "Saat ingin return setinggi mungkin", "Saat tidak peduli dengan keamanan"], "answer": "Untuk dana darurat dan kebutuhan jangka pendek", "explanation": "Bank cocok untuk uang yang harus aman dan mudah diakses."}, {"type": "true_false", "question": "Investasi selalu lebih baik daripada menyimpan uang di bank.", "answer": false, "explanation": "Investasi punya risiko dan cocok untuk uang jangka panjang, bukan semua kebutuhan."}, {"type": "fill_blank", "question": "Bank melindungi uang jangka pendek; investasi berpotensi menumbuhkan uang ____.", "answer": "jangka panjang", "explanation": "Investasi untuk tujuan yang masih jauh, dengan risiko yang bisa ditoleransi."}]'::jsonb
WHERE id = '33adafb3-57ed-44db-b4c9-4f9bf0d39f72'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa hubungan umum antara risiko dan return?", "options": ["Return tinggi selalu tanpa risiko", "Potensi return tinggi biasanya berarti risiko tinggi", "Risiko tinggi selalu menghasilkan return tinggi", "Tidak ada hubungan"], "answer": "Potensi return tinggi biasanya berarti risiko tinggi", "explanation": "Risiko dan return berjalan berdampingan; tidak ada makan siang gratis."}, {"type": "true_false", "question": "Tidak ada cara aman untuk mendapatkan return besar dengan cepat.", "answer": true, "explanation": "Return besar dengan cepat selalu disertai risiko besar atau kemungkinan penipuan."}, {"type": "fill_blank", "question": "Trade-off antara risiko dan return berarti kamu tidak bisa mendapatkan return tinggi tanpa menerima ____ lebih tinggi.", "answer": "risiko", "explanation": "Return dan risiko biasanya saling terkait."}]'::jsonb
WHERE id = 'e81a8f71-77ab-44ca-b48f-a0e985313e33'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa diversifikasi penting?", "options": ["Menjamin return tertinggi", "Mengurangi dampak jika satu investasi turun", "Menghilangkan semua risiko", "Memusatkan semua uang di satu saham"], "answer": "Mengurangi dampak jika satu investasi turun", "explanation": "Diversifikasi menyebarkan risiko sehingga kerugian satu aset tidak menghancurkan semuanya."}, {"type": "true_false", "question": "Menaruh semua uang di satu saham adalah contoh diversifikasi yang baik.", "answer": false, "explanation": "Diversifikasi berarti menyebarkan investasi, bukan memusatkannya."}, {"type": "fill_blank", "question": "Diversifikasi berarti tidak menaruh semua telur dalam satu ____.", "answer": "keranjang", "explanation": "Peribahasa ini menggambarkan pentingnya menyebarkan risiko."}]'::jsonb
WHERE id = '4666fa33-6865-43ae-824e-dd0d9a5d1ac2'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa itu reksa dana?", "options": ["Pinjaman dari bank", "Dana yang dipool dari banyak investor dan dikelola manajer investasi", "Tabungan dengan bunga tetap", "Asuransi jiwa"], "answer": "Dana yang dipool dari banyak investor dan dikelola manajer investasi", "explanation": "Reksa dana mengumpulkan uang banyak orang untuk diinvestasikan secara kolektif."}, {"type": "true_false", "question": "Semua reksa dana memiliki risiko dan return yang sama.", "answer": false, "explanation": "Jenis reksa dana berbeda-beda, mulai dari pasar uang yang relatif aman hingga saham yang lebih berisiko."}, {"type": "fill_blank", "question": "Reksa dana memungkinkan investor kecil memiliki ____ portofolio yang dikelola profesional.", "answer": "bagian", "explanation": "Dengan reksa dana, kamu membeli unit yang mewakili bagian dari portofolio besar."}]'::jsonb
WHERE id = '517b8905-e5a3-40ac-b1c8-ab00bace435a'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang dimaksud dengan saham?", "options": ["Pinjaman kepada perusahaan", "Bagian kepemilikan dalam perusahaan", "Tabungan di bank", "Polis asuransi"], "answer": "Bagian kepemilikan dalam perusahaan", "explanation": "Membeli saham berarti memiliki sebagian kecil dari perusahaan tersebut."}, {"type": "true_false", "question": "Membeli saham berarti kamu menjadi salah satu pemilik perusahaan, meski bagiannya kecil.", "answer": true, "explanation": "Saham mewakili kepemilikan, sehingga pemegang saham berbagi risiko dan potensi keuntungan."}, {"type": "fill_blank", "question": "Saham memberi potensi keuntungan, tetapi juga berisiko ____ jika perusahaan performanya buruk.", "answer": "rugi", "explanation": "Sebagai pemilik, kamu bisa untung atau rugi tergantung kinerja perusahaan."}]'::jsonb
WHERE id = '81906545-69e0-4854-8b84-ce3865e506f6'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Berapa jumlah saham dalam satu lot standar di IDX?", "options": ["1 saham", "10 saham", "100 saham", "1000 saham"], "answer": "100 saham", "explanation": "Di Bursa Efek Indonesia, satu lot standar terdiri dari 100 lembar saham."}, {"type": "true_false", "question": "IDX adalah singkatan dari Indonesia Digital Exchange.", "answer": false, "explanation": "IDX adalah Indonesia Stock Exchange atau Bursa Efek Indonesia."}, {"type": "fill_blank", "question": "Di IDX, saham diperdagangkan dalam kelipatan ____ lembar per lot.", "answer": "100", "explanation": "Satu lot saham di IDX berjumlah 100 lembar."}]'::jsonb
WHERE id = 'b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang menunjukkan harga terakhir saham sebelum pasar tutup?", "options": ["Open", "High", "Low", "Close"], "answer": "Close", "explanation": "Close adalah harga terakhir transaksi sebelum pasar ditutup."}, {"type": "true_false", "question": "Volume menunjukkan banyaknya saham yang berpindah tangan dalam satu periode.", "answer": true, "explanation": "Volume mengukur likuiditas dan aktivitas perdagangan saham."}, {"type": "fill_blank", "question": "Kapitalisasi pasar dihitung dari harga saham dikalikan dengan jumlah saham ____.", "answer": "beredar", "explanation": "Market cap = harga saham × jumlah saham beredar."}]'::jsonb
WHERE id = '1bf85505-f29c-4f3d-9bb4-b6accea3c3ca'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa yang dimaksud dengan portfolio thinking?", "options": ["Membeli satu saham saja", "Melihat keseluruhan aset dan bagaimana campurannya sesuai tujuan", "Menghindari semua investasi", "Fokus pada satu jenis aset"], "answer": "Melihat keseluruhan aset dan bagaimana campurannya sesuai tujuan", "explanation": "Portfolio thinking berarti menilai kombinasi seluruh kepemilikan, bukan satu aset sendiri."}, {"type": "true_false", "question": "Saham yang berisiko jika dimiliki sendiri bisa menjadi bagian yang wajar dalam portofolio yang lebih besar.", "answer": true, "explanation": "Risiko satu aset bisa diredam ketika menjadi bagian kecil dari portofolio terdiversifikasi."}, {"type": "fill_blank", "question": "Portofolio adalah kombinasi dari semua ____ finansial yang kamu miliki.", "answer": "aset", "explanation": "Portofolio mencakup tabungan, saham, reksa dana, dan aset lainnya."}]'::jsonb
WHERE id = '969d9364-8111-4f93-a048-c4a60218bc34'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa return setelah pajak penting?", "options": ["Karena pajak selalu nol", "Karena pajak bisa mengurangi jumlah uang yang benar-benar kamu terima", "Karena pajak meningkatkan return", "Karena pajak tidak berlaku untuk investasi"], "answer": "Karena pajak bisa mengurangi jumlah uang yang benar-benar kamu terima", "explanation": "Return kotor bisa lebih besar dari return bersih yang kamu simpan setelah pajak."}, {"type": "true_false", "question": "Semua jenis return investasi di Indonesia bebas pajak.", "answer": false, "explanation": "Berbagai jenis return, seperti bunga deposito dan dividen, bisa dikenakan pajak."}, {"type": "fill_blank", "question": "Return yang tersisa setelah dipotong pajas disebut ____ return.", "answer": "bersih", "explanation": "Net return adalah return yang benar-benar kamu dapat setelah pajak dan biaya."}]'::jsonb
WHERE id = 'f863f21c-c810-4cb1-8ce7-b70858d228e3'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Manakah yang termasuk indikator makro penting di Indonesia?", "options": ["Warna logo bank", "BI Rate, inflasi, dan nilai tukar", "Jumlah follower influencer", "Harga ponsel terbaru"], "answer": "BI Rate, inflasi, dan nilai tukar", "explanation": "BI Rate, inflasi, dan nilai tukar adalah sinyal besar kondisi ekonomi."}, {"type": "true_false", "question": "Indikator makro tidak memengaruhi kehidupan keuangan individu.", "answer": false, "explanation": "Indikator makro memengaruhi suku bunga, harga, dan daya beli semua orang."}, {"type": "fill_blank", "question": "Inflasi mengukur seberapa cepat ____ umum naik.", "answer": "harga", "explanation": "Inflasi adalah kenaikan harga barang dan jasa secara umum."}]'::jsonb
WHERE id = 'bae48217-0c05-458a-ad0c-387ce972c250'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa itu FOMO dalam konteks keuangan?", "options": ["Fear of missing out — takut ketinggalan tren", "Fear of making offers", "Focus on money only", "Form of market order"], "answer": "Fear of missing out — takut ketinggalan tren", "explanation": "FOMO membuat orang membeli sesuatu hanya karena orang lain melakukannya."}, {"type": "true_false", "question": "Bias perilaku hanya memengaruhi investor pemula.", "answer": false, "explanation": "Semua orang, termasuk investor berpengalaman, bisa terpengaruh bias perilaku."}, {"type": "fill_blank", "question": "Aversi rugi membuat rasa sakit kehilangan uang terasa lebih ____ daripada kegembiraan mendapatkan uang.", "answer": "kuat", "explanation": "Loss aversion berarti kerugian terasa lebih menyakitkan daripada keuntungan yang setara."}]'::jsonb
WHERE id = 'ec6ef517-82a4-4a35-826f-9b2cc0486896'::uuid;

UPDATE public.lessons
SET quiz_data_id = '[{"type": "multiple_choice", "question": "Apa langkah pertama dalam membangun rencana keuangan untuk kebanyakan anak muda Indonesia?", "options": ["Membeli saham sebanyak-banyaknya", "Menutupi kebutuhan dasar, membangun dana darurat, dan melunasi utang berbunga tinggi", "Membeli properti segera", "Mengabaikan asuransi kesehatan"], "answer": "Menutupi kebutuhan dasar, membangun dana darurat, dan melunasi utang berbunga tinggi", "explanation": "Fondasi keuangan yang kuat dimulai dari kebutuhan dasar, dana darurat, dan utang tinggi."}, {"type": "true_false", "question": "Rencana keuangan yang baik mencakup tujuan, dana darurat, utang, perlindungan, dan investasi.", "answer": true, "explanation": "Rencana keuangan menyatukan semua aspek keuangan dalam urutan yang masuk akal."}, {"type": "fill_blank", "question": "Sebelum berinvestasi agresif, pastikan kamu sudah punya dana ____ dan perlindungan kesehatan.", "answer": "darurat", "explanation": "Dana darurat dan perlindungan dasar harus didahulukan sebelum mengambil risiko investasi."}]'::jsonb
WHERE id = '72163741-bad2-4f67-b2d6-07509667b92f'::uuid;
