-- Indonesian (Bahasa Indonesia) translations for Koinaku lessons Batch 1 (lessons 1-8).
-- Generated from .loop/lesson-bodies-v2.json and .loop/lesson-variants-v2.json.

UPDATE lessons SET
  summary_id = 'Uang adalah alat yang membuat perdagangan, menabung, dan perencanaan jadi mungkin.',
  concept_body_id = 'Uang adalah apa saja yang umum diterima orang sebagai pembayaran barang dan jasa. Dalam kehidupan sehari-hari, uang punya tiga peran. Pertama, sebagai alat tukar: alih-alih menukar mie ayammu langsung dengan charger ponsel, kamu pakai rupiah. Kedua, sebagai penyimpan nilai: uang memungkinkanmu menabung hari ini dan berbelanja besok. Ketiga, sebagai satuan hitung: uang memberi harga pada semua barang sehingga kamu bisa membandingkan nilai dengan cepat.

Uang tunai, saldo GoPay, transfer bank, dan pembayaran QRIS semuanya adalah bentuk uang karena penjual menerimanya. Uang hanya berfungsi karena orang percaya padanya. Kepercayaan itu didukung oleh Bank Indonesia yang menerbitkan rupiah dan menjaga kestabilannya. Tanpa bentuk uang bersama, perdagangan harus dilakukan dengan barter, yang lambat dan merepotkan ketika penjual tidak menginginkan apa yang kamu miliki. Memahami tiga peran ini membuat pelajaran tentang inflasi, menabung, dan berinvestasi jadi lebih mudah diikuti. Mengenali tiga peran ini juga membantumu melihat mengapa menyimpan semua uang dalam bentuk tunai bukanlah satu-satunya pilihan, dan mengapa pembayaran digital bekerja sama baiknya dengan uang kertas di sebagian besar toko di Indonesia.',
  why_this_matters_id = 'Kalau kamu paham apa itu uang sebenarnya, kamu bisa memutuskan di mana menyimpannya, kapan membelanjakannya, dan kapan membiarkannya tumbuh alih-alih dibiarkan menganggur.',
  common_mistake_id = 'Berpikir uang hanya berupa uang tunai fisik dan mengabaikan dompet digital, saldo bank, serta bentuk pembayaran lain yang diterima.',
  quiz_data_id = '[{"type": "matching", "question": "Pasangkan fungsi uang dengan contohnya.", "pairs": [["Alat tukar", "Bayar mie ayam pakai Rp15.000"], ["Penyimpan nilai", "Menabung Rp500.000 untuk beli sepatu bulan depan"], ["Satuan hitung", "Harga pulpen Rp3.000 dan buku Rp50.000"]], "answer": {"Alat tukar": "Bayar mie ayam pakai Rp15.000", "Penyimpan nilai": "Menabung Rp500.000 untuk beli sepatu bulan depan", "Satuan hitung": "Harga pulpen Rp3.000 dan buku Rp50.000"}, "explanation": "Fungsi uang membantu kita memahami mengapa uang kertas, koin, maupun saldo digital bisa dipakai dalam kehidupan sehari-hari.", "difficulty": "beginner"}, {"type": "true_false", "question": "Saldo GoPay atau OVO tidak termasuk uang karena tidak berbentuk uang kertas.", "answer": false, "explanation": "Saldo elektronik tetap diakui sebagai alat tukar dan satuan hitung, sehingga termasuk bentuk uang digital.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Mengapa uang lebih praktis daripada barter?", "options": ["Karena uang bisa ditukar dengan barang apa saja yang dijual", "Karena uang terbuat dari logam mulia", "Karena barter lebih cepat", "Karena uang tidak bisa hilang"], "answer": "Karena uang bisa ditukar dengan barang apa saja yang dijual", "explanation": "Uang diterima umum, jadi kita tidak perlu mencari orang yang kebetulan membutuhkan barang kita.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Fungsi uang sebagai _____ memungkinkan kita membandingkan harga berbagai barang dengan mudah.", "answer": "satuan hitung", "explanation": "Satuan hitung membuat kita bisa menyatakan nilai barang dalam rupiah sehingga mudah membandingkan harga.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'money-basics-101';

UPDATE lessons SET
  summary_id = 'Rupiah yang sama bisa membeli jumlah berbeda tergantung di mana dan kapan kamu membelanjakannya.',
  concept_body_id = 'Nilai berarti seberapa berguna atau diinginkan sesuatu bagimu. Daya beli berarti seberapa banyak yang bisa kamu beli dengan jumlah uang tertentu. Rp 50.000 yang sama bisa membeli lebih banyak di beberapa tempat dan lebih sedikit di tempat lain karena harganya berbeda. Gaji nominal tinggi tidak selalu berarti hidup kaya jika sewa, makanan, dan transportasi mahal.

Daya beli juga berubah seiring waktu. Jika harga naik, uangmu membeli lebih sedikit. Jika harga turun, uangmu membeli lebih banyak. Hal ini penting saat kamu membandingkan penghasilan, harga, atau tabungan antarkota atau antartahun. Ekonom kadang menggunakan istilah nilai riil untuk menyebut nilai yang sudah disesuaikan dengan daya beli. Jumlah nominal tinggi tidak selalu berarti kamu kaya jika segala sesuatu di sekitarmu mahal. Memahami ini membantumu membandingkan tawaran kerja, merencanakan perjalanan, dan menilai apakah suatu harga wajar. Saat kamu bepergian dari kampung halaman ke Jakarta, kamu mungkin menyadari harga makanan yang sama lebih mahal. Itulah daya beli sedang bekerja. Membandingkan jumlah nominal tanpa memeriksa apa yang bisa dibelinya seperti membandingkan dua pelari berdasarkan ukuran sepatu mereka, bukan kecepatan lari.',
  why_this_matters_id = 'Saat menyusun anggaran atau membandingkan gaji, daya beli memberitahumu kisah nyata di balik angka rupiah tersebut.',
  common_mistake_id = 'Meyakini bahwa gaji lebih besar di kota yang lebih mahal selalu berarti hidup lebih baik, tanpa memeriksa apa yang bisa dibeli oleh gaji tersebut.',
  quiz_data_id = '[{"type": "multiple_choice", "question": "Mie ayam di Jakarta Rp18.000, di Yogyakarta Rp12.000. Manakah pernyataan yang benar tentang Rp50.000?", "options": ["Daya belinya lebih besar di Yogyakarta", "Daya belinya lebih besar di Jakarta", "Daya belinya sama karena nominalnya sama", "Rp50.000 tidak bisa beli mie ayam di dua kota"], "answer": "Daya belinya lebih besar di Yogyakarta", "explanation": "Dengan harga lebih murah, uang yang sama bisa membeli lebih banyak porsi, artinya daya beli lebih besar.", "difficulty": "beginner"}, {"type": "true_false", "question": "Jika harga barang naik, daya beli uang yang kita milai juga naik.", "answer": false, "explanation": "Ketika harga naik, uang yang sama bisa membeli lebih sedikit barang, sehingga daya beli menurun.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Daya beli menunjukkan seberapa _____ barang atau jasa yang bisa dibeli dengan sejumlah uang.", "answer": "banyak", "explanation": "Daya beli mengukur jumlah barang/jasa yang dapat dibeli, bukan hanya nominal uangnya.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Rina punya Rp100.000. Harga novel bekas di toko online Rp25.000, di toko fisik Rp40.000. Berapa perbedaan daya beli dalam jumlah novel?", "options": ["1,5 novel lebih banyak di toko online", "Tidak ada perbedaan", "Novel lebih murah di toko fisik", "Rp100.000 tidak cukup di dua tempat"], "answer": "1,5 novel lebih banyak di toko online", "explanation": "Di toko online Rp100.000 dapat 4 novel; di toko fisik hanya 2,5 novel. Selisihnya 1,5 novel.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'value-and-purchasing-power';

UPDATE lessons SET
  summary_id = 'Inflasi adalah kenaikan harga yang perlahan-lahan memangkas daya beli uang tunaimu.',
  concept_body_id = 'Inflasi adalah kenaikan harga barang dan jasa secara umum seiring waktu. Ketika inflasi terjadi, setiap rupiah membeli lebih sedikit dari sebelumnya. Bank Indonesia menargetkan inflasi rendah dan stabil, sekitar 2,5% plus minus 1% per tahun. Inflasi rendah adalah hal normal dalam ekonomi yang tumbuh, tetapi inflasi tinggi merugikan orang yang menyimpan uang tunai dalam jumlah besar.

Inflasi tidak berarti setiap harga naik dalam jumlah yang sama, tetapi biaya hidup secara keseluruhan cenderung naik. Uang tunai yang disimpan di bawah bantal kehilangan daya beli karena uang yang sama bisa membeli lebih sedikit barang tahun depan. Rekening tabungan yang memberikan bunga bisa memperlambat kerugian ini, tetapi hanya jika suku bunganya lebih tinggi dari inflasi. Itulah mengapa memikirkan inflasi penting sebelum memilih tempat menyimpan tabungan jangka panjang. Melindungi daya beli adalah salah satu alasan utama orang kemudian mempertimbangkan investasi, tetapi hanya setelah mereka membangun kebiasaan menabung yang stabil. Inflasi biasanya disebabkan oleh kombinasi kenaikan permintaan, biaya produksi yang lebih tinggi, dan perubahan jumlah uang beredar. Kamu tidak perlu jadi ekonom, tetapi kamu perlu tahu bahwa inflasi adalah fitur normal ekonomi modern. Bahayanya adalah mengabaikannya, bukan memahaminya.',
  why_this_matters_id = 'Inflasi memengaruhi setiap pilihan menabung dan berbelanja. Mengetahuinya membantumu melindungi uangmu alih-alih membiarkannya menyusut diam-diam.',
  common_mistake_id = 'Menyimpan semua tabungan jangka panjang dalam bentuk tunai dan menganggap nilai nominal uang akan tetap sama selamanya.',
  quiz_data_id = '[{"type": "true_false", "question": "Inflasi berarti harga barang dan jasa naik secara umum dalam jangka waktu tertentu.", "answer": true, "explanation": "Inflasi adalah kenaikan harga umum yang terus-menerus, bukan kenaikan satu barang saja.", "difficulty": "beginner"}, {"type": "true_false", "question": "Menyimpan semua uang di bawah bantal selalu aman dari inflasi.", "answer": false, "explanation": "Uang tunai tidak menghasilkan bunga, sehingga daya belinya menurun saat inflasi positif.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Bank Indonesia menargetkan inflasi sekitar _____ persen plus minus satu persen.", "answer": "2,5", "explanation": "Target inflasi BI adalah sekitar 2,5% ± 1% untuk menjaga stabilitas ekonomi.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Jika inflasi 5% per tahun dan tabunganmu bunga 3% per tahun, apa yang terjadi pada daya beli tabunganmu?", "options": ["Daya beli menurun 2%", "Daya beli naik 2%", "Daya beli tetap sama", "Daya beli naik 8%"], "answer": "Daya beli menurun 2%", "explanation": "Inflasi 5% menggerus nilai uang lebih cepat daripada bunga 3% menambahnya, sehingga daya beli riil turun sekitar 2%.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'inflation-101';

UPDATE lessons SET
  summary_id = 'Pendapatan adalah uang yang masuk; kekayaan adalah apa yang kamu simpan dan kembangkan dari waktu ke waktu.',
  concept_body_id = 'Pendapatan adalah aliran uang yang kamu terima, seperti gaji, uang saku, atau bayaran freelance. Kekayaan adalah stok uang dan barang berharga yang sudah kamu miliki, dikurangi apa yang kamu hutang. Seseorang bisa berpendapatan tinggi tetapi kekayaannya rendah jika hampir semua uangnya dibelanjakan. Orang lain bisa berpendapatan lebih rendah tetapi lebih kaya jika ia menabung dan berinvestasi secara konsisten.

Pendapatan mengukur kecepatan; kekayaan mengukur seberapa besar cadangan keuanganmu. Kesehatan finansial jangka panjang lebih bergantung pada apa yang kamu simpan daripada apa yang kamu hasilkan. Itulah mengapa anggaran, mengendalikan hutang, dan membentuk kebiasaan menabung penting di setiap tingkat pendapatan. Kamu bisa membayangkan pendapatan sebagai air yang mengalir ke dalam ember dan kekayaan sebagai air yang sudah ada di dalamnya. Jika ember bocor, aliran yang cepat tidak akan memenuhinya. Memperbaiki kebocoran, menabung lebih banyak, dan menghindari hutang berbunga tinggi itulah yang membangun kekayaan dari waktu ke waktu. Kekayaan juga mencakup barang yang bisa dijual, seperti sepeda motor atau keterampilan berharga, dikurangi hutang yang melekat padanya. Itulah mengapa dua orang dengan gaji yang sama bisa berakhir di posisi finansial yang sangat berbeda. Perbedaannya berasal dari pilihan, bukan hanya dari penghasilan.',
  why_this_matters_id = 'Di usia 18, pendapatanmu mungkin masih kecil, tapi kebiasaan membangun kekayaan bisa dimulai sekarang. Kekayaan dibangun dari apa yang tidak kamu belanjakan.',
  common_mistake_id = 'Menilai kesuksesan finansial hanya dari penghasilan bulanan sambil mengabaikan tabungan, hutang, dan kebiasaan berbelanja.',
  quiz_data_id = '[{"type": "matching", "question": "Pasangkan konsep dengan contohnya.", "pairs": [["Pendapatan", "Gaji Rp4 juta per bulan"], ["Kekayaan", "Tabungan Rp15 juta dikurangi utang Rp2 juta"], ["Pengeluaran", "Bayar kos Rp800 ribu per bulan"]], "answer": {"Pendapatan": "Gaji Rp4 juta per bulan", "Kekayaan": "Tabungan Rp15 juta dikurangi utang Rp2 juta", "Pengeluaran": "Bayar kos Rp800 ribu per bulan"}, "explanation": "Membedakan aliran uang (pendapatan/pengeluaran) dan stok kepemilikan (kekayaan) membantu kita menilai kesehatan keuangan.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Andi gaji Rp8 juta, tabungan nol. Budi gaji Rp4 juta, tabungan Rp15 juta. Siapa yang lebih kaya?", "options": ["Budi", "Andi", "Sama kaya", "Tidak bisa dibandingkan"], "answer": "Budi", "explanation": "Kekayaan diukur dari aset bersih yang dimiliki, bukan dari besarnya gaji.", "difficulty": "beginner"}, {"type": "true_false", "question": "Pendapatan tinggi selalu berarti kekayaan tinggi.", "answer": false, "explanation": "Jika pengeluaran lebih besar dari pendapatan, orang dengan gaji tinggi bisa memiliki kekayaan rendah atau bahkan utang.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Kekayaan bersih dihitung dari total aset dikurangi total _____.", "answer": "utang", "explanation": "Kekayaan bersih = aset - utang. Ini menunjukkan seberapa besar harta yang benar-benar kita miliki.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'income-vs-wealth';

UPDATE lessons SET
  summary_id = 'Menutupi kebutuhan terlebih dahulu membuat keinginan lebih dinikmati dan tidak menekan.',
  concept_body_id = 'Kebutuhan adalah sesuatu yang harus kamu miliki untuk hidup, belajar, atau bekerja dengan aman. Contohnya termasuk makanan, tempat tinggal, transportasi, dan pulsa dasar. Keinginan adalah sesuatu yang ingin kamu miliki tetapi bisa hidup tanpanya, seperti pakaian baru, tiket konser, atau langganan streaming premium.

Garis antara kebutuhan dan keinginan tidak selalu jelas. Misalnya, ponsel dasar adalah kebutuhan untuk kelas online, tetapi ponsel flagship terbaru adalah keinginan. Tujuannya bukan menghilangkan keinginan. Tujuannya adalah menutupi kebutuhan terlebih dahulu, menabung sesuatu berikutnya, lalu berbelanja untuk keinginan tanpa rasa bersalah atau utang. Banyak orang merasa stres karena membeli keinginan terlebih dahulu lalu kesulitan membayar kebutuhan. Membalik urutannya menciptakan ruang napas dan membuat pengeluaran lebih menyenangkan karena kamu tahu hal-hal penting sudah tertangani. Budaya dan media sosial sering mengaburkan garis ini dengan mengubah keinginan menjadi kebutuhan yang dirasakan. Ponsel dasar menjadi kebutuhan ketika kelas beralih ke daring, tetapi warna atau merek baru tetaplah keinginan. Belajar membedakan keduanya memberimu kendali atas uangmu alih-alih membiarkan pengiklan memutuskan untukmu.',
  why_this_matters_id = 'Memahami pembagian ini sejak dini membantumu menghindari kehabisan uang sebelum akhir bulan dan mencegah utang impulsif.',
  common_mistake_id = 'Menyebut setiap keinginan sebagai kebutuhan, lalu bertanya-tanya mengapa tidak ada uang tersisa untuk menabung atau keadaan darurat.',
  quiz_data_id = '[{"type": "ordering", "question": "Urutkan pengeluaran Sari dari yang paling mendesak (kebutuhan) hingga paling bisa ditunda (keinginan).", "options": ["Bayar kos", "Beli pulsa dan kuota", "Langganan streaming", "Beli sepatu baru"], "answer": ["Bayar kos", "Beli pulsa dan kuota", "Langganan streaming", "Beli sepatu baru"], "explanation": "Kos dan pulsa adalah kebutuhan dasar. Streaming dan sepatu baru adalah keinginan yang bisa ditunda.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Manakah yang termasuk kebutuhan bagi pelajar?", "options": ["Pulsa dan kuota internet untuk tugas", "Tiket konser", "Skin game terbaru", "Kopi kekinian setiap hari"], "answer": "Pulsa dan kuota internet untuk tugas", "explanation": "Pulsa dan kuota mendukung aktivitas belajar, sehingga termasuk kebutuhan.", "difficulty": "beginner"}, {"type": "true_false", "question": "Keinginan harus selalu dipenuhi terlebih dahulu agar hidup bahagia.", "answer": false, "explanation": "Kebutuhan dasar harus didahulukan. Keinginan baru dipertimbangkan setelah kebutuhan dan tabungan tercukupi.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Makan siang di kantin termasuk _____, sedangkan makan di kafe mahal setiap hari termasuk keinginan.", "answer": "kebutuhan", "explanation": "Makan untuk bertahan hidup dan belajar adalah kebutuhan, tetapi pilihan tempat mewah adalah keinginan.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'needs-vs-wants-101';

UPDATE lessons SET
  summary_id = 'Aset memasukkan uang ke kantongmu; liabilitas mengeluarkan uang dari kantongmu.',
  concept_body_id = 'Aset adalah sesuatu yang kamu miliki dan bisa memasukkan uang ke kantongmu atau tumbuh nilainya seiring waktu. Liabilitas adalah sesuatu yang kamu hutang atau sesuatu yang menghabiskan uangmu secara rutin. Benda fisik yang sama bisa jadi aset bagi satu orang dan liabilitas bagi orang lain, tergantung cara penggunaannya.

Misalnya, sepeda motor yang dibeli tunai dan digunakan untuk menghasilan sebagai pengemudi ojek online adalah aset karena membantu menghasilkan uang. Sepeda motor yang sama yang dibeli kredit hanya untuk bersenang-senang di akhir pekan adalah liabilitas karena membutuhkan cicilan, bensin, dan perawatan tanpa menghasilkan pemasukan. Bahkan rumah bisa jadi aset jika menghasilkan sewa, atau liabilitas jika cicilan KPR bank dan perawatannya menguras uangmu. Pertanyaan kuncinya adalah: apakah benda ini menambah uangku di masa depan atau menguranginya? Pendidikan dan keterampilan juga bisa jadi aset karena bisa meningkatkan penghasilanmu di masa depan. Namun, mereka baru menjadi aset jika meningkatkan kemampuanmu menghasilkan uang. Kursus atau gelar yang tidak memperbaiki prospek kerjamu bisa menjadi liabilitas jika meninggalkanmu dengan hutang pendidikan yang berat.',
  why_this_matters_id = 'Sebelum membeli sesuatu yang besar, tanyakan apakah benda itu akan menumbuhkan uangmu atau mengurasnya. Kebiasaan ini melindungimu dari utang yang menyamar sebagai gengsi.',
  common_mistake_id = 'Berpikir bahwa barang mahal seperti mobil atau sepeda motor secara otomatis adalah aset, padahal benda itu justru banyak memakan uang.',
  quiz_data_id = '[{"type": "matching", "question": "Pasangkan item dengan kategorinya.", "pairs": [["Aset", "Deposito yang menghasilkan bunga"], ["Liabilitas", "Cicilan motor hanya untuk gaya"], ["Bisa keduanya", "Motorbike yang dipakai kerja dan jalan-jalan"]], "answer": {"Aset": "Deposito yang menghasilkan bunga", "Liabilitas": "Cicilan motor hanya untuk gaya", "Bisa keduanya": "Motorbike yang dipakai kerja dan jalan-jalan"}, "explanation": "Kategori tergantung pada apakah item tersebut memasukkan atau mengeluarkan uang.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Dodi membeli motor untuk jadi ojek online. Eko membeli motor serupa hanya untuk jalan-jalan. Siapa yang lebih mungkin memiliki aset?", "options": ["Dodi", "Eko", "Keduanya sama", "Tidak ada yang benar"], "answer": "Dodi", "explanation": "Motor Dodi menghasilkan pendapatan, sehingga bersifat aset. Motor Eko hanya mengeluarkan biaya.", "difficulty": "beginner"}, {"type": "true_false", "question": "Aset selalu berbentuk barang fisik seperti rumah atau mobil.", "answer": false, "explanation": "Aset bisa berupa uang tunai, deposito, saham, keterampilan, atau bisnis yang menghasilkan uang.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Jika suatu barang mengeluarkan uang terus-menerus tanpa menghasilkan pendapatan, barang itu lebih bersifat _____.", "answer": "liabilitas", "explanation": "Liabilitas menguras uang, seperti cicilan barang konsumtif yang tidak menghasilkan pendapatan.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'assets-vs-liabilities';

UPDATE lessons SET
  summary_id = 'Risiko adalah kemungkinan bahwa kenyataan berakhir lebih buruk dari yang kamu harapkan.',
  concept_body_id = 'Risiko adalah kemungkinan bahwa hasil akan lebih buruk dari yang kamu harapkan. Risiko tidak selalu berarti bahaya; risiko berarti ketidakpastian tentang hasil. Setiap keputusan finansial membawa risiko tertentu, bahkan menyimpan uang tunai di bawah bantal, karena inflasi bisa mengurangi nilainya.

Risiko menjadi lebih mudah dikelola ketika kamu menamainya dengan jelas. Tanyakan pada dirimu: apa yang bisa salah? Seberapa mungkin terjadi? Seberapa buruk dampaknya? Bisakah aku mengurangi kemungkinannya atau membatasi kerugiannya? Menjawab pertanyaan ini sebelum bertindak adalah fondasi perilaku keuangan yang baik. Misalnya, membawa payung mengurangi risiko kehujanan, tetapi tidak menghilangkan kemungkinan hujan. Dalam keuangan, diversifikasi, dana darurat, dan asuransi adalah alat yang mengurangi risiko tertentu tanpa menghilangkan semua ketidakpastian. Kamu bisa memikirkan risiko sebagai memiliki dua bagian: kemungkinan sesuatu yang buruk terjadi, dan seberapa besar kerugiannya jika terjadi. Beberapa risiko layak diambil, seperti berinvestasi pada pendidikanmu. Yang lain tidak, seperti meminjamkan uang kepada orang asing di internet. Keahliannya adalah membedakan keduanya.',
  why_this_matters_id = 'Jika kamu bisa mengenali risiko sejak awal, kamu bisa melindungi tabungan, menghindari penipuan, dan membuat pilihan lebih tenang di bawah tekanan.',
  common_mistake_id = 'Berpikir bahwa menghindari semua keputusan menghilangkan risiko. Tidak melakukan apa-apa dengan uang juga punya risiko, terutama dari inflasi.',
  quiz_data_id = '[{"type": "case_study", "question": "Baca kasus berikut dan pilih respons terbaik.", "caseText": "Rina diminta meminjamkan Rp500.000 kepada teman yang baru beberapa kali bertemu. Teman itu berjanji membayar minggu depan, tetapi Rina mendengar dia sering menunda hutang.", "followUp": {"question": "Apa risiko utama yang dihadapi Rina?", "options": ["Teman tidak membayar kembali", "Rina kehilangan waktu", "Rina kehilangan kesempatan memakai uang itu", "Teman meminjam lagi"], "answer": "Teman tidak membayar kembali", "explanation": "Risiko kredit adalah lawan tidak memenuhi janji pembayaran."}, "answer": "Risiko utama adalah uangnya tidak kembali. Rina bisa meminimalkan risiko dengan meminjam dalam jumlah kecil atau meminta jaminan.", "explanation": "Risiko adalah kemungkinan hasil buruk. Meminjamkan uang kepada seseorang yang sering menunda berarti risiko gagal bayar tinggi.", "difficulty": "beginner"}, {"type": "true_false", "question": "Risiko hanya ada dalam investasi, tidak ada dalam kehidupan sehari-hari.", "answer": false, "explanation": "Risiko ada di mana saja: meminjamkan uang, naik kendaraan, memilih jurusan, bahkan menyimpan uang di rumah.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Manakah contoh risiko dalam kehidupan sehari-hari?", "options": ["Meminjamkan uang tanpa jaminan", "Menyimpan uang di bank berlisensi", "Membeli pulsa di konter resmi", "Membayar uang kos tepat waktu"], "answer": "Meminjamkan uang tanpa jaminan", "explanation": "Meminjamkan uang tanpa jaminan berisiko lawan tidak membayar kembali.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Risiko adalah kemungkinan hasil yang _____ dari yang diharapkan.", "answer": "lebih buruk", "explanation": "Risiko berkaitan dengan hasil negatif atau tidak sesuai harapan yang mungkin terjadi.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'understanding-risk';

UPDATE lessons SET
  summary_id = 'Uang yang tersedia lebih cepat biasanya lebih berharga daripada jumlah yang sama di kemudian hari.',
  concept_body_id = 'Nilai waktu uang berarti menerima jumlah uang yang sama lebih awal umumnya lebih baik daripada menerimanya nanti. Alasannya adalah biaya kesempatan: uang di tanganmu hari ini bisa menutupi kebutuhan, menghasilkan bunga, atau ditabung untuk suatu tujuan. Uang yang dijanjikan di masa depan mungkin tidak pernah datang, dan harga bisa naik sementara kamu menunggu.

Ide ini juga bekerja sebaliknya. Jika kamu meminjam Rp 1.000.000 hari ini, kamu biasanya harus mengembalikan lebih banyak nanti karena pemberi pinjaman melepaskan penggunaan uangnya. Waktu penting karena pilihan dan kepastian penting. Mulai menabung lebih awal memberi bunga majemuk lebih banyak waktu untuk bekerja, itulah sebabnya tabungan kecil yang dimulai di usia 18 bisa tumbuh lebih besar daripada tabungan lebih besar yang dimulai di usia 35. Memahami ini sekarang mempersiapkanmu untuk pelajaran tentang bunga, menabung, dan berinvestasi. Konsep ini juga menjelaskan mengapa pembayaran cicilan sering lebih mahal daripada membayar tunai di muka. Penjual melepaskan penggunaan uangnya, jadi mereka mengenakan biaya tambahan untuk penundaan itu. Setiap kali kamu menunda pembayaran atau penerimaan, nilai waktu uang adalah bagian dari kesepakatan tersebut.',
  why_this_matters_id = 'Waktu memengaruhi nilai uangmu. Mulai menabung lebih awal, membayar utang tepat waktu, dan memilih kapan menerima pembayaran akan lebih jelas dengan model berpikir ini.',
  common_mistake_id = 'Menunggu punya uang besar baru menabung atau berinvestasi, tanpa menyadari bahwa uang kecil yang lebih awal sering tumbuh lebih besar daripada uang besar yang datang belakangan.',
  quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa uang Rp500.000 yang diterima hari ini lebih baik daripada Rp500.000 yang diterima tiga bulan lagi?", "options": ["Karena bisa langsung dipakai atau ditabung", "Karena nominalnya lebih besar", "Karena uang masa depan tidak berharga", "Karena harga barang pasti turun"], "answer": "Karena bisa langsung dipakai atau ditabung", "explanation": "Uang sekarang bisa digunakan untuk kebutuhan atau menghasilkan bunga, sehingga memiliki nilai lebih.", "difficulty": "beginner"}, {"type": "true_false", "question": "Menerima uang lebih cepat selalu lebih baik daripada menerimanya nanti.", "answer": false, "explanation": "Secara umum uang sekarang lebih berharga, tetapi ada pengecualian seperti bunga tinggi pada pinjaman yang harus dibayar lebih cepat.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Uang yang diterima sekarang lebih bernilai karena bisa menghasilkan _____ jika ditabung atau diinvestasikan.", "answer": "bunga", "explanation": "Bunga adalah imbalan atas waktu penyimpanan uang, sehingga uang sekarang bisa tumbuh menjadi lebih besar di masa depan.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Biaya kesempatan dari menunggu pembayaran adalah ...", "options": ["Kehilangan kesempatan memakai atau menabung uang selama masa tunggu", "Nominal uang berkurang otomatis", "Uang hilang selamanya", "Bank meminta biaya administrasi"], "answer": "Kehilangan kesempatan memakai atau menabung uang selama masa tunggu", "explanation": "Selama menunggu, uang tersebut tidak bisa digunakan untuk kebutuhan atau menghasilkan bunga.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'time-value-of-money';
-- Indonesian translations for Batch 2 (lessons 9-16)
-- Generated for Koinaku lesson content

UPDATE lessons
SET summary_id = 'Anggaran adalah rencana yang membagi pemasukanmu menjadi kebutuhan, keinginan, serta tabungan atau pembayaran utang.',
    concept_body_id = 'Anggaran adalah rencana tertulis tentang bagaimana kamu akan membelanjakan dan menabung uangmu. Kerangka 50/30/20 adalah titik awal yang sederhana: sekitar 50% untuk kebutuhan, 30% untuk keinginan, dan 20% untuk tabungan serta melunasi utang. Di Indonesia, kamu mungkin perlu menyesuaikan angka-angka ini berdasarkan kontribusi keluarga, biaya hidup, dan harga lokal. Mahasiswa yang tinggal dengan orang tua mungkin bisa menabung 30%, sementara yang membayar kos penuh mungkin hanya bisa menabung 10%.

Nilai sebenarnya dari anggaran bukanlah kesempurnaan. Melainkan kesadaran. Ketika kamu tahu ke mana uangmu pergi, kamu bisa menemukan kebocoran, merencanakan tujuan, dan menghindari panik di akhir bulan. Anggaran hanya berhasil jika kamu membandingkan rencana dengan pengeluaran nyata dan menyesuaikannya seiring perubahan hidup. Anggap itu sebagai peta, bukan penjara. Banyak mahasiswa Indonesia menerima uang saku atau pendapatan freelance yang tidak tetap, sehingga pembagian ketat 50/30/20 mungkin tidak cocok setiap bulan. Yang penting adalah punya kategori dan batas, lalu menyesuaikan saat pendapatan berubah. Anggaran fleksibel mengalahkan anggaran sempurna yang kamu tinggalkan setelah satu minggu.',
    why_this_matters_id = 'Membuat anggaran mengubah stres uang menjadi rencana yang jelas. Ini adalah alat terbaik untuk memaksimalkan pendapatan kecil tanpa merasa kekurangan.',
    common_mistake_id = 'Membuat anggaran sempurna di atas kertas tapi tidak pernah melacak pengeluaran nyata, sehingga rencananya menjadi tidak berguna.',
    quiz_data_id = '[{"question":"Dalam anggaran 50/30/20, apa yang dicakup oleh angka 20%?","type":"multiple_choice","options":["Kebutuhan","Keinginan","Tabungan dan utang","Hanya investasi"],"answer":"Tabungan dan utang","explanation":"20% untuk tabungan dan melunasi utang, sementara 50% untuk kebutuhan dan 30% untuk keinginan."},{"question":"Ani memiliki pendapatan Rp 2.000.000. Berapa idealnya dialokasikan untuk tabungan atau utang?","type":"multiple_choice","options":["Rp 200.000","Rp 400.000","Rp 600.000","Rp 1.000.000"],"answer":"Rp 400.000","explanation":"20% dari Rp 2.000.000 adalah Rp 400.000 untuk tabungan dan utang."},{"question":"Mengapa penting untuk mencatat pengeluaran nyata?","type":"multiple_choice","options":["Karena uang akan tumbuh secara otomatis","Karena menunjukkan apakah anggaranmu sesuai kenyataan","Karena diwajibkan oleh OJK","Karena menggantikan kebutuhan menabung"],"answer":"Karena menunjukkan apakah anggaranmu sesuai kenyataan","explanation":"Mencatat pengeluaran mengungkapkan apakah rencanamu realistis dan di mana perlu penyesuaian."}]'::jsonb
WHERE slug = 'budgeting-101';

UPDATE lessons
SET summary_id = 'Dana darurat adalah jaring pengaman terpisah yang melindungi tabungan jangka panjangmu dari pengeluaran mendadak.',
    concept_body_id = 'Dana darurat adalah uang yang disisihkan khusus untuk biaya mendesak dan tak terduga seperti sakit, kehilangan pekerjaan, atau ponsel rusak. Panduan umum adalah menabung tiga hingga enam bulan pengeluaran rutin. Jika pendapatanmu stabil dan tidak ada tanggungan, tiga bulan mungkin cukup. Jika pendapatanmu tidak tetap atau kamu menanggung keluarga, targetkan mendekati enam bulan atau lebih.

Dana ini sebaiknya disimpan di tempat yang aman dan mudah diakses, seperti rekening tabungan terpisah di bank yang dijamin LPS, deposito jangka pendek, atau reksa dana pasar uang berisiko rendah. Dana darurat tidak boleh disimpan di saham, kripto, atau instrumen apa pun yang nilainya bisa turun tajam saat kamu tiba-tiba membutuhkan uang. Tujuannya adalah stabilitas, bukan imbal hasil tinggi. Membangun dana ini sebelum berinvestasi melindungi rencana jangka panjangmu dari guncangan jangka pendek. Mulailah dari yang kecil jika harus. Bahkan satu bulan pengeluaran lebih baik daripada tidak ada sama sekali. Tujuannya adalah membangun kebiasaan memisahkan uang darurat dari uang belanja. Setelah dana terbentuk, kamu akan merasa lebih tenang ketika biaya tak terduga muncul, dan bisa berpikir lebih jernih tentang investasi.',
    why_this_matters_id = 'Dana darurat melindungi rencana masa depanmu. Tanpa itu, krisis kecil bisa memaksamu berutang dengan bunga tinggi atau menjual investasi dalam kerugian.',
    common_mistake_id = 'Mencampur uang darurat dengan pengeluaran harian, atau mengejar imbal hasil lebih tinggi dengan menaruh tabungan darurat di aset berisiko.',
    quiz_data_id = '[{"type":"multiple_choice","difficulty":"beginner","question":"Berapa lama pengeluaran rutin yang umumnya dianjurkan untuk dana darurat?","options":["1 bulan","3–6 bulan","12 bulan","Tidak perlu dana darurat"],"answer":"3–6 bulan","explanation":"Aturan praktisnya adalah menyimpan cadangan 3–6 bulan pengeluaran rutin, disesuaikan dengan stabilitas pendapatan dan tanggungan.","parameters":{}},{"type":"true_false","difficulty":"beginner","question":"Dana darurat boleh disimpan dalam saham untuk potensi keuntungan lebih besar.","answer":false,"explanation":"Saham berfluktuasi dan bisa turun saat darurat terjadi. Dana darurat sebaiknya disimpan di instrumen aman dan likuid.","parameters":{}},{"type":"multiple_choice","difficulty":"beginner","question":"Mengapa dana darurat penting disiapkan sebelum mulai berinvestasi?","options":["Menjamin investasi selalu untung","Menghindari menjual investasi saat darurat","Menggantikan asuransi jiwa","Meningkatkan imbal hasil deposito"],"answer":"Menghindari menjual investasi saat darurat","explanation":"Dengan ada dana darurat, kamu tidak perlu mencairkan investasi dalam kondisi pasar yang kurang menguntungkan.","parameters":{}}]'::jsonb
WHERE slug = 'emergency-fund-101';

UPDATE lessons
SET summary_id = 'Menabung otomatis di awal bulan, bukan berharap ada sisa di akhir bulan.',
    concept_body_id = 'Bayar diri sendiri dulu berarti memindahkan uang ke tabungan sebelum kamu membelanjakan apa pun. Alih-alih menunggu sisa di akhir bulan, kamu memutuskan berapa banyak yang akan ditabung dan memindahkannya segera saat pendapatan datang.

Ini berhasil karena tekad kita terbatas. Jika menabung adalah prioritas terakhir, sering kali uang itu lenyap dalam pembelian kecil harian seperti kopi tambahan, camilan, atau pembelian aplikasi impulsif. Mengotomatisasi transfer membuat menabung menjadi default, bukan keputusan. Bahkan jumlah kecil yang ditabung di awal membangun kebiasaan yang menjadi lebih mudah seiring pertumbuhan pendapatan. Seiring waktu, membayar diri sendiri dulu menjadi tidak terasa, dan tabunganmu tumbuh tanpa membutuhkan disiplin konstan. Kamu bisa mulai dengan hanya Rp 50.000 atau Rp 100.000 per bulan. Jumlahnya tidak seberapa dibanding kebiasaannya. Setelah sistem berjalan, kamu bisa meningkatkannya kapan saja pendapatanmu naik. Keajaibannya adalah menabung terjadi tanpa membutuhkan keputusan harian.',
    why_this_matters_id = 'Kebiasaan ini mengubah menabung dari perjuangan menjadi rutinitas. Ini salah satu cara paling andal untuk membangun kekayaan meski pendapatan kecil.',
    common_mistake_id = 'Berencana menabung dari sisa setelah belanja, lalu kaget ketika tidak ada yang tersisa.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'pay-yourself-first';

UPDATE lessons
SET summary_id = 'Flash sale, hype influencer, dan camilan kecil harian bisa menguras anggaran secara diam-diam.',
    concept_body_id = 'Jebakan pengeluaran adalah apa pun yang menipumu agar membeli lebih dari yang direncanakan. Jebakan umum meliputi flash sale yang menciptakan urgensi palsu, rekomendasi influencer yang membuatmu merasa ketinggalan, dan camilan kecil harian yang terasa murah sendiri tapi cepat bertumpuk. Penjual menggunakan penghitung waktu mundur, label stok terbatas, dan bukti sosial untuk mendorongmu memutuskan dengan cepat.

Pertahanan terbaik adalah jeda. Sebelum membeli, tanyakan: apakah aku merencanakan ini kemarin? Apakah aku mampu membelinya dari anggaran keinginan? Apakah aku masih menginginkannya satu minggu lagi? Memberi diri sendiri bahkan satu hari untuk memutuskan sering kali mematahkan pesona belanja impulsif. Ini bukan berarti tidak pernah menikmati hidup. Ini berarti memilih keinginan dengan sengaja sehingga uangmu pergi ke hal-hal yang benar-benar kamu hargai. Jebakan lain adalah bundling, di mana kamu membeli lebih banyak untuk mendapatkan gratis ongkir atau diskon kecil. Yang ketiga adalah inflasi gaya hidup, di mana pengeluaran naik begitu pendapatan naik. Menangkal jebakan ini bukan berarti hidup seperti pertapa. Ini berarti belanja dengan tujuan, bukan secara tidak sengaja.',
    why_this_matters_id = 'Di usia 18 tahun, uangmu masih kecil tapi kebiasaanmu sedang terbentuk. Belajar menolak jebakan sekarang melindungi pendapatan yang jauh lebih besar nanti.',
    common_mistake_id = 'Membeli sesuatu hanya karena sedang diskon, padahal kamu tidak akan membelinya jika harganya normal.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'spending-traps';

UPDATE lessons
SET summary_id = 'Utang konsumen berbunga tinggi bisa tumbuh lebih cepat dari kemampuanmu membayarnya.',
    concept_body_id = 'Utang adalah uang yang kamu pinjam dan berjanji membayarnya kembali nanti, biasanya dengan biaya tambahan yang disebut bunga. Utang menjadi jebakan ketika bunga atau denda keterlambatan tumbuh lebih cepat dari pendapatanmu. Di Indonesia, aplikasi PayLater, pinjaman online (pinjol), dan kartu kredit membuat berhutang terasa mudah, tapi ketinggalan satu pembayaran bisa membuat saldo membengkak.

Strategi teraman adalah menghindari berhutang untuk barang-barang yang cepat kehilangan nilai, seperti pakaian atau gadget. Jika kamu sudah punya utang berbunga tinggi, jalan keluar tercepat biasanya adalah membayar utang dengan bunga tertinggi terlebih dahulu sambil membayar minimum pada utang lainnya. Ini disebut metode avalanche. Tujuannya adalah menghentikan pertumbuhan utang sebelum menguasai anggaran bulananmu. Membayar hanya minimum biasanya adalah jalan paling lambat dan paling mahal. Pembayaran minimum dirancang untuk membuatmu tetap berhutang lebih lama karena bunganya terus tumbuh. Jika kamu hanya membayar minimum pada pinjaman berbunga tinggi, kamu mungkin akhirnya membayar lebih banyak bunga daripada jumlah pinjaman awal. Itulah mengapa menghentikan pertumbuhan adalah prioritas pertama.',
    why_this_matters_id = 'Satu utang kecil bisa menelan seluruh anggaran bulananmu. Memahami cara utang tumbuh membantumu menolak berhutang untuk keinginan.',
    common_mistake_id = 'Menggunakan PayLater atau kartu kredit untuk keinginan tanpa membaca suku bunga dan tanggal jatuh tempo.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'debt-traps';

UPDATE lessons
SET summary_id = 'Tujuan yang jelas dengan nominal dan tenggat waktu mengubah keinginan menjadi rencana yang bisa dicapai.',
    concept_body_id = 'Tujuan keuangan adalah target yang kamu tetapkan untuk uangmu. Tujuan yang baik spesifik, punya nominal, dan punya tenggat waktu. Tujuan kabur seperti ''menabung lebih banyak'' jarang berhasil karena tidak ada cara mengukur kemajuan. Tujuan yang lebih baik adalah ''menabung Rp 5.000.000 untuk laptop pada Desember.''

Tujuan biasanya dikelompokkan berdasarkan waktu. Tujuan jangka pendek adalah di bawah satu tahun, seperti membeli ponsel. Tujuan jangka menengah adalah satu hingga lima tahun, seperti membangun dana darurat atau membiayai kursus. Tujuan jangka panjang adalah lebih dari lima tahun, seperti memulai bisnis atau membangun dana pensiun. Memecah tujuan besar menjadi tabungan bulanan membuatnya terasa mungkin. Menuliskan tujuan dan melacak kemajuan setiap bulan secara dramatis meningkatkan peluang keberhasilan. Membagikan tujuan dengan teman atau anggota keluarga yang dipercaya bisa meningkatkan akuntabilitas. Kamu juga bisa menggunakan pengingat visual, seperti pelacak tabungan di ponsel. Semakin konkret tujuannya, semakin mudah menolak godaan kecil yang akan menundanya.',
    why_this_matters_id = 'Tujuan yang jelas memberi tujuan pada anggaranmu. Mereka membuat menolak belanja impulsif lebih mudah karena kamu tahu apa yang sedang kamu pilih.',
    common_mistake_id = 'Menetapkan tujuan kabur seperti ''menabung lebih banyak'' tanpa angka atau tenggat waktu, lalu merasa buntu ketika tidak ada yang berubah.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'goal-setting-101';

UPDATE lessons
SET summary_id = 'Imbal hasil tinggi yang dijamin tanpa risiko tidak ada; janji itu adalah tanda penipuan klasik.',
    concept_body_id = 'Jika sebuah investasi menjanjikan imbal hasil tinggi, risiko nol, dan tekanan untuk merekrut teman, itu hampir pasti penipuan. Dalam keuangan, imbal hasil dan risiko saling terhubung. Siapa pun yang menjanjikan keuntungan pasti berbohong atau menyembunyikan risikonya. OJK secara rutin memperingatkan masyarakat tentang investasi ilegal yang menggunakan trik persis ini.

Tiga tanda bahaya yang perlu diingat adalah imbal hasil dijamin, tanpa risiko, dan bonus perekrutan. Berinvestasi nyata melibatkan ketidakpastian, dan bahkan produk yang teregulasi bisa kehilangan nilai. Respons teraman adalah berhenti, memeriksa izin OJK, dan mengabaikan rasa takut ketinggalan (FOMO). Tidak ada peluang yang sah yang hilang dalam dua jam. Jika kamu merasa dipaksa, itu adalah sinyal untuk mundur. Penipu sering menggunakan testimoni palsu, foto mewah, dan tenggat waktu mendesak untuk menggoyahkan penilaianmu. Mereka menargetkan anak muda yang baru berinvestasi dan ingin cepat mengembangkan uangnya. Ingatlah bahwa membangun kekayaan biasanya lambat; apa pun yang menjanjikan kecepatan pantas mendapat kecurigaan ekstra.',
    why_this_matters_id = 'Satu penipuan bisa menghabiskan tabungan dan kepercayaanmu pada uang. Mengetahui tanda bahaya sejak dini melindungi dirimu dan teman-temanmu.',
    common_mistake_id = 'Bergabung dengan investasi karena teman bergabung, tanpa memeriksa apakah produk tersebut berizin OJK.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'too-good-to-be-true';

UPDATE lessons
SET summary_id = 'Selalu verifikasi bahwa produk keuangan berizin OJK sebelum mengirim uang.',
    concept_body_id = 'OJK, Otoritas Jasa Keuangan, melisensi dan mengawasi bank, perusahaan asuransi, manajer investasi, dan banyak produk investasi. Produk yang tidak terdaftar di situs web OJK adalah ilegal dan tidak dilindungi. Jika perusahaan gagal atau lari dengan uangmu, peluang pemulihanmu sangat kecil.

Sebelum berinvestasi, kunjungi situs web resmi OJK dan gunakan alat pencarian Waspada Investasi atau pengecekan izin. Periksa nama perusahaan, nama produk, dan nomor izin. Jika seorang penjual sah, mereka tidak akan memaksamu untuk melewati langkah ini. Menghabiskan lima menit untuk memverifikasi bisa menyelamatkanmu dari kehilangan segalanya. Kebiasaan memeriksa sebelum mengirim uang adalah perlindungan paling penting yang bisa dibangun oleh investor berusia 18 tahun. Jangan percaya tangkapan layar atau tautan yang dikirim penjual, karena itu bisa dipalsukan. Selalu ketik alamat situs web resmi OJK sendiri atau gunakan bookmark. Jika produknya sah, pengecekan izin akan cepat. Jika tidak, kamu baru saja menyelamatkan diri dari penipuan.',
    why_this_matters_id = 'Memeriksa izin hanya membutuhkan menit tapi mencegah kerugian yang bisa memakan waktu bertahun-tahun untuk pulih. Ini adalah kebiasaan investasi paling penting yang bisa kamu bangun.',
    common_mistake_id = 'Mempercayai teman, influencer, atau tangkapan layar tanpa memverifikasi produk di situs resmi OJK.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'check-ojk-license';
-- Indonesian translations for Batch 3 (lessons 17-24)
-- Generated for Koinaku lesson content

UPDATE lessons
SET summary_id = 'Penipu menyamar jadi orang atau lembaga yang kita percaya untuk mencuri data dan uangmu.',
    concept_body_id = 'Phishing adalah pesan palsu yang dibuat untuk mencuri data pribadi, kata sandi, atau OTP-mu. Rekayasa sosial adalah saat penipu memanipulasimu secara emosional, misalnya dengan berpura-pura jadi teman, keluarga, petugas bank, atau pejabat pemerintah. Serangan ini sering membuat situasi terasa genting: ''rekeningmu akan diblokir'' atau ''paketmu macet.''

Tanggapan paling aman adalah jangan buru-buru. Jangan klik link di pesan yang tidak kamu duga. Jangan bagikan OTP, PIN, atau kata sandi. Jika pesan itu mengaku dari bank, buka aplikasi bank resmi atau hubungi nomor resmi, bukan membalas pesan tersebut. Bank sungguhan tidak akan pernah meminta OTP-mu. Jika ragu, berhenti dan verifikasi lewat jalur yang kita percaya. Penipu juga sering menyamar jadi kurir, toko online, bahkan gebetan. Mereka biasanya minta bantuan kecil dulu untuk membangun kepercayaan. Begitu seseorang meminta PIN, OTP, atau kata sandi, percakapan harus diakhiri. Tidak ada lembaga terpercaya yang akan meminta hal itu.',
    why_this_matters_id = 'Satu OTP yang dicuri bisa mengosongkan rekeningmu dalam hitungan detik. Belajar mengenali phishing melindungi uang, identitas, dan ketenangan pikiranmu.',
    common_mistake_id = 'Mengklik link di SMS atau WhatsApp tanpa memeriksa pengirimnya, apalagi saat pesan itu membuat panik.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'phishing-social-engineering';

UPDATE lessons
SET summary_id = 'Bisnis sungguhan menghasilkan uang dari pelanggan; skema piramida menghasilkan uang dari perekrutan.',
    concept_body_id = 'Bisnis multi-level marketing yang sah utamanya menghasilkan uang dengan menjual produk nyata ke pelanggan nyata. Skema piramida utamanya menghasilkan uang dengan merekrut anggota baru yang membayar biaya atau membeli stok. Skema piramida akan runtuh saat perekrutan melambat karena tidak cukup orang baru untuk membayar yang lama.

Tanda-tanda waspada antara lain: penghasilan terutama dari merekrut, dipaksa membeli paket stok besar, janji kaya instan, dan tekanan untuk cepat merekrut teman serta keluarga. Jika penghasilan lebih bergantung pada ajakan orang masuk daripada penjualan produk, besar kemungkinan itu skema piramida. OJK sudah mengingatkan masyarakat untuk hati-hati dengan tawaran semacam ini. Ingat, bisnis sungguhan bisa bertahan meski tidak ada anggota baru yang bergabung. Tanda bahaya lain adalah saat perusahaan membuatmu enggan mencari tahu sendiri atau bilang yang ragu-ragu itu cuma negatif. Bisnis yang sah justru terbuka terhadap pertanyaan dan punya harga produk yang jelas. Jika model bisnisnya bergantung pada jaringan pertemananmu, patut dicermati dengan saksama.',
    why_this_matters_id = 'Skema piramida bisa merusak pertemanan dan keuangan. Membedakan penjualan produk dan perekrutan melindungimu agar tidak dimanfaatkan orang lain.',
    common_mistake_id = 'Ikut ''peluang bisnis'' hanya karena diminta teman atau keluarga, tanpa cek dulu apakah penghasilannya dari penjualan atau perekrutan.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'mlm-pyramid-red-flags';

UPDATE lessons
SET summary_id = 'Bunga adalah biaya saat meminjam uang atau imbalan saat menyimpannya.',
    concept_body_id = 'Bunga adalah uang tambahan yang kamu bayar saat meminjam, atau uang tambahan yang kamu terima saat menabung atau meminjamkan. Saat menyetor uang di bank, bank membayar bunga karena bisa menggunakan uangmu untuk meminjamkan ke orang lain. Saat kamu meminjam, kamu membayar bunga karena pemberi pinjaman melepaskan penggunaan uang tersebut.

Bunga sederhana dihitung hanya dari jumlah pokok. Misalnya, bunga 4% per tahun dari Rp 1.000.000 memberimu Rp 40.000 dalam setahun. Suku bunga penting karena memengaruhi seberapa cepat hutang tumbuh dan seberapa cepat tabungan bertambah. Selalu periksa apakah suku bunganya per tahun, per bulan, atau per hari sebelum membandingkan penawaran. Bunga per bulan yang kelihatan kecil bisa menjadi besar saat dijadikan bunga per tahun. Bunga majemuk pada hutang sangat berbahaya karena jumlah yang kamu utang bisa terus bertambah meski kamu berhenti meminjam. Itulah sebabnya pinjaman dengan bunga tinggi bisa melonjak tak terkendali. Memahami bunga dari dua sisi, sebagai penabung dan peminjam, membantumu menggunakannya dengan bijak dan menghindari jebakan.',
    why_this_matters_id = 'Bunga memengaruhi dua sisi uangmu: yang kamu dapat dari tabungan dan yang kamu bayar untuk hutang. Memahaminya membantumu membandingkan produk secara jujur.',
    common_mistake_id = 'Abaikan apakah suku bunga itu per tahun atau per bulan, sehingga pinjaman terlihat lebih murah dari kenyataannya.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'interest-101';

UPDATE lessons
SET summary_id = 'Bunga majemuk artinya kamu mendapat bunga dari bunga yang sudah dihasilkan, jadi uangmu tumbuh lebih cepat seiring waktu.',
    concept_body_id = 'Bunga majemuk terjadi saat kamu mendapat bunga bukan hanya dari uang yang pertama kali disimpan, tapi juga dari bunga yang sudah dihasilkan uang itu. Ini menciptakan efek bola salju: semakin lama uang dibiarkan, semakin cepat pertumbuhannya. Dua faktor paling penting adalah waktu dan suku bunga.

Memulai lebih awal lebih berarti daripada memulai dalam jumlah besar. Tabungan kecil yang dimulai awal bisa tumbuh lebih besar dari tabungan besar yang dimulai belakangan karena punya lebih banyak waktu untuk berkembang. Tentu saja, di dunia nyata imbal hasil tidak dijamin dan nilainya bisa turun. Pelajaran ini tentang kekuatan waktu, bukan janji untung. Meski begitu, matematika bunga majemuk adalah salah satu alasan para pengajar keuangan menyarankan anak muda untuk mulai menabung secepatnya. Aturan 72 adalah cara sederhana untuk memperkirakan waktu menggandakan uang: bagi 72 dengan tingkat imbal hasil tahunanmu. Dengan imbal hasil 6% per tahun, uang akan kira-kira berlipat ganda dalam 12 tahun. Ini hanya perkiraan kasar dan bukan jaminan, tapi menunjukkan mengapa waktu sangat kuat bila dipadukan dengan bunga majemuk.',
    why_this_matters_id = 'Di usia 18, waktu adalah keunggulan terbesarmu. Memulai dengan nominal kecil sekarang bisa mengalahkan memulai besar nanti, berkat bunga majemuk.',
    common_mistake_id = 'Menunggu gaji besar baru mulai menabung, tanpa sadar bahwa waktu yang hilang tidak bisa dibeli kembali.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'compound-interest-101';

UPDATE lessons
SET summary_id = 'Bank melindungi uang jangka pendek; investasi bisa menumbuhkan uang jangka panjang tapi punya risiko.',
    concept_body_id = 'Rekening bank adalah tempat menyimpan uang yang aman dan mudah diambil. Tabungan dan deposito biasanya memberikan bunga lebih rendah dan stabil, serta dilindungi oleh program seperti LPS dalam batas tertentu. Investasi seperti saham, obligasi, atau reksa dana menawarkan peluang imbal hasil lebih tinggi tapi juga risiko nilai merosot.

Tempat yang tepat bergantung pada kapan kamu butuh uangnya. Uang yang segera dibutuhkan, seperti uang kuliah bulan depan atau dana darurat, sebaiknya disimpan di bank. Uang yang tidak akan dibutuhkan bertahun-tahun ke depan bisa dipertimbangkan untuk investasi, karena kamu punya waktu untuk pulih dari penurunan jangka pendek. Jangan pernah mencampur dua tujuan ini. Menaruh dana darurat di saham bisa memaksamu menjual saat rugi, sementara menyimpan uang jangka panjang seperti tabungan pensiun di rekening bunga rendah bisa membuat inflasi memakannya perlahan. Likuiditas artinya seberapa cepat aset bisa diuangkan tanpa kehilangan nilai berarti. Tabungan bank sangat likuid. Saham dan reksa dana kurang likuid karena harganya berubah setiap hari dan menjual saat panik bisa berarti kerugian. Padankan likuiditas dengan tujuanmu agar tidak terpaksa menjual di waktu yang salah.',
    why_this_matters_id = 'Memilih tempat yang salah untuk uangmu bisa berarti melewatkan pertumbuhan atau terpaksa menjual dengan rugi. Padankan alat keuangan dengan tujuannya.',
    common_mistake_id = 'Menaruh uang yang segera dibutuhkan ke investasi berisiko, berharap untung cepat sebelum tenggat waktu yang sudah pasti.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'bank-vs-investment';

UPDATE lessons
SET summary_id = 'Potensi imbal hasil yang lebih tinggi biasanya datang dengan risiko lebih besar; tidak ada cara aman untuk kaya cepat.',
    concept_body_id = 'Imbal hasil adalah uang yang kamu dapat atau rugi dari investasi seiring waktu. Risiko adalah kemungkinan imbal hasil aktual lebih buruk dari perkiraan. Secara umum, investasi dengan potensi imbal hasil lebih tinggi juga membawa risiko lebih besar. Ini sering disebut trade-off risiko dan imbal hasil.

Tidak ada makan siang gratis di dunia keuangan. Jika ada yang menjanjikan imbal hasil tinggi dengan risiko kecil atau tanpa risiko, kemungkinan mereka menyembunyikan sesuatu atau menjalankan penipuan. Instrumen aman seperti deposito bank melindungi uangmu tapi biasanya tumbuh pelan. Instrumen berisiko seperti saham atau reksa dana saham bisa tumbuh lebih cepat tapi nilainya juga bisa turun tajam. Tugasmu adalah memadankan tingkat risiko dengan tujuan dan kemampuanmu menahan kerugian tanpa panik. Toleransi risiko itu pribadi. Bergantung pada stabilitas penghasilan, tujuan, dan reaksimu saat rugi. Dua orang seumuran bisa punya profil risiko yang sangat berbeda. Tidak ada satu jawaban benar, tapi ada proses yang benar: sesuaikan risiko dengan tujuan dan kenyamananmu.',
    why_this_matters_id = 'Memahami risiko dan imbal hasil membantumu menghindari penipuan dan memilih instrumen yang cocok dengan tujuanmu tanpa panik.',
    common_mistake_id = 'Mengejar imbal hasil tertinggi tanpa bertanya berapa banyak uang yang bisa hilang dan kapan uang itu dibutuhkan.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'risk-return-101';

UPDATE lessons
SET summary_id = 'Menyebarkan uang ke berbagai aset mengurangi kerugian saat salah satunya turun.',
    concept_body_id = 'Diversifikasi artinya menyebarkan uang ke berbagai investasi, industri, atau jenis aset agar satu peristiwa buruk tidak menghabiskan semuanya. Jika semua uangmu di satu saham dan perusahaan itu terlibat skandal, kamu bisa rugi besar. Jika uangmu tersebar di banyak saham, obligasi, dan tunai, satu masalah punya dampak lebih kecil.

Diversifikasi tidak menjamin untung atau menghilangkan semua risiko. Pasar masih bisa turun secara luas. Tapi diversifikasi mengurangi risiko bahwa satu kesalahan atau berita buruk akan menghancurkan tabunganmu. Pelajaran berikutnya akan menunjukkan bagaimana reksa dana bisa jadi cara mudah untuk diversifikasi bagi pemula. Idenya sederhana: jangan biarkan satu hari buruk menentukan masa depan keuanganmu. Korelasi artinya seberapa erat dua investasi bergerak bersama. Jika kamu punya banyak saham bank, mereka bisa turun bersamaan saat krisis perbankan. Diversifikasi sejati berarti memiliki aset yang tidak semuanya bereaksi sama terhadap berita yang sama. Itulah sebabnya mencampur saham, obligasi, dan tunai bisa membantu.',
    why_this_matters_id = 'Diversifikasi melindungimu dari kepercayaan berlebihan pada satu perusahaan, satu tren, atau satu tips saham dari influencer.',
    common_mistake_id = 'Menaruh semua tabungan ke satu saham atau kripto hanya karena teman atau kreator TikTok bilang harganya akan naik.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'diversification-101';

UPDATE lessons
SET summary_id = 'Reksa dana mengumpulkan uang dari banyak orang dan menginvestasikannya melalui manajer berizin.',
    concept_body_id = 'Reksa dana, atau mutual fund, adalah kumpulan uang dari banyak investor yang dikelola oleh manajer investasi berizin. Saat kamu membeli unit reksa dana, kamu memiliki bagian kecil dari keseluruhan dana. Dana itu diinvestasikan dalam campuran aset sesuai aturan yang berlaku.

Tiga jenis utama adalah reksa dana pasar uang, yang paling aman dan paling likuid; reksa dana pendapatan tetap, yang berinvestasi di obligasi dan menawarkan risiko sedang; serta reksa dana saham, yang berinvestasi di saham dan membawa risiko lebih tinggi dengan potensi imbal hasil lebih besar. Reksa dana bisa jadi cara sederhana untuk diversifikasi karena uangmu tersebar di banyak aset meski kamu hanya menginvestasikan nominal kecil. Biaya dan kinerja masa lalu perlu dicek, tapi tidak menjamin hasil di masa depan. Setiap unit reksa dana memiliki nilai aktiva bersih, atau NAV, yang mencerminkan total nilai investasi dana dibagi jumlah unit. NAV berubah seiring perubahan investasi di dalamnya. Saat membeli atau menjual, kamu memperdagangkan unit dengan NAV terkini, bukan langsung memiliki saham atau obligasi di dalamnya.',
    why_this_matters_id = 'Reksa dana memungkinkan pemula mulai dengan nominal kecil, diversifikasi, dan mengandalkan manajer berizin daripada menebak-nebak saham yang harus dibeli.',
    common_mistake_id = 'Memilih reksa dana hanya berdasarkan imbal hasil tinggi tahun lalu, tanpa memeriksa jenis dana dan tingkat risikonya.',
    quiz_data_id = NULL::jsonb
WHERE slug = 'reksa-dana-basics';
-- Indonesian translations for Batch 4 (lessons 25-32)
-- Generated by translator agent

UPDATE lessons SET
  summary_id = 'Saham itu bagian kecil dari kepemilikan sebuah perusahaan.',
  concept_body_id = 'Saham, atau stock, adalah bagian kepemilikan dalam sebuah perusahaan. Saat kamu membeli saham, kamu jadi salah satu pemilik perusahaan itu, meski bagiannya kecil. Sebagai pemilik, kamu bisa untung kalau perusahaan berkembang dan makin berharga, tapi juga bisa rugi kalau performanya jelek.

Harga saham berubah karena pembeli dan penjual punya pendapat berbeda soal nilai perusahaan. Kalau yang mau beli lebih banyak dari yang mau jual, harga cenderung naik. Kalau yang mau jual lebih banyak, harga cenderung turun. Punya saham bukan judi, tapi juga bukan cara cepat pasti cuan. Ini adalah kepemilikan dalam bisnis nyata, dan nilai bisnis itu berubah seiring perubahan dunia. Perusahaan juga bisa membagikan dividen, yaitu bagian dari laba yang dibagikan ke pemegang saham. Tidak semua perusahaan membagikan dividen; ada yang menyimpan laba untuk berkembang lebih cepat. Sebagai pemegang saham, kamu punya klaim atas aset dan penghasilan perusahaan sesuai jumlah saham yang kamu miliki, meski ini bukan berarti kamu bisa masuk kantor dan menyuruh-nyuruh.',
  why_this_matters_id = 'Memahami saham sebagai kepemilikan, bukan cuma angka di layar, membantu kamu riset perusahaan alih-alih ikut-ikutan pergerakan harga.',
  common_mistake_id = 'Beli saham karena harganya naik terus, padahal belum tahu apa yang sebenarnya dilakukan perusahaan itu.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'what-is-a-stock';

UPDATE lessons SET
  summary_id = 'IDX punya aturan jelas: saham diperdagangkan dalam lot 100 lembar, dan ada program perlindungan investor untuk efek yang tercatat.',
  concept_body_id = 'IDX adalah singkatan dari Bursa Efek Indonesia, tempat saham dan efek lain diperdagangkan secara teregulasi. Di IDX, saham dibeli dan dijual dalam satuan lot, dan satu lot standar adalah 100 lembar saham. Artinya, kamu tidak bisa beli hanya satu lembar saham perusahaan tercatat; minimal harus beli satu lot.

Perdagangan IDX berlangsung di hari kerja, biasanya Senin sampai Jumat. Ada juga mekanisme perlindungan investor, seperti SIPF (Securities Investor Protection Fund), yang memberikan perlindungan bagi investor di efek tercatat dalam batas tertentu. Aturan-aturan ini ada supaya perdagangan adil dan investor kecil terlindungi. Mengetahui aturan sebelum bertransaksi mencegah order ditolak dan kebingungan. Sebelum bisa transaksi di IDX, kamu perlu rekening efek di sekuritas yang terdaftar di OJK. Sekuritas berfungsi sebagai gerbang kamu ke bursa. Selalu pastikan sekuritasmu berizin, karena sekuritas tanpa izin tidak dilindungi SIPF atau pengawasan OJK.',
  why_this_matters_id = 'Memahami aturan IDX sebelum transaksi mencegah order ditolak dan kebingungan soal berapa uang yang sebenarnya dibutuhkan untuk beli saham.',
  common_mistake_id = 'Coba beli saham IDX kurang dari 100 lembar dan tidak mengerti kenapa ordernya ditolak.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'idx-basics-101';

UPDATE lessons SET
  summary_id = 'Ringkasan saham menunjukkan rentang harga, harga penutupan, volume perdagangan, dan nilai total perusahaan.',
  concept_body_id = 'Halaman saham menampilkan angka-angka yang menggambarkan bagaimana saham bertransaksi dalam sehari. Open adalah harga di awal perdagangan. High adalah harga tertinggi yang tercapai. Low adalah harga terendah yang tercapai. Close adalah harga terakhir sebelum pasar tutup. Volume adalah jumlah saham yang berpindah tangan. Market capitalization, atau kapitalisasi pasar, adalah nilai total seluruh saham perusahaan dikalikan harga saat ini.

Angka-angka ini menggambarkan aktivitas, bukan kualitas. Volume tinggi berarti banyak yang bertransaksi hari itu. Harga tinggi tidak otomatis berarti perusahaan bagus. Membaca halaman saham adalah keterampilan, bukan alat prediksi. Selalu lihat gambaran lengkap dan gunakan berbagai sumber sebelum mengambil keputusan. Satu angka tidak pernah menceritakan seluruh cerita. Kapitalisasi pasar membantu kamu memahami ukuran perusahaan, bukan apakah sahamnya murah atau mahal. Saham Rp 1.000 bisa terlalu mahal, dan saham Rp 10.000 bisa sepadan. Harga saja tidak menunjukkan nilai. Gabungkan data halaman saham dengan informasi perusahaan sebelum membuat opini.',
  why_this_matters_id = 'Membaca halaman saham membantu kamu beralih dari tebak-tebakan ke pengamatan. Ini keterampilan dasar sebelum riset atau simulasi.',
  common_mistake_id = 'Menganggap saham yang lonjak harganya besar atau volumenya tinggi otomatis bagus dibeli.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'reading-a-stock-page';

UPDATE lessons SET
  summary_id = 'Portofolio adalah gabungan seluruh kepemilikanmu, dan komposisinya harus sesuai dengan tujuanmu.',
  concept_body_id = 'Portofolio adalah gabungan dari semua aset keuangan yang kamu miliki, seperti tunai, tabungan, reksa dana, dan saham. Berpikir portofolio berarti melihat gambaran besar, bukan menilai satu-satu aset sendiri. Satu saham mungkin berisiko, tapi porsi kecil saham dalam portofolio yang lebih besar bisa masuk akal.

Komposisi yang tepat tergantung pada tujuan dan jangka waktumu. Uang yang segera dibutuhkan sebaiknya disimpan di tempat yang aman dan mudah diakses. Uang yang tidak dibutuhkan bertahun-tahun bisa memuat lebih banyak aset pertumbuhan. Seiring perubahan tujuan, komposisi portofoliomu perlu ditinjau ulang. Ini bukan soal memilih pemenang; ini soal membangun rencana yang cocok dengan kehidupanmu dan membuatmu tetap tenang saat pasar bergejolak. Rebalancing artinya menyesuaikan komposisi kembali ke target dari waktu ke waktu. Misalnya, kalau saham sedang bagus dan sekarang porsinya lebih besar dari rencana, kamu bisa menjual sebagian dan pindahkan ke aset yang lebih aman. Ini menjaga tingkat risikomu tetap selaras dengan rencana awal.',
  why_this_matters_id = 'Berpikir portofolio membantumu menghindari jebakan menaruh semua uang ke satu saham hits lalu panik saat harganya turun.',
  common_mistake_id = 'Menilai kesehatan keuangan hanya dari satu saham, sementara tunai, utang, dan kepemilikan lain diabaikan.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'portfolio-thinking';

UPDATE lessons SET
  summary_id = 'Keuntungan investasi bisa kena pajak, jadi imbal hasil yang kamu bawa pulang bisa lebih rendah dari angka yang tertera.',
  concept_body_id = 'Saat kamu menghasilkan uang dari investasi, pemerintah bisa mengambil sebagian sebagai pajak. Di Indonesia, jenis imbal hasil yang berbeda bisa kena pajak berbeda. Misalnya, bunga deposito dan dividen saham keduanya bisa kena pajak. Jumlah yang benar-benar kamu simpan setelah pajak disebut imbal hasil bersih, sedangkan jumlah sebelum pajak disebut imbal hasil kotor.

Aturan pajak bisa berubah, dan detailnya tergantung situasimu dan jenis rekeningnya. Pelajarannya, bandingkan investasi menggunakan imbal hasil bersih, bukan cuma imbal hasil kotor yang diiklankan. Membayar pajak adalah kewajiban hukum, tapi kamu bisa menyusun keuangan dengan bijak dalam aturan yang berlaku. Untuk saran spesifik, konsultasikan dengan konsultan pajak atau panduan resmi dari Direktorat Jenderal Pajak. Beberapa tabungan jangka panjang mungkin punya insentif pajak menurut aturan Indonesia, tapi aturannya bisa berubah. Selalu cek peraturan terbaru dari Ditjen Pajak atau penasihat yang berkualifikasi. Poin utamanya, anggap investasi sebagai permainan imbal hasil bersih, di mana yang kamu simpan lebih penting dari yang kamu dapat di atas kertas.',
  why_this_matters_id = 'Mengabaikan pajak bisa membuat investasi terlihat lebih bagus dari kenyataannya. Imbal hasil bersih lah yang penting untuk kekayaanmu.',
  common_mistake_id = 'Bandingkan investasi hanya dari imbal hasil kotor yang diiklankan tanpa mempertimbangkan pajak dan biaya.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'taxes-on-returns';

UPDATE lessons SET
  summary_id = 'Sinyal besar seperti BI Rate, inflasi, dan nilai tukar memengaruhi harga, bunga, dan daya belimu.',
  concept_body_id = 'Indikator makro adalah sinyal skala besar yang menggambarkan kesehatan ekonomi. Tiga yang penting di Indonesia adalah BI Rate, yaitu suku bunga acuan Bank Indonesia; inflasi, yang mengukur seberapa cepat harga naik; dan nilai tukar, yang menunjukkan berapa rupiah dibutuhkan untuk membeli satu dolar AS atau mata uang lain.

Indikator ini memengaruhi uangmu secara tidak langsung. Saat BI menaikkan BI Rate, bunga deposito bank bisa naik, tapi meminjam jadi lebih mahal dan harga saham bisa lebih volatil. Saat rupiah melemah terhadap dolar AS, gadget impor dan BBM bisa jadi lebih mahal. Kamu tidak bisa mengendalikan indikator ini, tapi memahami keberadaannya membantumu mengerti kenapa harga dan nilai investasi bergerak tanpa harus bereaksi ke setiap berita. Kamu tidak perlu memprediksi indikator ini dengan sempurna. Ekonom profesional saja sering berselisih. Yang penting adalah mengenali arah umumnya supaya kamu tidak kaget saat bunga deposito naik, cicilan kredit melonjak, atau harga impor berubah. Tetap update informasi, tapi tetap fokus pada rencanamu sendiri.',
  why_this_matters_id = 'Indikator makro menjelaskan kebisingan latar belakang soal harga dan imbal hasil investasi. Memahaminya membantumu fokus pada apa yang bisa kamu kendalikan, bukan panik karena berita.',
  common_mistake_id = 'Mencoba menentukan waktu investasi sempurna berdasarkan berita makro, padahal bahkan ahli pun biasanya gagal melakukannya.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'macro-indicators';

UPDATE lessons SET
  summary_id = 'Emosimu bisa mendorongmu ikut-ikutan kerumunan, takut rugi, atau kejar tren tanpa berpikir.',
  concept_body_id = 'Bias perilaku artinya jalan pintas berpikir yang bisa mengarah ke keputusan finansial buruk. Tiga bias umum adalah FOMO, atau fear of missing out, yang membuatmu membeli sesuatu hanya karena orang lain juga beli; loss aversion, yang membuat rasa sakit rugi uang terasa lebih kuat daripada senangnya dapat uang dalam jumlah sama; dan herd behavior, yang membuatmu mengikuti kerumunan tanpa riset sendiri.

Bias-bias ini wajar, tapi bisa mahal. Pertahanan terbaik adalah melambat, menuliskan alasan keputusanmu, dan mengeceknya dengan tujuanmu. Kalau kamu beli karena tren viral, itu sinyal untuk berhenti sejenak. Investasi yang bagus biasanya membosankan, sementara investasi buruk sering terasa seru. Kesadaran tidak menghilangkan emosi, tapi memberimu kesempatan untuk memutuskan pakai kepala juga, bukan cuma perasaan. Salah satu teknik praktis adalah menetapkan aturan investasi sebelumnya, seperti hanya beli setelah membaca laporan tahunan perusahaan atau hanya investasi dalam jumlah tetap setiap bulan. Aturan mengurangi jumlah keputusan emosional yang harus kamu ambil di saat itu, yaitu saat bias paling kuat.',
  why_this_matters_id = 'Mengenali bias dirimu sendiri adalah salah satu keterampilan investasi paling berharga. Ini melindungimu dari hype, panik, dan penyesalan.',
  common_mistake_id = 'Beli investasi karena terasa urgent atau populer, tanpa memeriksa apakah cocok dengan rencanamu.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'behavioral-bias-intro';

UPDATE lessons SET
  summary_id = 'Rencana keuangan menyusun tujuan, dana darurat, utang, perlindungan, dan investasi dalam satu urutan yang jelas.',
  concept_body_id = 'Rencana keuangan adalah peta sederhana soal ke mana uangmu harus pergi. Bagi kebanyakan anak muda Indonesia, langkah awalnya adalah: penuhi kebutuhan dasar, bangun dana darurat kecil, lunasi utang berbunga tinggi, lindungi diri dengan perlindungan kesehatan seperti BPJS Kesehatan atau asuransi kesehatan swasta kalau memungkinkan, dan baru setelah itu pertimbangkan investasi. Urutannya penting karena tidak ada gunanya mengejar imbal hasil investasi sementara dana darurat atau utang berbunga tinggi bisa menghapuskan hasilnya.

Rencanamu harus sesuai dengan kehidupanmu. Kalau tidak punya utang dan ada dukungan keluarga, kamu mungkin bisa mulai investasi lebih cepat. Kalau penghasilan tidak stabil, bangun dana darurat lebih besar dulu. Tinjau rencanamu setiap beberapa bulan seiring perubahan pendapatan, tujuan, dan tanggung jawab. Rencana bukan dokumen satu kali; ini kebiasaan mengecek posisimu dan langkah selanjutnya. Perlindungan mencakup perlindungan kesehatan seperti BPJS Kesehatan dan, di kemudian hari, asuransi jiwa kalau sudah punya tanggungan. Di usia 18, perlindungan paling penting biasanya adalah kesehatan, karena satu tagihan rumah sakit bisa menghabiskan tabungan. Setelah fondasi ini kuat, investasi jadi cara menumbuhkan uang, bukan judi.',
  why_this_matters_id = 'Rencana mengubah saran keuangan acak jadi tindakan pribadi. Ini membantumu tahu apa yang harus dilakukan selanjutnya, sekecil apa pun pendapatanmu.',
  common_mistake_id = 'Langsung terjun investasi sebelum punya dana darurat atau melunasi utang berbunga tinggi.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'building-financial-plan';
