-- Indonesian (Bahasa Indonesia) translations for Koinaku lessons Batch 1 (lessons 1-8).
-- Generated from .loop/lesson-bodies-v2.json and .loop/lesson-variants-v2.json.

UPDATE lessons SET
  summary_id = 'Uang adalah alat yang membuat perdagangan, menabung, dan perencanaan jadi mungkin.',
  concept_body_id = 'Uang adalah apa saja yang umum diterima orang sebagai pembayaran barang dan jasa. Dalam kehidupan sehari-hari, uang punya tiga peran. Pertama, sebagai alat tukar: alih-alih menukar mie ayammu langsung dengan charger ponsel, kamu pakai rupiah. Kedua, sebagai penyimpan nilai: uang memungkinkanmu menabung hari ini dan berbelanja besok. Ketiga, sebagai satuan hitung: uang memberi harga pada semua barang sehingga kamu bisa membandingkan nilai dengan cepat.

Uang tunai, saldo GoPay, transfer bank, dan pembayaran QRIS semuanya adalah bentuk uang karena penjual menerimanya. Uang hanya berfungsi karena orang percaya padanya. Kepercayaan itu didukung oleh Bank Indonesia yang menerbitkan rupiah dan menjaga kestabilannya. Tanpa bentuk uang bersama, perdagangan harus dilakukan dengan barter, yang lambat dan merepotkan ketika penjual tidak menginginkan apa yang kamu miliki. Memahami tiga peran ini membuat pelajaran tentang inflasi, menabung, dan berinvestasi jadi lebih mudah diikuti. Mengenali tiga peran ini juga membantumu melihat mengapa menyimpan semua uang dalam bentuk tunai bukanlah satu-satunya pilihan, dan mengapa pembayaran digital bekerja sama baiknya dengan uang kertas di sebagian besar toko di Indonesia.',
  why_this_matters_id = 'Kalau kamu paham apa itu uang sebenarnya, kamu bisa memutuskan di mana menyimpannya, kapan membelanjakannya, dan kapan membiarkannya tumbuh alih-alih dibiarkan menganggur.',
  common_mistake_id = 'Berpikir uang hanya berupa uang tunai fisik dan mengabaikan dompet digital, saldo bank, serta bentuk pembayaran lain yang diterima.',
  quiz_data_id = '[{"type": "matching", "question": "Pasangkan fungsi uang dengan contohnya.", "pairs": [["Alat tukar", "Bayar mie ayam pakai Rp15.000"], ["Penyimpan nilai", "Menabung Rp500.000 untuk beli sepatu bulan depan"], ["Satuan hitung", "Harga pulpen Rp3.000 dan buku Rp50.000"]], "answer": {"Alat tukar": "Bayar mie ayam pakai Rp15.000", "Penyimpan nilai": "Menabung Rp500.000 untuk beli sepatu bulan depan", "Satuan hitung": "Harga pulpen Rp3.000 dan buku Rp50.000"}, "explanation": "Fungsi uang membantu kita memahami mengapa uang kertas, koin, maupun saldo digital bisa dipakai dalam kehidupan sehari-hari.", "difficulty": "beginner"}, {"type": "true_false", "question": "Saldo GoPay atau OVO tidak termasuk uang karena tidak berbentuk uang kertas.", "answer": false, "explanation": "Saldo elektronik tetap diakui sebagai alat tukar dan satuan hitung, sehingga termasuk bentuk uang digital.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Mengapa uang lebih praktis daripada barter?", "options": ["Karena uang bisa ditukar dengan barang apa saja yang dijual", "Karena uang terbuat dari logam mulia", "Karena barter lebih cepat", "Karena uang tidak bisa hilang"], "answer": "Karena uang bisa ditukar dengan barang apa saja yang dijual", "explanation": "Uang diterima umum, jadi kita tidak perlu mencari orang yang kebetulan membutuhkan barang kita.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Fungsi uang sebagai _____ memungkinkan kita membandingkan harga berbagai barang dengan mudah.", "answer": "satuan hitung", "explanation": "Satuan hitung membuat kita bisa menyatakan nilai barang dalam rupiah sehingga mudah membandingkan harga.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'money-basics-101';

UPDATE lessons SET
  summary_id = 'Rupiah yang sama bisa membeli jumlah berbeda tergantung di mana dan kapan kamu membelanjakannya.',
  concept_body_id = 'Nilai berarti seberapa berguna atau diinginkan sesuatu bagimu. Daya beli berarti seberapa banyak yang bisa kamu beli dengan jumlah uang tertentu. Rp 50.000 yang sama bisa membeli lebih banyak di beberapa tempat dan lebih sedikit di tempat lain karena harganya berbeda. Gaji nominal tinggi tidak selalu berarti hidup kaya jika sewa, makanan, dan transportasi mahal.

Daya beli juga berubah seiring waktu. Jika harga naik, uangmu membeli lebih sedikit. Jika harga turun, uangmu membeli lebih banyak. Hal ini penting saat kamu membandingkan penghasilan, harga, atau tabungan antarkota atau antartahun. Ekonom kadang menggunakan istilah nilai riil untuk menyebut nilai yang sudah disesuaikan dengan daya beli. Jumlah nominal tinggi tidak selalu berarti kamu kaya jika segala sesuatu di sekitarmu mahal. Memahami ini membantumu membandingkan tawaran kerja, merencanakan perjalanan, dan menilai apakah suatu harga wajar. Saat kamu bepergian dari kampung halaman ke Jakarta, kamu mungkin menyadari harga makanan yang sama lebih mahal. Itulah daya beli sedang bekerja. Membandingkan jumlah nominal tanpa memeriksa apa yang bisa dibelinya seperti membandingkan dua pelari berdasarkan ukuran sepatu mereka, bukan kecepatan lari.',
  why_this_matters_id = 'Saat menyusun anggaran atau membandingkan gaji, daya beli memberitahumu kisah nyata di balik angka rupiah tersebut.',
  common_mistake_id = 'Meyakini bahwa gaji lebih besar di kota yang lebih mahal selalu berarti hidup lebih baik, tanpa memeriksa apa yang bisa dibeli oleh gaji tersebut.',
  quiz_data_id = '[{"type": "multiple_choice", "question": "Mie ayam di Jakarta Rp18.000, di Yogyakarta Rp12.000. Manakah pernyataan yang benar tentang Rp50.000?", "options": ["Daya belinya lebih besar di Yogyakarta", "Daya belinya lebih besar di Jakarta", "Daya belinya sama karena nominalnya sama", "Rp50.000 tidak bisa beli mie ayam di dua kota"], "answer": "Daya belinya lebih besar di Yogyakarta", "explanation": "Dengan harga lebih murah, uang yang sama bisa membeli lebih banyak porsi, artinya daya beli lebih besar.", "difficulty": "beginner"}, {"type": "true_false", "question": "Jika harga barang naik, daya beli uang yang kita milai juga naik.", "answer": false, "explanation": "Ketika harga naik, uang yang sama bisa membeli lebih sedikit barang, sehingga daya beli menurun.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Daya beli menunjukkan seberapa _____ barang atau jasa yang bisa dibeli dengan sejumlah uang.", "answer": "banyak", "explanation": "Daya beli mengukur jumlah barang/jasa yang dapat dibeli, bukan hanya nominal uangnya.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Rina punya Rp100.000. Harga novel bekas di toko online Rp25.000, di toko fisik Rp40.000. Berapa perbedaan daya beli dalam jumlah novel?", "options": ["1,5 novel lebih banyak di toko online", "Tidak ada perbedaan", "Novel lebih murah di toko fisik", "Rp100.000 tidak cukup di dua tempat"], "answer": "1,5 novel lebih banyak di toko online", "explanation": "Di toko online Rp100.000 dapat 4 novel; di toko fisik hanya 2,5 novel. Selisihnya 1,5 novel.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'value-and-purchasing-power';

UPDATE lessons SET
  summary_id = 'Inflasi adalah kenaikan harga yang perlahan-lahan memangkas daya beli uang tunaimu.',
  concept_body_id = 'Inflasi adalah kenaikan harga barang dan jasa secara umum seiring waktu. Ketika inflasi terjadi, setiap rupiah membeli lebih sedikit dari sebelumnya. Bank Indonesia menargetkan inflasi rendah dan stabil, sekitar 2,5% plus minus 1% per tahun. Inflasi rendah adalah hal normal dalam ekonomi yang tumbuh, tetapi inflasi tinggi merugikan orang yang menyimpan uang tunai dalam jumlah besar.

Inflasi tidak berarti setiap harga naik dalam jumlah yang sama, tetapi biaya hidup secara keseluruhan cenderung naik. Uang tunai yang disimpan di bawah bantal kehilangan daya beli karena uang yang sama bisa membeli lebih sedikit barang tahun depan. Rekening tabungan yang memberikan bunga bisa memperlambat kerugian ini, tetapi hanya jika suku bunganya lebih tinggi dari inflasi. Itulah mengapa memikirkan inflasi penting sebelum memilih tempat menyimpan tabungan jangka panjang. Melindungi daya beli adalah salah satu alasan utama orang kemudian mempertimbangkan investasi, tetapi hanya setelah mereka membangun kebiasaan menabung yang stabil. Inflasi biasanya disebabkan oleh kombinasi kenaikan permintaan, biaya produksi yang lebih tinggi, dan perubahan jumlah uang beredar. Kamu tidak perlu jadi ekonom, tetapi kamu perlu tahu bahwa inflasi adalah fitur normal ekonomi modern. Bahayanya adalah mengabaikannya, bukan memahaminya.',
  why_this_matters_id = 'Inflasi memengaruhi setiap pilihan menabung dan berbelanja. Mengetahuinya membantumu melindungi uangmu alih-alih membiarkannya menyusut diam-diam.',
  common_mistake_id = 'Menyimpan semua tabungan jangka panjang dalam bentuk tunai dan menganggap nilai nominal uang akan tetap sama selamanya.',
  quiz_data_id = '[{"type": "true_false", "question": "Inflasi berarti harga barang dan jasa naik secara umum dalam jangka waktu tertentu.", "answer": true, "explanation": "Inflasi adalah kenaikan harga umum yang terus-menerus, bukan kenaikan satu barang saja.", "difficulty": "beginner"}, {"type": "true_false", "question": "Menyimpan semua uang di bawah bantal selalu aman dari inflasi.", "answer": false, "explanation": "Uang tunai tidak menghasilkan bunga, sehingga daya belinya menurun saat inflasi positif.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Bank Indonesia menargetkan inflasi sekitar _____ persen plus minus satu persen.", "answer": "2,5", "explanation": "Target inflasi BI adalah sekitar 2,5% ± 1% untuk menjaga stabilitas ekonomi.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Jika inflasi 5% per tahun dan tabunganmu bunga 3% per tahun, apa yang terjadi pada daya beli tabunganmu?", "options": ["Daya beli menurun 2%", "Daya beli naik 2%", "Daya beli tetap sama", "Daya beli naik 8%"], "answer": "Daya beli menurun 2%", "explanation": "Inflasi 5% menggerus nilai uang lebih cepat daripada bunga 3% menambahnya, sehingga daya beli riil turun sekitar 2%.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'inflation-101';

UPDATE lessons SET
  summary_id = 'Pendapatan adalah uang yang masuk; kekayaan adalah apa yang kamu simpan dan kembangkan dari waktu ke waktu.',
  concept_body_id = 'Pendapatan adalah aliran uang yang kamu terima, seperti gaji, uang saku, atau bayaran freelance. Kekayaan adalah stok uang dan barang berharga yang sudah kamu miliki, dikurangi apa yang kamu hutang. Seseorang bisa berpendapatan tinggi tetapi kekayaannya rendah jika hampir semua uangnya dibelanjakan. Orang lain bisa berpendapatan lebih rendah tetapi lebih kaya jika ia menabung dan berinvestasi secara konsisten.

Pendapatan mengukur kecepatan; kekayaan mengukur seberapa besar cadangan keuanganmu. Kesehatan finansial jangka panjang lebih bergantung pada apa yang kamu simpan daripada apa yang kamu hasilkan. Itulah mengapa anggaran, mengendalikan hutang, dan membentuk kebiasaan menabung penting di setiap tingkat pendapatan. Kamu bisa membayangkan pendapatan sebagai air yang mengalir ke dalam ember dan kekayaan sebagai air yang sudah ada di dalamnya. Jika ember bocor, aliran yang cepat tidak akan memenuhinya. Memperbaiki kebocoran, menabung lebih banyak, dan menghindari hutang berbunga tinggi itulah yang membangun kekayaan dari waktu ke waktu. Kekayaan juga mencakup barang yang bisa dijual, seperti sepeda motor atau keterampilan berharga, dikurangi hutang yang melekat padanya. Itulah mengapa dua orang dengan gaji yang sama bisa berakhir di posisi finansial yang sangat berbeda. Perbedaannya berasal dari pilihan, bukan hanya dari penghasilan.',
  why_this_matters_id = 'Di usia 18, pendapatanmu mungkin masih kecil, tapi kebiasaan membangun kekayaan bisa dimulai sekarang. Kekayaan dibangun dari apa yang tidak kamu belanjakan.',
  common_mistake_id = 'Menilai kesuksesan finansial hanya dari penghasilan bulanan sambil mengabaikan tabungan, hutang, dan kebiasaan berbelanja.',
  quiz_data_id = '[{"type": "matching", "question": "Pasangkan konsep dengan contohnya.", "pairs": [["Pendapatan", "Gaji Rp4 juta per bulan"], ["Kekayaan", "Tabungan Rp15 juta dikurangi utang Rp2 juta"], ["Pengeluaran", "Bayar kos Rp800 ribu per bulan"]], "answer": {"Pendapatan": "Gaji Rp4 juta per bulan", "Kekayaan": "Tabungan Rp15 juta dikurangi utang Rp2 juta", "Pengeluaran": "Bayar kos Rp800 ribu per bulan"}, "explanation": "Membedakan aliran uang (pendapatan/pengeluaran) dan stok kepemilikan (kekayaan) membantu kita menilai kesehatan keuangan.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Andi gaji Rp8 juta, tabungan nol. Budi gaji Rp4 juta, tabungan Rp15 juta. Siapa yang lebih kaya?", "options": ["Budi", "Andi", "Sama kaya", "Tidak bisa dibandingkan"], "answer": "Budi", "explanation": "Kekayaan diukur dari aset bersih yang dimiliki, bukan dari besarnya gaji.", "difficulty": "beginner"}, {"type": "true_false", "question": "Pendapatan tinggi selalu berarti kekayaan tinggi.", "answer": false, "explanation": "Jika pengeluaran lebih besar dari pendapatan, orang dengan gaji tinggi bisa memiliki kekayaan rendah atau bahkan utang.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Kekayaan bersih dihitung dari total aset dikurangi total _____.", "answer": "utang", "explanation": "Kekayaan bersih = aset - utang. Ini menunjukkan seberapa besar harta yang benar-benar kita miliki.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'income-vs-wealth';

UPDATE lessons SET
  summary_id = 'Menutupi kebutuhan terlebih dahulu membuat keinginan lebih dinikmati dan tidak menekan.',
  concept_body_id = 'Kebutuhan adalah sesuatu yang harus kamu miliki untuk hidup, belajar, atau bekerja dengan aman. Contohnya termasuk makanan, tempat tinggal, transportasi, dan pulsa dasar. Keinginan adalah sesuatu yang ingin kamu miliki tetapi bisa hidup tanpanya, seperti pakaian baru, tiket konser, atau langganan streaming premium.

Garis antara kebutuhan dan keinginan tidak selalu jelas. Misalnya, ponsel dasar adalah kebutuhan untuk kelas online, tetapi ponsel flagship terbaru adalah keinginan. Tujuannya bukan menghilangkan keinginan. Tujuannya adalah menutupi kebutuhan terlebih dahulu, menabung sesuatu berikutnya, lalu berbelanja untuk keinginan tanpa rasa bersalah atau utang. Banyak orang merasa stres karena membeli keinginan terlebih dahulu lalu kesulitan membayar kebutuhan. Membalik urutannya menciptakan ruang napas dan membuat pengeluaran lebih menyenangkan karena kamu tahu hal-hal penting sudah tertangani. Budaya dan media sosial sering mengaburkan garis ini dengan mengubah keinginan menjadi kebutuhan yang dirasakan. Ponsel dasar menjadi kebutuhan ketika kelas beralih ke daring, tetapi warna atau merek baru tetaplah keinginan. Belajar membedakan keduanya memberimu kendali atas uangmu alih-alih membiarkan pengiklan memutuskan untukmu.',
  why_this_matters_id = 'Memahami pembagian ini sejak dini membantumu menghindari kehabisan uang sebelum akhir bulan dan mencegah utang impulsif.',
  common_mistake_id = 'Menyebut setiap keinginan sebagai kebutuhan, lalu bertanya-tanya mengapa tidak ada uang tersisa untuk menabung atau keadaan darurat.',
  quiz_data_id = '[{"type": "ordering", "question": "Urutkan pengeluaran Sari dari yang paling mendesak (kebutuhan) hingga paling bisa ditunda (keinginan).", "options": ["Bayar kos", "Beli pulsa dan kuota", "Langganan streaming", "Beli sepatu baru"], "answer": ["Bayar kos", "Beli pulsa dan kuota", "Langganan streaming", "Beli sepatu baru"], "explanation": "Kos dan pulsa adalah kebutuhan dasar. Streaming dan sepatu baru adalah keinginan yang bisa ditunda.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Manakah yang termasuk kebutuhan bagi pelajar?", "options": ["Pulsa dan kuota internet untuk tugas", "Tiket konser", "Skin game terbaru", "Kopi kekinian setiap hari"], "answer": "Pulsa dan kuota internet untuk tugas", "explanation": "Pulsa dan kuota mendukung aktivitas belajar, sehingga termasuk kebutuhan.", "difficulty": "beginner"}, {"type": "true_false", "question": "Keinginan harus selalu dipenuhi terlebih dahulu agar hidup bahagia.", "answer": false, "explanation": "Kebutuhan dasar harus didahulukan. Keinginan baru dipertimbangkan setelah kebutuhan dan tabungan tercukupi.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Makan siang di kantin termasuk _____, sedangkan makan di kafe mahal setiap hari termasuk keinginan.", "answer": "kebutuhan", "explanation": "Makan untuk bertahan hidup dan belajar adalah kebutuhan, tetapi pilihan tempat mewah adalah keinginan.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'needs-vs-wants-101';

UPDATE lessons SET
  summary_id = 'Aset memasukkan uang ke kantongmu; liabilitas mengeluarkan uang dari kantongmu.',
  concept_body_id = 'Aset adalah sesuatu yang kamu miliki dan bisa memasukkan uang ke kantongmu atau tumbuh nilainya seiring waktu. Liabilitas adalah sesuatu yang kamu hutang atau sesuatu yang menghabiskan uangmu secara rutin. Benda fisik yang sama bisa jadi aset bagi satu orang dan liabilitas bagi orang lain, tergantung cara penggunaannya.

Misalnya, sepeda motor yang dibeli tunai dan digunakan untuk menghasilan sebagai pengemudi ojek online adalah aset karena membantu menghasilkan uang. Sepeda motor yang sama yang dibeli kredit hanya untuk bersenang-senang di akhir pekan adalah liabilitas karena membutuhkan cicilan, bensin, dan perawatan tanpa menghasilkan pemasukan. Bahkan rumah bisa jadi aset jika menghasilkan sewa, atau liabilitas jika cicilan KPR bank dan perawatannya menguras uangmu. Pertanyaan kuncinya adalah: apakah benda ini menambah uangku di masa depan atau menguranginya? Pendidikan dan keterampilan juga bisa jadi aset karena bisa meningkatkan penghasilanmu di masa depan. Namun, mereka baru menjadi aset jika meningkatkan kemampuanmu menghasilkan uang. Kursus atau gelar yang tidak memperbaiki prospek kerjamu bisa menjadi liabilitas jika meninggalkanmu dengan hutang pendidikan yang berat.',
  why_this_matters_id = 'Sebelum membeli sesuatu yang besar, tanyakan apakah benda itu akan menumbuhkan uangmu atau mengurasnya. Kebiasaan ini melindungimu dari utang yang menyamar sebagai gengsi.',
  common_mistake_id = 'Berpikir bahwa barang mahal seperti mobil atau sepeda motor secara otomatis adalah aset, padahal benda itu justru banyak memakan uang.',
  quiz_data_id = '[{"type": "matching", "question": "Pasangkan item dengan kategorinya.", "pairs": [["Aset", "Deposito yang menghasilkan bunga"], ["Liabilitas", "Cicilan motor hanya untuk gaya"], ["Bisa keduanya", "Motorbike yang dipakai kerja dan jalan-jalan"]], "answer": {"Aset": "Deposito yang menghasilkan bunga", "Liabilitas": "Cicilan motor hanya untuk gaya", "Bisa keduanya": "Motorbike yang dipakai kerja dan jalan-jalan"}, "explanation": "Kategori tergantung pada apakah item tersebut memasukkan atau mengeluarkan uang.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Dodi membeli motor untuk jadi ojek online. Eko membeli motor serupa hanya untuk jalan-jalan. Siapa yang lebih mungkin memiliki aset?", "options": ["Dodi", "Eko", "Keduanya sama", "Tidak ada yang benar"], "answer": "Dodi", "explanation": "Motor Dodi menghasilkan pendapatan, sehingga bersifat aset. Motor Eko hanya mengeluarkan biaya.", "difficulty": "beginner"}, {"type": "true_false", "question": "Aset selalu berbentuk barang fisik seperti rumah atau mobil.", "answer": false, "explanation": "Aset bisa berupa uang tunai, deposito, saham, keterampilan, atau bisnis yang menghasilkan uang.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Jika suatu barang mengeluarkan uang terus-menerus tanpa menghasilkan pendapatan, barang itu lebih bersifat _____.", "answer": "liabilitas", "explanation": "Liabilitas menguras uang, seperti cicilan barang konsumtif yang tidak menghasilkan pendapatan.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'assets-vs-liabilities';

UPDATE lessons SET
  summary_id = 'Risiko adalah kemungkinan bahwa kenyataan berakhir lebih buruk dari yang kamu harapkan.',
  concept_body_id = 'Risiko adalah kemungkinan bahwa hasil akan lebih buruk dari yang kamu harapkan. Risiko tidak selalu berarti bahaya; risiko berarti ketidakpastian tentang hasil. Setiap keputusan finansial membawa risiko tertentu, bahkan menyimpan uang tunai di bawah bantal, karena inflasi bisa mengurangi nilainya.

Risiko menjadi lebih mudah dikelola ketika kamu menamainya dengan jelas. Tanyakan pada dirimu: apa yang bisa salah? Seberapa mungkin terjadi? Seberapa buruk dampaknya? Bisakah aku mengurangi kemungkinannya atau membatasi kerugiannya? Menjawab pertanyaan ini sebelum bertindak adalah fondasi perilaku keuangan yang baik. Misalnya, membawa payung mengurangi risiko kehujanan, tetapi tidak menghilangkan kemungkinan hujan. Dalam keuangan, diversifikasi, dana darurat, dan asuransi adalah alat yang mengurangi risiko tertentu tanpa menghilangkan semua ketidakpastian. Kamu bisa memikirkan risiko sebagai memiliki dua bagian: kemungkinan sesuatu yang buruk terjadi, dan seberapa besar kerugiannya jika terjadi. Beberapa risiko layak diambil, seperti berinvestasi pada pendidikanmu. Yang lain tidak, seperti meminjamkan uang kepada orang asing di internet. Keahliannya adalah membedakan keduanya.',
  why_this_matters_id = 'Jika kamu bisa mengenali risiko sejak awal, kamu bisa melindungi tabungan, menghindari penipuan, dan membuat pilihan lebih tenang di bawah tekanan.',
  common_mistake_id = 'Berpikir bahwa menghindari semua keputusan menghilangkan risiko. Tidak melakukan apa-apa dengan uang juga punya risiko, terutama dari inflasi.',
  quiz_data_id = '[{"type": "case_study", "question": "Baca kasus berikut dan pilih respons terbaik.", "caseText": "Rina diminta meminjamkan Rp500.000 kepada teman yang baru beberapa kali bertemu. Teman itu berjanji membayar minggu depan, tetapi Rina mendengar dia sering menunda hutang.", "followUp": {"question": "Apa risiko utama yang dihadapi Rina?", "options": ["Teman tidak membayar kembali", "Rina kehilangan waktu", "Rina kehilangan kesempatan memakai uang itu", "Teman meminjam lagi"], "answer": "Teman tidak membayar kembali", "explanation": "Risiko kredit adalah lawan tidak memenuhi janji pembayaran."}, "answer": "Risiko utama adalah uangnya tidak kembali. Rina bisa meminimalkan risiko dengan meminjam dalam jumlah kecil atau meminta jaminan.", "explanation": "Risiko adalah kemungkinan hasil buruk. Meminjamkan uang kepada seseorang yang sering menunda berarti risiko gagal bayar tinggi.", "difficulty": "beginner"}, {"type": "true_false", "question": "Risiko hanya ada dalam investasi, tidak ada dalam kehidupan sehari-hari.", "answer": false, "explanation": "Risiko ada di mana saja: meminjamkan uang, naik kendaraan, memilih jurusan, bahkan menyimpan uang di rumah.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Manakah contoh risiko dalam kehidupan sehari-hari?", "options": ["Meminjamkan uang tanpa jaminan", "Menyimpan uang di bank berlisensi", "Membeli pulsa di konter resmi", "Membayar uang kos tepat waktu"], "answer": "Meminjamkan uang tanpa jaminan", "explanation": "Meminjamkan uang tanpa jaminan berisiko lawan tidak membayar kembali.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Risiko adalah kemungkinan hasil yang _____ dari yang diharapkan.", "answer": "lebih buruk", "explanation": "Risiko berkaitan dengan hasil negatif atau tidak sesuai harapan yang mungkin terjadi.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'understanding-risk';

UPDATE lessons SET
  summary_id = 'Uang yang tersedia lebih cepat biasanya lebih berharga daripada jumlah yang sama di kemudian hari.',
  concept_body_id = 'Nilai waktu uang berarti menerima jumlah uang yang sama lebih awal umumnya lebih baik daripada menerimanya nanti. Alasannya adalah biaya kesempatan: uang di tanganmu hari ini bisa menutupi kebutuhan, menghasilkan bunga, atau ditabung untuk suatu tujuan. Uang yang dijanjikan di masa depan mungkin tidak pernah datang, dan harga bisa naik sementara kamu menunggu.

Ide ini juga bekerja sebaliknya. Jika kamu meminjam Rp 1.000.000 hari ini, kamu biasanya harus mengembalikan lebih banyak nanti karena pemberi pinjaman melepaskan penggunaan uangnya. Waktu penting karena pilihan dan kepastian penting. Mulai menabung lebih awal memberi bunga majemuk lebih banyak waktu untuk bekerja, itulah sebabnya tabungan kecil yang dimulai di usia 18 bisa tumbuh lebih besar daripada tabungan lebih besar yang dimulai di usia 35. Memahami ini sekarang mempersiapkanmu untuk pelajaran tentang bunga, menabung, dan berinvestasi. Konsep ini juga menjelaskan mengapa pembayaran cicilan sering lebih mahal daripada membayar tunai di muka. Penjual melepaskan penggunaan uangnya, jadi mereka mengenakan biaya tambahan untuk penundaan itu. Setiap kali kamu menunda pembayaran atau penerimaan, nilai waktu uang adalah bagian dari kesepakatan tersebut.',
  why_this_matters_id = 'Waktu memengaruhi nilai uangmu. Mulai menabung lebih awal, membayar utang tepat waktu, dan memilih kapan menerima pembayaran akan lebih jelas dengan model berpikir ini.',
  common_mistake_id = 'Menunggu punya uang besar baru menabung atau berinvestasi, tanpa menyadari bahwa uang kecil yang lebih awal sering tumbuh lebih besar daripada uang besar yang datang belakangan.',
  quiz_data_id = '[{"type": "multiple_choice", "question": "Mengapa uang Rp500.000 yang diterima hari ini lebih baik daripada Rp500.000 yang diterima tiga bulan lagi?", "options": ["Karena bisa langsung dipakai atau ditabung", "Karena nominalnya lebih besar", "Karena uang masa depan tidak berharga", "Karena harga barang pasti turun"], "answer": "Karena bisa langsung dipakai atau ditabung", "explanation": "Uang sekarang bisa digunakan untuk kebutuhan atau menghasilkan bunga, sehingga memiliki nilai lebih.", "difficulty": "beginner"}, {"type": "true_false", "question": "Menerima uang lebih cepat selalu lebih baik daripada menerimanya nanti.", "answer": false, "explanation": "Secara umum uang sekarang lebih berharga, tetapi ada pengecualian seperti bunga tinggi pada pinjaman yang harus dibayar lebih cepat.", "difficulty": "beginner"}, {"type": "fill_blank", "question": "Uang yang diterima sekarang lebih bernilai karena bisa menghasilkan _____ jika ditabung atau diinvestasikan.", "answer": "bunga", "explanation": "Bunga adalah imbalan atas waktu penyimpanan uang, sehingga uang sekarang bisa tumbuh menjadi lebih besar di masa depan.", "difficulty": "beginner"}, {"type": "multiple_choice", "question": "Biaya kesempatan dari menunggu pembayaran adalah ...", "options": ["Kehilangan kesempatan memakai atau menabung uang selama masa tunggu", "Nominal uang berkurang otomatis", "Uang hilang selamanya", "Bank meminta biaya administrasi"], "answer": "Kehilangan kesempatan memakai atau menabung uang selama masa tunggu", "explanation": "Selama menunggu, uang tersebut tidak bisa digunakan untuk kebutuhan atau menghasilkan bunga.", "difficulty": "beginner"}]'::jsonb
WHERE slug = 'time-value-of-money';
