-- Indonesian translations for Batch 4 (lessons 25-32)
-- Generated by translator agent

UPDATE lessons SET
  summary_id = 'Saham itu bagian kecil dari kepemilikan sebuah perusahaan.',
  concept_body_id = 'Saham, atau stock, adalah bagian kepemilikan dalam sebuah perusahaan. Saat kamu membeli saham, kamu jadi salah satu pemilik perusahaan itu, meski bagiannya kecil. Sebagai pemilik, kamu bisa untung kalau perusahaan berkembang dan makin berharga, tapi juga bisa rugi kalau performanya jelek.

Harga saham berubah karena pembeli dan penjual punya pendapat berbeda soal nilai perusahaan. Kalau yang mau beli lebih banyak dari yang mau jual, harga cenderung naik. Kalau yang mau jual lebih banyak, harga cenderung turun. Punya saham bukan judi, tapi juga bukan cara cepat pasti cuan. Ini adalah kepemilikan dalam bisnis nyata, dan nilai bisnis itu berubah seiring perubahan dunia. Perusahaan juga bisa membagikan dividen, yaitu bagian dari laba yang dibagikan ke pemegang saham. Tidak semua perusahaan membagikan dividen; ada yang menyimpan laba untuk berkembang lebih cepat. Sebagai pemegang saham, kamu punya klaim atas aset dan penghasilan perusahaan sesuai jumlah saham yang kamu miliki, meski ini bukan berarti kamu bisa masuk kantor dan menyuruh-nyuruh.',
  why_this_matters_id = 'Memahami saham sebagai kepemilikan, bukan cuma angka di layar, membantu kamu riset perusahaan alih-alih ikut-ikutan pergerakan harga.',
  common_mistake_id = 'Beli saham karena harganya naik terus, padahal belum tahu apa yang sebenarnya dilakukan perusahaan itu.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'what-is-a-stock';

UPDATE lessons SET
  summary_id = 'IDX punya aturan jelas: saham diperdagangkan dalam lot 100 lembar, dan ada program perlindungan investor untuk efek yang tercatat.',
  concept_body_id = 'IDX adalah singkatan dari Bursa Efek Indonesia, tempat saham dan efek lain diperdagangkan secara teregulasi. Di IDX, saham dibeli dan dijual dalam satuan lot, dan satu lot standar adalah 100 lembar saham. Artinya, kamu tidak bisa beli hanya satu lembar saham perusahaan tercatat; minimal harus beli satu lot.

Perdagangan IDX berlangsung di hari kerja, biasanya Senin sampai Jumat. Ada juga mekanisme perlindungan investor, seperti SIPF (Securities Investor Protection Fund), yang memberikan perlindungan bagi investor di efek tercatat dalam batas tertentu. Aturan-aturan ini ada supaya perdagangan adil dan investor kecil terlindungi. Mengetahui aturan sebelum bertransaksi mencegah order ditolak dan kebingungan. Sebelum bisa transaksi di IDX, kamu perlu rekening efek di sekuritas yang terdaftar di OJK. Sekuritas berfungsi sebagai gerbang kamu ke bursa. Selalu pastikan sekuritasmu berizin, karena sekuritas tanpa izin tidak dilindungi SIPF atau pengawasan OJK.',
  why_this_matters_id = 'Memahami aturan IDX sebelum transaksi mencegah order ditolak dan kebingungan soal berapa uang yang sebenarnya dibutuhkan untuk beli saham.',
  common_mistake_id = 'Coba beli saham IDX kurang dari 100 lembar dan tidak mengerti kenapa ordernya ditolak.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'idx-basics-101';

UPDATE lessons SET
  summary_id = 'Ringkasan saham menunjukkan rentang harga, harga penutupan, volume perdagangan, dan nilai total perusahaan.',
  concept_body_id = 'Halaman saham menampilkan angka-angka yang menggambarkan bagaimana saham bertransaksi dalam sehari. Open adalah harga di awal perdagangan. High adalah harga tertinggi yang tercapai. Low adalah harga terendah yang tercapai. Close adalah harga terakhir sebelum pasar tutup. Volume adalah jumlah saham yang berpindah tangan. Market capitalization, atau kapitalisasi pasar, adalah nilai total seluruh saham perusahaan dikalikan harga saat ini.

Angka-angka ini menggambarkan aktivitas, bukan kualitas. Volume tinggi berarti banyak yang bertransaksi hari itu. Harga tinggi tidak otomatis berarti perusahaan bagus. Membaca halaman saham adalah keterampilan, bukan alat prediksi. Selalu lihat gambaran lengkap dan gunakan berbagai sumber sebelum mengambil keputusan. Satu angka tidak pernah menceritakan seluruh cerita. Kapitalisasi pasar membantu kamu memahami ukuran perusahaan, bukan apakah sahamnya murah atau mahal. Saham Rp 1.000 bisa terlalu mahal, dan saham Rp 10.000 bisa sepadan. Harga saja tidak menunjukkan nilai. Gabungkan data halaman saham dengan informasi perusahaan sebelum membuat opini.',
  why_this_matters_id = 'Membaca halaman saham membantu kamu beralih dari tebak-tebakan ke pengamatan. Ini keterampilan dasar sebelum riset atau simulasi.',
  common_mistake_id = 'Menganggap saham yang lonjak harganya besar atau volumenya tinggi otomatis bagus dibeli.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'reading-a-stock-page';

UPDATE lessons SET
  summary_id = 'Portofolio adalah gabungan seluruh kepemilikanmu, dan komposisinya harus sesuai dengan tujuanmu.',
  concept_body_id = 'Portofolio adalah gabungan dari semua aset keuangan yang kamu miliki, seperti tunai, tabungan, reksa dana, dan saham. Berpikir portofolio berarti melihat gambaran besar, bukan menilai satu-satu aset sendiri. Satu saham mungkin berisiko, tapi porsi kecil saham dalam portofolio yang lebih besar bisa masuk akal.

Komposisi yang tepat tergantung pada tujuan dan jangka waktumu. Uang yang segera dibutuhkan sebaiknya disimpan di tempat yang aman dan mudah diakses. Uang yang tidak dibutuhkan bertahun-tahun bisa memuat lebih banyak aset pertumbuhan. Seiring perubahan tujuan, komposisi portofoliomu perlu ditinjau ulang. Ini bukan soal memilih pemenang; ini soal membangun rencana yang cocok dengan kehidupanmu dan membuatmu tetap tenang saat pasar bergejolak. Rebalancing artinya menyesuaikan komposisi kembali ke target dari waktu ke waktu. Misalnya, kalau saham sedang bagus dan sekarang porsinya lebih besar dari rencana, kamu bisa menjual sebagian dan pindahkan ke aset yang lebih aman. Ini menjaga tingkat risikomu tetap selaras dengan rencana awal.',
  why_this_matters_id = 'Berpikir portofolio membantumu menghindari jebakan menaruh semua uang ke satu saham hits lalu panik saat harganya turun.',
  common_mistake_id = 'Menilai kesehatan keuangan hanya dari satu saham, sementara tunai, utang, dan kepemilikan lain diabaikan.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'portfolio-thinking';

UPDATE lessons SET
  summary_id = 'Keuntungan investasi bisa kena pajak, jadi imbal hasil yang kamu bawa pulang bisa lebih rendah dari angka yang tertera.',
  concept_body_id = 'Saat kamu menghasilkan uang dari investasi, pemerintah bisa mengambil sebagian sebagai pajak. Di Indonesia, jenis imbal hasil yang berbeda bisa kena pajak berbeda. Misalnya, bunga deposito dan dividen saham keduanya bisa kena pajak. Jumlah yang benar-benar kamu simpan setelah pajak disebut imbal hasil bersih, sedangkan jumlah sebelum pajak disebut imbal hasil kotor.

Aturan pajak bisa berubah, dan detailnya tergantung situasimu dan jenis rekeningnya. Pelajarannya, bandingkan investasi menggunakan imbal hasil bersih, bukan cuma imbal hasil kotor yang diiklankan. Membayar pajak adalah kewajiban hukum, tapi kamu bisa menyusun keuangan dengan bijak dalam aturan yang berlaku. Untuk saran spesifik, konsultasikan dengan konsultan pajak atau panduan resmi dari Direktorat Jenderal Pajak. Beberapa tabungan jangka panjang mungkin punya insentif pajak menurut aturan Indonesia, tapi aturannya bisa berubah. Selalu cek peraturan terbaru dari Ditjen Pajak atau penasihat yang berkualifikasi. Poin utamanya, anggap investasi sebagai permainan imbal hasil bersih, di mana yang kamu simpan lebih penting dari yang kamu dapat di atas kertas.',
  why_this_matters_id = 'Mengabaikan pajak bisa membuat investasi terlihat lebih bagus dari kenyataannya. Imbal hasil bersih lah yang penting untuk kekayaanmu.',
  common_mistake_id = 'Bandingkan investasi hanya dari imbal hasil kotor yang diiklankan tanpa mempertimbangkan pajak dan biaya.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'taxes-on-returns';

UPDATE lessons SET
  summary_id = 'Sinyal besar seperti BI Rate, inflasi, dan nilai tukar memengaruhi harga, bunga, dan daya belimu.',
  concept_body_id = 'Indikator makro adalah sinyal skala besar yang menggambarkan kesehatan ekonomi. Tiga yang penting di Indonesia adalah BI Rate, yaitu suku bunga acuan Bank Indonesia; inflasi, yang mengukur seberapa cepat harga naik; dan nilai tukar, yang menunjukkan berapa rupiah dibutuhkan untuk membeli satu dolar AS atau mata uang lain.

Indikator ini memengaruhi uangmu secara tidak langsung. Saat BI menaikkan BI Rate, bunga deposito bank bisa naik, tapi meminjam jadi lebih mahal dan harga saham bisa lebih volatil. Saat rupiah melemah terhadap dolar AS, gadget impor dan BBM bisa jadi lebih mahal. Kamu tidak bisa mengendalikan indikator ini, tapi memahami keberadaannya membantumu mengerti kenapa harga dan nilai investasi bergerak tanpa harus bereaksi ke setiap berita. Kamu tidak perlu memprediksi indikator ini dengan sempurna. Ekonom profesional saja sering berselisih. Yang penting adalah mengenali arah umumnya supaya kamu tidak kaget saat bunga deposito naik, cicilan kredit melonjak, atau harga impor berubah. Tetap update informasi, tapi tetap fokus pada rencanamu sendiri.',
  why_this_matters_id = 'Indikator makro menjelaskan kebisingan latar belakang soal harga dan imbal hasil investasi. Memahaminya membantumu fokus pada apa yang bisa kamu kendalikan, bukan panik karena berita.',
  common_mistake_id = 'Mencoba menentukan waktu investasi sempurna berdasarkan berita makro, padahal bahkan ahli pun biasanya gagal melakukannya.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'macro-indicators';

UPDATE lessons SET
  summary_id = 'Emosimu bisa mendorongmu ikut-ikutan kerumunan, takut rugi, atau kejar tren tanpa berpikir.',
  concept_body_id = 'Bias perilaku artinya jalan pintas berpikir yang bisa mengarah ke keputusan finansial buruk. Tiga bias umum adalah FOMO, atau fear of missing out, yang membuatmu membeli sesuatu hanya karena orang lain juga beli; loss aversion, yang membuat rasa sakit rugi uang terasa lebih kuat daripada senangnya dapat uang dalam jumlah sama; dan herd behavior, yang membuatmu mengikuti kerumunan tanpa riset sendiri.

Bias-bias ini wajar, tapi bisa mahal. Pertahanan terbaik adalah melambat, menuliskan alasan keputusanmu, dan mengeceknya dengan tujuanmu. Kalau kamu beli karena tren viral, itu sinyal untuk berhenti sejenak. Investasi yang bagus biasanya membosankan, sementara investasi buruk sering terasa seru. Kesadaran tidak menghilangkan emosi, tapi memberimu kesempatan untuk memutuskan pakai kepala juga, bukan cuma perasaan. Salah satu teknik praktis adalah menetapkan aturan investasi sebelumnya, seperti hanya beli setelah membaca laporan tahunan perusahaan atau hanya investasi dalam jumlah tetap setiap bulan. Aturan mengurangi jumlah keputusan emosional yang harus kamu ambil di saat itu, yaitu saat bias paling kuat.',
  why_this_matters_id = 'Mengenali bias dirimu sendiri adalah salah satu keterampilan investasi paling berharga. Ini melindungimu dari hype, panik, dan penyesalan.',
  common_mistake_id = 'Beli investasi karena terasa urgent atau populer, tanpa memeriksa apakah cocok dengan rencanamu.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'behavioral-bias-intro';

UPDATE lessons SET
  summary_id = 'Rencana keuangan menyusun tujuan, dana darurat, utang, perlindungan, dan investasi dalam satu urutan yang jelas.',
  concept_body_id = 'Rencana keuangan adalah peta sederhana soal ke mana uangmu harus pergi. Bagi kebanyakan anak muda Indonesia, langkah awalnya adalah: penuhi kebutuhan dasar, bangun dana darurat kecil, lunasi utang berbunga tinggi, lindungi diri dengan perlindungan kesehatan seperti BPJS Kesehatan atau asuransi kesehatan swasta kalau memungkinkan, dan baru setelah itu pertimbangkan investasi. Urutannya penting karena tidak ada gunanya mengejar imbal hasil investasi sementara dana darurat atau utang berbunga tinggi bisa menghapuskan hasilnya.

Rencanamu harus sesuai dengan kehidupanmu. Kalau tidak punya utang dan ada dukungan keluarga, kamu mungkin bisa mulai investasi lebih cepat. Kalau penghasilan tidak stabil, bangun dana darurat lebih besar dulu. Tinjau rencanamu setiap beberapa bulan seiring perubahan pendapatan, tujuan, dan tanggung jawab. Rencana bukan dokumen satu kali; ini kebiasaan mengecek posisimu dan langkah selanjutnya. Perlindungan mencakup perlindungan kesehatan seperti BPJS Kesehatan dan, di kemudian hari, asuransi jiwa kalau sudah punya tanggungan. Di usia 18, perlindungan paling penting biasanya adalah kesehatan, karena satu tagihan rumah sakit bisa menghabiskan tabungan. Setelah fondasi ini kuat, investasi jadi cara menumbuhkan uang, bukan judi.',
  why_this_matters_id = 'Rencana mengubah saran keuangan acak jadi tindakan pribadi. Ini membantumu tahu apa yang harus dilakukan selanjutnya, sekecil apa pun pendapatanmu.',
  common_mistake_id = 'Langsung terjun investasi sebelum punya dana darurat atau melunasi utang berbunga tinggi.',
  quiz_data_id = NULL::jsonb
WHERE slug = 'building-financial-plan';
