-- KO-225 group 1 batch 03: high-confidence duplicated Indonesian questions

update public.content_variants set body = $json${"type":"fill_blank","answer":"panic","question":"Selling shares in panic when prices fall is called ____ selling.","difficulty":"beginner","parameters":{},"explanation":"Panic selling is selling investments out of fear, often to long-term detriment."}$json$::jsonb where id = '0da1cd80-2542-4111-807e-5a0d81509537';
update public.content_variants set body = $json${"type":"fill_blank","answer":"IHSG","question":"The index that reflects major stock price movements in Indonesia is called ____.","difficulty":"beginner","parameters":{},"explanation":"IHSG is the Composite Stock Price Index."}$json$::jsonb where id = '0e041f3a-bb8d-48d8-9a5a-4acc2e094a1a';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Buying IDR 25,000 coffee every day because it feels cheap","options":["Buying IDR 25,000 coffee every day because it feels cheap","Pay fees on time","Save at the beginning of the month","Buy credit as needed"],"question":"Which is a spending trap?","difficulty":"beginner","explanation":"Continuous small expenses can pile up big and drain the budget."}$json$::jsonb where id = '0e0b0cfa-c17d-4c71-89b2-7d4eed145683';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"20%","options":["50%","30%","20%","10%"],"question":"Under the 50/30/20 rule, what percentage of income is allocated to savings and paying off debt?","difficulty":"beginner","parameters":{},"explanation":"The 50/30/20 rule uses 50% for needs, 30% for wants, and 20% for savings and debt."}$json$::jsonb where id = '0ec5a6ac-f406-4e49-b42e-42233f280f18';
update public.content_variants set body = $json${"type":"case_study","answer":"Rina's portfolio is too conservative for a long time horizon.","caseText":"Rina is 19 years old, wants to retire at the age of 50. Currently he puts 100% of his money in savings with 3% interest. Inflation averages 4%.","followUp":{"answer":"Savings do not keep up with inflation for long-term goals","options":["Savings do not keep up with inflation for long-term goals","Savings are too risky","Savings are enough for long-term goals","Inflation has no effect on savings"],"question":"What is the main problem with Rina's portfolio?","explanation":"For long-term goals, savings with low interest can lose purchasing power due to inflation."},"question":"Read the following cases and choose the best response.","difficulty":"intermediate","explanation":"The portfolio must be tailored to the goals and time. For long-term retirement, you need assets that have the potential to grow higher."}$json$::jsonb where id = '0f782703-54ff-4292-a678-08fa6d7fdf70';
update public.content_variants set body = $json${"type":"word_bank","answer":["egg","basket"],"options":["egg","basket"],"question":"Complete: \"Don't put all your _____ in one _____.\"","difficulty":"intermediate","parameters":{},"explanation":"This proverb illustrates the importance of spreading risk in investing."}$json$::jsonb where id = '0fb15be0-28a8-456e-aee7-0e2036e3385c';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Keeping all money in cash in the long term remains safe from inflation.","difficulty":"beginner","parameters":{},"explanation":"Cash does not earn interest, so its purchasing power decreases if inflation is positive."}$json$::jsonb where id = '10949e6a-477d-4b6a-ad3d-a1d656528be8';
update public.content_variants set body = $json${"type":"case_study","answer":"Emergency funds prevent us from going into debt when urgent needs arise.","caseText":"Budi, an online motorcycle taxi driver, earns an irregular income. The cellphone was damaged and the repair cost was IDR 3,000,000. He doesn't have an emergency fund.","followUp":{"answer":"Forced to borrow from a high-interest loan","options":["Forced to borrow from a high-interest loan","Can't buy food","Couldn't work for several days because my cellphone was damaged","Having to borrow from family with social consequences"],"question":"What is the biggest risk facing Budi?","explanation":"Without an emergency fund, people are often forced to take on high-interest debt to cover urgent needs."},"question":"Read the following cases and choose the best response.","difficulty":"beginner","explanation":"An emergency fund is a financial hedge that protects us from high-interest debt when unexpected needs arise."}$json$::jsonb where id = '10fde24d-d9fb-4d6a-8a37-2244a3931376';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Keeping all your money under your pillow is always safe from inflation.","difficulty":"beginner","explanation":"Cash does not earn interest, so its purchasing power decreases when inflation is positive."}$json$::jsonb where id = '12dd724a-f26c-4cfa-abf3-78086485a30f';
update public.content_variants set body = $json${"type":"fill_blank","answer":"BI","question":"Bank Indonesia regulates a reference interest rate called the _____ Rate.","difficulty":"advanced","explanation":"BI Rate is a reference interest rate that influences loan and savings interest."}$json$::jsonb where id = '149c1e73-282c-430c-83e0-5d82669101af';

