-- Migration: KO-FOCUS-001 — Separate Daily Focus question bank from lesson content
-- Generated from daily-focus-quiz-bank-v2-2026-07-26.csv
-- Scope: 123 bilingual questions across 8 chapters + Foundation 0.

BEGIN;

-- 1. Create a standalone table for Daily Focus questions.
CREATE TABLE IF NOT EXISTS daily_focus_questions (
  id TEXT PRIMARY KEY,
  chapter TEXT NOT NULL,
  topic TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  type TEXT NOT NULL,
  body JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE daily_focus_questions IS 'Standalone question bank for Daily Focus, separate from lesson content_variants.';

-- 2. Seed the bank with fresh questions.
INSERT INTO daily_focus_questions (id, chapter, topic, difficulty, type, body, is_active) VALUES
  ('DF2-F6E70FBB', 'Money Basics', 'money_basics', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which of the following best describes money?", "options": ["A government decree that fixes prices", "Anything widely accepted as payment for goods and services", "A physical object that must be made of gold", "A promise from a bank to lend"], "answer": "Anything widely accepted as payment for goods and services", "explanation": "Money works because people agree to accept it in exchange for value; form matters less than trust.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-E6BE1A5D', 'Money Basics', 'inflation', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A rise in the price of one product, such as boba tea, is the same as economy-wide inflation.", "answer": false, "explanation": "Inflation is a broad increase in prices across the economy, not a single item becoming more expensive.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-079F643B', 'Money Basics', 'interest', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "If Rp 10,000,000 in a deposit earns 5% simple interest per year, how much interest do you earn in one year?", "options": ["Rp 500,000", "Rp 5,000,000", "Rp 50,000", "Rp 10,500,000"], "answer": "Rp 500,000", "explanation": "Simple interest is calculated only on the original principal: 5% of Rp 10,000,000 is Rp 500,000.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-8411F95E', 'Money Basics', 'income_wealth', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which statement best separates income from wealth?", "options": ["Income is what you keep; wealth is what you earn", "Income is money coming in; wealth is what you own minus what you owe", "Income is the same as wealth", "Wealth is only cash in a savings account"], "answer": "Income is money coming in; wealth is what you own minus what you owe", "explanation": "Income is a flow over time. Wealth is a stock at a point in time: assets minus liabilities.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-E594EBC8', 'Money Basics', 'needs_vs_wants', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "You have Rp 200,000 and must choose between lunch or a game skin. Lunch keeps you productive; the skin is cosmetic. Which is closer to a need?", "options": ["The game skin", "Lunch", "Both are needs", "Neither is a need"], "answer": "Lunch", "explanation": "A need supports your health and ability to function; a want is nice to have but optional.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-4662E391', 'Money Basics', 'assets_liabilities', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "An item can behave like an asset for one person and a liability for another depending on how it is used.", "answer": true, "explanation": "The same object can produce value or drain money based on use, not just the label.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-CCF5264D', 'Money Basics', 'risk_basics', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which choice is an example of a risk that cannot be eliminated, only managed?", "options": ["Keeping cash at home and losing it to theft or inflation", "Putting all money in one friend''s business", "Buying only government bonds", "Avoiding all financial decisions"], "answer": "Keeping cash at home and losing it to theft or inflation", "explanation": "Every financial choice carries some risk; even cash faces inflation and theft risk.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7F1B9F1F', 'Money Basics', 'time_value_money', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the main reason Rp 1,000,000 today is generally worth more than Rp 1,000,000 in five years?", "options": ["Money today can be invested or used immediately", "Banknotes become physically smaller", "Future money is illegal", "Prices always fall"], "answer": "Money today can be invested or used immediately", "explanation": "Money has time value because it can earn returns and meet needs sooner.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-80D69164', 'Money Basics', 'inflation', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "Inflation slowly reduces the _____ of money, meaning the same amount buys less over time.", "answer": "purchasing power", "explanation": "Purchasing power is what your money can actually buy; inflation erodes it.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A3FBE19C', 'Money Basics', 'money_basics', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL the roles money commonly plays.", "options": ["Medium of exchange", "Store of value", "Unit of account", "Guarantee of profit"], "answer": ["Medium of exchange", "Store of value", "Unit of account"], "explanation": "Money lets people trade, save purchasing power, and compare prices. It does not guarantee profit.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A233A7C7', 'Money Basics', 'needs_vs_wants', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Put these steps in the right order for checking if a purchase is a need or a want.", "options": ["Ask if you can live or function without it", "Check if it fits your budget", "Decide whether to buy now or later", "Buy immediately"], "answer": ["Ask if you can live or function without it", "Check if it fits your budget", "Decide whether to buy now or later"], "explanation": "First classify the item, then check affordability, then decide timing.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-FE33EC26', 'Money Basics', 'interest', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "Fill in the blanks: Compound interest earns interest on both the original _____ and the interest already added.", "options": ["principal", "amount", "balance"], "answer": ["principal"], "explanation": "Compound interest grows faster because it applies to the principal plus accumulated interest.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-F73B3A95', 'Money Basics', 'assets_liabilities', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match each term with its meaning.", "pairs": [["Asset", "Something that can produce value"], ["Liability", "Something that costs you money"], ["Income", "Money coming in"], ["Wealth", "Assets minus liabilities"]], "answer": {"Asset": "Something that can produce value", "Liability": "Something that costs you money", "Income": "Money coming in", "Wealth": "Assets minus liabilities"}, "explanation": "These four terms form the basic vocabulary of a personal balance sheet.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-0EE776E7', 'Money Basics', 'risk_basics', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which of the following is the safest place for money you might need next week?", "options": ["A separate savings account", "A speculative stock", "A locked one-year deposit", "A friend''s borrowed wallet"], "answer": "A separate savings account", "explanation": "Short-term money should be safe and accessible, not locked or volatile.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A5AA9009', 'Money Basics', 'income_wealth', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Wealth is measured by how much you earn each month.", "answer": false, "explanation": "Wealth is assets minus liabilities; high earners can have low or negative wealth if they spend and borrow heavily.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-9D73517A', 'Money Life Skills', 'budgeting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "A good first step in building a budget is to:", "options": ["Track where your money actually goes for a month", "Buy a premium finance app", "Borrow money to cover expenses", "Set aspirational spending targets"], "answer": "Track where your money actually goes for a month", "explanation": "You cannot improve a budget you do not understand. Start with honest tracking.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-C94DA484', 'Money Life Skills', 'saving_habits', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What does ''pay yourself first'' usually mean?", "options": ["Save a planned amount before spending on wants", "Pay all bills first", "Treat yourself to something nice every payday", "Lend money to friends first"], "answer": "Save a planned amount before spending on wants", "explanation": "Automating savings before discretionary spending makes consistency easier.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-50E5823A', 'Money Life Skills', 'spending_behavior', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A flash sale with 70% off is always a good deal if you save money compared to the original price.", "answer": false, "explanation": "A discount is only a saving if the purchase was already planned and fits your budget; otherwise it is unplanned spending.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-C5D19E3E', 'Money Life Skills', 'behavioral_finance', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which habit best helps you avoid impulse spending?", "options": ["Wait 24-48 hours before non-essential purchases", "Save payment details in every app", "Shop when bored", "Follow every influencer sale"], "answer": "Wait 24-48 hours before non-essential purchases", "explanation": "A cooling-off period turns many impulse wants into forgotten wants.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-3A965096', 'Money Life Skills', 'budgeting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Using the 50/30/20 rule, what does the 50% typically cover?", "options": ["Needs", "Wants", "Savings and debt repayment", "Entertainment"], "answer": "Needs", "explanation": "The 50/30/20 rule allocates 50% to needs, 30% to wants, and 20% to savings and debt repayment.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7100A62F', 'Money Life Skills', 'spending_behavior', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "A spending _____ is anything that nudges you to spend more than you planned.", "answer": "trigger", "explanation": "Triggers can be notifications, emotions, social pressure, or app designs that encourage impulse buying.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-5E0EC026', 'Money Life Skills', 'spending_behavior', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL useful ways to reduce subscription creep.", "options": ["Review bank statements monthly", "Cancel unused services", "Share family plans where allowed", "Add new trials every week"], "answer": ["Review bank statements monthly", "Cancel unused services", "Share family plans where allowed"], "explanation": "Regular reviews and cancelling unused services keep recurring costs aligned with your priorities.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-C2B6440E', 'Money Life Skills', 'budgeting', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order these budgeting steps from first to last.", "options": ["Record income", "Track spending", "Set goals", "Allocate money", "Review and adjust"], "answer": ["Record income", "Track spending", "Set goals", "Allocate money", "Review and adjust"], "explanation": "Budgeting starts with knowing what you have, then where it goes, then deciding where it should go.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-EAD1A302', 'Money Life Skills', 'behavioral_finance', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Mental accounting means treating money differently depending on where it came from or how it is labelled.", "answer": true, "explanation": "Mental accounting can lead to overspending a ''bonus'' while carefully budgeting a salary, even though money is fungible.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7CA072ED', 'Money Life Skills', 'spending_behavior', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which of the following is a sign that a spending habit may be becoming a trap?", "options": ["You hide purchases from people close to you", "You track every receipt", "You wait for sales on planned items", "You compare prices before buying"], "answer": "You hide purchases from people close to you", "explanation": "Secrecy and guilt around spending are warning signs that a habit is harming your finances.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-61199921', 'Money Life Skills', 'saving_habits', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "Automating a transfer to savings on payday is one way to make saving a _____ habit.", "answer": "consistent", "explanation": "Automation reduces the willpower needed to save and makes consistency automatic.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-FE9A1DA7', 'Money Life Skills', 'budgeting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "If your income is irregular, what is the safest budgeting approach?", "options": ["Budget based on your lowest recent month and save the surplus in better months", "Spend whatever comes in", "Borrow against next month''s expected income", "Ignore budgeting until income stabilizes"], "answer": "Budget based on your lowest recent month and save the surplus in better months", "explanation": "Irregular income needs a conservative baseline so lean months do not create debt.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-6DE7864D', 'Money Life Skills', 'saving_habits', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "Complete the sentence: Paying yourself first means saving before you _____.", "options": ["spend on wants", "pay bills", "earn income", "invest"], "answer": ["spend on wants"], "explanation": "The idea is to prioritise future needs by saving before discretionary spending.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-2B9CAE52', 'Money Life Skills', 'budgeting', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A budget should never be changed once it is set.", "answer": false, "explanation": "A budget is a living plan. Life changes, so the budget should be reviewed and adjusted regularly.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-DB529F6F', 'Protect Yourself', 'scam_defense', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which is the safest response to an Instagram DM promising 20% guaranteed monthly returns?", "options": ["Check OJK''s investment alert list and ignore the message", "Send a small amount to test", "Share the link with friends", "Ask for the manager''s WhatsApp"], "answer": "Check OJK''s investment alert list and ignore the message", "explanation": "Guaranteed high returns are a classic scam signal. Verify licenses through official OJK channels.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-522BB17F', 'Protect Yourself', 'phishing_social_engineering', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A real bank officer may ask for your OTP to verify a transaction over the phone.", "answer": false, "explanation": "Legitimate banks never ask for OTPs or passwords. Treat any such request as a scam.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-E4EC4916', 'Protect Yourself', 'ojk_license_check', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the main purpose of checking an OJK license before investing?", "options": ["To confirm the product or platform is legally supervised", "To guarantee profit", "To avoid paying taxes", "To get a higher return"], "answer": "To confirm the product or platform is legally supervised", "explanation": "OJK supervision means there are rules and dispute channels; it does not guarantee returns.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-C6A3CF32', 'Protect Yourself', 'scam_defense', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL common red flags of an investment scam.", "options": ["Guaranteed high returns", "Pressure to recruit friends", "Urgency and limited slots", "Registered on OJK''s official list"], "answer": ["Guaranteed high returns", "Pressure to recruit friends", "Urgency and limited slots"], "explanation": "Registration on OJK''s list is a green flag, not a red flag.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-31EFDD7B', 'Protect Yourself', 'phishing_social_engineering', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "A message says ''Your package is stuck, click here to pay customs.'' What should you do first?", "options": ["Open the official courier app or website and check the tracking number", "Click the link and enter details", "Reply with your address", "Forward to family"], "answer": "Open the official courier app or website and check the tracking number", "explanation": "Phishing often uses fake delivery issues. Always verify through official channels.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-4E083EA9', 'Protect Yourself', 'ojk_license_check', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "In Indonesia, you can use OJK''s investment _____ list to check whether an investment offer is illegal.", "answer": "alerta", "explanation": "OJK publishes an alert list of illegal investments and unauthorised entities.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-2322E413', 'Protect Yourself', 'mlm_pyramid', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "An MLM scheme that pays you mainly for recruiting new members rather than selling real products is sustainable.", "answer": false, "explanation": "Recruitment-focused MLMs collapse when recruitment slows because there is no real product income.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-87D89923', 'Protect Yourself', 'scam_defense', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which detail should make you most suspicious of a ''financial coach'' offering guaranteed returns?", "options": ["They promise no risk and high profit", "They ask about your goals", "They explain fees clearly", "They are registered with OJK"], "answer": "They promise no risk and high profit", "explanation": "Risk and return are linked; anyone promising high returns with no risk is either lying or scamming.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-21B00D6C', 'Protect Yourself', 'scam_defense', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order the safest response when you receive a suspicious investment message.", "options": ["Stop and do not click", "Verify the license on OJK''s official site", "Delete or report the message", "Warn friends if it is a known scam"], "answer": ["Stop and do not click", "Verify the license on OJK''s official site", "Delete or report the message", "Warn friends if it is a known scam"], "explanation": "Pause, verify, act, and share warnings only after confirmation.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-62B573F6', 'Protect Yourself', 'phishing_social_engineering', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "Never share your _____ or password with anyone claiming to be from a bank.", "options": ["OTP", "PIN", "account number", "name"], "answer": ["OTP"], "explanation": "OTP and passwords are secrets. No legitimate bank employee will ask for them.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A976938B', 'Protect Yourself', 'scam_defense', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "A friend invites you to join a ''private crypto signal group'' with guaranteed profits. What is the wisest move?", "options": ["Decline and remind them that guarantees in crypto are a red flag", "Invest immediately to not miss out", "Borrow money to join", "Recruit more friends"], "answer": "Decline and remind them that guarantees in crypto are a red flag", "explanation": "Guaranteed profits, especially in crypto, are a major warning sign.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-00A92EF3', 'Protect Yourself', 'ojk_license_check', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Checking OJK''s license is only necessary for large investments.", "answer": false, "explanation": "Scams target small amounts too. Always verify, regardless of how much you plan to invest.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-FD1BFF06', 'Protect Yourself', 'scam_defense', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match the scam type with its hallmark.", "pairs": [["Ponzi", "Pays old investors with new investors'' money"], ["Pyramid", "Rewards recruiting more than selling"], ["Phishing", "Pretends to be a trusted entity to steal data"], ["Pump and dump", "Artificially hypes an asset then sells"]], "answer": {"Ponzi": "Pays old investors with new investors'' money", "Pyramid": "Rewards recruiting more than selling", "Phishing": "Pretends to be a trusted entity to steal data", "Pump and dump": "Artificially hypes an asset then sells"}, "explanation": "Recognising the pattern helps you spot scams before losing money.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-44B7BED1', 'Protect Yourself', 'scam_defense', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "If an offer sounds too good to be _____, it usually is.", "answer": "true", "explanation": "Extraordinary claims with little risk are one of the oldest scam signs.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-50993F7A', 'Let''s Talk About Debt', 'good_debt_vs_bad_debt', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which debt is most likely to be ''good debt''?", "options": ["A student loan that increases your future income", "A PayLater purchase of trendy clothes", "A credit card used for dining out every weekend", "A loan for a luxury vacation"], "answer": "A student loan that increases your future income", "explanation": "Good debt helps you build income or wealth; bad debt buys depreciating wants.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-F8558FBD', 'Let''s Talk About Debt', 'credit_cards', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Paying only the minimum on a credit card keeps the balance from growing.", "answer": false, "explanation": "Minimum payments usually leave most of the balance subject to interest, so the debt can grow.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-EE3C684C', 'Let''s Talk About Debt', 'debt_repayment', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "You have Rp 2,000,000 extra to pay debt. You owe Rp 5,000,000 on a credit card at 24% annual interest and Rp 2,000,000 to a friend at 0%. Which should you pay first using the avalanche method?", "options": ["The credit card", "The friend", "Split equally", "Pay neither"], "answer": "The credit card", "explanation": "Avalanche prioritises the highest-interest debt while keeping minimum payments on the rest.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-B56391FF', 'Let''s Talk About Debt', 'pay_later', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the biggest hidden danger of using PayLater for small wants?", "options": ["It hides the full cost and encourages impulse buying", "It is always illegal", "It has no fees", "It builds credit history automatically"], "answer": "It hides the full cost and encourages impulse buying", "explanation": "Small instalments feel affordable, but fees and impulse purchases can add up quickly.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-0A3FB5AD', 'Let''s Talk About Debt', 'debt_traps', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL signs that you may be falling into a debt trap.", "options": ["Borrowing to pay off other debt", "Hiding bills from family", "Paying only minimums every month", "Tracking spending weekly"], "answer": ["Borrowing to pay off other debt", "Hiding bills from family", "Paying only minimums every month"], "explanation": "Tracking spending weekly is healthy; the others are warning signs.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-771F18E1', 'Let''s Talk About Debt', 'debt_repayment', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "The debt _____ method targets the smallest balance first to build motivation.", "answer": "snowball", "explanation": "Snowball gives quick wins by clearing small debts first; avalanche usually saves more interest.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A04E3766', 'Let''s Talk About Debt', 'credit_cards', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which behaviour turns a credit card from a useful tool into a costly problem?", "options": ["Treating the credit limit as extra income", "Paying the full balance every month", "Using it only for planned groceries", "Setting an automatic full payment"], "answer": "Treating the credit limit as extra income", "explanation": "A credit card is a short-term loan; the limit is not income.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-1CA995D0', 'Let''s Talk About Debt', 'good_debt_vs_bad_debt', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A motorbike loan is always bad debt because it is a vehicle.", "answer": false, "explanation": "A motorbike loan can be good debt if the bike is used to earn income that exceeds the repayments.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-815983EF', 'Let''s Talk About Debt', 'debt_repayment', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order the steps for paying off debt responsibly.", "options": ["Stop adding new debt", "List all debts with interest rates and minimums", "Pay minimums on every debt", "Put extra toward the highest-interest debt"], "answer": ["Stop adding new debt", "List all debts with interest rates and minimums", "Pay minimums on every debt", "Put extra toward the highest-interest debt"], "explanation": "A clear plan stops panic and prevents missed payments.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-EE28A752', 'Let''s Talk About Debt', 'debt_repayment', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "When you cannot make a payment, the best first step is to _____ the lender early.", "options": ["contact", "ignore", "avoid", "block"], "answer": ["contact"], "explanation": "Early communication often leads to restructuring options and protects your credit record.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-B3197593', 'Let''s Talk About Debt', 'debt_traps', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Why can minimum payments on high-interest debt be dangerous?", "options": ["They keep the debt alive and growing through interest", "They make the debt disappear faster", "They have no fees", "They improve your credit score instantly"], "answer": "They keep the debt alive and growing through interest", "explanation": "Minimum payments mostly cover interest, so the principal shrinks slowly or not at all.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-586CA19E', 'Let''s Talk About Debt', 'pay_later', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "PayLater is safe as long as the provider is licensed by OJK.", "answer": false, "explanation": "Even licensed PayLater can lead to overspending and fees; license is necessary but not sufficient for safety.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-3A68F423', 'Let''s Talk About Debt', 'good_debt_vs_bad_debt', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match each borrowing scenario with its likely category.", "pairs": [["Student loan for a certification", "Often good debt"], ["PayLater for a hoodie", "Usually bad debt"], ["Credit card paid in full monthly", "Useful tool"], ["Borrowing to gamble", "Dangerous debt"]], "answer": {"Student loan for a certification": "Often good debt", "PayLater for a hoodie": "Usually bad debt", "Credit card paid in full monthly": "Useful tool", "Borrowing to gamble": "Dangerous debt"}, "explanation": "Category depends on purpose, cost, and whether the debt produces value.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A9C800BA', 'Let''s Talk About Debt', 'good_debt_vs_bad_debt', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "When evaluating debt, always compare the interest rate to the _____ the debt might create.", "answer": "value", "explanation": "Productive debt should create more value than it costs; consumptive debt rarely does.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-89A91AE0', 'Plan Your Money', 'emergency_fund', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the most important feature of an emergency fund?", "options": ["It is safe and easy to access quickly", "It earns the highest possible return", "It is locked for five years", "It is invested in stocks"], "answer": "It is safe and easy to access quickly", "explanation": "Emergency funds must be available when urgent needs arise; high returns are secondary.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-32039225', 'Plan Your Money', 'emergency_fund', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "An emergency fund should be used for planned annual expenses like holiday travel.", "answer": false, "explanation": "Planned expenses belong in a sinking fund or budget category, not the emergency fund.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-DF3121D7', 'Plan Your Money', 'goal_setting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which goal is written in the most actionable way?", "options": ["Save Rp 6,000,000 for a laptop by December 2027", "Buy a laptop someday", "Save more money", "Spend less on food"], "answer": "Save Rp 6,000,000 for a laptop by December 2027", "explanation": "Specific amount and deadline make a goal measurable and trackable.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-750A6BE8', 'Plan Your Money', 'goal_setting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "You need Rp 12,000,000 in 12 months and already have Rp 3,000,000. Ignoring interest, how much must you save each month?", "options": ["Rp 750,000", "Rp 1,000,000", "Rp 500,000", "Rp 12,000,000"], "answer": "Rp 750,000", "explanation": "You still need Rp 9,000,000. Divided by 12 months, that is Rp 750,000 per month.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-0380E24A', 'Plan Your Money', 'emergency_fund', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL good places to keep an emergency fund.", "options": ["A separate savings account", "A liquid money-market fund", "Cash under a mattress", "A locked long-term bond"], "answer": ["A separate savings account", "A liquid money-market fund"], "explanation": "Emergency funds need safety and quick access; cash at home is risky and long-term bonds are not liquid enough.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-4E7E3099', 'Plan Your Money', 'financial_planning', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "A financial plan connects your income, expenses, goals, and _____ into one coherent roadmap.", "answer": "risk tolerance", "explanation": "A plan only works if it reflects how much risk you can handle while pursuing your goals.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-8FC71BA4', 'Plan Your Money', 'goal_setting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Why should short-term goals usually be funded with savings rather than investments?", "options": ["Investments can fall in value over short periods", "Savings always earn more", "Investments are illegal for short-term goals", "Savings are harder to access"], "answer": "Investments can fall in value over short periods", "explanation": "Money needed soon should not be exposed to market volatility.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-AA2AECC1', 'Plan Your Money', 'financial_planning', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A realistic financial plan can be adjusted when life changes.", "answer": true, "explanation": "Flexibility is a strength; rigid plans break when circumstances change.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-1BA9237C', 'Plan Your Money', 'goal_setting', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Put these goal-setting steps in order.", "options": ["Define what you want", "Set a target amount", "Choose a deadline", "Calculate monthly savings", "Start saving"], "answer": ["Define what you want", "Set a target amount", "Choose a deadline", "Calculate monthly savings", "Start saving"], "explanation": "A concrete goal has a what, how much, and when before you begin saving.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-E6F3ECB5', 'Plan Your Money', 'emergency_fund', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "Complete: A good first emergency fund target for a young worker is often three to six months of essential _____.", "options": ["expenses", "income", "wants", "loans"], "answer": ["expenses"], "explanation": "The fund should cover essential living costs, not total income or discretionary wants.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-D9957CA4', 'Plan Your Money', 'goal_setting', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which action makes a savings goal more likely to succeed?", "options": ["Automating a monthly transfer to a separate account", "Hoping extra money is left at month end", "Keeping the goal secret", "Changing the goal whenever progress feels slow"], "answer": "Automating a monthly transfer to a separate account", "explanation": "Automation and separation reduce the temptation to spend the money elsewhere.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-1F9A3CC1', 'Plan Your Money', 'financial_planning', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Financial planning is only for people with high incomes.", "answer": false, "explanation": "Planning helps at every income level because it prioritises limited resources toward what matters most.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-E760D974', 'Plan Your Money', 'financial_planning', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match each goal with the best account type.", "pairs": [["Emergency fund", "Separate savings account"], ["Retirement", "Long-term investment"], ["Next month''s rent", "Current account"], ["New phone in 6 months", "Short-term savings"]], "answer": {"Emergency fund": "Separate savings account", "Retirement": "Long-term investment", "Next month''s rent": "Current account", "New phone in 6 months": "Short-term savings"}, "explanation": "Time horizon and purpose determine where money should sit.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-56DCAE4C', 'Plan Your Money', 'financial_planning', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "Your financial plan should be reviewed when your income, goals, or _____ change significantly.", "answer": "expenses", "explanation": "Major changes in any of these areas can make an old plan unrealistic.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-1C637AF4', 'Grow Your Money', 'compound_interest', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is compound interest?", "options": ["Interest earned on both the original amount and previously earned interest", "A fixed fee charged by banks", "Interest paid only once at the end", "A government tax on savings"], "answer": "Interest earned on both the original amount and previously earned interest", "explanation": "Compounding accelerates growth because each period''s interest adds to the base for the next period.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-AE1B139E', 'Grow Your Money', 'risk_return', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A higher potential return usually comes with higher risk.", "answer": true, "explanation": "Risk and return are related; promises of high return with low risk are usually scams.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-0F70DC82', 'Grow Your Money', 'compound_interest', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Using the rule of 72, about how many years does it take for money to double at 6% annual return?", "options": ["12 years", "6 years", "72 years", "36 years"], "answer": "12 years", "explanation": "Divide 72 by the annual return rate: 72 / 6 = 12 years.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-9E0DE51B', 'Grow Your Money', 'bank_vs_investment', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which option is usually the safest place for money you may need within one year?", "options": ["A bank savings account", "A single stock", "Cryptocurrency", "A long-term property project"], "answer": "A bank savings account", "explanation": "Short-term money should prioritise capital preservation and liquidity over growth.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-24EAB111', 'Grow Your Money', 'diversification', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL benefits of diversification.", "options": ["Reduces exposure to a single investment", "Smooths returns over time", "Guarantees no losses", "Spreads risk across assets"], "answer": ["Reduces exposure to a single investment", "Smooths returns over time", "Spreads risk across assets"], "explanation": "Diversification reduces concentration risk but cannot eliminate all losses.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-C4DE2659', 'Grow Your Money', 'reksa_dana', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "A reksa dana is a pooled investment vehicle managed by an investment _____.", "answer": "manager", "explanation": "Reksa dana lets many investors pool money to buy a diversified portfolio managed professionally.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-01CEED4F', 'Grow Your Money', 'risk_return', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What does ''time in the market'' generally mean for long-term investors?", "options": ["Staying invested over long periods rather than timing short-term peaks", "Checking prices every hour", "Buying only when news is positive", "Selling everything in a downturn"], "answer": "Staying invested over long periods rather than timing short-term peaks", "explanation": "Long-term investors benefit from compounding and avoid the difficulty of predicting short-term moves.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7E36C2D6', 'Grow Your Money', 'bank_vs_investment', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "A deposit account and an equity mutual fund have the same risk profile.", "answer": false, "explanation": "Deposits are generally safer with lower returns; equity funds can fluctuate but offer higher long-term growth potential.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-2317C315', 'Grow Your Money', 'financial_planning', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order these steps for someone starting to grow their money.", "options": ["Build an emergency fund", "Pay off high-interest debt", "Start investing for long-term goals", "Diversify across asset classes"], "answer": ["Build an emergency fund", "Pay off high-interest debt", "Start investing for long-term goals", "Diversify across asset classes"], "explanation": "A stable base comes before growth investing.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-4AD6422E', 'Grow Your Money', 'compound_interest', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "The rule of 72 estimates how long it takes for an investment to _____.", "options": ["double", "triple", "halve", "disappear"], "answer": ["double"], "explanation": "Divide 72 by the annual growth rate to approximate doubling time.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-9D908310', 'Grow Your Money', 'reksa_dana', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which statement about reksa dana is true?", "options": ["It pools money from many investors to buy a diversified portfolio", "It guarantees fixed returns", "It is only for wealthy people", "It cannot be redeemed before maturity"], "answer": "It pools money from many investors to buy a diversified portfolio", "explanation": "Reksa dana offers diversification and professional management without requiring a large capital.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-82E4017D', 'Grow Your Money', 'risk_return', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "You should invest money you might need next month because stocks usually go up.", "answer": false, "explanation": "Short-term needs should be in stable, liquid accounts because stocks can fall suddenly.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-DFECAE85', 'Grow Your Money', 'risk_return', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match the investment concept with its meaning.", "pairs": [["Compound interest", "Earnings on earnings"], ["Diversification", "Spreading investments"], ["Risk-return trade-off", "Higher potential reward usually means higher risk"], ["Liquidity", "How quickly an asset can be converted to cash"]], "answer": {"Compound interest": "Earnings on earnings", "Diversification": "Spreading investments", "Risk-return trade-off": "Higher potential reward usually means higher risk", "Liquidity": "How quickly an asset can be converted to cash"}, "explanation": "These core ideas help compare savings and investment choices.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-1C69B012', 'Grow Your Money', 'debt_management', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "Before chasing high returns, first make sure your emergency fund and high-interest _____ are under control.", "answer": "debt", "explanation": "High-interest debt usually costs more than investments earn, so pay it down before aggressive investing.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-0E0D0C62', 'Investing in Indonesia', 'stocks', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What does owning a share of stock represent?", "options": ["A partial ownership claim in a company", "A loan to the company", "A guaranteed dividend", "A fixed deposit certificate"], "answer": "A partial ownership claim in a company", "explanation": "Stock represents fractional ownership; it is not a loan or a guaranteed payment.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-E1AF62F1', 'Investing in Indonesia', 'idx_basics', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "The IDX is Indonesia''s main stock exchange.", "answer": true, "explanation": "IDX stands for Indonesia Stock Exchange (Bursa Efek Indonesia).", "parameters": {}}'::jsonb, TRUE),
  ('DF2-C6F57AA4', 'Investing in Indonesia', 'stock_analysis', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "A stock has a P/E ratio of 25. Roughly, what does that mean?", "options": ["Investors currently pay Rp 25 for every Rp 1 of annual earnings per share", "The stock costs Rp 25", "The company earns Rp 25 profit per share", "The dividend is 25%"], "answer": "Investors currently pay Rp 25 for every Rp 1 of annual earnings per share", "explanation": "P/E compares price to earnings per share; it is one valuation signal, not the only one.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-92EDB1A1', 'Investing in Indonesia', 'portfolio', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Why might an Indonesian investor hold both IDX stocks and government bonds (SUN)?", "options": ["To diversify across different asset classes and risks", "Because stocks and bonds always move together", "To avoid paying taxes", "Because bonds are always risk-free"], "answer": "To diversify across different asset classes and risks", "explanation": "Mixing stocks and bonds can balance growth potential with income and stability.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-CDB16D84', 'Investing in Indonesia', 'stocks', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL things an investor should check before buying an Indonesian stock.", "options": ["The company''s fundamentals", "OJK-licensed broker", "The stock''s historical price", "Guaranteed future returns"], "answer": ["The company''s fundamentals", "OJK-licensed broker", "The stock''s historical price"], "explanation": "No one can guarantee future returns; the rest are sensible research steps.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-CA9972DE', 'Investing in Indonesia', 'taxes', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "In Indonesia, capital gains on stocks held in the regular market are generally subject to a final _____ on sale.", "answer": "tax", "explanation": "Investors should understand taxes on returns; rates and rules can change and may differ by account type.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-AEFA64F5', 'Investing in Indonesia', 'stock_analysis', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "A stock''s beta measures:", "options": ["Its sensitivity to overall market movements", "Its dividend yield", "Its total assets", "Its CEO''s popularity"], "answer": "Its sensitivity to overall market movements", "explanation": "Beta indicates how much a stock tends to move relative to the broader market.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-6AF6B093', 'Investing in Indonesia', 'portfolio', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Investing in a single popular stock is safer than investing in a broad index fund.", "answer": false, "explanation": "A single stock exposes you to company-specific risk; an index fund spreads that risk across many companies.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-F6F7A02D', 'Investing in Indonesia', 'idx_basics', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order the typical steps to start investing in IDX stocks.", "options": ["Open an account with an OJK-licensed broker", "Fund the account", "Research a stock or index", "Place a buy order", "Monitor and review"], "answer": ["Open an account with an OJK-licensed broker", "Fund the account", "Research a stock or index", "Place a buy order", "Monitor and review"], "explanation": "Start with a licensed broker and capital you can afford to leave invested for the long term.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-F36836A2', 'Investing in Indonesia', 'stock_analysis', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "Reading a stock page usually includes price, market cap, P/E ratio, and _____ yield.", "options": ["dividend", "interest", "inflation", "credit"], "answer": ["dividend"], "explanation": "Dividend yield shows annual dividends relative to the stock price.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7A512151', 'Investing in Indonesia', 'macro_indicators', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which macro indicator is most closely watched for its effect on interest rates and inflation in Indonesia?", "options": ["BI rate", "Number of new shopping malls", "Social media followers of a company", "Monthly rainfall"], "answer": "BI rate", "explanation": "Bank Indonesia''s policy rate influences borrowing costs and is closely tied to inflation expectations.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A4B50E37', 'Investing in Indonesia', 'portfolio', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Market timing consistently beats a simple buy-and-hold strategy for most investors.", "answer": false, "explanation": "Research shows most investors fail to time the market well; disciplined holding and diversification usually win.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-EEBF993B', 'Investing in Indonesia', 'idx_basics', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match the term with its Indonesian stock-market meaning.", "pairs": [["IDX", "Indonesia Stock Exchange"], ["SUN", "Government bonds"], ["IPO", "First sale of stock to the public"], ["Market cap", "Total value of all shares"]], "answer": {"IDX": "Indonesia Stock Exchange", "SUN": "Government bonds", "IPO": "First sale of stock to the public", "Market cap": "Total value of all shares"}, "explanation": "Knowing local terms helps you read Indonesian market news and disclosures.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-38D4B392', 'Investing in Indonesia', 'goal_setting', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "Before investing, decide your time horizon, risk tolerance, and _____.", "answer": "goal", "explanation": "Investing without a goal makes it hard to choose the right asset mix or stay disciplined during volatility.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-18F29E2F', 'Cryptocurrency 101', 'what_is_cryptocurrency', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which statement best describes Bitcoin?", "options": ["A decentralised digital asset with no central issuer", "A government-issued digital rupiah", "A share of a technology company", "A deposit account with a fixed interest rate"], "answer": "A decentralised digital asset with no central issuer", "explanation": "Bitcoin operates on a decentralised network; it is not issued or backed by any government or company.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-2FA802D7', 'Cryptocurrency 101', 'crypto_risks', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Cryptocurrency prices are generally stable and predictable.", "answer": false, "explanation": "Crypto prices can be highly volatile; large swings up or down are common.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-96BA844B', 'Cryptocurrency 101', 'how_to_buy_crypto_safely', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the safest first step before buying crypto in Indonesia?", "options": ["Use a Bappebti-registered exchange and understand the risks", "Buy from a random Telegram seller", "Borrow money to buy more", "Trust a ''guaranteed profit'' group"], "answer": "Use a Bappebti-registered exchange and understand the risks", "explanation": "Use regulated platforms and never trust guarantees in crypto.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-6F654FE3', 'Cryptocurrency 101', 'crypto_risks', 'beginner', 'select_all', '{"type": "select_all", "difficulty": "beginner", "question": "Select ALL common crypto scams.", "options": ["Fake exchange apps", "Guaranteed return promises", "Phishing links in DMs", "Rug pulls in unknown tokens"], "answer": ["Fake exchange apps", "Guaranteed return promises", "Phishing links in DMs", "Rug pulls in unknown tokens"], "explanation": "These are all well-documented risks in the crypto space.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-A13BB091', 'Cryptocurrency 101', 'crypto_vs_investing_vs_gambling', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the key difference between investing and gambling?", "options": ["Investing is based on analysis and accepting measured risk; gambling relies mainly on chance", "There is no difference", "Investing always guarantees profit", "Gambling is regulated and investing is not"], "answer": "Investing is based on analysis and accepting measured risk; gambling relies mainly on chance", "explanation": "Investing involves research, time horizon, and risk management; gambling is mostly random outcomes.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-0FF7E68C', 'Cryptocurrency 101', 'what_is_cryptocurrency', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "A private key is like a password that gives full control of your crypto _____.", "answer": "wallet", "explanation": "Whoever holds the private key controls the assets; losing it can mean permanent loss.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-F7EB3F3C', 'Cryptocurrency 101', 'crypto_risks', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "It is safe to store all your crypto on an exchange long term because exchanges cannot be hacked.", "answer": false, "explanation": "Exchanges can be hacked or fail; long-term holders often use personal wallets with proper key management.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-37624DC6', 'Cryptocurrency 101', 'crypto_vs_investing_vs_gambling', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which behaviour is closest to gambling rather than investing?", "options": ["Buying a coin because a celebrity tweeted about it without research", "Buying a broad index fund and holding for ten years", "Building an emergency fund before investing", "Reading company annual reports"], "answer": "Buying a coin because a celebrity tweeted about it without research", "explanation": "Impulse buying based on hype is speculation or gambling, not disciplined investing.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-67C7A680', 'Cryptocurrency 101', 'how_to_buy_crypto_safely', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order the safest actions for someone curious about crypto.", "options": ["Learn how it works", "Only use money you can afford to lose", "Choose a regulated exchange", "Start with a small amount", "Store keys securely"], "answer": ["Learn how it works", "Only use money you can afford to lose", "Choose a regulated exchange", "Start with a small amount", "Store keys securely"], "explanation": "Education, limited capital, regulation, and security come before any significant exposure.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-65470C18', 'Cryptocurrency 101', 'what_is_cryptocurrency', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "In Indonesia, crypto is regulated as a _____ asset by Bappebti, not as legal tender.", "options": ["commodity", "currency", "stock", "bond"], "answer": ["commodity"], "explanation": "Crypto is treated as a tradable commodity in Indonesia, not as official currency.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-BAD53E70', 'Cryptocurrency 101', 'crypto_risks', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is a ''rug pull'' in crypto?", "options": ["Developers abandon a project and take investors'' funds", "A physical rug is sold for crypto", "A government ban on mining", "A type of hardware wallet"], "answer": "Developers abandon a project and take investors'' funds", "explanation": "Rug pulls happen when project creators disappear with the money, often in little-known tokens.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7C6FC7C6', 'Cryptocurrency 101', 'crypto_risks', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Because crypto is digital, it is protected from all forms of fraud.", "answer": false, "explanation": "Crypto transactions are irreversible and the space has many scams; users must protect themselves.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-5B0D8370', 'Cryptocurrency 101', 'what_is_cryptocurrency', 'beginner', 'matching', '{"type": "matching", "difficulty": "beginner", "question": "Match each crypto term with its meaning.", "pairs": [["Blockchain", "Distributed digital ledger"], ["Wallet", "Stores your crypto keys"], ["Exchange", "Platform to buy and sell crypto"], ["Volatility", "Large price swings"]], "answer": {"Blockchain": "Distributed digital ledger", "Wallet": "Stores your crypto keys", "Exchange": "Platform to buy and sell crypto", "Volatility": "Large price swings"}, "explanation": "Understanding basic terminology helps you navigate crypto safely.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-8D945211', 'Cryptocurrency 101', 'crypto_vs_investing_vs_gambling', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "Only invest in crypto with money you are truly willing to _____.", "answer": "lose", "explanation": "Crypto is highly speculative; never use money needed for essentials or short-term obligations.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-458F1AEB', 'Foundation 0', 'money_basics', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which of the following is a store of value?", "options": ["Money saved in a savings account", "A promise to do chores", "A favourite song", "A meal already eaten"], "answer": "Money saved in a savings account", "explanation": "A store of value lets you save purchasing power for future use.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-57B99AC0', 'Foundation 0', 'income_wealth', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Income and wealth mean the same thing.", "answer": false, "explanation": "Income is money coming in; wealth is what you have accumulated after subtracting debts.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-107A7BED', 'Foundation 0', 'risk_basics', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What is the best simple definition of risk?", "options": ["The chance that something bad happens to your money", "A guarantee of loss", "The same as return", "Only something that happens to stocks"], "answer": "The chance that something bad happens to your money", "explanation": "Risk is the possibility of an unwanted financial outcome, not a certainty.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-63553A8F', 'Foundation 0', 'needs_vs_wants', 'beginner', 'fill_blank', '{"type": "fill_blank", "difficulty": "beginner", "question": "A need is something you must have to live and _____.", "answer": "function", "explanation": "Needs support basic living and functioning; wants are optional extras.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-50F3A6EE', 'Foundation 0', 'assets_liabilities', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "Which is an example of an asset that could become a liability?", "options": ["A motorbike bought only for weekend fun on credit", "A savings account", "A skill that earns freelance income", "A government bond"], "answer": "A motorbike bought only for weekend fun on credit", "explanation": "The same item can be an asset or liability depending on use and cost.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-7102F36A', 'Foundation 0', 'saving_vs_investing', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "Saving is for short-term needs, while investing is usually for long-term growth.", "answer": true, "explanation": "Savings prioritise safety and access; investing accepts volatility for potential growth.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-026305CA', 'Foundation 0', 'inflation', 'beginner', 'multiple_choice', '{"type": "multiple_choice", "difficulty": "beginner", "question": "What does inflation do to the purchasing power of cash?", "options": ["It can reduce it over time", "It always increases it", "It has no effect", "It doubles it every year"], "answer": "It can reduce it over time", "explanation": "As prices rise, the same amount of cash buys fewer goods and services.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-862AA31A', 'Foundation 0', 'interest', 'beginner', 'word_bank', '{"type": "word_bank", "difficulty": "beginner", "question": "Interest is the price of using _____ over time.", "options": ["money", "gold", "land", "labour"], "answer": ["money"], "explanation": "Interest is what you earn for lending money or pay for borrowing it.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-61B05F80', 'Foundation 0', 'risk_basics', 'beginner', 'ordering', '{"type": "ordering", "difficulty": "beginner", "question": "Order these from safest to riskiest for short-term money.", "options": ["Cash in a bank account", "Government bond", "Broad stock index", "Single speculative stock"], "answer": ["Cash in a bank account", "Government bond", "Broad stock index", "Single speculative stock"], "explanation": "Safety and liquidity decrease as potential return and volatility increase.", "parameters": {}}'::jsonb, TRUE),
  ('DF2-02D0F4B6', 'Foundation 0', 'emergency_fund', 'beginner', 'true_false', '{"type": "true_false", "difficulty": "beginner", "question": "An emergency fund should be kept somewhere risky to earn higher returns.", "answer": false, "explanation": "Emergency funds need safety and quick access; risky investments can lose value exactly when you need the money.", "parameters": {}}'::jsonb, TRUE);

-- 3. Update Daily Focus generation to use the separate bank.
-- The engine currently supports multiple_choice, true_false, and swipe_yes_no;
-- other types are stored for future engine support.
CREATE OR REPLACE FUNCTION ensure_daily_focus_challenge(
  p_user_id UUID,
  p_time_zone TEXT
)
RETURNS daily_focus_challenges
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_time_zone TEXT := assert_focus_time_zone(p_time_zone);
  v_today DATE := (NOW() AT TIME ZONE v_time_zone)::DATE;
  v_profile focus_profiles;
  v_questions JSONB;
  v_challenge daily_focus_challenges;
BEGIN
  INSERT INTO focus_profiles (user_id, time_zone)
  VALUES (p_user_id, v_time_zone)
  ON CONFLICT (user_id) DO NOTHING;

  SELECT * INTO v_profile
  FROM focus_profiles
  WHERE user_id = p_user_id
  FOR UPDATE;

  UPDATE focus_profiles
  SET time_zone = v_time_zone,
      updated_at = NOW()
  WHERE user_id = p_user_id
  RETURNING * INTO v_profile;

  SELECT COALESCE(jsonb_agg(question_body), '[]'::JSONB)
  INTO v_questions
  FROM (
    SELECT dfq.body AS question_body
    FROM daily_focus_questions AS dfq
    WHERE dfq.is_active = TRUE
      AND dfq.type IN ('multiple_choice', 'true_false', 'swipe_yes_no')
      AND dfq.body ? 'question'
      AND dfq.body ? 'answer'
    ORDER BY md5(dfq.id || p_user_id::TEXT || v_today::TEXT)
    LIMIT 5
  ) AS selectable_questions;

  IF jsonb_array_length(v_questions) <> 5 THEN
    RAISE EXCEPTION 'Daily Focus needs at least five active binary or multiple-choice question variants';
  END IF;

  INSERT INTO daily_focus_challenges (
    user_id, challenge_date, time_zone, max_focus, focus_remaining, questions
  ) VALUES (
    p_user_id, v_today, v_time_zone, v_profile.max_focus, v_profile.max_focus, v_questions
  )
  ON CONFLICT (user_id, challenge_date) DO NOTHING;

  SELECT * INTO v_challenge
  FROM daily_focus_challenges
  WHERE user_id = p_user_id AND challenge_date = v_today;

  RETURN v_challenge;
END;
$$;

COMMIT;