-- KO-225 group 5 continuation batch 22

update public.content_variants set body_id = $json${"type":"matching","answer":{"Deflation":"Penurunan harga secara umum","Inflation":"Kenaikan harga secara umum","Stagflation":"Inflasi tinggi + stagnasi","Hyperinflation":"Kenaikan harga yang sangat cepat"},"options":{"left":["Inflasi","Deflasi","Stagflasi","Hiperinflasi"],"right":["Kenaikan harga secara umum","Penurunan harga secara umum","Inflasi tinggi + stagnasi","Kenaikan harga yang sangat cepat"]},"question":"Cocokkan setiap kondisi perekonomian dengan definisinya:","difficulty":"beginner","parameters":{},"explanation":"Pertandingan yang benar: Inflasi → Kenaikan harga secara umum, Deflasi → Penurunan harga secara umum, Stagflasi → Inflasi tinggi + stagnasi, Hiperinflasi → Kenaikan harga yang sangat cepat"}$json$::jsonb where id = 'cf1c55b9-4335-416d-9c09-f730775dd273';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["Rasio P/E","EPS"],"options":["Rasio P/E","EPS","KIJANG","kapitalisasi pasar"],"question":"Metrik fundamental seperti ________ dan ________ membantu mengevaluasi penilaian saham.","difficulty":"beginner","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah: P/E rasio, EPS."}$json$::jsonb where id = 'cf553b03-cc9b-4753-8a00-8101cf9031e9';
update public.content_variants set body = $json${"text":"Dodi bought a motorbike on credit to become an online motorcycle taxi driver. The motorbike makes money every day from orders, even though he still pays in installments. For Dodi, the motorbike is an asset because it puts money in his pocket."}$json$::jsonb where id = 'cf6fe211-324f-41b3-8089-135cc6b7c0a0';
update public.content_variants set body_id = $json${"type":"calculation","answer":"1,600,000","question":"Anda mendapat penghasilan Rp 8 juta setiap bulannya. Mengikuti aturan 50/30/20, berapa jumlah yang harus ditabung dan berhutang?","difficulty":"beginner","parameters":{"hint":"Calculate 20% of the monthly income."},"explanation":"20% dari 8.000.000 = 0,20 × 8.000.000 = Rp 1.600.000."}$json$::jsonb where id = 'cf9963d4-a613-4275-b306-b7e4c298cf17';
update public.content_variants set body_id = $json${"type":"scenario","answer":"Investasikan secara bertahap seiring berjalannya waktu","options":["Investasikan semuanya sekaligus","Investasikan secara bertahap seiring berjalannya waktu","Tunggu waktu yang tepat","Jangan pernah berinvestasi"],"question":"Sebuah perusahaan memberikan kenaikan 8% ketika inflasi 3%. Apa yang terjadi dengan daya saing mereka vs rival asing? Apa yang akan dilakukan oleh orang yang melek finansial?","difficulty":"intermediate","parameters":{"scenario_text":"A company gives 8% raises when inflation is 3%. What happens to their competitiveness vs foreign rivals?"},"explanation":"Dalam skenario ini, berinvestasi secara bertahap dari waktu ke waktu merupakan pendekatan yang paling seimbang dan tepat dalam pengambilan keputusan keuangan."}$json$::jsonb where id = 'cfdfdaac-ce62-4a7f-aeb8-65f33fe68fb6';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["mempertaruhkan","kembali"],"options":["mempertaruhkan","kembali","diversifikasi","likuiditas"],"question":"Investor harus memahami trade-off antara ________ dan ________ yang diharapkan.","difficulty":"advanced","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah : risk, return."}$json$::jsonb where id = 'd0e1f766-ac1e-4090-9726-509f6cf0cbd2';
update public.content_variants set body = $json${"text":"Bayu follows influencers who always recommend the latest gadgets. He felt he had to buy so he wouldn't miss out. Even though the laptop is still functioning well."}$json$::jsonb where id = 'd1b5aa49-2e15-4e54-9a0c-db4c278e2696';
update public.content_variants set body = $json${"text":"Investment choices should be tailored to your goals and risk tolerance. Emergency funds should not be invested aggressively."}$json$::jsonb where id = 'd1b89173-1815-4d4c-9b1f-f5538127168d';
update public.content_variants set body_id = $json${"type":"comparison","answer":"Investasi dana indeks","options":["Pemilihan saham aktif","Investasi dana indeks","Keduanya membutuhkan keahlian yang sama","Tidak ada yang baik untuk pemula"],"question":"Bandingkan pengambilan saham aktif vs investasi dana indeks untuk pemula dengan waktu terbatas. Mana yang lebih cocok?","difficulty":"advanced","parameters":{},"explanation":"Dana indeks menawarkan diversifikasi instan, biaya lebih rendah, dan memerlukan lebih sedikit penelitian dan pemantauan."}$json$::jsonb where id = 'd1cfce5e-ec1d-4e68-874d-3730cefe5501';
update public.content_variants set body = $json${"text":"Fajar, a new employee in Jakarta, uses a financial records application to track daily expenses. He realized that 30% of his money was spent on food delivery. He started bringing provisions and reducing delivery orders.","source_ids":["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}$json$::jsonb where id = 'd2c9427e-e3c7-475c-bf8c-46f831a4db38';

