-- KO-225 group 5 exact duplicate translation batch 6

update public.content_variants set body = $json${"text":"An emergency fund is special savings for sudden needs such as illness, job loss, or home repairs. The amount is usually 3–6 months of routine expenses. Distinguish it from saving for holidays or shopping, because emergency funds are only used when it's really urgent."}$json$::jsonb where id = '3cd9f173-828a-4382-8b66-f4e35412d7c7';
update public.content_variants set body = $json${"text":"An investor buys BBRI shares at a price of IDR 4,000 per share. A year later the price was IDR 4,800. The capital gain is 20%, not including dividends the company may distribute.","source_ids":["52aff5b9-0d1c-42d8-8dba-a1a97a3f3b3f"]}$json$::jsonb where id = '3d09d13a-f45b-4e43-bd66-1f6fb3b2fda8';
update public.content_variants set body = $json${"text":"Main types: money market (low risk), fixed income (medium), stocks (high risk/return). Choose according to your goals and time."}$json$::jsonb where id = '3db49742-a2ed-4aab-838e-7ce80d8142b3';
update public.content_variants set body = $json${"text":"Emergency funds are special savings for urgent needs such as illness, job loss, or damage to productive equipment. The amount is generally 3-6 months of expenses."}$json$::jsonb where id = '3f627048-75b6-4f32-8c48-a934e52fef98';
update public.content_variants set body = $json${"text":"The new investment application offers a balance bonus of IDR 1 million if users make a deposit of IDR 500,000. After deposit, the application cannot be accessed. The promise of big bonuses is a common tactic of fraud."}$json$::jsonb where id = '3f86d847-4384-4d91-9952-d7c16916ebac';
update public.content_variants set body = $json${"text":"Pak Sutrisno lost IDR 2 million because he panicked about selling shares when the price fell 15%. Two months later the share price rose again. He learned that panic selling can destroy long-term plans.","source_ids":["eca56a9e-df9b-432f-b360-c1ab6450a2ae"]}$json$::jsonb where id = '423b8a3a-a442-4c30-bf87-392a2b84df09';
update public.content_variants set body = $json${"text":"Rina saves IDR 1,000,000 in a deposit with interest of 4% per year. After one year, he received interest of IDR 40,000. Interest is a reward given by the bank because Rina lent her money to the bank temporarily."}$json$::jsonb where id = '44b16109-6165-47ac-aa56-490486f96d10';
update public.content_variants set body = $json${"text":"Stock trading on IDX takes place on working days, Monday-Friday. If Doni wants to buy shares, he must have a securities account at a registered securities company."}$json$::jsonb where id = '4571c39b-920e-4816-ad58-478c795b5d35';
update public.content_variants set body = $json${"text":"Rina has IDR 10,000,000. If it's all held in shares of one small company and that company goes bankrupt, the money is gone. If he buys a mutual fund containing many shares, a loss on one share does not destroy the entire investment."}$json$::jsonb where id = '4573ae74-7a47-4f9b-a91b-97f193fbb4ba';
update public.content_variants set body = $json${"text":"Needs are important things for living and studying, such as food, shelter, transportation, and credit. Desires are pleasant but not urgent."}$json$::jsonb where id = '4cc0e3d7-76e6-4d52-85f7-55e54a5b7f88';

