-- KO-225 group 1 translation batch 10

update public.content_variants set body = $json${"type":"word_bank","answer":["Money","less"],"options":["Money","less"],"question":"Complete the following sentences with words from the word bank: \"Inflation allows the same _____ to buy _____ goods over time.\"","difficulty":"beginner","parameters":{},"explanation":"Rising prices due to inflation reduce the number of goods that can be purchased with the same money."}$json$::jsonb where id = '54eddea4-5d9c-48d4-9473-b43809101711';
update public.content_variants set body = $json${"type":"case_study","answer":"Flash sales often make us buy things we don't need. Pausing before checkout is a simple strategy to avoid pitfalls.","caseText":"Dina found a flash sale buy 2 get 1 free skincare. There is still only half the skincare available at home, and this skincare is not a routine requirement.","followUp":{"answer":"Wait 24-48 hours and ask if it is really needed","options":["Wait 24-48 hours and ask if it is really needed","Check out immediately before it runs out","Buy because it's free 1","Share with friends to buy too"],"question":"What should Dina do before checkout?","explanation":"Pausing helps us avoid impulse purchases triggered by fake discounts."},"question":"Read the case and choose the best response.","difficulty":"beginner","explanation":"The spending trap often looks like saving money, but actually makes us buy things we don't need."}$json$::jsonb where id = '583e2ce4-82c7-4a71-b659-a6bd8d02577e';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because it is difficult to predict consistently","options":["Because it is difficult to predict consistently","Because macro indicators are not important","Because only banks are affected","Because macro indicators have not changed"],"question":"Why don't novice investors need to try 'timing' macro indicators?","difficulty":"advanced","explanation":"No one consistently predicts macro moves; focus on what can be controlled."}$json$::jsonb where id = '584ca181-c868-4f85-8c0b-5cc32bbccf83';
update public.content_variants set body = $json${"type":"fill_blank","answer":"three","question":"The commonly recommended emergency fund size is _____ to six months of expenses.","difficulty":"beginner","explanation":"An emergency fund should ideally be 3-6 months of expenses to deal with emergencies."}$json$::jsonb where id = '5d4289d6-5309-467e-b1bd-5c135964b46f';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because taxes reduce net returns","options":["Because taxes reduce net returns","Because taxes add to returns","Because taxes are only for companies","Because taxes do not apply to small investors"],"question":"Why is it important to take taxes into account when comparing returns?","difficulty":"advanced","explanation":"Gross returns can be higher than net returns after tax."}$json$::jsonb where id = '5e4b73d1-354e-4b17-ad3a-f6c81238675f';
update public.content_variants set body = $json${"type":"fill_blank","answer":"Lots","question":"Purchasing power shows how _____ goods or services can be purchased with a certain amount of money.","difficulty":"beginner","explanation":"Purchasing power measures the amount of goods/services that can be purchased, not just the nominal amount of money."}$json$::jsonb where id = '5eaa1a1c-6d45-4e7a-8934-f02a6068fdf1';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"So that investors can assess the health of the company","options":["To pay taxes","So that investors can assess the health of the company","To get free advertising","To change the share price"],"question":"Why are companies listed on IDX required to disclose financial reports?","difficulty":"intermediate","parameters":{},"explanation":"Transparency in financial reports helps investors make data-based decisions."}$json$::jsonb where id = '60915792-532d-4287-aa8a-6304a9c381fb';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because the money is managed professionally and diversified","options":["Because the money is managed professionally and diversified","Because profits are guaranteed by the government","Because there is no risk","Because it only takes IDR 10,000"],"question":"Why are mutual funds suitable for beginners like Ani?","difficulty":"intermediate","explanation":"Mutual funds allow beginners to have many assets at once with professional management."}$json$::jsonb where id = '61868608-687b-4fa6-961f-bac9de08bad0';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"PayLater and online lending are always free without risk.","difficulty":"beginner","explanation":"PayLater and Pinjol often charge interest, fines or fees which can make debts balloon."}$json$::jsonb where id = '61a7c4c5-4668-43ac-a170-a71c70db8fb8';
update public.content_variants set body = $json${"type":"ordering","answer":["Identify categories that exceed the limit","Reduce wants category spending","Transfer the difference to savings","Evaluate next month's budget"],"options":["Identify categories that exceed the limit","Reduce wants category spending","Transfer the difference to savings","Evaluate next month's budget"],"question":"Order steps to overcome expenses that exceed the budget.","difficulty":"beginner","parameters":{},"explanation":"Starting from identifying problems, reducing desires, switching to savings, then evaluating the next budget."}$json$::jsonb where id = '61a89b27-6785-4f78-9625-8a7895584967';

