-- KO-225 group 5 continuation batch 15

update public.content_variants set body_id = $json${"type":"true_false","answer":false,"question":"Anda harus kaya untuk mulai berinvestasi.","difficulty":"intermediate","parameters":{},"explanation":"Pernyataan ini tidak benar. Kesalahpahaman umum dapat menyebabkan keputusan keuangan yang buruk."}$json$::jsonb where id = 'b2a1c7f9-ec47-4e08-a6df-780f7c823aea';
update public.content_variants set body_id = $json${"type":"ordering","answer":["Rasakan kepanikan pasar","Berhenti dan bernapas","Tinjau rencana investasi Anda","Periksa fundamentalnya","Putuskan berdasarkan strategi, bukan emosi"],"options":["Rasakan kepanikan pasar","Berhenti dan bernapas","Tinjau rencana investasi Anda","Periksa fundamentalnya","Putuskan berdasarkan strategi, bukan emosi"],"question":"Urutkan langkah-langkah untuk menangani volatilitas pasar secara emosional:","difficulty":"advanced","parameters":{},"explanation":"Urutan yang benar adalah: Rasakan kepanikan pasar → Berhenti dan bernapaslah → Tinjau rencana investasi Anda → Periksa fundamental → Putuskan berdasarkan strategi, bukan emosi"}$json$::jsonb where id = 'b34b9739-773d-470d-aa67-54dfcb39fb5d';
update public.content_variants set body = $json${"text":"Today's BBCA shares opened at IDR 8,450, the highest was IDR 8,620, the lowest was IDR 8,400, and closed at IDR 8,550. Volume 45 million pieces. Open, high, low, close show the price range, while volume shows how actively the stock is traded."}$json$::jsonb where id = 'b35d054e-2feb-433b-8240-92644c266b9a';
update public.content_variants set body_id = $json${"type":"image_interpretation","answer":"Portofolio optimal untuk setiap tingkat risiko","options":["Pengembalian tertinggi terlepas dari risikonya","Portofolio optimal untuk setiap tingkat risiko","Portofolio yang paling aman","Ambang batas pengembalian yang terjamin"],"question":"[GAMBAR: Plot sebar yang menunjukkan risiko (volatilitas) pada sumbu X dan keuntungan pada sumbu Y. Beberapa saham Indonesia diplot. Garis diagonal menunjukkan batas efisien.]\n\nApa yang dimaksud dengan garis batas efisien?","difficulty":"advanced","parameters":{"image_description":"A scatter plot showing risk (volatility) on X-axis and return on Y-axis. Multiple Indonesian stocks plotted. A diagonal line shows the efficient frontier."},"explanation":"Perbatasan efisien mewakili portofolio yang menawarkan ekspektasi pengembalian tertinggi pada tingkat risiko tertentu."}$json$::jsonb where id = 'b36c4fea-5bf0-4114-825e-58f3d0b07906';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"kebutuhan vs keinginan","question":"Konsep ________ membantu individu membedakan antara pengeluaran penting dan tidak penting.","difficulty":"beginner","parameters":{},"explanation":"Memahami kebutuhan versus keinginan merupakan hal mendasar dalam penganggaran dan tabungan."}$json$::jsonb where id = 'b41b7977-5a92-419d-8c9f-8fbaa5a086d1';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"kebutuhan vs keinginan","question":"Konsep ________ membantu individu membedakan antara pengeluaran penting dan tidak penting.","difficulty":"intermediate","parameters":{},"explanation":"Memahami kebutuhan versus keinginan merupakan hal mendasar dalam penganggaran dan tabungan."}$json$::jsonb where id = 'b41d6b59-d3bd-495f-8800-0033d06a24c3';
update public.content_variants set body_id = $json${"type":"calculation","answer":"69,770,000","question":"Jika Anda menabung Rp 1.000.000 setiap bulan dengan bunga majemuk 6% per bulan, berapa jumlah yang akan Anda miliki setelah 5 tahun?","difficulty":"beginner","parameters":{"hint":"Use FV annuity formula with monthly compounding."},"explanation":"Menggunakan nilai masa depan dari rumus anuitas: FV = PMT × [(1+r)^n - 1]/r. Dengan r = 0,5% bulanan, n = 60, PMT = 1.000.000. FV ≈ Rp 69,77M."}$json$::jsonb where id = 'b5317ffd-6013-4fb5-949b-495de78b361d';
update public.content_variants set body_id = $json${"type":"ordering","answer":["Buka akun pialang","Selesaikan proses KYC","Setoran dana","Riset saham","Tempatkan pesanan pertama"],"options":["Buka akun pialang","Selesaikan proses KYC","Setoran dana","Riset saham","Tempatkan pesanan pertama"],"question":"Berikut langkah-langkah memulai investasi saham Indonesia:","difficulty":"beginner","parameters":{},"explanation":"Urutan yang benar adalah: Buka akun pialang → Selesaikan proses KYC → Setor dana → Riset saham → Lakukan pemesanan pertama"}$json$::jsonb where id = 'b5977add-1ed7-41da-8372-5174241f2341';
update public.content_variants set body = $json${"text":"A retiree who relies on cash savings will find his life more expensive every year. Savings that do not grow faster than inflation will run out of purchasing power.","source_ids":["097b62c4-9aae-4933-a870-ac74a526b8f1"]}$json$::jsonb where id = 'b6d211ca-35fe-4c5e-bbad-d88153c631b9';
update public.content_variants set body_id = $json${"type":"calculation","answer":"-2%","question":"Rekening tabungan Anda membayar bunga 3% setiap tahun. Inflasi adalah 5%. Berapa perkiraan keuntungan sebenarnya Anda?","difficulty":"advanced","parameters":{"hint":"Subtract inflation from the nominal interest rate."},"explanation":"Pengembalian riil ≈ pengembalian nominal - tingkat inflasi = 3% - 5% = -2%. Daya beli Anda menurun."}$json$::jsonb where id = 'b7c3f735-831d-457c-abfa-d9df1d65a946';

