-- KO-225 group 1 continuation batch 19

update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Following social media trends without research is an example of healthy herd behavior.","difficulty":"advanced","explanation":"Herd behavior can be dangerous if decisions are based on FOMO, not analysis."}$json$::jsonb where id = 'cfd0730f-511d-4ec9-87ea-89bb977f445b';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"SIPF provides protection for investors in the Indonesian capital market.","difficulty":"intermediate","explanation":"SIPF is a mechanism for protecting investors in the capital market according to regulations."}$json$::jsonb where id = 'd107ce71-ef08-4e0f-b42a-d1a2ed504944';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Variable income makes it unnecessary to create a budget.","difficulty":"intermediate","parameters":{},"explanation":"Non-fixed income actually requires a more flexible budget and emergency funds."}$json$::jsonb where id = 'd2a7dc2a-386d-41ae-9cd8-b4c2e5273c6a';
update public.content_variants set body = $json${"type":"fill_blank","answer":"risky","question":"For long-term goals, a portfolio can have more assets that have growth potential even though they are more _____.","difficulty":"intermediate","explanation":"Long time horizons allow us to withstand fluctuations in risky assets for potential higher returns."}$json$::jsonb where id = 'd525b34a-2f38-4860-bea1-8a8e92890b01';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Separate savings that are easy to withdraw","options":["Separate savings that are easy to withdraw","Individual shares","Volatile crypto","Borrowed money from friends"],"question":"Which is the most suitable place to store emergency funds?","difficulty":"beginner","explanation":"Emergency funds must be safe and liquid, so separate savings are the right choice."}$json$::jsonb where id = 'd91a8a8b-b2d1-4942-a58f-93cbcfe26641';
update public.content_variants set body = $json${"type":"ordering","answer":["Record all income","Divide expenses into needs, wants, and savings","Set limits for each category","Evaluate at the end of the month and adjust the next budget"],"options":["Record all income","Divide expenses into needs, wants, and savings","Set limits for each category","Evaluate at the end of the month and adjust the next budget"],"question":"Sequence the steps to create a monthly budget.","difficulty":"beginner","parameters":{},"explanation":"Start with income, then categorize it, set limits, and evaluate regularly."}$json$::jsonb where id = 'd9727e4a-e7db-4ae2-ba81-da5c9bbcc91e';
update public.content_variants set body = $json${"type":"fill_blank","answer":"Service","question":"OJK is an abbreviation for Financial _____ Authority.","difficulty":"beginner","explanation":"The Financial Services Authority regulates and supervises financial services in Indonesia."}$json$::jsonb where id = 'd9a8bc49-ebc2-445d-8b3c-0197b76c5190';
update public.content_variants set body = $json${"type":"matching","pairs":[["BI Rate rises","Savings/deposit interest tends to rise"],["High inflation","The purchasing power of money decreases"],["Rupiah weakens","Prices of imported goods tend to rise"]],"answer":{"BI Rate naik":"Savings/deposit interest tends to rise","Inflasi tinggi":"The purchasing power of money decreases","Rupiah melemah":"Prices of imported goods tend to rise"},"question":"Match macro indicators with their impact.","difficulty":"advanced","explanation":"Macro indicators are interrelated and influence personal finance."}$json$::jsonb where id = 'def9e811-af63-416e-abd9-521b0aa92d5f';
update public.content_variants set body = $json${"type":"word_bank","answer":["Increase in raw material prices","High demand","Rupiah weakens"],"options":["Increase in raw material prices","High demand","Rupiah weakens","High savings interest"],"question":"Factors that can trigger inflation: ____","difficulty":"intermediate","parameters":{},"explanation":"Rising raw material prices, high demand and a weakening rupiah can trigger inflation."}$json$::jsonb where id = 'e060ea82-d95d-4ddf-9f37-5e889b24bda4';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Any business that has levels of recruits is definitely a pyramid scheme.","difficulty":"beginner","explanation":"Tiers exist in many businesses. What makes the difference is whether the main income is from product sales or from recruitment fees."}$json$::jsonb where id = 'e0fe4634-688c-4989-b3dd-caa122527c0e';

