-- KO-225 group 1 continuation batch 20

update public.content_variants set body = $json${"type":"ordering","answer":["Select a registered securities company","Open a stock account","Deposit funds","Buy shares"],"options":["Select a registered securities company","Open a stock account","Deposit funds","Buy shares"],"question":"Sequence the steps to start investing in real shares:","difficulty":"beginner","parameters":{},"explanation":"Choose a security, open an account, deposit, then buy shares."}$json$::jsonb where id = 'e3f99b53-3697-4ec5-b484-5755bf8be7e9';
update public.content_variants set body = $json${"type":"case_study","answer":"This suggests a pyramid scheme because revenue depends on recruits, not product sales.","caseText":"Sari was invited to the skincare business. Entry package IDR 3,000,000. Big profits can be made if Sari recruits two friends, each of whom also has to buy a package of IDR 3,000,000. Sales of products to final consumers are hardly discussed.","followUp":{"answer":"Pyramid scheme","options":["Pyramid scheme","MLM is purely product based","Franchise franchise","Term savings"],"question":"What type of business is this?","explanation":"The main profits come from recruits and registration fees, not product sales."},"question":"Read the following cases and choose the best response.","difficulty":"beginner","explanation":"Pyramid schemes will collapse when there are no new members. Avoid businesses that emphasize recruiting rather than product sales."}$json$::jsonb where id = 'e7c4d48d-e538-4fba-823f-19d81735b4e3';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Inflation means that the prices of goods and services increase generally over a certain period of time.","difficulty":"beginner","explanation":"Inflation is a continuous increase in general prices, not an increase in just one item."}$json$::jsonb where id = 'e912ae59-23ab-43db-a05a-fe1695f8dc59';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Paper trading on Coins using real money.","difficulty":"beginner","parameters":{},"explanation":"Paper trading uses virtual money, not real money."}$json$::jsonb where id = 'eaa33b3e-75eb-43d1-a45c-aa8a2e08d1cd';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Purchasing power is greater in Yogyakarta","options":["Purchasing power is greater in Yogyakarta","Purchasing power is greater in Jakarta","The purchasing power is the same because the nominal value is the same","IDR 50,000 can't buy chicken noodles in two cities"],"question":"Chicken noodles in Jakarta Rp. 18,000, in Yogyakarta Rp. 12,000. Which statement is correct regarding Rp. 50,000?","difficulty":"beginner","explanation":"With a cheaper price, the same money can buy more portions, meaning greater purchasing power."}$json$::jsonb where id = 'eadf4fdc-8b39-4e53-949c-c41995c3a90c';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Emergency funds should be combined with daily spending money so that it is easy to access.","difficulty":"beginner","explanation":"Emergency funds should be separated so that they are not used for daily needs."}$json$::jsonb where id = 'eaea7d91-a34c-43f6-816a-57f05e7e6099';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"The returns advertised on investment products are definitely the same as those received by investors.","difficulty":"advanced","explanation":"Gross returns do not take into account taxes, fees and potential price changes."}$json$::jsonb where id = 'ececba83-82b0-46a1-b174-59f4115dcc48';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Lending money without collateral","options":["Lending money without collateral","Save money in a licensed bank","Buy credit at the official counter","Pay boarding fees on time"],"question":"Which is an example of risk in everyday life?","difficulty":"beginner","explanation":"Lending money without collateral risks the opponent not paying back."}$json$::jsonb where id = 'ef3c2514-0e5d-444c-8ac8-7582f6ab06f0';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Bank deposits with interest of 4% per year remain profitable even though inflation is 5% per year.","difficulty":"intermediate","parameters":{},"explanation":"Real deposit returns are negative because inflation is higher than interest."}$json$::jsonb where id = 'f003118b-c0c6-4729-838f-00b512ecacc7';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"1.5 more novels in the online store","options":["1.5 more novels in the online store","No difference","Novels are cheaper in physical stores","Rp. 100,000 is not enough in two places"],"question":"Rina has IDR 100,000. The price of a used novel in online stores is IDR 25,000, in physical stores IDR 40,000. What is the difference in purchasing power in the number of novels?","difficulty":"beginner","explanation":"In the online shop IDR 100,000 can get 4 novels; in physical stores only 2.5 novels. The difference is 1.5 novels."}$json$::jsonb where id = 'f1fd8db9-568c-4812-bdac-29195e7496e5';

