-- KO-225 group 1 batch 04: high-confidence duplicated Indonesian questions

update public.content_variants set body = $json${"type":"word_bank","answer":["go on","general"],"options":["go on","general"],"question":"Complete the following sentences with words from the word bank: \"Inflation occurs when the prices of goods and services _____ _____.\"","difficulty":"beginner","parameters":{},"explanation":"Inflation is a general increase in the prices of goods and services over a certain period of time."}$json$::jsonb where id = '15321024-10c5-4659-be9e-e726156bc6b4';
update public.content_variants set body = $json${"type":"fill_blank","answer":"data","question":"Phishing is a scam that impersonates a legitimate institution to steal _____ users.","difficulty":"beginner","explanation":"The aim of phishing is to steal personal data, passwords or OTP."}$json$::jsonb where id = '15867c25-09a3-4840-a193-f1820cba3281';
update public.content_variants set body = $json${"type":"fill_blank","answer":"effect","question":"To start buying shares on IDX, investors need to open a _____ account first.","difficulty":"beginner","parameters":{},"explanation":"A securities account is opened through a securities company so that investors can transact shares on IDX."}$json$::jsonb where id = '1748054b-8cea-4f9a-a3a7-b4ca4d972196';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"If the message appears to be from the bank, clicking on the link in it is always safe.","difficulty":"beginner","explanation":"Fraudsters can imitate the appearance of a bank. Always verify via the application or official number."}$json$::jsonb where id = '1779115e-75eb-417e-b06a-0af9bf2812da';
update public.content_variants set body = $json${"type":"matching","pairs":[["Emergency fund","Bank savings"],["1 year goal","Deposit"],["10 year goal","Stock mutual funds"]],"answer":{"Dana darurat":"Bank savings","Tujuan 1 tahun":"Deposit","Tujuan 10 tahun":"Stock mutual funds"},"question":"Match financial goals with the best fit.","difficulty":"intermediate","explanation":"The choice of instrument depends on the time and risk that can be tolerated."}$json$::jsonb where id = '178bb67f-d272-4e3a-8f5e-9fdf49211758';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Inflation that is too high will damage people's purchasing power.","difficulty":"beginner","parameters":{},"explanation":"High inflation causes the prices of goods to rise quickly, so that the same money can buy less."}$json$::jsonb where id = '17e173b7-c87c-4b24-808c-51bf77d911f6';
update public.content_variants set body = $json${"type":"fill_blank","answer":"Out","question":"FOMO is an abbreviation for Fear Of Missing _____.","difficulty":"advanced","explanation":"FOMO is the fear of missing out on an opportunity, which often drives impulsive decisions."}$json$::jsonb where id = '1dce8489-7003-478e-bf24-a1e88e04ea62';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Pay monthly fees","options":["Watch the cinema every week","Pay monthly fees","Buy new sneakers","Premium coffee subscription"],"question":"Which is a need, not a want?","difficulty":"beginner","parameters":{},"explanation":"Boarding house is a need for housing, while others can be postponed."}$json$::jsonb where id = '1e3c6de4-0bae-4ff6-8274-44b6979dd463';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because savings interest is lower than price increases","options":["Because savings interest is lower than price increases","Because the bank closed the account","Because inflation does not affect money","Because the price of goods falls"],"question":"Why can savings with low interest lose real value when inflation is high?","difficulty":"beginner","parameters":{},"explanation":"If savings interest is below inflation, the purchasing power of money decreases even though the nominal value remains the same."}$json$::jsonb where id = '1e9872b6-6586-4476-8bbb-af173d669d7c';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"SIPF provides protection to investors who hold securities in securities companies.","difficulty":"beginner","parameters":{},"explanation":"The Securities Investor Protection Fund (SIPF) protects investors in listed securities according to regulations."}$json$::jsonb where id = '225aa5e9-80de-444e-9a8c-f8599d3ce322';

