-- KO-225 group 5 exact duplicate translation batch 10

update public.content_variants set body = $json${"text":"A Telegram group promises profits of 20% per month, without risk, and asks to refer friends for greater profits. Promises like this violate the law of the market: high returns always have high risks. If it's too good to be true, it probably is."}$json$::jsonb where id = '7bcde6c6-2143-4896-a16a-07daa42861f1';
update public.content_variants set body = $json${"text":"Money market mutual funds have low risk and low returns. Individual stocks have high risk and potentially high returns. There is no instrument that provides high returns without risk.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = '7c92b500-a30e-42e1-8697-6b2f3de999ab';
update public.content_variants set body = $json${"text":"A portfolio is a combination of all the assets we own. Thinking about a portfolio means considering the whole, not just one asset."}$json$::jsonb where id = '7d1444b8-993e-47cb-b2d1-387be70a81ff';
update public.content_variants set body = $json${"text":"Money market mutual funds are low risk and suitable for the short term. Medium fixed income mutual funds. Stock mutual funds have the potential for high returns but fluctuate greatly."}$json$::jsonb where id = '82cd30d9-f6ac-481e-bc3c-390650297252';
update public.content_variants set body = $json${"text":"The time value of money means that money received now is more valuable than money received in the future, because money now can be used, saved, or invested."}$json$::jsonb where id = '866365a1-94f0-4391-a04f-662ada90e261';
update public.content_variants set body = $json${"text":"A chicken noodle seller in Jakarta keeps his business capital in three places: some in BCA savings, some in money market mutual funds, and a small part in blue chip stocks. If one place has problems, the business can still run.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = '8672cb4a-c413-4c53-9d73-2209349fc2d2';
update public.content_variants set body = $json${"text":"Rina saw her shares fall 5%. Because he was afraid of bigger losses, he immediately sold. Even though the aim is long-term investment and declines are normal. Loss aversion makes him overreact."}$json$::jsonb where id = '8750708a-9e0c-403a-8b64-c22b43b518e6';
update public.content_variants set body = $json${"text":"High income does not automatically make us rich. If expenses are greater than income, wealth can be zero or negative even if the salary is large."}$json$::jsonb where id = '89011549-5080-4d55-8961-f5615e63ba0d';
update public.content_variants set body = $json${"text":"Two investors have IDR 20,000,000. One bought GOTO, DCII, and other tech stocks all together. Others bought GOTO, BBRI, TLKM and bond mutual funds. Second investors are more protected if the technology sector corrects.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = '8aafa57f-2f8d-4f50-a440-bf2343cb590e';
update public.content_variants set body = $json${"text":"Buying 1 lot of BBCA shares means buying 100 shares of Bank Central Asia. By buying shares, we become owners of a small part of the bank. If the bank makes a profit, the share value can rise; if it loses, it can go down."}$json$::jsonb where id = '8c2fd7c4-35a6-4902-b0ac-f40336330a33';

