-- KO-225 group 5 continuation batch 13

update public.content_variants set body = $json${"text":"Alya receives pocket money of IDR 2,500,000 per month. He applies 50/30/20: IDR 1,250,000 for needs (boarding, food, transport), IDR 750,000 for desires (watching movies, snacks), and IDR 500,000 for savings.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04","ad0e8258-4e0a-4378-b257-4fd3628c6953"]}$json$::jsonb where id = 'a5fd353d-8499-4a87-8bde-8e5e9298d426';
update public.content_variants set body = $json${"text":"A friend recommended a 'crypto staking' app I'd never heard of. Before depositing, Budi opened the OJK website, looked for the name of the application on the list of licensed companies. Not found. Budi refused to invest and told his friend."}$json$::jsonb where id = 'a6374b54-3e4f-4c49-8b9f-e711ffd640fe';
update public.content_variants set body = $json${"text":"Debt traps occur when we borrow for consumption, pay late, or only pay the minimum so that interest accumulates."}$json$::jsonb where id = 'a72062cf-eda5-42a4-84e1-fa04875a7b11';
update public.content_variants set body = $json${"text":"A student in Malang uses the envelope method: at the beginning of every month he divides his pocket money into several categories in separate wallets. When the entertainment envelope ran out, he stopped having fun.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = 'a87ceb81-5fda-48a0-b1ec-9f2cacf16671';
update public.content_variants set body = $json${"text":"Five students formed an investment study group. They decided to set aside IDR 100,000 every month to buy IDX30 shares periodically. This strategy is called dollar-cost averaging.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'a993a433-bf70-4cb5-9fe4-9808518405b9';
update public.content_variants set body = $json${"text":"Budi wants to own a house in 10 years. He makes a plan: calculate funding needs, set aside every month, choose investment instruments according to the horizon, and evaluate every year."}$json$::jsonb where id = 'a9c1ccda-7c46-462a-9c71-50525fffb3c9';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Berapa tingkat bunganya dan apakah saya mampu membayar pembayarannya?","options":["Apakah ini akan mengesankan teman-teman saya?","Berapa tingkat bunganya dan apakah saya mampu membayar pembayarannya?","Apakah barang tersebut sedang dijual?","Apakah itu datang dengan pengiriman gratis?"],"question":"Pertanyaan mana yang harus Anda tanyakan sebelum berhutang?","difficulty":"beginner","parameters":{},"explanation":"Memahami biaya dan kemampuan Anda untuk membayar kembali sangat penting sebelum meminjam."}$json$::jsonb where id = 'a9ca8616-0323-499a-84fe-85325e69f7b8';
update public.content_variants set body_id = $json${"type":"calculation","answer":"8.4%","question":"Jika Rp 100 juta tumbuh menjadi Rp 150 juta dalam 5 tahun, berapa perkiraan tingkat pertumbuhan gabungan tahunan (CAGR)?","difficulty":"beginner","parameters":{"hint":"Use the CAGR formula: (FV/PV)^(1/years) - 1."},"explanation":"CAGR = (Nilai Akhir / Nilai Awal)^(1/n) - 1 = (150/100)^(1/5) - 1 ≈ 8,4%."}$json$::jsonb where id = 'a9de97c3-4235-4df4-ad50-399ef8dc65d7';
update public.content_variants set body = $json${"text":"Purchasing power is how much goods or services can be purchased with a certain amount of money. Rp. 50,000 could be worth more in a small town than in a big city if prices are cheaper."}$json$::jsonb where id = 'aab987c6-3037-4636-a1df-fec5acbe99bf';
update public.content_variants set body_id = $json${"type":"definition_match","answer":{"Crash":"Penurunan drastis harga saham secara tiba-tiba sebesar 20% atau lebih","Correction":"Penurunan 10% atau lebih dari puncaknya baru-baru ini","Bear Market":"Suatu kondisi pasar dimana harga sedang turun atau diperkirakan akan turun","Bull Market":"Suatu kondisi pasar dimana harga sedang naik atau diperkirakan akan naik"},"options":{"terms":["Pasar Banteng","Pasar Beruang","Koreksi","Menabrak"],"definitions":["Suatu kondisi pasar dimana harga sedang naik atau diperkirakan akan naik","Suatu kondisi pasar dimana harga sedang turun atau diperkirakan akan turun","Penurunan 10% atau lebih dari puncaknya baru-baru ini","Penurunan drastis harga saham secara tiba-tiba sebesar 20% atau lebih"]},"question":"Cocokkan setiap istilah pasar dengan deskripsinya:","difficulty":"intermediate","parameters":{},"explanation":"Pertandingan yang benar: Bull Market = Kondisi pasar di mana harga sedang naik atau diperkirakan akan naik, Bear Market = Kondisi pasar di mana harga akan turun atau diperkirakan akan turun, Correction = Penurunan sebesar 10% atau lebih dari harga puncak baru-baru ini, Crash = Penurunan harga saham secara tiba-tiba dan drastis sebesar 20% atau lebih"}$json$::jsonb where id = 'abeab129-bb52-4d2f-8378-12d3e6321a0f';

