-- KO-225 group 1 continuation batch 21

update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"High inflation always increases the purchasing power of money.","difficulty":"advanced","explanation":"High inflation erodes purchasing power because the price of goods rises."}$json$::jsonb where id = 'f23d2d24-3b2d-4f29-b3e9-3c5732b6a1fd';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Productive MLM focuses on selling products; recruiting focus pyramid","options":["Productive MLM focuses on selling products; recruiting focus pyramid","Illegal MLM; legal pyramid","Both are the same","Pyramids sell more products"],"question":"What is the main difference between productive MLM and pyramid schemes?","difficulty":"beginner","explanation":"The primary source of income determines whether the business is product-based or pyramid-based."}$json$::jsonb where id = 'f3341059-f4b9-4bde-97ef-71854156447f';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Purchasing power decreases 2%","options":["Purchasing power decreases 2%","Purchasing power rises 2%","Purchasing power remains the same","Purchasing power rises 8%"],"question":"If inflation is 5% per year and your savings interest is 3% per year, what happens to the purchasing power of your savings?","difficulty":"beginner","explanation":"5% inflation erodes the value of money faster than 3% interest adds to it, so real purchasing power falls by about 2%."}$json$::jsonb where id = 'f37f554e-94cb-41e1-ba93-ea27c1cc428b';
update public.content_variants set body = $json${"type":"ordering","answer":["Determine financial goals","Understand risk tolerance","Select different types of assets","Monitor and adjust regularly"],"options":["Determine financial goals","Understand risk tolerance","Select different types of assets","Monitor and adjust regularly"],"question":"Sequence the steps for compiling a healthy portfolio.","difficulty":"intermediate","parameters":{},"explanation":"Start with goals, understand risks, diversify, then monitor and adjust."}$json$::jsonb where id = 'f433c456-836d-462b-8d20-10789fc09fe1';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"High returns usually come with high risk","options":["High returns usually come with high risk","Safe investments always generate big profits","High risk means definite loss","Return and risk are not related"],"question":"Which statement is correct about the relationship between risk and return?","difficulty":"intermediate","explanation":"Investors demand greater compensation for taking on greater risks."}$json$::jsonb where id = 'f66c2e8d-4334-4225-91fc-d88cb2a005c9';
update public.content_variants set body = $json${"type":"fill_blank","answer":"flower","question":"Compound interest means we get interest from the initial capital and also from the _____ that was obtained previously.","difficulty":"intermediate","explanation":"Compound interest earns interest on interest, not just on the initial capital."}$json$::jsonb where id = 'f78d1771-d1c1-4b66-b489-ceb46fab20fa';
update public.content_variants set body = $json${"type":"fill_blank","answer":"tall","question":"To get out of the debt trap, pay off the debt with the highest _____ interest first.","difficulty":"beginner","explanation":"High-interest debt accumulates the fastest, so it should be prioritized."}$json$::jsonb where id = 'f7903fde-3b1f-4297-a521-ddc574317e68';
update public.content_variants set body = $json${"type":"word_bank","answer":["Instant diversification","Liquid on the exchange"],"options":["Instant diversification","Lower costs","No risk","Liquid on the exchange"],"question":"Benefits of ETFs over individual stocks: ____","difficulty":"intermediate","parameters":{},"explanation":"ETFs provide instant diversification and are traded on exchanges."}$json$::jsonb where id = 'f7f83a1f-0967-4088-aa4f-23d84d4f671f';
update public.content_variants set body = $json${"type":"word_bank","answer":["Need","Desire","Savings"],"options":["Need","Desire","Savings","Consumer debt"],"question":"The 50/30/20 budget category consists of: ____","difficulty":"beginner","parameters":{},"explanation":"50/30/20 is needs, wants, and savings/debt."}$json$::jsonb where id = 'f8d09cdf-e55b-461a-9451-a2cbca6ce749';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Requesting an OTP via an unsolicited link","options":["Requesting an OTP via an unsolicited link","Use the official bank number","Provide information without asking for data","Send proof of transaction"],"question":"Which are the characteristics of a phishing message?","difficulty":"beginner","explanation":"Official financial institutions do not ask for OTP or password via the link."}$json$::jsonb where id = 'fa2d8d28-a24e-413f-977a-109c0176dbf0';

