-- KO-225: these two English matching questions had English duplicated into
-- body_id. Keep body English and provide a complete Indonesian counterpart.

update public.content_variants
set body_id = $json${"type":"matching","answer":{"FOMO":"Takut ketinggalan","Loss Aversion":"Takut rugi lebih besar daripada senang mendapat untung","Overconfidence":"Rasa percaya diri yang berlebihan","Confirmation Bias":"Mencari informasi yang membenarkan keyakinan"},"options":{"left":["Takut rugi","Takut ketinggalan","Bias konfirmasi","Rasa percaya diri berlebihan"],"right":["Takut rugi lebih besar daripada senang mendapat untung","Takut ketinggalan","Mencari informasi yang membenarkan keyakinan","Rasa percaya diri yang berlebihan"]},"question":"Cocokkan setiap bias perilaku dengan definisinya:","difficulty":"advanced","parameters":{},"explanation":"Pasangan yang benar: Takut rugi → Takut rugi lebih besar daripada senang mendapat untung, Takut ketinggalan → Takut ketinggalan, Bias konfirmasi → Mencari informasi yang membenarkan keyakinan, Rasa percaya diri berlebihan → Rasa percaya diri yang berlebihan"}$json$::jsonb
where id = 'fcf9cb8f-3187-4b1c-b018-15f2d5017a17';

update public.content_variants
set body_id = $json${"type":"matching","answer":{"FOMO":"Takut ketinggalan","Loss Aversion":"Takut rugi lebih besar daripada senang mendapat untung","Overconfidence":"Rasa percaya diri yang berlebihan","Confirmation Bias":"Mencari informasi yang membenarkan keyakinan"},"options":{"left":["Takut rugi","Takut ketinggalan","Bias konfirmasi","Rasa percaya diri berlebihan"],"right":["Takut rugi lebih besar daripada senang mendapat untung","Takut ketinggalan","Mencari informasi yang membenarkan keyakinan","Rasa percaya diri yang berlebihan"]},"question":"Cocokkan setiap bias perilaku dengan definisinya:","difficulty":"intermediate","parameters":{},"explanation":"Pasangan yang benar: Takut rugi → Takut rugi lebih besar daripada senang mendapat untung, Takut ketinggalan → Takut ketinggalan, Bias konfirmasi → Mencari informasi yang membenarkan keyakinan, Rasa percaya diri berlebihan → Rasa percaya diri yang berlebihan"}$json$::jsonb
where id = 'ffaa48e9-5e02-4dc8-bbee-d3fcade25b92';
