-- KO-225: translate the three remaining Indonesian payloads containing
-- genuine English learner-facing strings. Preserve matching labels and keys.
update public.content_variants
set body_id = $json${"type":"definition_match","answer":{"Crash":"Penurunan harga saham yang tiba-tiba dan drastis sebesar 20% atau lebih","Correction":"Penurunan 10% atau lebih dari puncak terbaru","Bear Market":"Kondisi pasar ketika harga sedang turun atau diperkirakan akan turun","Bull Market":"Kondisi pasar ketika harga sedang naik atau diperkirakan akan naik"},"options":{"terms":["Bull Market","Bear Market","Correction","Crash"],"definitions":["Kondisi pasar ketika harga sedang naik atau diperkirakan akan naik","Kondisi pasar ketika harga sedang turun atau diperkirakan akan turun","Penurunan 10% atau lebih dari puncak terbaru","Penurunan harga saham yang tiba-tiba dan drastis sebesar 20% atau lebih"]},"question":"Cocokkan setiap istilah pasar dengan deskripsinya:","difficulty":"beginner","parameters":{},"explanation":"Kecocokan yang benar: Bull Market = Kondisi pasar ketika harga sedang naik atau diperkirakan akan naik, Bear Market = Kondisi pasar ketika harga sedang turun atau diperkirakan akan turun, Correction = Penurunan 10% atau lebih dari puncak terbaru, Crash = Penurunan dramatis mendadak sebesar 20% atau lebih dalam harga saham"}$json$::jsonb
where id = '52572775-5603-4e00-aac5-a7e53ce25485';

update public.content_variants
set body_id = $json${"type":"definition_match","answer":{"Crash":"Penurunan harga saham yang tiba-tiba dan drastis sebesar 20% atau lebih","Correction":"Penurunan 10% atau lebih dari puncak terbaru","Bear Market":"Kondisi pasar ketika harga sedang turun atau diperkirakan akan turun","Bull Market":"Kondisi pasar ketika harga sedang naik atau diperkirakan akan naik"},"options":{"terms":["Bull Market","Bear Market","Correction","Crash"],"definitions":["Kondisi pasar ketika harga sedang naik atau diperkirakan akan naik","Kondisi pasar ketika harga sedang turun atau diperkirakan akan turun","Penurunan 10% atau lebih dari puncak terbaru","Penurunan harga saham yang tiba-tiba dan drastis sebesar 20% atau lebih"]},"question":"Cocokkan setiap istilah pasar dengan deskripsinya:","difficulty":"advanced","parameters":{},"explanation":"Kecocokan yang benar: Bull Market = Kondisi pasar ketika harga sedang naik atau diperkirakan akan naik, Bear Market = Kondisi pasar ketika harga sedang turun atau diperkirakan akan turun, Koreksi = Penurunan 10% atau lebih dari puncak terbaru, Crash = Penurunan dramatis mendadak sebesar 20% atau lebih dalam harga saham"}$json$::jsonb
where id = 'a73b4c7b-bbfb-416a-9242-14c4e3ea2489';

update public.content_variants
set body_id = $json${"type":"spot_mistake","answer":["Investasi berdasarkan takhayul","Klaim informasi orang dalam yang tidak terverifikasi","Tidak ada analisis fundamental","Mengikuti saran dari pihak yang tidak memenuhi syarat"],"options":["Investasi berdasarkan takhayul","Klaim informasi orang dalam yang tidak terverifikasi","Tidak ada analisis fundamental","Mengikuti saran dari pihak yang tidak memenuhi syarat","Tidak ada kesalahan","Hanya satu kesalahan kecil"],"question":"Baca pernyataan berikut dan identifikasi kesalahan finansial:\n\nSaya berinvestasi berdasarkan ramalan zodiak dan saran admin grup WhatsApp yang mengaku punya informasi orang dalam. Saya tidak pernah membaca laporan keuangan.","difficulty":"beginner","parameters":{"mistake_count":4},"explanation":"Keputusan investasi harus didasarkan pada riset dan fundamental, bukan takhayul atau tips yang belum terverifikasi."}$json$::jsonb
where id = 'ea4f0582-88d3-4942-b51f-095ac74ea811';
