-- KO-225 group 5 continuation batch 21

update public.content_variants set body_id = $json${"type":"calculation","answer":"8.4%","question":"Jika Rp 100 juta tumbuh menjadi Rp 150 juta dalam 5 tahun, berapa perkiraan tingkat pertumbuhan gabungan tahunan (CAGR)?","difficulty":"advanced","parameters":{"hint":"Use the CAGR formula: (FV/PV)^(1/years) - 1."},"explanation":"CAGR = (Nilai Akhir / Nilai Awal)^(1/n) - 1 = (150/100)^(1/5) - 1 ≈ 8,4%."}$json$::jsonb where id = 'ca6b784d-981d-4ff4-8566-ed9e33de4c76';
update public.content_variants set body = $json${"text":"Doni started saving IDR 100,000 per month from the age of 18 with a return of 6% per year. His brother started saving Rp. 100,000 per month from the age of 28. At the age of 40, Doni had much more because his money had time to grow longer and the interest earned more interest."}$json$::jsonb where id = 'cb099265-e8b8-4d05-b6e7-6a3978336e66';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["FOMO","keengganan terhadap kerugian"],"options":["FOMO","keengganan terhadap kerugian","mentalitas kawanan","bias konfirmasi"],"question":"Bias perilaku yang umum mencakup ________, ________, dan mengikuti orang banyak tanpa penelitian.","difficulty":"beginner","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah: FOMO, loss aversion."}$json$::jsonb where id = 'cb5ecd86-d77c-436a-aa20-b774d43957f2';
update public.content_variants set body = $json${"text":"Rian uses a financial records application to record every daily expense. At the end of every week, he reviews whether his spending is within budget. If it exceeds the limit, it reduces the next week's wish category.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = 'cba0520f-5650-4088-afa8-dcabf2737b00';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"2.5","question":"Bank Indonesia menargetkan inflasi sekitar ________ persen per tahun.","difficulty":"beginner","parameters":{},"explanation":"Sasaran inflasi BI sekitar 2,5% dengan batas toleransi ±1%."}$json$::jsonb where id = 'cbeba65a-79f8-4e35-abef-6c78f8d835fb';
update public.content_variants set body_id = $json${"type":"scenario","answer":"Rencanakan tujuan jangka panjang","options":["Fokus pada keuntungan jangka pendek","Rencanakan tujuan jangka panjang","Bereaksi terhadap setiap berita","Abaikan pasar"],"question":"Anda menghabiskan Rp 2 juta/bulan untuk pengiriman makanan. Apa salah satu cara untuk memotongnya tanpa memasaknya setiap hari? Apa kemungkinan hasil jangka panjang dari setiap pilihan?","difficulty":"beginner","parameters":{"scenario_text":"You spend Rp 2M/month on food delivery. What is one way to cut this without cooking every day?"},"explanation":"Dalam skenario ini, rencana untuk tujuan jangka panjang mewakili pendekatan yang paling seimbang dan terinformasi dalam pengambilan keputusan keuangan."}$json$::jsonb where id = 'cc6d1ed3-26ff-4a50-aeee-9e02744f5983';
update public.content_variants set body_id = $json${"type":"calculation","answer":"10","question":"Sebuah perusahaan mempunyai laba bersih sebesar Rp 100 miliar dan 10 miliar saham beredar. Apa itu EPSnya?","difficulty":"advanced","parameters":{"hint":"Divide total net income by the number of shares."},"explanation":"EPS = Laba Bersih / Saham Beredar = 100M / 10M = Rp 10 per saham."}$json$::jsonb where id = 'ccdd9af1-0bf5-4dd2-a24c-82773ea03b95';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Situs OJK","options":["Komentar Instagram","Situs OJK","Seorang teman yang sudah berinvestasi","Hanya aplikasi milik perusahaan"],"question":"Sebelum berinvestasi, di mana Anda harus memeriksa apakah produk atau perusahaan tersebut terdaftar secara sah?","difficulty":"beginner","parameters":{},"explanation":"OJK memiliki daftar resmi produk dan perusahaan keuangan yang memiliki izin. Selalu verifikasi di sana."}$json$::jsonb where id = 'cd625c3d-8fbc-4c29-9f69-89399bd16531';
update public.content_variants set body = $json${"text":"In 2020, Rina can buy 10 bowls of chicken noodles for IDR 120,000. In 2025, the price of chicken noodles will increase to IDR 16,000 per bowl, so that IDR 120,000 is only enough for 7.5 bowls. Inflation reduces the purchasing power of money that sits idle."}$json$::jsonb where id = 'cdd0bac9-61b3-4487-a3cd-28af29c48423';
update public.content_variants set body_id = $json${"type":"true_false","answer":false,"question":"Membayar utang berbunga tinggi hanya dalam jumlah minimum adalah strategi jangka panjang yang baik.","difficulty":"beginner","parameters":{},"explanation":"Pembayaran minimum meregangkan utang dan meningkatkan total bunga yang dibayarkan."}$json$::jsonb where id = 'cf1831df-afa2-42e8-8c7c-b93259a871dc';

