-- KO-225 group 1 translation batch 6

update public.content_variants set body = $json${"type":"ordering","answer":["Get to know your financial goals","Choose a combination of stocks, bonds, and mutual funds","Divide funds according to risk profile","Re-evaluate every 6 months"],"options":["Get to know your financial goals","Choose a combination of stocks, bonds, and mutual funds","Divide funds according to risk profile","Re-evaluate every 6 months"],"question":"Sequence the steps to build a diversified portfolio.","difficulty":"intermediate","parameters":{},"explanation":"Starting from the goal, select instruments, allocate according to the risk profile, then evaluate periodically."}$json$::jsonb where id = '2ea83ce2-acbf-42bb-be56-601b8ec7880d';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Legitimate investments always promise definite profits to customers.","difficulty":"beginner","explanation":"Legitimate investments involve risks and do not promise guaranteed profits."}$json$::jsonb where id = '3190f6d6-197f-4afd-84d9-ddd50db4ef18';
update public.content_variants set body = $json${"type":"case_study","answer":"If an offer combines high returns, no risk, and a referral scheme, that's a big red flag.","caseText":"A WhatsApp group offers investment with the promise: '20% profit per month, no risk, capital IDR 500,000, invite 2 friends for bonus.'","followUp":{"answer":"Stop and check OJK permission, do not transfer","options":["Stop and check OJK permission, do not transfer","Transfer IDR 500,000 because it is risk-free","Invite friends to get bonuses","Invest IDR 5,000,000 for big profits"],"question":"What should you do?","explanation":"High returns are guaranteed and the invite a friend scheme is a characteristic of fraudulent investments."},"question":"Read the following cases and choose the best response.","difficulty":"beginner","explanation":"Legitimate investments do not promise guaranteed returns. Always check OJK permission before spending money."}$json$::jsonb where id = '33ef8bda-e07c-49ef-a83e-61188c382ff9';
update public.content_variants set body = $json${"type":"ordering","answer":["Select registered securities","Open a securities account","Deposit funds","Make stock transactions"],"options":["Select registered securities","Open a securities account","Deposit funds","Make stock transactions"],"question":"Sort the stages of becoming a stock investor on IDX.","difficulty":"intermediate","parameters":{},"explanation":"Select registered securities, open a securities account, deposit funds, then carry out stock transactions."}$json$::jsonb where id = '34475e6f-3af3-4aa8-841a-909a6acba69c';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Buy a minimum of 1 lot (100 shares)","options":["Buy a minimum of 1 lot (100 shares)","Bought exactly 75 pieces","Selling 25 pieces","Borrow shares from a broker"],"question":"Doni wants to buy 75 shares of TLKM. What should he do?","difficulty":"intermediate","explanation":"IDX uses lot units, minimum 1 lot = 100 shares."}$json$::jsonb where id = '34d89769-e71b-47c7-8f55-534ac2eae7dc';
update public.content_variants set body = $json${"type":"fill_blank","answer":"risk","question":"For long-term goals, investments have the potential to provide higher returns but also have higher _____.","difficulty":"intermediate","explanation":"Higher returns generally come with higher risk."}$json$::jsonb where id = '353b5699-b19e-4b66-bbf6-4bede6119f31';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Stocks are ownership, bonds are loans","options":["Stocks are ownership, bonds are loans","Stocks are safer than bonds","Bonds are ownership","Both are the same"],"question":"Stocks are different from bonds because...","difficulty":"intermediate","explanation":"Shareholders own the company; Bondholders lend money to the company."}$json$::jsonb where id = '35820ca4-a032-4cb3-95db-18cb3b11ff3b';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Dodi","options":["Dodi","Eco","Both are the same","None of that is true"],"question":"Dodi bought a motorbike to become an online motorcycle taxi. Eko bought a similar motorbike just for traveling. Who is more likely to own assets?","difficulty":"beginner","explanation":"Dodi's motorbike generates income, so it is an asset. Eco motorbikes only cost money."}$json$::jsonb where id = '3602d75d-f33e-4d53-9f1e-1e59060fb7ff';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"So that it is not used for routine shopping","options":["So that it is not used for routine shopping","To get higher interest","So as not to be taxed","So you can lend it to a friend"],"question":"Why should emergency funds be separated from daily savings?","difficulty":"beginner","parameters":{},"explanation":"Separating emergency funds prevents urgent money from being absorbed by daily expenses that could otherwise be postponed."}$json$::jsonb where id = '37c03eb1-6122-43ab-a6d6-30b9842fac3b';
update public.content_variants set body = $json${"type":"fill_blank","answer":"need","question":"In the 50/30/20 rule, 50% is used for _____, 30% for desires, and 20% for savings and debt.","difficulty":"beginner","explanation":"50% for living needs, 30% for desires, and 20% for savings and paying off debt."}$json$::jsonb where id = '389b4cb4-7b95-478a-bceb-09190b9cda1d';

