-- KO-225 group 5 final exact duplicate translations

update public.content_variants set body_id = $json${"type":"fill_blank","answer":"keengganan terhadap kerugian","question":"Kecenderungan untuk merasakan kerugian yang lebih besar dibandingkan keuntungan yang setara disebut ________.","difficulty":"advanced","parameters":{},"explanation":"Keengganan terhadap kerugian adalah konsep kunci dalam keuangan perilaku di mana kerugian merugikan dua kali lipat dibandingkan keuntungan yang dirasakan baik."}$json$::jsonb where id = 'd684ccf0-835c-4054-a7d4-11f27e083645';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"20","question":"Aturan 50/30/20 menyarankan pengalokasian ________ persen pendapatan untuk tabungan dan pembayaran utang.","difficulty":"intermediate","parameters":{},"explanation":"Aturan 50/30/20 mengalokasikan 50% untuk kebutuhan, 30% untuk keinginan, dan 20% untuk tabungan dan utang."}$json$::jsonb where id = 'd7977056-e476-48c5-97b6-0a5193d109a1';
update public.content_variants set body = $json${"text":"Ani works part time with a salary of IDR 2,000,000 per month. Boarding IDR 800,000 and food IDR 600,000 are necessities (70%). He wants to stream and hang out Rp. 400,000 (20%). According to 50/30/20, he should set aside IDR 200,000 (10%) for savings/debt, ideally reducing desires by 30% so that savings are 20%."}$json$::jsonb where id = 'd7ec453f-4959-4e6a-a536-eafbab47e54c';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Sesuatu yang memiliki atau menghasilkan nilai","options":["Sesuatu yang selalu membutuhkan uang","Sesuatu yang memiliki atau menghasilkan nilai","Hanya properti fisik","Barang apa pun yang Anda beli secara kredit"],"question":"Dalam keuangan pribadi, apa yang dimaksud dengan aset?","difficulty":"beginner","parameters":{},"explanation":"Aset adalah sesuatu yang menyimpan atau menghasilkan nilai bagi Anda."}$json$::jsonb where id = 'd8577208-a1d6-450b-8f07-009e8689bbbb';
update public.content_variants set body_id = $json${"type":"definition_match","answer":{"Leverage":"Penggunaan modal pinjaman untuk meningkatkan potensi keuntungan","Solvency":"Kemampuan untuk memenuhi kewajiban keuangan jangka panjang","Liquidity":"Kemudahan suatu aset dapat dikonversi menjadi uang tunai","Volatility":"Tingkat variasi harga perdagangan dari waktu ke waktu"},"options":{"terms":["Likuiditas","Solvabilitas","Manfaat","Keriangan"],"definitions":["Kemudahan suatu aset dapat dikonversi menjadi uang tunai","Kemampuan untuk memenuhi kewajiban keuangan jangka panjang","Penggunaan modal pinjaman untuk meningkatkan potensi keuntungan","Tingkat variasi harga perdagangan dari waktu ke waktu"]},"question":"Cocokkan setiap konsep keuangan dengan definisinya:","difficulty":"beginner","parameters":{},"explanation":"Kecocokan yang benar: Likuiditas = Kemudahan suatu aset dapat dikonversi menjadi uang tunai, Solvabilitas = Kemampuan untuk memenuhi kewajiban keuangan jangka panjang, Leverage = Penggunaan modal pinjaman untuk meningkatkan potensi keuntungan, Volatilitas = Tingkat variasi harga perdagangan dari waktu ke waktu"}$json$::jsonb where id = 'd87701b4-aaff-4e3f-bf2e-9c0712bacd65';
update public.content_variants set body_id = $json${"type":"ordering","answer":["Hitung pendapatan bulanan","Buat daftar pengeluaran tetap","Buat daftar pengeluaran variabel","Tetapkan target tabungan","Sesuaikan pengeluaran untuk memenuhi tujuan"],"options":["Hitung pendapatan bulanan","Buat daftar pengeluaran tetap","Buat daftar pengeluaran variabel","Tetapkan target tabungan","Sesuaikan pengeluaran untuk memenuhi tujuan"],"question":"Urutan langkah-langkah membuat anggaran bulanan:","difficulty":"advanced","parameters":{},"explanation":"Urutan yang benar adalah: Hitung pendapatan bulanan → Cantumkan pengeluaran tetap → Cantumkan pengeluaran variabel → Tetapkan target tabungan → Sesuaikan pengeluaran untuk mencapai tujuan"}$json$::jsonb where id = 'd8a9c0a0-a4a1-48f4-946a-875847c1f7e8';
update public.content_variants set body = $json${"text":"Diversification reduces risk without having to predict which assets will perform best. That's why diversification is often called the 'free lunch' in investing."}$json$::jsonb where id = 'd91dc4a5-02e7-4ec5-9e78-6873f2e98cc9';
update public.content_variants set body_id = $json${"type":"image_interpretation","answer":"Periksa izin OJK","options":["Baca prospektusnya","Periksa izin OJK","Hitung potensi keuntungan","Minta pendapat teman"],"question":"[GAMBAR: Diagram alur: Mulai → Periksa izin OJK → Jika ya: lanjutkan ke penelitian → Jika tidak: berhenti dan lapor. Cabang menunjukkan jalur aman vs tidak aman.]\n\nApa pos pemeriksaan PERTAMA dalam diagram alur keamanan finansial ini?","difficulty":"beginner","parameters":{"image_description":"A flowchart: Start → Check OJK license → If yes: proceed to research → If no: stop and report. Branches show safe vs unsafe paths."},"explanation":"Diagram alur tersebut secara eksplisit menunjukkan verifikasi izin OJK sebagai titik keputusan pertama sebelum tindakan lebih lanjut."}$json$::jsonb where id = 'd9d16a3e-e111-4513-a5e7-d5687a0c4cef';
update public.content_variants set body_id = $json${"type":"comparison","answer":"ETF Pasar","options":["Stok tunggal","ETF Pasar","Keduanya mempunyai risiko yang sama","Risiko tidak dapat diukur"],"question":"Bandingkan risikonya: membeli satu saham vs ETF yang melacak seluruh pasar. Manakah yang memiliki risiko tidak sistematis yang lebih rendah?","difficulty":"beginner","parameters":{},"explanation":"ETF memiliki banyak saham, menghilangkan risiko spesifik perusahaan (tidak sistematis) yang dimiliki oleh satu saham."}$json$::jsonb where id = 'da1b4073-b5a3-4055-82e4-e67f75ca5743';
update public.content_variants set body_id = $json${"type":"case_study","answer":"Tika, karena dia menabung dan berinvestasi","caseText":"Rudi mendapat penghasilan Rp 10 juta per bulan. Dia menyewa mobil baru, makan di luar setiap hari, dan tidak punya tabungan. Tika mendapat penghasilan Rp 5 juta per bulan. Ia hidup sederhana, menabung Rp 1 juta setiap bulan, dan menginvestasikannya.","followUp":{"answer":"Tika, karena dia menabung dan berinvestasi","options":["Rudi, karena penghasilannya lebih banyak","Tika, karena dia menabung dan berinvestasi","Mereka akan mendapatkan hal yang sama","Itu tergantung pada pekerjaan mereka"],"question":"Setelah lima tahun, siapa yang mungkin memiliki kekayaan lebih banyak?","difficulty":"beginner","parameters":{},"explanation":"Kekayaan berasal dari apa yang Anda pelihara dan kembangkan, bukan hanya dari apa yang Anda hasilkan."},"difficulty":"beginner","parameters":{},"explanation":"Kekayaan berasal dari apa yang Anda pelihara dan kembangkan, bukan hanya dari apa yang Anda hasilkan."}$json$::jsonb where id = 'da6c83e2-f344-4a0d-a07a-3ec29b12cb93';

