-- KO-225 group 5: reviewed translation of Indonesian-shaped duplicate payloads (batch 01).
update public.content_variants set body = $json${"text":"Money is a medium of exchange that many people agree upon. Without money, we would have to barter—exchange goods directly—which is difficult because the needs of both parties may not match."}$json$::jsonb where id = '0523f63e-c588-4d15-ba71-3697aeee434d';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because money can be exchanged for anything that is sold","options":["Because money can be exchanged for anything that is sold","Because money is made of precious metals","Because bartering is faster","Because money cannot be lost"],"question":"Why is money more practical than bartering?","difficulty":"beginner","explanation":"Money is universally accepted, so we don't need to find someone who happens to need our goods."}$json$::jsonb where id = '0a4c0ef1-8387-487f-a33d-4536d2064060';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"High returns with guaranteed safety","options":["Low and stable interest","High returns with guaranteed safety","Registered with OJK","Has a clear physical office"],"question":"What is the most common characteristic of a fraudulent investment?","difficulty":"beginner","parameters":{},"explanation":"High returns with guaranteed safety is a hallmark of fraudulent investments."}$json$::jsonb where id = '11626cdd-14d6-4df2-bde0-798b1cc3081b';
update public.content_variants set body = $json${"text":"Bayu wants to buy chicken noodles at a food stall, but the seller doesn't want to exchange them for a pen. Bayu uses Rp15,000, and the seller accepts it immediately. Money facilitates exchange because everyone agrees that money has value."}$json$::jsonb where id = '11d54e82-64bf-47d2-923a-313f2ad5b9a0';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Recording income and expenses","options":["Shopping every day without keeping track","Recording income and expenses","Taking online loans for lifestyle","Transferring money to a number sent via WA"],"question":"Which habit best supports financial health?","difficulty":"beginner","parameters":{},"explanation":"Keeping track of finances helps us understand and control the flow of money."}$json$::jsonb where id = '16cad133-49ba-4efe-8eba-bbdd64ef8a56';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Fear of losing Rp 100,000 is stronger than the joy of gaining Rp 100,000","options":["Joy of gaining Rp 100,000","Fear of losing Rp 100,000 is stronger than the joy of gaining Rp 100,000","Diversifying the portfolio","Saving in a deposit account"],"question":"Which is an example of loss aversion?","difficulty":"intermediate","parameters":{},"explanation":"Loss aversion means the pain of losing is stronger than the joy of gaining the same amount."}$json$::jsonb where id = '1b4e86dc-e201-4666-bcda-76798df2c369';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Phone credit and internet data for online classes","options":["Concert tickets","Phone credit and internet data for online classes","Latest game skins","Coffee at a cafe"],"question":"Which is considered a necessity for Indonesian students?","difficulty":"beginner","parameters":{},"explanation":"Phone credit and internet data support learning activities, so they are considered necessities."}$json$::jsonb where id = '1e8cd781-0892-490d-9bb2-86dc2b4a1d14';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Phone credit and internet data for online classes","options":["K-pop concert tickets","Phone credit and internet data for online classes","Latest game skins","Coffee at a hipster cafe"],"question":"Which is most considered a necessity for Indonesian students?","difficulty":"beginner","parameters":{},"explanation":"Phone credit and internet data support learning activities, so they are considered necessities."}$json$::jsonb where id = '25846500-0b82-4af4-9258-4b895f0e87d7';
update public.content_variants set body = $json${"text":"Siti opened a savings account with no admin fees at a state-owned bank. Every week she sets aside Rp 50,000 from her allowance. A year later, her savings reached Rp 2,600,000 without her realizing it.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = '2b232f24-729c-495c-9b6c-dfcabf87a153';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Distinguishing needs from wants","options":["Buying as many assets as possible","Distinguishing needs from wants","Seeking online loans","Joining a friend's investment"],"question":"What is the first step in managing money wisely?","difficulty":"beginner","parameters":{},"explanation":"Distinguishing needs from wants is the basic foundation of money management."}$json$::jsonb where id = '3134c519-24c7-4e38-822c-be9ac7030e78';
