-- KO-225 group 4 lesson translation batch 3

update public.lessons set summary_id = $text$Cryptocurrency adalah aset digital yang berjalan di jaringan komputer bersama yang disebut blockchain. Bitcoin dan Ethereum adalah yang paling terkenal, namun tidak ada satupun yang merupakan uang resmi di Indonesia.$text$, concept_body_id = $text$Cryptocurrency adalah uang digital yang hanya ada sebagai catatan di jaringan yang disebut blockchain. Blockchain adalah buku besar umum yang dibagikan ke ribuan komputer di seluruh dunia. Karena banyak komputer menyimpan salinannya, sangat sulit bagi satu orang untuk mengubah catatannya sendirian. Bitcoin, dibuat pada tahun 2009, adalah mata uang kripto pertama. Orang sering membandingkannya dengan “emas digital” karena persediaannya terbatas dan harganya ditentukan oleh permintaan. Ethereum, diluncurkan pada tahun 2015, menambahkan kontrak pintar – program kecil yang berjalan secara otomatis ketika kondisi terpenuhi – yang menjadikannya platform untuk banyak proyek kripto lainnya.

Di Indonesia, mata uang kripto diperlakukan sebagai komoditas, atau *aset kripto*, berdasarkan peraturan Bappebti. Ini bukan mata uang resmi seperti rupiah, sehingga tidak bisa digunakan untuk membayar pajak, membeli kopi, atau melunasi hutang. Harganya ditentukan oleh penawaran dan permintaan di bursa, yang berarti harga bisa naik atau turun tajam dalam beberapa jam. Bagi generasi muda Indonesia, kripto mungkin menarik untuk dipelajari, namun memilikinya berarti memiliki aset digital yang berisiko, bukan jaminan cara untuk membangun kekayaan.$text$, why_this_matters_id = $text$Crypto muncul terus-menerus di grup TikTok, Telegram, dan WhatsApp. Mengetahui dasar-dasarnya membantu Anda membedakan antara diskusi teknologi nyata dan promosi penjualan.$text$, common_mistake_id = $text$Menganggap kripto adalah “uang gratis” atau jalan pintas yang dijamin untuk menjadi kaya dengan cepat.$text$ where id = '7a00458a-6815-4b91-91bc-02a102fbff3f';
update public.lessons set summary_id = $text$Paket PayLater dan beli sekarang bayar nanti membuat pengeluaran terasa bebas, namun biaya keterlambatan, bunga, dan pembelian impulsif dapat mengubah pembelian kecil menjadi hutang yang membuat stres.$text$, concept_body_id = $text$Beli sekarang bayar nanti (BNPL), sering disebut PayLater di aplikasi Indonesia, memungkinkan Anda membagi pembelian menjadi beberapa cicilan kecil. Ini terasa terjangkau, namun menyembunyikan seluruh biaya dan mendorong pembelian barang-barang yang tidak Anda perlukan. Jika Anda melewatkan tanggal jatuh tempo, biaya keterlambatan dan bunga dapat membuat barang tersebut jauh lebih mahal dari harga aslinya. Banyak pengguna yang mendapatkan beberapa tagihan PayLater sekaligus dan kesulitan melacak semuanya.

Meski penyedia PayLater berlisensi wajib mengikuti aturan OJK, namun produknya sendiri dirancang untuk memudahkan pembelanjaan. Bahayanya bukan pada aplikasinya; itu adalah kebiasaan menghabiskan uang yang belum Anda peroleh. Pendekatan paling aman adalah menggunakan PayLater hanya untuk kebutuhan terencana yang sesuai dengan anggaran Anda, bukan untuk keinginan yang dipicu oleh flash sale atau postingan influencer. Jika Anda tidak dapat membayar seluruh harga hari ini, menabung terlebih dahulu biasanya lebih murah dan mengurangi stres.$text$, why_this_matters_id = $text$PayLater melatih Anda untuk membelanjakan uang yang tidak Anda miliki. Satu pembayaran yang terlewat dapat memicu siklus biaya dan stres.$text$, common_mistake_id = $text$Menggunakan PayLater untuk keinginan karena "hanya Rp 50.000 per bulan" tanpa membaca ketentuan biaya keterlambatan dan bunga.$text$ where id = 'e124806b-ba2c-46ef-ab65-20beff16fff6';

