-- KO-225 group 5 continuation batch 18

update public.content_variants set body_id = $json${"type":"comparison","answer":"Mulailah berinvestasi sejak dini","options":["Lunasi pinjaman terlebih dahulu hingga tuntas","Mulailah berinvestasi sejak dini","Jangan melakukan keduanya, habiskan untuk pengalaman","Bagi secara merata"],"question":"Untuk usia 25 tahun dengan pendapatan stabil: apakah lebih baik memprioritaskan pembayaran pinjaman mahasiswa berbunga rendah atau mulai berinvestasi lebih awal?","difficulty":"intermediate","parameters":{},"explanation":"Pada usia muda, kekuatan bunga majemuk memudahkan memulai investasi sejak dini, sementara pinjaman berbunga rendah dapat dikelola secara bersamaan."}$json$::jsonb where id = 'bdb4df3d-9578-49dd-ad73-606d7aa55d5f';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Keuntungan atau kerugian uang Anda","options":["Jumlah yang Anda investasikan","Keuntungan atau kerugian uang Anda","Jenis rekening bank","Pengembalian pajak pemerintah"],"question":"Apa keuntungan di bidang keuangan?","difficulty":"beginner","parameters":{},"explanation":"Pengembalian mengukur berapa banyak uang yang Anda hasilkan atau hilangkan dibandingkan dengan jumlah yang Anda masukkan."}$json$::jsonb where id = 'bddcfcce-0cfb-4875-afc9-14cd0314b858';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"diversifikasi","question":"________ adalah praktik menyebarkan investasi ke berbagai aset untuk mengurangi risiko.","difficulty":"beginner","parameters":{},"explanation":"Diversifikasi memastikan bahwa kinerja buruk dalam satu investasi tidak menghancurkan keseluruhan portofolio."}$json$::jsonb where id = 'be4aeda6-952c-4c2b-970e-ab5e8bef3075';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"kebutuhan vs keinginan","question":"Konsep ________ membantu individu membedakan antara pengeluaran penting dan tidak penting.","difficulty":"beginner","parameters":{},"explanation":"Memahami kebutuhan versus keinginan merupakan hal mendasar dalam penganggaran dan tabungan."}$json$::jsonb where id = 'bee5e997-c65d-4484-8d31-3cd6ad7b57d6';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"keengganan terhadap kerugian","question":"Kecenderungan untuk merasakan kerugian yang lebih besar dibandingkan keuntungan yang setara disebut ________.","difficulty":"advanced","parameters":{},"explanation":"Keengganan terhadap kerugian adalah konsep kunci dalam keuangan perilaku di mana kerugian merugikan dua kali lipat dibandingkan keuntungan yang dirasakan baik."}$json$::jsonb where id = 'bf367494-bd4e-4851-b22d-0b242ba5c358';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"memulai sejak dini dan tetap konsisten","options":["memilih saham terbaik","memulai sejak dini dan tetap konsisten","mengatur waktu pasar dengan sempurna","memiliki informasi orang dalam"],"question":"Faktor terpenting dalam membangun kekayaan melalui investasi adalah ________.","difficulty":"advanced","parameters":{},"explanation":"Waktu di pasar dan kontribusi yang konsisten jauh lebih penting daripada pemilihan saham atau penentuan waktu pasar."}$json$::jsonb where id = 'c0671012-4b93-46a6-8915-11bb76253a97';
update public.content_variants set body = $json${"text":"Andi promoter's salary is IDR 8 million/month, but this is spent on motorbike installments, hanging out and online shopping. His savings are zero. Budi Barista's salary is IDR 4 million/month, sets aside IDR 500 thousand per month, and already has savings of IDR 15 million. Budi is richer because wealth is a stock owned, not an inflow."}$json$::jsonb where id = 'c1b1ba06-0414-4c9b-b0f5-751beed805d0';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"menukarkan","question":"Uang yang diterima setiap orang sebagai pembayaran atas barang dan jasa disebut media ____.","difficulty":"beginner","parameters":{},"explanation":"Alat tukar adalah sesuatu yang diterima secara luas sebagai imbalan atas barang dan jasa."}$json$::jsonb where id = 'c23848aa-a0bb-49e3-b7cd-0755d66170fd';
update public.content_variants set body = $json${"text":"Never click on links, enter passwords, or provide the OTP of unsolicited messages. Contact the official service via the official number/website."}$json$::jsonb where id = 'c27a330f-5225-4d40-a685-b9262f1ec76c';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"lebih rendah","options":["lebih tinggi","lebih rendah","setara","tidak dapat diprediksi"],"question":"Portofolio yang terdiversifikasi biasanya memiliki risiko ________ dibandingkan portofolio terkonsentrasi dengan ekspektasi pengembalian yang sama.","difficulty":"intermediate","parameters":{},"explanation":"Diversifikasi mengurangi risiko yang tidak sistematis (khusus perusahaan) tanpa mengorbankan keuntungan yang diharapkan."}$json$::jsonb where id = 'c2c3ed88-4472-4205-9c07-8ad1d105b38c';

