-- KO-225 group 5 exact duplicate translation batch 8

update public.content_variants set body = $json${"text":"How to check: visit the OJK website, open the 'Investment Alert' section or list of licensed companies, then search for the name of the application/company. If there isn't, don't invest."}$json$::jsonb where id = '5f123bce-bd86-4d49-bcd3-414129a2f377';
update public.content_variants set body = $json${"text":"During the New Order era, Indonesia experienced hyperinflation. Prices of goods can change within a matter of days. This experience is a lesson in why price stability is important for the economy.","source_ids":["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}$json$::jsonb where id = '5fa2cbda-7ebb-4e15-be62-6c5f189bb481';
update public.content_variants set body = $json${"text":"The Indonesian Stock Exchange (IDX) is Indonesia's national stock market. Listed companies can sell shares to the public, so investors become owners of a small portion of the company. On IDX, 1 lot is equal to 100 shares. Stock prices move according to supply and demand. SIPF provides protection to investors in listed securities.","ai_assist_context":"Introduce IDX, share lots and investor protection using IDX and OJK sources. Encourage users to do research before transacting."}$json$::jsonb where id = '6601f54d-f37c-4407-b420-bde5e5b0128c';
update public.content_variants set body = $json${"text":"Government bonds are generally safer than shares of small companies. Therefore, government bond yields are usually lower than potential stocks."}$json$::jsonb where id = '6639883b-5c97-471f-bb07-0a3161135fe3';
update public.content_variants set body = $json${"text":"Distinguishing needs and wants helps us create a budget. Simple rule: pay for needs first, then allocate the rest for wants and savings."}$json$::jsonb where id = '676b28c2-2fca-438a-8461-a984c8850867';
update public.content_variants set body = $json${"text":"Buying shares is different from lending money. Shares = ownership. Bonds = loans."}$json$::jsonb where id = '6806e5a2-1113-40b2-a9ad-902b5c3fa470';
update public.content_variants set body = $json${"text":"Income is money that comes in periodically, such as a salary or pocket money. Wealth is the total assets we own minus debt, or net stock of ownership."}$json$::jsonb where id = '693a366a-7503-41bb-863b-8585dc5e90ea';
update public.content_variants set body = $json${"text":"Doni wants to buy new headphones for IDR 800,000, even though his old headphones are still working. On the other hand, he only had IDR 1 million and he had not paid the IDR 700,000 boarding fee. Headphones are a want, cost is a need."}$json$::jsonb where id = '6bc6ffbd-3cd2-4996-9ffa-a6da56e5cc57';
update public.content_variants set body = $json${"text":"In 2020, a portion of nasi Padang in Jakarta is priced at IDR 25,000. In 2025, the same price will be IDR 32,000. This price increase indicates inflation: the purchasing power of the rupiah decreases over time.","source_ids":["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}$json$::jsonb where id = '6bccef67-4bae-4330-a414-e86e411a32f7';
update public.content_variants set body = $json${"text":"Someone who puts all their money in a deposit at 4% per year has low risk, but their purchasing power can be eroded by 5% inflation. The real return is negative 1%.","source_ids":["097b62c4-9aae-4933-a870-ac74a526b8f1","47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = '6d00adde-de7d-4c40-9254-d8e90310fed6';

