-- Migration 016: Expand content_variants pool
-- Adds 10+ examples and 10+ questions per launch lesson for per-session variety.

-- Lesson IDs
-- money-basics-101: 0fa42c9f-66b9-42c1-b622-9f194a505a06
-- budgeting-101:   fb9f7f07-c324-4054-8fb7-e38bec2f847c
-- inflation-101:   ef1869f8-82e4-4ced-9b9e-e79fcb799b72
-- risk-return-101: e81a8f71-77ab-44ca-b48f-a0e985313e33
-- idx-basics-101:  b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311

INSERT INTO content_variants (lesson_id, variant_type, body, difficulty, is_active) VALUES

-- ============================================================
-- MONEY BASICS 101 — Examples
-- ============================================================
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Rina, mahasiswa semester 2 di Bandung, menerima uang saku Rp 2.000.000 per bulan. Ia mencatat: kos Rp 800.000, makan Rp 700.000, pulsa/kuota Rp 150.000, dan tabungan Rp 200.000. Sisanya Rp 150.000 untuk hiburan. Dengan mencatat, Rina tahu uangnya habis untuk hal penting, bukan spontan.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953", "7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Andi melihat promo di Instagram: \"Investasi Rp 500.000 dapat Rp 5 juta dalam sebulan, dijamin aman.\" Andi curiga, lalu cek perusahaan tersebut di situs OJK. Ternyata tidak terdaftar. Andi memutuskan tidak transfer dan melapor ke OJK.", "source_ids": ["9ddb5412-52b8-4461-b2e5-a5443ac63ca8", "337c397d-743e-4d1b-8344-09e47b95be90"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Maya membedakan kebutuhan dan keinginan sebelum belanja online. Kebutuhan: skincare habis, sabun cuci piring, dan vitamin. Keinginan: sepatu baru diskon 50%. Maya membeli kebutuhan dulu, menunda keinginan sampai tabungannya cukup.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Budi kerja magang dengan gaji Rp 1.200.000 per bulan. Setiap gajian, ia langsung pindahkan Rp 200.000 ke rekening tabungan terpisah. Setelah 6 bulan, Budi punya dana darurat Rp 1.200.000 untuk biaya kesehatan atau keperluan mendesak.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04", "53eef1ac-2553-48d9-92a0-af6159d7d369"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Seorang pedagang di pasar tradisional ditawari skema \"uang kembali 2 kali lipat dalam seminggu\" oleh kenalan. Ia ingat pesan OJK: imbal hasil tinggi tanpa risiko itu tidak wajar. Ia menolak dan mengingatkan tetangganya.", "source_ids": ["9ddb5412-52b8-4461-b2e5-a5443ac63ca8"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Siti membuka rekening tabungan tanpa biaya admin di bank BUMN. Setiap minggu ia menyisihkan Rp 50.000 dari uang jajannya. Setahun kemudian, tabungannya Rp 2.600.000 tanpa ia sadari.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Doni hampir transfer Rp 1 juta ke nomor rekening yang dikirim via WhatsApp oleh \"customer service\" bank. Ia berhenti dan langsung hubungi call center bank resmi. Ternyata itu modus penipuan.", "source_ids": ["9ddb5412-52b8-4461-b2e5-a5443ac63ca8", "337c397d-743e-4d1b-8344-09e47b95be90"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Kelompok mahasiswa di Yogyakarta membuat catatan keuangan bersama untuk acara kampus. Mereka memisahkan anggaran makan, transport, perlengkapan, dan cadangan 10%. Sisa uang dikembalikan transparan ke setiap anggota.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Lia membandingkan harga mie instan di e-commerce dan warung dekat kos. Meski online sedikit lebih murah, ongkir membuatnya lebih mahal. Lia membeli di warung agar hemat dan mendukung usaha lokal.", "source_ids": ["53eef1ac-2553-48d9-92a0-af6159d7d369"]}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'example', '{"text": "Pak Harto, pensiunan, tidak pernah memberikan PIN ATM kepada siapa pun, termasuk yang mengaku petugas bank. Ia tahu bank resmi tidak akan meminta PIN. Uang pensiunnya tetap aman.", "source_ids": ["9ddb5412-52b8-4461-b2e5-a5443ac63ca8"]}', 'beginner', true),

-- ============================================================
-- MONEY BASICS 101 — Questions
-- ============================================================
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "multiple_choice", "question": "Manakah yang paling termasuk kebutuhan untuk pelajar Indonesia?", "options": ["Tiket konser K-pop", "Pulsa dan kuota internet untuk kelas online", "Skin game terbaru", "Kopi di kafe hipster"], "answer": "Pulsa dan kuota internet untuk kelas online", "explanation": "Pulsa dan kuota internet mendukung kegiatan belajar, sehingga termasuk kebutuhan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "true_false", "question": "Investasi yang menjanjikan imbal hasil tinggi dan dijamin aman tanpa risiko biasanya dapat dipercaya.", "answer": false, "explanation": "Penawaran dengan imbal hasil tinggi dan jaminan tanpa risiko adalah ciri umum investasi ilegal. Selalu periksa izin OJK.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "multiple_choice", "question": "Langkah pertama mengelola uang dengan bijak adalah?", "options": ["Membeli aset sebanyak-banyaknya", "Membedakan kebutuhan dan keinginan", "Mencari pinjaman online", "Ikut investasi teman"], "answer": "Membedakan kebutuhan dan keinginan", "explanation": "Membedakan kebutuhan dan keinginan adalah fondasi dasar pengelolaan uang.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "fill_blank", "question": "Sebelum berinvestasi, selalu periksa izin produk keuangan di situs ____.", "answer": "OJK", "explanation": "Otoritas Jasa Keuangan (OJK) mengawasi produk keuangan di Indonesia.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "multiple_choice", "question": "Dana darurat penting untuk?", "options": ["Beli gadget baru", "Biaya kesehatan atau keperluan mendesak", "Liburan ke Bali", "Semua jawaban benar"], "answer": "Biaya kesehatan atau keperluan mendesak", "explanation": "Dana darurat digunakan untuk kebutuhan tak terduga, bukan keinginan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "word_bank", "question": "Susunlah urutan langkah sehat mengelola uang: ____", "options": ["Catat pemasukan", "Pisahkan kebutuhan & keinginan", "Sisihkan tabungan", "Evaluasi pengeluaran"], "answer": ["Catat pemasukan", "Pisahkan kebutuhan & keinginan", "Sisihkan tabungan", "Evaluasi pengeluaran"], "explanation": "Catat, pisahkan, tabung, lalu evaluasi adalah siklus pengelolaan uang yang sehat.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "true_false", "question": "Bank resmi akan meminta PIN ATM melalui WhatsApp untuk keamanan rekening.", "answer": false, "explanation": "Bank resmi tidak pernah meminta PIN, password, atau kode OTP kepada nasabah.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "multiple_choice", "question": "Ciri investasi bodong yang paling umum adalah?", "options": ["Bunga rendah dan stabil", "Imbal hasil tinggi dengan jaminan aman", "Terdaftar di OJK", "Memiliki kantor fisik jelas"], "answer": "Imbal hasil tinggi dengan jaminan aman", "explanation": "Imbal hasil tinggi dengan jaminan aman adalah ciri khas investasi bodong.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "ordering", "question": "Urutkan prioritas penggunaan uang saku dari yang paling penting:", "options": ["Tabungan darurat", "Makan dan transport", "Tiket konser", "Bayar UKT"], "answer": ["Bayar UKT", "Makan dan transport", "Tabungan darurat", "Tiket konser"], "explanation": "Prioritas utama adalah kebutuhan pendidikan, makan/transport, tabungan, baru keinginan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "multiple_choice", "question": "Kebiasaan mana yang paling mendukung kesehatan keuangan?", "options": ["Belanja setiap hari tanpa catatan", "Mencatat pemasukan dan pengeluaran", "Ikut pinjaman online untuk gaya hidup", "Transfer uang ke nomor yang dikirim via WA"], "answer": "Mencatat pemasukan dan pengeluaran", "explanation": "Mencatat keuangan membantu kita memahami dan mengontrol aliran uang.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('0fa42c9f-66b9-42c1-b622-9f194a505a06', 'question', '{"type": "multiple_choice", "question": "Apa yang sebaiknya dilakukan jika ada penawaran investasi mencurigakan?", "options": ["Langsung transfer segera", "Cek izin di OJK dan diskusikan dengan orang dewasa", "Ajak semua teman ikut", "Pinjam uang untuk ikut"], "answer": "Cek izin di OJK dan diskusikan dengan orang dewasa", "explanation": "Verifikasi izin OJK dan konsultasi membantu menghindari investasi bodong.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),

-- ============================================================
-- BUDGETING 101 — Examples
-- ============================================================
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Alya menerima uang saku Rp 2.500.000 per bulan. Ia menerapkan 50/30/20: Rp 1.250.000 untuk kebutuhan (kos, makan, transport), Rp 750.000 untuk keinginan (nonton, jajan), dan Rp 500.000 untuk tabungan.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04", "ad0e8258-4e0a-4378-b257-4fd3628c6953"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Fajar, karyawan baru di Jakarta, menggunakan aplikasi catatan keuangan untuk melacak pengeluaran harian. Ia menyadari 30% uangnya habis untuk delivery makanan. Ia mulai membawa bekal dan mengurangi pesan antar.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Keluarga Pak Budi di Surabaya membuat anggaran bulanan dengan menyisihkan dulu Rp 1 juta untuk tabungan pendidikan anak, baru kemudian mengatur pengeluaran lainnya. Prinsip \"bayar diri sendiri dulu\" membantu mereka konsisten menabung.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Nina ingin membeli laptop Rp 8 juta. Gajinya Rp 4 juta per bulan. Ia membuat target menabung Rp 1 juta per bulan selama 8 bulan, bukan memakai paylater dengan bunga tinggi.", "source_ids": ["53eef1ac-2553-48d9-92a0-af6159d7d369"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Sebuah UKM di Bandung memisahkan rekening operasional dan rekening pribadi pemilik. Pemilik mengambil gaji tetap Rp 3 juta per bulan, sehingga keuangan bisnis tidak tercampur dengan pengeluaran pribadi.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}', 'intermediate', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Raka mengevaluasi langganannya setiap 3 bulan: streaming, musik, cloud, gym. Ia membatalkan dua langganan yang jarang digunakan dan menghemat Rp 150.000 per bulan.", "source_ids": ["53eef1ac-2553-48d9-92a0-af6159d7d369"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Ibu Siti membuat daftar belanja mingguan sebelum ke pasar. Dengan daftar, ia tidak tergoda membeli barang di luar kebutuhan dan menghemat Rp 100.000 per minggu.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Dewa, freelancer desain, memiliki pendapatan tidak tetap. Bulan ramai ia tabung 30% penghasilan, bulan sepi ia pakai tabungan tersebut tanpan mengutang.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}', 'intermediate', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Seorang mahasiswa di Malang menggunakan metode amplop: setiap awal bulan ia membagi uang saku ke beberapa kategori dalam dompet terpisah. Ketika amplop hiburan habis, ia berhenti berfoya-foya.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'example', '{"text": "Keluarga muda di Tangerang menyisihkan 10% gaji untuk dana darurat sebelum membayar tagihan. Setelah 1 tahun, mereka punya cadangan 3 bulan pengeluaran.", "source_ids": ["ad0e8258-4e0a-4378-b257-4fd3628c6953", "53eef1ac-2553-48d9-92a0-af6159d7d369"]}', 'beginner', true),

-- ============================================================
-- BUDGETING 101 — Questions
-- ============================================================
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "multiple_choice", "question": "Menurut aturan 50/30/20, berapa persen uang yang idealnya untuk kebutuhan?", "options": ["20%", "30%", "50%", "80%"], "answer": "50%", "explanation": "Aturan 50/30/20: 50% kebutuhan, 30% keinginan, 20% tabungan atau utang.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "true_false", "question": "Keinginan adalah pengeluaran yang harus dipenuhi untuk hidup sehari-hari.", "answer": false, "explanation": "Keinginan adalah hal yang menyenangkan tetapi bisa ditunda, berbeda dengan kebutuhan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "fill_blank", "question": "Prinsip \"bayar ____ dulu\" berarti menyisihkan tabungan sebelum berbelanja.", "answer": "diri sendiri", "explanation": "Bayar diri sendiri dulu artinya prioritaskan tabungan sebelum pengeluaran lain.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "multiple_choice", "question": "Jika gaji Rina Rp 5.000.000, berapa idealnya untuk tabungan dengan aturan 50/30/20?", "options": ["Rp 500.000", "Rp 1.000.000", "Rp 1.500.000", "Rp 2.500.000"], "answer": "Rp 1.000.000", "explanation": "20% dari Rp 5.000.000 adalah Rp 1.000.000.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "ordering", "question": "Urutkan langkah membuat anggaran sederhana:", "options": ["Tetapkan tujuan tabungan", "Catat pemasukan", "Evaluasi akhir bulan", "Bagi pengeluaran ke kategori"], "answer": ["Catat pemasukan", "Bagi pengeluaran ke kategori", "Tetapkan tujuan tabungan", "Evaluasi akhir bulan"], "explanation": "Catat pemasukan, bagi pengeluaran, tetapkan tujuan tabungan, lalu evaluasi.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "true_false", "question": "Pendapatan tidak tetap membuat anggaran tidak perlu dibuat.", "answer": false, "explanation": "Pendapatan tidak tetap justru membutuhkan anggaran lebih fleksibel dan dana darurat.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "multiple_choice", "question": "Manakah yang termasuk kebutuhan, bukan keinginan?", "options": ["Nonton bioskop setiap minggu", "Bayar kos bulanan", "Beli sneakers baru", "Langganan kopi premium"], "answer": "Bayar kos bulanan", "explanation": "Kos adalah kebutuhan tempat tinggal, sedangkan yang lain bisa ditunda.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "word_bank", "question": "Kategori anggaran 50/30/20 terdiri dari: ____", "options": ["Kebutuhan", "Keinginan", "Tabungan", "Hutang konsumtif"], "answer": ["Kebutuhan", "Keinginan", "Tabungan"], "explanation": "50/30/20 adalah kebutuhan, keinginan, dan tabungan/utang.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "multiple_choice", "question": "Tujuan evaluasi anggaran setiap bulan adalah?", "options": ["Menghabiskan sisa uang", "Melihat kebocoran pengeluaran dan memperbaiki kebiasaan", "Membandingkan gaji dengan teman", "Mencari pinjaman baru"], "answer": "Melihat kebocoran pengeluaran dan memperbaiki kebiasaan", "explanation": "Evaluasi membantu kita melihat di mana uang bocor dan memperbaikinya.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "multiple_choice", "question": "Kebiasaan mana yang paling mendukung anggaran sehat?", "options": ["Belanja impulsif setiap gajian", "Membawa bekal dan membatasi pesan antar", "Menggunakan paylater untuk semua keinginan", "Tidak mencatat pengeluaran"], "answer": "Membawa bekal dan membatasi pesan antar", "explanation": "Membatasi pengeluaran tidak perlu dan membawa bekal membantu anggaran tetap sehat.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('fb9f7f07-c324-4054-8fb7-e38bec2f847c', 'question', '{"type": "true_false", "question": "Dana darurat sebaiknya disisihkan setelah semua keinginan terpenuhi.", "answer": false, "explanation": "Dana darurat sebaiknya disisihkan di awal, sebelum keinginan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),

-- ============================================================
-- INFLATION 101 — Examples
-- ============================================================
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Tahun 2020, harga seporsi nasi padang di kantin kampus Rp 15.000. Tiga tahun kemudian, harganya menjadi Rp 20.000. Uang yang sama kini membeli porsi lebih kecil. Itulah inflasi menggerus daya beli.", "source_ids": ["e49fe239-c534-4bed-b0bd-a7950b9e35c4", "8da2696d-9836-4a3b-9524-da7e2b823c60"]}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Bank Indonesia menetapkan target inflasi 2,5% ± 1% pada 2025. Jika inflasi terlalu tinggi, harga barang naik cepat dan orang sulit merencanakan pengeluaran. Jika terlalu rendah, ekonomi bisa melambat.", "source_ids": ["097b62c4-9aae-4933-a870-ac74a526b8f1"]}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Pak Tono menyimpan uang Rp 10 juta di bantal selama 10 tahun. Jika inflasi rata-rata 4% per tahun, daya beli uang itu menurun. Barang yang dulu Rp 10 juta, kini mungkin butuh Rp 14,8 juta.", "source_ids": ["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Susi memiliki tabungan di bank dengan bunga 3% per tahun, sedangkan inflasi 5%. Daya beli tabungannya turun 2% per tahun meski nominalnya bertambah. Ini disebut real return negatif.", "source_ids": ["097b62c4-9aae-4933-a870-ac74a526b8f1"]}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Ketika harga beras naik, pedagang nasi goreng di pinggir jalan menaikkan harga jual dari Rp 12.000 menjadi Rp 15.000. Inflasi bahan baku merambat ke harga jual ke konsumen.", "source_ids": ["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Di zaman Orde Baru, Indonesia pernah mengalami hiperinflasi. Harga barang bisa berubah dalam hitung hari. Pengalaman itu menjadi pelajaran kenapa stabilitas harga penting bagi ekonomi.", "source_ids": ["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}', 'advanced', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Aplikasi belanja online sering memberikan diskon besar. Namun jika diskon membuat kita membeli barang yang tidak dibutuhkan, kita tetap kehilangan daya beli karena uang habis untuk hal tidak penting.", "source_ids": ["53eef1ac-2553-48d9-92a0-af6159d7d369"]}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Nilai tukar rupiah terhadap dolar Amerika mempengaruhi harga barang impor seperti minyak dan obat-obatan. Jika rupiah melemah, harga barang-barang itu naik dan memicu inflasi.", "source_ids": ["8da2696d-9836-4a3b-9524-da7e2b823c60"]}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Seorang pensiunan yang bergantung pada tabungan tunai akan merasa hidupnya semakin mahal setiap tahun. Tabungan yang tidak bertumbuh lebih cepat dari inflasi akan kehabisan daya beli.", "source_ids": ["097b62c4-9aae-4933-a870-ac74a526b8f1"]}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'example', '{"text": "Mahasiswa yang menyewa kos di dekat kampus mengalami kenaikan harga kos 10% per tahun. Uang saku yang tetap membuatnya harus mencari kos lebih jauh atau mengurangi pengeluaran lain.", "source_ids": ["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}', 'beginner', true),

-- ============================================================
-- INFLATION 101 — Questions
-- ============================================================
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "multiple_choice", "question": "Apa yang dimaksud dengan inflasi?", "options": ["Kenaikan jumlah uang beredar", "Penurunan daya beli uang terhadap barang dan jasa", "Peningkatan nilai tukar rupiah", "Penurunan harga barang secara umum"], "answer": "Penurunan daya beli uang terhadap barang dan jasa", "explanation": "Inflasi adalah kenaikan harga barang dan jasa secara umum yang mengurangi daya beli uang.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "true_false", "question": "Jika inflasi 5% per tahun, tabungan dengan bunga 3% per tahun masih meningkat daya belinya.", "answer": false, "explanation": "Daya beli menurun karena inflasi (5%) lebih tinggi dari bunga tabungan (3%).", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "multiple_choice", "question": "Institusi yang bertugas menjaga stabilitas harga di Indonesia adalah?", "options": ["OJK", "BI", "IDX", "Kemenkeu"], "answer": "BI", "explanation": "Bank Indonesia (BI) bertugas menjaga stabilitas nilai tukar rupiah dan mengendalikan inflasi.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "fill_blank", "question": "Target inflasi Bank Indonesia adalah sekitar ____% ± 1%.", "answer": "2,5", "explanation": "Bank Indonesia menetapkan target inflasi sekitar 2,5% ± 1%.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "multiple_choice", "question": "Mengapa rupiah melemah bisa memicu inflasi?", "options": ["Karena bunga bank naik", "Karena harga barang impor naik", "Karena gaji naik", "Karena tabungan bertambah"], "answer": "Karena harga barang impor naik", "explanation": "Rupiah melemah membuat barang impor seperti minyak dan obat lebih mahal.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "ordering", "question": "Urutkan dari yang paling ringan hingga paling ekstrem:", "options": ["Hiperinflasi", "Deflasi", "Inflasi ringan", "Inflasi tinggi"], "answer": ["Deflasi", "Inflasi ringan", "Inflasi tinggi", "Hiperinflasi"], "explanation": "Deflasi (harga turun), inflasi ringan, inflasi tinggi, hiperinflasi (sangat ekstrem).", "difficulty": "advanced", "parameters": {}}', 'advanced', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "true_false", "question": "Menyimpan uang tunai dalam jumlah besar di rumah adalah cara terbaik mengalahkan inflasi.", "answer": false, "explanation": "Uang tunai tidak bertumbuh, sehingga daya belinya tergerus inflasi.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "multiple_choice", "question": "Dalam jangka panjang, investasi apa yang umumnya digunakan untuk melindungi nilai dari inflasi?", "options": ["Tabungan biasa", "Emas atau saham", "Uang di bantal", "Dompet digital kosong"], "answer": "Emas atau saham", "explanation": "Aset seperti emas dan saham berpotensi bertumbuh melebihi inflasi dalam jangka panjang.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "word_bank", "question": "Faktor yang dapat memicu inflasi: ____", "options": ["Kenaikan harga bahan baku", "Permintaan tinggi", "Rupiah melemah", "Bunga tabungan tinggi"], "answer": ["Kenaikan harga bahan baku", "Permintaan tinggi", "Rupiah melemah"], "explanation": "Kenaikan harga bahan baku, permintaan tinggi, dan rupiah melemah bisa memicu inflasi.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "multiple_choice", "question": "Apa akibat inflasi tinggi bagi perencanaan keuangan?", "options": ["Lebih mudah menabung", "Biaya hidup tidak pasti dan sulit diperkirakan", "Gaji otomatis naik", "Bunga pinjaman turun"], "answer": "Biaya hidup tidak pasti dan sulit diperkirakan", "explanation": "Inflasi tinggi membuat biaya hidup tidak pasti, sehingga perencanaan keuangan sulit.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('ef1869f8-82e4-4ced-9b9e-e79fcb799b72', 'question', '{"type": "multiple_choice", "question": "Jika harga sepeda motor bekas naik dari Rp 8 juta menjadi Rp 8,8 juta dalam setahun, berapa laju inflasi harga motor itu?", "options": ["8%", "10%", "12%", "15%"], "answer": "10%", "explanation": "Kenaikan Rp 800.000 dari Rp 8 juta adalah 10%.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),

-- ============================================================
-- RISK & RETURN 101 — Examples
-- ============================================================
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Ahmad mulai menabung Rp 500.000 per bulan di reksa dana pasar uang sejak usia 20. Temannya Bayu mulai menabung jumlah sama di usia 30. Karena bunga majemuk, Ahmad memiliki nilai lebih besar saat usia 40 meski total setoran tidak jauh berbeda.", "source_ids": ["eca56a9e-df9b-432f-b360-c1ab6450a2ae", "f7003b72-8158-4a9e-a853-1c3bf914ea4a"]}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Rina memiliki Rp 10 juta. Ia membeli saham satu perusahaan teknologi. Jika perusahaan itu rugi, seluruh portofolionya terkena. Temannya membeli 5 saham berbeda: perbankan, konsumer, energi, kesehatan, dan teknologi. Risikonya lebih tersebar.", "source_ids": ["f7003b72-8158-4a9e-a853-1c3bf914ea4a"]}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Reksa dana pasar uang memiliki risiko rendah dan return rendah. Saham individual memiliki risiko tinggi dan return berpotensi tinggi. Tidak ada instrumen yang memberikan return tinggi tanpa risiko.", "source_ids": ["f7003b72-8158-4a9e-a853-1c3bf914ea4a"]}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Pak Sutrisno kalah Rp 2 juta karena panik menjual saham ketika harga turun 15%. Dua bulan kemudian harga saham itu naik lagi. Ia belajar bahwa panik selling bisa menghancurkan rencana jangka panjang.", "source_ids": ["eca56a9e-df9b-432f-b360-c1ab6450a2ae"]}', 'intermediate', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Dewi memiliki dana darurat 6 bulan pengeluaran di tabungan, sehingga ia tidak perlu menjual investasi sahamnya saat butuh uang mendesak. Dana darurat melindungi investasi jangka panjang.", "source_ids": ["7f4b83f2-8f1d-415c-9d4f-64e6284bef04", "f7003b72-8158-4a9e-a853-1c3bf914ea4a"]}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Seorang investor muda dengan tujuan pensiun 30 tahun ke depan bisa menoleransi fluktuasi pasar. Seorang investor yang butuh uang untuk DP rumah 2 tahun lagi sebaiknya memilih instrumen lebih stabil.", "source_ids": ["f7003b72-8158-4a9e-a853-1c3bf914ea4a"]}', 'intermediate', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Bimo mendengar saham ABC naik 50% dalam sebulan. Ia membeli tanpa riset. Ternyata kenaikan itu hanya spekulasi singkat dan harga turun 30%. Bimo belajar bahwa mengikuti tren tanpa pemahaman adalah risiko besar.", "source_ids": ["eca56a9e-df9b-432f-b360-c1ab6450a2ae"]}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Dalam sejarah pasar modal Indonesia, IHSG pernah anjlok saat krisis 1998 dan 2008, tetapi dalam jangka panjang indeks tersebut naik. Investor yang bertahan dan rutin menabung cenderung mendapat hasil positif.", "source_ids": ["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}', 'advanced', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Seseorang yang menempatkan semua uangnya di deposito 4% per tahun memiliki risiko rendah, tetapi daya belinya bisa tergerus inflasi 5%. Return realnya negatif 1%.", "source_ids": ["097b62c4-9aae-4933-a870-ac74a526b8f1", "f7003b72-8158-4a9e-a853-1c3bf914ea4a"]}', 'intermediate', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'example', '{"text": "Lima mahasiswa membentuk kelompok belajar investasi. Mereka memutuskan setiap bulan menyisihkan Rp 100.000 untuk beli saham IDX30 secara berkala. Strategi ini disebut dollar-cost averaging.", "source_ids": ["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}', 'beginner', true),

-- ============================================================
-- RISK & RETURN 101 — Questions
-- ============================================================
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "multiple_choice", "question": "Hubungan umum antara risiko dan return adalah?", "options": ["Risiko tinggi, return rendah", "Risiko rendah, return tinggi", "Risiko tinggi, return berpotensi tinggi", "Tidak ada hubungan"], "answer": "Risiko tinggi, return berpotensi tinggi", "explanation": "Umumnya, semakin tinggi potensi return, semakin tinggi risikonya.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "true_false", "question": "Diversifikasi berarti menempatkan semua uang di satu instrumen yang paling menjanjikan.", "answer": false, "explanation": "Diversifikasi adalah menyebarkan investasi ke berbagai instrumen untuk mengurangi risiko.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "multiple_choice", "question": "Mengapa waktu investasi penting?", "options": ["Karena pasar selalu naik setiap hari", "Karena bunga majemuk bekerja lebih baik dalam jangka panjang", "Karena biaya administrasi lebih murah", "Karena tidak ada risiko"], "answer": "Karena bunga majemuk bekerja lebih baik dalam jangka panjang", "explanation": "Semakin lama waktu investasi, semakin besar efek bunga majemuk.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "fill_blank", "question": "Menjual saham dalam panik ketika harga turun disebut ____ selling.", "answer": "panic", "explanation": "Panic selling adalah menjual investasi karena takut, sering merugikan jangka panjang.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "multiple_choice", "question": "Investor yang butuh uang untuk DP rumah dalam 2 tahun sebaiknya memilih?", "options": ["Saham individu yang spekulatif", "Instrumen stabil seperti deposito atau pasar uang", "Kripto dengan volatilitas tinggi", "Tidak menabung sama sekali"], "answer": "Instrumen stabil seperti deposito atau pasar uang", "explanation": "Untuk tujuan jangka pendek, pilih instrumen stabil agar nilai tidak tergerus pasar.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "ordering", "question": "Urutkan langkah menyusun portofolio sederhana:", "options": ["Tentukan tujuan", "Pilih instrumen sesuai risiko", "Diversifikasi", "Evaluasi berkala"], "answer": ["Tentukan tujuan", "Pilih instrumen sesuai risiko", "Diversifikasi", "Evaluasi berkala"], "explanation": "Tentukan tujuan, pilih instrumen, diversifikasi, lalu evaluasi secara berkala.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "true_false", "question": "Deposito bank dengan bunga 4% per tahun tetap menguntungkan meski inflasi 5% per tahun.", "answer": false, "explanation": "Return real deposito negatif karena inflasi lebih tinggi dari bunga.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "multiple_choice", "question": "Apa fungsi dana darurat dalam berinvestasi?", "options": ["Untuk membeli saham murah", "Untuk menghindari penjualan investasi saat butuh uang mendesak", "Untuk membayar pajak", "Untuk berjudi di pasar"], "answer": "Untuk menghindari penjualan investasi saat butuh uang mendesak", "explanation": "Dana darurat melindungi investasi jangka panjang dari kebutuhan mendesak.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "word_bank", "question": "Cara mengurangi risiko spesifik saham: ____", "options": ["Beli banyak saham dari sektor berbeda", "Menyimpan semua uang di satu saham", "Menabung di bantal", "Ikut tren tanpa riset"], "answer": ["Beli banyak saham dari sektor berbeda"], "explanation": "Diversifikasi antar sektor mengurangi risiko jika satu perusahaan atau sektor lesu.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "multiple_choice", "question": "Seseorang yang baru mulai berinvestasi sebaiknya?", "options": ["Langsung berutang untuk beli saham", "Belajar dulu dan mulai dengan uang yang tidak akan digunakan dalam jangka pendek", "Ikut saran influencer tanpa riset", "Menempatkan semua uang di satu saham teman"], "answer": "Belajar dulu dan mulai dengan uang yang tidak akan digunakan dalam jangka pendek", "explanation": "Pemula harus belajar dan menggunakan uang dingin agar tidak panik saat pasar turun.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('e81a8f71-77ab-44ca-b48f-a0e985313e33', 'question', '{"type": "multiple_choice", "question": "Jika inflasi 5% dan return investasi 8%, berapa return real kasarnya?", "options": ["3%", "5%", "8%", "13%"], "answer": "3%", "explanation": "Return real = return nominal - inflasi = 8% - 5% = 3%.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),

-- ============================================================
-- IDX BASICS 101 — Examples
-- ============================================================
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "PT Bank Central Asia Tbk memiliki kode saham BBCA di Bursa Efek Indonesia. Jika seseorang membeli 1 lot BBCA, ia memiliki 100 lembar saham dan menjadi salah satu pemilik kecil perusahaan tersebut.", "source_ids": ["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760", "58e3fb2d-7dbc-4a08-ab1a-379af3fa5c38"]}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Indeks Harga Saham Gabungan (IHSG) mencerminkan pergerakan harga saham-saham besar di Indonesia. Jika IHSG naik, artinya mayoritas saham besar naik, meski tidak semua saham ikut naik.", "source_ids": ["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "SIPF (Securities Investor Protection Fund) melindungi investor jika perusahaan sekuritas bangkrut. Dana investor yang disimpan di rekening saham terpisah dari aset perusahaan sekuritas.", "source_ids": ["5fa2799e-2b92-46e8-b68a-c9d64847410c"]}', 'intermediate', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Untuk berinvestasi saham sungguhan di Indonesia, seseorang perlu membuka rekening saham di perusahaan sekuritas yang terdaftar di OJK, seperti Ajaib, Stockbit, IPOT, atau sekuritas konvensional.", "source_ids": ["52aff5b9-0d1c-42d8-8dba-a1a97a3f3b3f", "47189cc8-8e51-4890-ace4-3f30b913f5ee"]}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Saham GOTO dan saham BBCA memiliki karakter berbeda. GOTO adalah perusahaan teknologi yang masih berkembang dengan volatilitas tinggi. BBCA adalah bank besar dengan sejarah laba yang lebih stabil.", "source_ids": ["58e3fb2d-7dbc-4a08-ab1a-379af3fa5c38"]}', 'intermediate', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Di IDX, transaksi saham terjadi pada jam bursa 09.00–15.00 WIB. Harga saham berubah setiap detik sesuai permintaan dan penawaran dari investor.", "source_ids": ["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Seorang investor membeli saham BBRI di harga Rp 4.000 per lembar. Setahun kemudian harganya Rp 4.800. Keuntungan modalnya 20%, belum termasuk dividen yang mungkin dibagikan perusahaan.", "source_ids": ["52aff5b9-0d1c-42d8-8dba-a1a97a3f3b3f"]}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Perusahaan yang terdaftar di IDX wajib mengungkapkan laporan keuangan secara berkala. Investor dapat membaca laporan keuangan tersebut untuk menilai kesehatan perusahaan sebelum membeli sahamnya.", "source_ids": ["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760", "5fa2799e-2b92-46e8-b68a-c9d64847410c"]}', 'intermediate', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "Koin menggunakan paper trading dengan harga penutupan harian. Saat sungguhan, harga saham bisa berbeda sedikit karena spread dan biaya broker. Paper trading mengajarkan konsep tanpa biaya transaksi nyata.", "source_ids": ["52aff5b9-0d1c-42d8-8dba-a1a97a3f3b3f"]}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'example', '{"text": "ETF adalah kumpulan saham yang diperdagangkan seperti satu saham. Misalnya ETF IDX30 memungkinkan investor membeli 30 saham besar sekaligus dalam satu transaksi, sehingga langsung diversifikasi.", "source_ids": ["58e3fb2d-7dbc-4a08-ab1a-379af3fa5c38"]}', 'intermediate', true),

-- ============================================================
-- IDX BASICS 101 — Questions
-- ============================================================
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "multiple_choice", "question": "Apa fungsi utama Bursa Efek Indonesia (IDX)?", "options": ["Menerbitkan uang rupiah", "Tempat membeli dan menjual saham di Indonesia", "Mengatur suku bunga bank", "Menyalurkan kredit UMKM"], "answer": "Tempat membeli dan menjual saham di Indonesia", "explanation": "IDX adalah pasar tempat saham dan efek lain diperdagangkan di Indonesia.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "true_false", "question": "Membeli 1 lot saham BBCA berarti membeli 10 lembar saham.", "answer": false, "explanation": "1 lot saham di IDX sama dengan 100 lembar saham.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "fill_blank", "question": "Indeks yang mencerminkan pergerakan harga saham besar di Indonesia disebut ____.", "answer": "IHSG", "explanation": "IHSG adalah Indeks Harga Saham Gabungan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "multiple_choice", "question": "Berapa lembar saham dalam 1 lot di IDX?", "options": ["10", "50", "100", "1000"], "answer": "100", "explanation": "Di Bursa Efek Indonesia, 1 lot = 100 lembar saham.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "multiple_choice", "question": "Apa yang melindungi investor jika perusahaan sekuritas bangkrut?", "options": ["SIPF", "BI Rate", "PPN", "OJK tax"], "answer": "SIPF", "explanation": "SIPF (Securities Investor Protection Fund) melindungi dana investor di perusahaan sekuritas.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "ordering", "question": "Urutkan langkah memulai investasi saham sungguhan:", "options": ["Pilih perusahaan sekuritas terdaftar", "Buka rekening saham", "Deposit dana", "Beli saham"], "answer": ["Pilih perusahaan sekuritas terdaftar", "Buka rekening saham", "Deposit dana", "Beli saham"], "explanation": "Pilih sekuritas, buka rekening, deposit, baru beli saham.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "true_false", "question": "Paper trading di Koin menggunakan uang sungguhan.", "answer": false, "explanation": "Paper trading menggunakan uang virtual, bukan uang sungguhan.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "multiple_choice", "question": "Mengapa perusahaan terdaftar di IDX wajib mengungkapkan laporan keuangan?", "options": ["Untuk membayar pajak", "Agar investor dapat menilai kesehatan perusahaan", "Untuk mendapatkan iklan gratis", "Untuk mengubah harga saham"], "answer": "Agar investor dapat menilai kesehatan perusahaan", "explanation": "Transparansi laporan keuangan membantu investor membuat keputusan berdasarkan data.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "word_bank", "question": "Manfaat ETF dibanding saham individual: ____", "options": ["Diversifikasi instan", "Biaya lebih rendah", "Tidak ada risiko", "Likuid di bursa"], "answer": ["Diversifikasi instan", "Likuid di bursa"], "explanation": "ETF memberikan diversifikasi instan dan diperdagangkan di bursa.", "difficulty": "intermediate", "parameters": {}}', 'intermediate', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "multiple_choice", "question": "Jika harga saham TLKM Rp 3.500 per lembar, berapa biaya membeli 2 lot?", "options": ["Rp 350.000", "Rp 700.000", "Rp 3.500.000", "Rp 7.000.000"], "answer": "Rp 700.000", "explanation": "2 lot = 200 lembar. 200 × Rp 3.500 = Rp 700.000.", "difficulty": "beginner", "parameters": {}}', 'beginner', true),
('b4a1a53f-efd6-4e2a-b3a4-58bb7afd9311', 'question', '{"type": "multiple_choice", "question": "Jam perdagangan saham di IDX adalah?", "options": ["08.00–14.00 WIB", "09.00–15.00 WIB", "10.00–16.00 WIB", "24 jam"], "answer": "09.00–15.00 WIB", "explanation": "Jam bursa IDX adalah 09.00–15.00 WIB.", "difficulty": "beginner", "parameters": {}}', 'beginner', true);
