ALTER TABLE public.user_settings
  ADD COLUMN IF NOT EXISTS streak_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS friend_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS cohort_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE;
