-- KO-225 group 5 continuation batch 25

update public.content_variants set body = $json${"text":"A financial plan doesn't have to be perfect from the start. Start simple, then evaluate and adjust as income and goals change."}$json$::jsonb where id = 'da916aef-39a8-4511-92d4-2770d5ea1655';
update public.content_variants set body_id = $json${"type":"matching","answer":{"Bond":"Hutang pendapatan tetap","Stock":"Kepemilikan perusahaan","Deposit":"Produk tabungan bank","Mutual Fund":"Kendaraan investasi gabungan"},"options":{"left":["Deposito","Saham","Menjalin kedekatan","Reksa Dana"],"right":["Produk tabungan bank","Kepemilikan perusahaan","Hutang pendapatan tetap","Kendaraan investasi gabungan"]},"question":"Cocokkan setiap jenis investasi dengan uraiannya:","difficulty":"advanced","parameters":{},"explanation":"Kecocokan yang benar: Deposito → Produk tabungan bank, Saham → Kepemilikan perusahaan, Obligasi → Hutang pendapatan tetap, Reksa Dana → Kendaraan investasi gabungan"}$json$::jsonb where id = 'db4382d6-6763-4f67-af2a-0cb690ed043c';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Ini memungkinkan kita membandingkan harga berbagai barang","options":["Itu bisa disimpan di bawah kasur","Ini memungkinkan kita membandingkan harga berbagai barang","Itu dicetak oleh pemerintah","Ini dapat digunakan di negara mana pun"],"question":"Apa yang dimaksud dengan uang sebagai “satuan hitung”?","difficulty":"beginner","parameters":{},"explanation":"Satuan hitung berarti segala sesuatu memiliki harga dalam mata uang yang sama, sehingga memudahkan perbandingan."}$json$::jsonb where id = 'dbb3978e-5f87-4eb2-9611-ac98d93edd04';
update public.content_variants set body_id = $json${"type":"comparison","answer":"Rekening tabungan dengan hasil tinggi","options":["Rekening tabungan dengan hasil tinggi","Portofolio saham","Keduanya sama-sama tepat","Dompet mata uang kripto"],"question":"Untuk dana darurat: apakah rekening tabungan dengan imbal hasil tinggi atau portofolio saham lebih tepat?","difficulty":"intermediate","parameters":{},"explanation":"Dana darurat membutuhkan likuiditas dan pelestarian modal, yang mana rekening tabungan menyediakan lebih baik daripada saham yang bergejolak."}$json$::jsonb where id = 'dbb87dd6-fc20-4289-b7cb-52cc13a022cb';
update public.content_variants set body_id = $json${"type":"comparison","answer":"Setoran bank berizin OJK","options":["Setoran bank berizin OJK","Platform P2P tanpa izin","Keduanya sama-sama aman","Tidak dapat menentukan"],"question":"Mana yang umumnya lebih aman: menyimpan Rp 50 juta di deposito bank berizin OJK atau berinvestasi di platform P2P tanpa izin yang menjanjikan keuntungan 15%?","difficulty":"beginner","parameters":{},"explanation":"Deposito berlisensi diatur dan diasuransikan. Platform yang tidak berlisensi membawa risiko penipuan dan tidak ada perlindungan investor."}$json$::jsonb where id = 'dcb3e303-7e25-4203-9594-4933bfdab3e8';
update public.content_variants set body_id = $json${"type":"scenario","answer":"Analisis datanya","options":["Percayai intuisi Anda","Analisis datanya","Tanya teman","Salin influencer"],"question":"Bandingkan inflasi yang disebabkan oleh biaya (kejutan harga minyak) vs inflasi yang disebabkan oleh permintaan (stimulus fiskal). Mana yang lebih sulit dikendalikan? Informasi penting apa yang hilang sebelum mengambil keputusan?","difficulty":"intermediate","parameters":{"scenario_text":"Compare cost-push inflation (oil price shock) vs demand-pull inflation (fiscal stimulus). Which is harder to control?"},"explanation":"Dalam skenario ini, analisis data mewakili pendekatan yang paling seimbang dan terinformasi dalam pengambilan keputusan keuangan."}$json$::jsonb where id = 'de5546f1-3b8a-4119-8961-5f4d6b23698d';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["Rasio P/E","EPS"],"options":["Rasio P/E","EPS","KIJANG","kapitalisasi pasar"],"question":"Metrik fundamental seperti ________ dan ________ membantu mengevaluasi penilaian saham.","difficulty":"advanced","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah: P/E rasio, EPS."}$json$::jsonb where id = 'dfa4e434-ae37-40ae-b0bb-67ed73a9e27e';
update public.content_variants set body_id = $json${"type":"comparison","answer":"Obligasi pemerintah","options":["Deposito tetap","Obligasi pemerintah","Keduanya setara","Tidak ada yang bisa mengalahkan inflasi"],"question":"Bandingkan deposito tetap (4% per tahun) vs obligasi pemerintah (6% per tahun) untuk investor konservatif. Mana yang menawarkan keuntungan riil lebih baik jika inflasi 3%?","difficulty":"beginner","parameters":{},"explanation":"Setoran pengembalian riil: 4% - 3% = 1%. Obligasi: 6% - 3% = 3%. Obligasi memberikan perlindungan inflasi yang lebih baik."}$json$::jsonb where id = 'e071e9d8-a34a-40d7-b27d-b6ae0e71902e';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Dijamin, tinggi, dan bebas risiko","options":["Angka ini lebih tinggi dibandingkan inflasi","Dijamin, tinggi, dan bebas risiko","Itu berasal dari deposito bank","Itu dibayar setiap bulan"],"question":"Manakah yang merupakan tanda peringatan bahwa pengembalian yang dijanjikan mungkin merupakan penipuan?","difficulty":"beginner","parameters":{},"explanation":"Investasi riil tidak bisa menjanjikan keuntungan tinggi tanpa risiko. Kombinasi tersebut adalah sinyal penipuan klasik."}$json$::jsonb where id = 'e0b5d38a-f0e3-4c7b-bbd3-170c5538dcd2';
update public.content_variants set body_id = $json${"type":"image_interpretation","answer":"Sebagian besar bulan mendekati rata-rata, dan jarang terjadi ekstrem","options":["Pengembalian didistribusikan secara normal","Pengembalian dapat diprediksi","Sebagian besar bulan mendekati rata-rata, dan jarang terjadi ekstrem","Setiap bulan kemungkinannya sama"],"question":"[GAMBAR: Histogram yang menunjukkan distribusi imbal hasil IHSG setiap bulan selama 20 tahun. Sebagian besar bulan mengelompok sekitar 0-2%, dengan ekor meluas hingga -15% dan +15%.]\n\nApa yang disarankan oleh bentuk distribusi ini terhadap keuntungan pasar?","difficulty":"advanced","parameters":{"image_description":"A histogram showing distribution of monthly returns for the IDX Composite over 20 years. Most months cluster around 0-2%, with tails extending to -15% and +15%."},"explanation":"Distribusi berbentuk lonceng dengan sebagian besar data mendekati mean dan lebih sedikit observasi di bagian ekor merupakan karakteristik distribusi return."}$json$::jsonb where id = 'e107d4b1-bad2-4247-a515-16cb3d5c4da8';

