-- KO-225 group 5: reviewed translation of Indonesian-shaped duplicate payloads (batch 04).
update public.content_variants set body = $json${"type":"matching","pairs":[["Medium of exchange","Pay for chicken noodles with Rp15,000"],["Store of value","Save Rp500,000 to buy shoes next month"],["Unit of account","Price of a pen is Rp3,000 and a book is Rp50,000"]],"answer":{"Medium of exchange":"Pay for chicken noodles with Rp15,000","Unit of account":"Price of a pen is Rp3,000 and a book is Rp50,000","Store of value":"Save Rp500,000 to buy shoes next month"},"question":"Match the function of money with its example.","difficulty":"beginner","explanation":"The functions of money help us understand why paper money, coins, and digital balances can be used in everyday life."}$json$::jsonb where id = 'de142f5d-3207-4b06-92fc-0c9e3021b81c';
update public.content_variants set body = $json${"text":"Rina's GoPay balance of Rp50,000 can be used to pay for online rides and top-up credit. Even though it's not in the form of paper money, electronic balances still function as a medium of exchange because they are recognized as payment."}$json$::jsonb where id = 'e4ae917f-3ffe-46b7-adc6-8139bfcff909';
update public.content_variants set body = $json${"text":"Mr. Harto, a retiree, never gives his ATM PIN to anyone, including those claiming to be bank officials. He knows that official banks will not ask for a PIN. His pension money remains safe.","source_ids":["9ddb5412-52b8-4461-b2e5-a5443ac63ca8"]}$json$::jsonb where id = 'eccf4689-7c00-441a-935e-2d13a373b911';
update public.content_variants set body = $json${"text":"Ways to get out of the debt trap: stop taking new loans, pay off high-interest debt first, and allocate more than the minimum payment."}$json$::jsonb where id = 'f088598b-076c-400a-9bc4-a85c13827a4a';
update public.content_variants set body = $json${"text":"Phishing is a fraud attempt that mimics official institutions to steal personal data, passwords, or OTPs. Social engineering manipulates emotions like fear or honor."}$json$::jsonb where id = 'f2a0c581-5aa3-4f36-84b5-ca0195b8878d';
update public.content_variants set body = $json${"text":"The value of money is not only determined by its amount but also by the price of the goods you want to buy. If prices rise, purchasing power decreases even if the nominal amount of money remains the same."}$json$::jsonb where id = 'f471b0d3-5907-42b6-a5b3-b3b327cf49be';
update public.content_variants set body = $json${"type":"fill_blank","answer":"needs","question":"Something that must be fulfilled for living and learning is called _____.","difficulty":"beginner","parameters":{},"explanation":"Needs are essential expenses that must be prioritized, unlike wants that can be postponed."}$json$::jsonb where id = 'f5641316-d243-43e4-bab7-042556269c2f';
update public.content_variants set body = $json${"text":"Nina wants to buy a laptop for Rp8 million. Her salary is Rp4 million per month. She sets a target to save Rp1 million per month for 8 months, instead of using paylater with high interest.","source_ids":["53eef1ac-2553-48d9-92a0-af6159d7d369"]}$json$::jsonb where id = 'f7f2137f-ec74-418a-9b13-fd3c62d087b1';
update public.content_variants set body = $json${"text":"A student renting a room near campus experiences a 10% increase in rent per year. With a fixed allowance, they have to look for a room further away or reduce other expenses.","source_ids":["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}$json$::jsonb where id = 'fad6dd9a-ebe8-40dc-9d70-c1d4a56afc81';
update public.content_variants set body = $json${"text":"Doni's father tells him that movie tickets used to be Rp35,000, now they are Rp50,000. With Rp100,000, Doni could watch 2.8 times before, now only 2 times. Inflation causes prices to rise gradually from year to year."}$json$::jsonb where id = 'fb815ef8-7e95-4f4d-a9b7-e468e28293bb';
