-- KO-225 group 5 exact duplicate translation batch 7

update public.content_variants set body = $json${"text":"Rina wants to buy a house in 10 years. Bank savings at 3% interest may not be enough to keep up with inflation. Investments such as stock mutual funds carry higher risks but have the potential to provide greater returns for long-term goals."}$json$::jsonb where id = '4d78262a-6c7a-42fd-bca5-31c6a715f23e';
update public.content_variants set body = $json${"text":"Fani wants to buy a laptop of IDR 5,000,000 for college in 10 months. He needs to save IDR 500,000 per month. This target is specific and has a deadline, so Fani can measure her progress every month."}$json$::jsonb where id = '4e7ab39f-afd0-42e3-9f27-63a8a36113b4';
update public.content_variants set body = $json${"text":"Saving upfront is more reliable than saving from what's left. If you wait for the rest, there is usually nothing left because expenses will follow the money available."}$json$::jsonb where id = '50a4b982-d95a-4001-9265-f17b71ce4ac7';
update public.content_variants set body = $json${"text":"Behavioral biases are thought patterns that distort financial decisions. For example, FOMO, loss aversion, and herd behavior (following the crowd)."}$json$::jsonb where id = '5181d92f-5934-4f5b-8aa2-10453fc0fa2c';
update public.content_variants set body = $json${"text":"Online shopping applications often provide big discounts. However, if discounts make us buy things we don't need, we still lose purchasing power because our money is spent on unimportant things.","source_ids":["53eef1ac-2553-48d9-92a0-af6159d7d369"]}$json$::jsonb where id = '51960795-f4ca-4da6-92a8-7340e13da59f';
update public.content_variants set body = $json${"text":"Stall A only sells chicken noodles. When chicken prices soared, sales plummeted. Warung B sells chicken noodles, iced tea, fried rice and fried foods. If one menu makes a loss, the other menu still brings in money. Warung B is more diversified."}$json$::jsonb where id = '532f9393-9028-4009-97bd-2c4d0c49362e';
update public.content_variants set body = $json${"text":"Mutual funds are a forum for collecting money from many investors, then managed by an investment manager to purchase various assets according to the type of mutual fund."}$json$::jsonb where id = '56498ba7-4c3d-4836-ad4a-11c36ff55f47';
update public.content_variants set body = $json${"text":"Taxes on investment returns reduce the net profits we receive. Therefore, compare net returns, not just gross figures."}$json$::jsonb where id = '5bdc521c-4a2f-4de2-8555-614ff8ac9147';
update public.content_variants set body = $json${"text":"Pak Tono kept Rp. 10 million in his pillow for 10 years. If inflation averages 4% per year, the purchasing power of that money decreases. Items that used to cost IDR 10 million, now might cost IDR 14.8 million.","source_ids":["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}$json$::jsonb where id = '5df74bbd-1665-4a01-bcd7-87a42521ec67';
update public.content_variants set body = $json${"text":"Types of returns that can be taxed in Indonesia include deposit interest, dividends and capital gains in accordance with applicable tax regulations."}$json$::jsonb where id = '5e17f295-6bc3-479d-a0da-9ec5708e90cc';

