-- KO-225 group 5 continuation batch 16

update public.content_variants set body_id = $json${"type":"word_bank","answer":["kebutuhan","ingin"],"options":["kebutuhan","ingin","tabungan","dana darurat"],"question":"Perencanaan keuangan dimulai dengan membedakan ________ dari ________, kemudian membangun cadangan.","difficulty":"beginner","parameters":{},"explanation":"Kata-kata yang benar dari bank adalah: kebutuhan, keinginan."}$json$::jsonb where id = 'b7de35b7-4d29-4c96-9d18-f93f1195febf';
update public.content_variants set body = $json${"text":"Rina was offered IDR 1 million in cash now or IDR 1 million a year later. If he accepts it now, the money can be saved in a deposit and earn interest. Receiving early gives him more value."}$json$::jsonb where id = 'b8058b41-c540-43a9-ae5b-332592daf77d';
update public.content_variants set body = $json${"text":"Rina lent IDR 200,000 to a friend who was often late in paying. The risk is that the friend doesn't pay back. The reward is that her friend can quickly solve the problem and Rina gets a reputation as a helpful friend."}$json$::jsonb where id = 'b83b8186-aab0-485c-aa27-cf875b0fddda';
update public.content_variants set body = $json${"text":"Sari is an office employee with health insurance from the company and no dependents. He set an emergency fund for 3 months of expenses and set aside 10% of his salary every month to fill it. Once it was full, Sari started channeling the rest into stock mutual funds for long-term goals.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = 'b867493b-629a-4438-b7cf-e23d154c3e9f';
update public.content_variants set body_id = $json${"type":"matching","answer":{"Sideways":"Gerakan datar","Correction":"10%+ penurunan dari puncak","Bear Market":"Harga jatuh","Bull Market":"Kenaikan harga"},"options":{"left":["Pasar Banteng","Pasar Beruang","Ke samping","Koreksi"],"right":["Kenaikan harga","Harga jatuh","Gerakan datar","10%+ penurunan dari puncak"]},"question":"Cocokkan setiap kondisi pasar dengan deskripsinya:","difficulty":"advanced","parameters":{},"explanation":"Pertandingan yang benar: Bull Market → Kenaikan harga, Bear Market → Penurunan harga, Sideways → Pergerakan datar, Koreksi → 10%+ penurunan dari puncak"}$json$::jsonb where id = 'b8792eb4-aa37-443d-ac8c-d1cfd67987d8';
update public.content_variants set body_id = $json${"type":"image_interpretation","answer":"Kekuatan bunga majemuk","options":["Waktu pasar","Kekuatan bunga majemuk","Keuntungan perdagangan harian","Lindung nilai mata uang"],"question":"[GAMBAR: Infografis yang menunjukkan pertumbuhan gabungan: Rp 1 juta yang diinvestasikan setiap bulan dengan pengembalian tahunan 7% tumbuh menjadi Rp 1,2 miliar selama 30 tahun vs hanya Rp 360 juta tanpa bunga.]\n\nPrinsip apa yang diilustrasikan oleh infografis ini?","difficulty":"intermediate","parameters":{"image_description":"An infographic showing compound growth: Rp 1M invested monthly at 7% annual return grows to Rp 1.2B over 30 years vs only Rp 360M without interest."},"explanation":"Perbedaan dramatis antara akumulasi sederhana dan pertumbuhan gabungan menunjukkan pentingnya memulai sejak dini dan tetap berinvestasi."}$json$::jsonb where id = 'b89daebc-effd-4c0e-b16d-474af5eb6240';
update public.content_variants set body_id = $json${"type":"calculation","answer":"24%","question":"Satu saham berharga Rp 5.000 per saham. Anda membeli 200 saham. Setelah 1 tahun, harganya menjadi Rp 6.200. Berapa persentase pengembalian Anda?","difficulty":"beginner","parameters":{"hint":"Calculate total initial cost, total final value, then percentage change."},"explanation":"Investasi awal: 200 × 5.000 = 1.000.000. Nilai akhir: 200×6.200 = 1.240.000. Pengembalian = (1.240.000 - 1.000.000) / 1.000.000 = 24%."}$json$::jsonb where id = 'ba17e0e1-00df-40cf-b290-9d67726e29b1';
update public.content_variants set body_id = $json${"type":"scenario","answer":"Kumpulkan lebih banyak informasi","options":["Segera bertindak","Kumpulkan lebih banyak informasi","Konsultasikan dengan profesional","Jangan lakukan apa pun"],"question":"BBCA punya P/E 18, BBRI punya P/E 12. Apakah otomatis BBRI lebih murah? Apa langkah selanjutnya yang paling rasional?","difficulty":"intermediate","parameters":{"scenario_text":"BBCA has P/E 18, BBRI has P/E 12. Does this automatically mean BBRI is cheaper?"},"explanation":"Dalam skenario ini, mengumpulkan lebih banyak informasi merupakan pendekatan yang paling seimbang dan terinformasi dalam pengambilan keputusan keuangan."}$json$::jsonb where id = 'ba48b038-9319-4bee-881b-e6720289731e';
update public.content_variants set body = $json${"text":"Bayu has IDR 5,000,000. He needs IDR 2,000,000 next month for tuition fees. The Rp. 2 million was kept in savings so that it was easy to withdraw. IDR 3,000,000 that is not used immediately can be turned into deposits or mutual funds according to the purpose."}$json$::jsonb where id = 'ba6a3e0f-c88c-4d8f-a3ae-8dac43abf6b0';
update public.content_variants set body = $json${"text":"Banks (savings/deposits) are generally safe and liquid, suitable for emergency funds and short-term goals. Investments have the potential for higher returns but have risks and are suitable for the long term."}$json$::jsonb where id = 'baa35b90-38ba-4048-9b1d-e046b3298e91';

