-- KO-225 group 1 continuation batch 18

update public.content_variants set body = $json${"type":"fill_blank","answer":"pay yourself first","question":"Automating transfers to savings as soon as your salary comes in is an example of the _____ principle.","difficulty":"beginner","explanation":"With automation, savings happen without needing to rely on willpower every month."}$json$::jsonb where id = 'c275915c-9d7d-4716-a63c-c9dae6e4bfb3';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Keeping large amounts of cash at home is the best way to beat inflation.","difficulty":"beginner","parameters":{},"explanation":"Cash does not grow, so its purchasing power is eroded by inflation."}$json$::jsonb where id = 'c33e96e8-bc41-4348-b247-88c179fce2b5';
update public.content_variants set body = $json${"type":"fill_blank","answer":"recording","question":"The activity of recording every small expense every day is called _____ expenses.","difficulty":"beginner","parameters":{},"explanation":"Recording expenses helps us monitor money flow and run a budget with discipline."}$json$::jsonb where id = 'c5a4db39-7ac9-4687-b940-f1649f311a18';
update public.content_variants set body = $json${"type":"ordering","answer":["Prices of goods rise","The same money buys less","Purchasing power decreases","People reduce consumption"],"options":["Prices of goods rise","The same money buys less","Purchasing power decreases","People reduce consumption"],"question":"Sort the impact of inflation on people's purchasing power.","difficulty":"beginner","parameters":{},"explanation":"Inflation raises prices, so money buys less, purchasing power decreases, and consumption decreases."}$json$::jsonb where id = 'c63097f1-d5d4-4c02-bdad-7d3d5d618bd5';
update public.content_variants set body = $json${"type":"fill_blank","answer":"500.000","question":"Fani wants to buy a laptop for IDR 5,000,000 in 10 months, so she has to save IDR_____ per month.","difficulty":"beginner","explanation":"IDR 5,000,000 divided by 10 months equals IDR 500,000 per month."}$json$::jsonb where id = 'c6ada195-8e7c-4fba-9663-cacda1bc5782';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"BI","options":["FSA","BI","IDX","Ministry of Finance"],"question":"The institution tasked with maintaining price stability in Indonesia is?","difficulty":"beginner","parameters":{},"explanation":"Bank Indonesia (BI) is tasked with maintaining the stability of the rupiah exchange rate and controlling inflation."}$json$::jsonb where id = 'cb88a442-97e4-494c-925b-4dc4970625db';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"After the emergency funds have been collected, you can start allocating the excess funds to long-term investments.","difficulty":"beginner","parameters":{},"explanation":"An emergency fund is the foundation of finance. Once fulfilled, other funds can be allocated for investment according to your goals and risk profile."}$json$::jsonb where id = 'cc85d84f-08c7-461b-8750-712a91b383f8';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Rp. 52,500","options":["Rp. 52,500","Rp. 50,000","Rp. 5,000","Rp. 100,000"],"question":"Savings IDR 1,000,000 with 5% interest per year. After the first year the balance is IDR 1,050,000. How much is the second year's interest?","difficulty":"intermediate","explanation":"5% of IDR 1,050,000 is IDR 52,500."}$json$::jsonb where id = 'cf14409e-eb82-448c-be72-00e33ae27110';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"A budget means we shouldn't spend any money on entertainment at all.","difficulty":"beginner","explanation":"A 50/30/20 budget sets aside 30% for wants, including entertainment, as long as it stays within limits."}$json$::jsonb where id = 'cf83323b-f919-48b9-a1fb-5b8e1d527f06';
update public.content_variants set body = $json${"type":"ordering","answer":["Determine goals","Choose instruments according to risk","Diversification","Periodic evaluation"],"options":["Determine goals","Choose instruments according to risk","Diversification","Periodic evaluation"],"question":"Sequence the steps for compiling a simple portfolio:","difficulty":"beginner","parameters":{},"explanation":"Determine goals, choose instruments, diversify, then evaluate regularly."}$json$::jsonb where id = 'cfb21e77-6a6b-466b-86fc-3acca267d9ac';

