-- KO-225 group 5 exact duplicate translation batch 9

update public.content_variants set body = $json${"text":"Rina has IDR 10 million. He bought shares in a technology company. If the company loses, its entire portfolio is hit. His friend bought 5 different stocks: banking, consumer, energy, health, and technology. The risks are more spread out.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = '6e22a1b2-3e5d-486e-a6c1-1a89b52565b1';
update public.content_variants set body = $json${"text":"SIPF (Securities Investor Protection Fund) provides protection for investors in the capital market according to regulations. This is one of the investor protection mechanisms."}$json$::jsonb where id = '6ec64db1-40ae-4ee8-a238-ba5d3880bcf6';
update public.content_variants set body = $json${"text":"Bayu received a WhatsApp message on behalf of BCA Bank: 'Your account is blocked, click the link to activate it.' The link asks for OTP and password. Bayu didn't click and immediately contacted the official BCA call center. The message is phishing."}$json$::jsonb where id = '6ee9e84c-72b1-414d-8d55-652b4ef327fa';
update public.content_variants set body = $json${"text":"An ETF is a collection of shares that trade like a single stock. For example, the IDX30 ETF allows investors to buy 30 large shares at once in one transaction, thereby providing immediate diversification.","source_ids":["58e3fb2d-7dbc-4a08-ab1a-379af3fa5c38"]}$json$::jsonb where id = '74ef7fbc-1abc-4cb4-b03d-d7d515ca1e5f';
update public.content_variants set body = $json${"text":"Bayu has a goal of 'saving more.' He doesn't know how much to set aside or when to reach it. After he changed it to 'save IDR 2 million in 5 months' or IDR 400,000 per month, he became more motivated."}$json$::jsonb where id = '75e8f63a-c60c-4fae-ad40-ac1ff44179c0';
update public.content_variants set body = $json${"text":"In the history of the Indonesian capital market, the JCI fell during the 1998 and 2008 crises, but in the long term the index rose. Investors who persist and save regularly tend to get positive results.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = '770ddcbd-4488-4f0b-9ac6-a78b820f0712';
update public.content_variants set body = $json${"text":"Rina saves IDR 1,000,000 with interest of 5% per year. The first year you get IDR 50,000. The second year, the interest is calculated from IDR 1,050,000, so it is bigger. This is compound interest."}$json$::jsonb where id = '78e582e9-9850-4550-b137-5c8af57c7c16';
update public.content_variants set body = $json${"text":"The 50/30/20 rule divides income: 50% for needs, 30% for wants, and 20% for savings and paying off debt."}$json$::jsonb where id = '7967140c-bfaa-405d-8eb2-31cdcce599aa';
update public.content_variants set body = $json${"text":"In general, the higher the potential return, the higher the risk that must be accepted. There is no high-yielding investment without risk."}$json$::jsonb where id = '7b12b4fc-1f4b-4a72-9603-197a1d585a9c';
update public.content_variants set body = $json${"text":"Novice investors do not need to try to conquer macro indicators. What can be controlled are goals, diversification and savings discipline."}$json$::jsonb where id = '7b3159b2-4ff9-4f0e-bd64-efac2d1f3941';

