-- KO-225 group 5 continuation batch 26

update public.content_variants set body = $json${"text":"Mr Budi's family in Surabaya makes a monthly budget by first setting aside IDR 1 million for savings for their children's education, then managing other expenses. The principle of \"pay yourself first\" helps them consistently save.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = 'e1d15afb-5d2b-4651-a0ce-d2847e65ca0d';
update public.content_variants set body = $json${"text":"Rina has IDR 10,000,000: IDR 3 million in savings, IDR 4 million in money market mutual funds, and IDR 3 million in one share. This is a portfolio, although it still needs better diversification."}$json$::jsonb where id = 'e25241f2-5b10-4e97-ae3e-fc5a0f2addff';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"didorong oleh emosi","options":["pasien dalam jangka panjang","didorong oleh emosi","sangat rasional","gaya dana indeks"],"question":"Seorang investor yang memeriksa portofolionya setiap hari dan sering melakukan perdagangan cenderung menunjukkan perilaku ________.","difficulty":"advanced","parameters":{},"explanation":"Pemantauan dan perdagangan yang sering sering kali mengarah pada pengambilan keputusan yang emosional daripada strategi yang disiplin."}$json$::jsonb where id = 'e3259501-704c-4182-b789-c09fba2dfaeb';
update public.content_variants set body = $json${"text":"Managing risk does not mean avoiding risk completely. We recognize the risks, decide whether the rewards are worth it, then take safety measures if necessary."}$json$::jsonb where id = 'e4944274-1c80-41c0-90a5-8a1c90147c1f';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"bertahun-tahun","question":"Anda harus menabung untuk keadaan darurat terlebih dahulu, kemudian menginvestasikan uang yang tidak Anda perlukan untuk beberapa ____.","difficulty":"beginner","parameters":{},"explanation":"Berinvestasi adalah yang terbaik untuk mendapatkan uang yang dapat Anda tinggalkan untuk waktu yang lebih lama."}$json$::jsonb where id = 'e4c84d4d-14eb-4665-a02b-c1e351285a2c';
update public.content_variants set body_id = $json${"type":"image_interpretation","answer":"Saham secara historis melampaui inflasi","options":["Rekening tabungan mengalahkan inflasi","Saham secara historis melampaui inflasi","Semua investasi adalah sama","Uang tunai adalah penyimpan nilai terbaik"],"question":"[GAMBAR: Diagram batang yang membandingkan tingkat inflasi (3%) vs bunga rekening tabungan (2%) vs rata-rata pengembalian pasar saham (10%) selama 10 tahun.]\n\nWawasan penting apa yang diungkapkan oleh perbandingan ini?","difficulty":"intermediate","parameters":{"image_description":"A bar chart comparing inflation rate (3%) vs savings account interest (2%) vs stock market average return (10%) over 10 years."},"explanation":"Grafik tersebut menunjukkan bahwa meskipun tabungan kehilangan daya beli karena inflasi, ekuitas secara historis memberikan keuntungan yang melebihi inflasi."}$json$::jsonb where id = 'e4e6929b-322e-4a09-8ecc-4f7deeb4f553';
update public.content_variants set body_id = $json${"type":"spot_mistake","answer":["Membawa saldo kartu kredit yang tinggi","Hanya membayar minimum","Menggunakan pulsa untuk pembelian rutin tanpa rencana","Akumulasi bunga bulanan 2,5%."],"options":["Membawa saldo kartu kredit yang tinggi","Hanya membayar minimum","Menggunakan pulsa untuk pembelian rutin tanpa rencana","Akumulasi bunga bulanan 2,5%.","Tidak ada kesalahan","Hanya satu kesalahan kecil"],"question":"Bacalah pernyataan berikut dan kenali kesalahan finansialnya:\n\nSaya menggunakan kartu kredit saya untuk semua pembelian karena saya mendapatkan cashback. Saya hanya membayar saldo minimum setiap bulannya. Saya mempunyai utang kartu kredit sebesar Rp 50 juta.","difficulty":"advanced","parameters":{"mistake_count":4},"explanation":"Utang kartu kredit sebesar 2,5% setiap bulannya bertambah ke tingkat yang sangat buruk. Pembayaran minimum memperpanjang hutang selama bertahun-tahun."}$json$::jsonb where id = 'e4ff7e2b-04b1-4be0-8051-3dae5efecfc9';
update public.content_variants set body_id = $json${"type":"comparison","answer":"Rata-rata biaya dolar","options":["Investasi sekaligus","Rata-rata biaya dolar","Keduanya menghilangkan risiko waktu","Tidak ada yang membantu"],"question":"Bandingkan investasi sekaligus dengan rata-rata biaya dolar (DCA) di pasar yang bergejolak. Mana yang biasanya mengurangi risiko waktu?","difficulty":"intermediate","parameters":{},"explanation":"DCA menyebarkan pembelian dari waktu ke waktu, mengurangi dampak investasi pada puncak pasar."}$json$::jsonb where id = 'e51ea97f-8dee-47e7-a4b5-147d4d54a5aa';
update public.content_variants set body_id = $json${"type":"ordering","answer":["Periksa izin OJK","Baca prospektusnya","Pahami risikonya","Mulailah dengan jumlah kecil","Pantau secara teratur"],"options":["Periksa izin OJK","Baca prospektusnya","Pahami risikonya","Mulailah dengan jumlah kecil","Pantau secara teratur"],"question":"Pesan langkah-langkah uji tuntas yang tepat sebelum berinvestasi:","difficulty":"intermediate","parameters":{},"explanation":"Urutan yang benar adalah: Cek izin OJK → Baca prospektus → Pahami risikonya → Mulai dengan jumlah kecil → Pantau secara berkala"}$json$::jsonb where id = 'e54b1852-a0c1-435f-aea4-ae274ef24f9d';
update public.content_variants set body = $json${"text":"Ani is 19 years old, earns IDR 2.5 million/month from freelance design, has no emergency funds, and has a PayLater debt of IDR 2 million. The plan: 1) create a small emergency fund, 2) pay down PayLater debt, 3) create a 50/30/20 budget, 4) start health insurance, 5) start small investments."}$json$::jsonb where id = 'e5578081-99f4-45b3-861e-560a0047279b';

