-- KO-440: Chapter 11 — Decision Analysis Lab visual-learning refinement.
-- All figures are fictional/calculated learning examples, not trade advice.
BEGIN;

WITH m(slug, source_code) AS (VALUES
 ('decision-multicandle-context','CH08-OJK-CAPITAL'),
 ('decision-volume-confirmation','CH08-IDX-TRADING'),
 ('decision-zones-false-breakouts','CH08-OJK-CAPITAL'),
 ('decision-timeframe-comparison','CH08-IDX-TRADING'),
 ('decision-risk-reward','OJK-ADV-001'),
 ('decision-position-sizing','OJK-ADV-001'),
 ('decision-bias-and-narratives','OJK-003'),
 ('decision-thesis-invalidation','OJK-ADV-001'))
INSERT INTO public.lesson_sources (lesson_id, source_id, relevance_type, citation_label, is_primary, display_order)
SELECT l.id,s.id,'primary',s.source_code,TRUE,10 FROM m
JOIN public.lessons l ON l.slug=m.slug AND l.is_published
JOIN public.sources s ON s.source_code=m.source_code
ON CONFLICT (lesson_id,source_id) DO UPDATE SET relevance_type=EXCLUDED.relevance_type,citation_label=EXCLUDED.citation_label,is_primary=TRUE,display_order=10;

WITH b(slug,kind,status,content) AS (VALUES
 ('decision-multicandle-context','annotated_data','illustrative',$j${"en":{"icon":"🕯️","eyebrow":"Sequence beats snap judgement","title":"Four candles give more context than one","altText":"An illustrative four-candle chart shows a rise, pause, rejection, and follow-through.","disclosure":"Illustrative candles only. A sequence describes past behaviour; it does not predict the next move.","payload":{"quoteTitle":"Illustrative sequence","chart":{"accent":"advanced","candles":[{"open":100,"high":108,"low":98,"close":106,"label":"Rise"},{"open":106,"high":109,"low":103,"close":105,"label":"Pause"},{"open":105,"high":110,"low":101,"close":102,"label":"Reject"},{"open":102,"high":106,"low":99,"close":103,"label":"Follow"}],"markers":[{"number":1,"candleIndex":0,"position":"close"},{"number":2,"candleIndex":2,"position":"high"},{"number":3,"candleIndex":3,"position":"close"}]},"annotations":[{"number":1,"label":"Start with the sequence","detail":"Several candles reveal whether a move is developing."},{"number":2,"label":"Name the reaction","detail":"A wick records a test, not a guaranteed reversal."},{"number":3,"label":"Wait for context","detail":"Later evidence still cannot guarantee an outcome."}]}},"id":{"icon":"🕯️","eyebrow":"Rangkaian lebih penting","title":"Empat candle memberi lebih banyak konteks daripada satu","altText":"Grafik empat candle ilustratif menunjukkan kenaikan, jeda, penolakan, dan tindak lanjut.","disclosure":"Candle ini hanya ilustrasi. Rangkaian menggambarkan masa lalu, bukan langkah berikutnya.","payload":{"quoteTitle":"Rangkaian ilustratif","chart":{"accent":"advanced","candles":[{"open":100,"high":108,"low":98,"close":106,"label":"Naik"},{"open":106,"high":109,"low":103,"close":105,"label":"Jeda"},{"open":105,"high":110,"low":101,"close":102,"label":"Tolak"},{"open":102,"high":106,"low":99,"close":103,"label":"Lanjut"}],"markers":[{"number":1,"candleIndex":0,"position":"close"},{"number":2,"candleIndex":2,"position":"high"},{"number":3,"candleIndex":3,"position":"close"}]},"annotations":[{"number":1,"label":"Mulai dari rangkaian","detail":"Beberapa candle menunjukkan perkembangan."},{"number":2,"label":"Sebutkan reaksi","detail":"Wick mencatat pengujian, bukan pembalikan yang dijamin."},{"number":3,"label":"Tunggu konteks","detail":"Bukti setelahnya tetap tidak menjamin hasil."}]}}}$j$::jsonb),
 ('decision-volume-confirmation','comparison','illustrative',$j${"en":{"icon":"📊","eyebrow":"Volume is a clue, not proof","title":"A bigger bar asks a better question","altText":"A comparison contrasts ordinary activity with unusually high activity.","disclosure":"Illustrative volume labels only. Volume is historical activity, not a forecast.","payload":{"leftTitle":"Ordinary activity","rightTitle":"Unusually high activity","rows":[{"left":"A move with ordinary volume","right":"A move with an unusually high volume bar"},{"left":"Ask what else changed","right":"Ask what news or level needs checking"},{"left":"Does not prove continuation","right":"Still does not prove continuation"}]}},"id":{"icon":"📊","eyebrow":"Volume adalah petunjuk","title":"Bar yang lebih besar mengajukan pertanyaan lebih baik","altText":"Perbandingan membedakan aktivitas biasa dan sangat tinggi.","disclosure":"Label volume ini hanya ilustrasi. Volume adalah aktivitas historis, bukan ramalan.","payload":{"leftTitle":"Aktivitas biasa","rightTitle":"Aktivitas sangat tinggi","rows":[{"left":"Pergerakan dengan volume biasa","right":"Pergerakan dengan bar volume sangat tinggi"},{"left":"Tanyakan apa lagi yang berubah","right":"Tanyakan berita atau level yang perlu diperiksa"},{"left":"Tidak membuktikan kelanjutan","right":"Tetap tidak membuktikan kelanjutan"}]}}}$j$::jsonb),
 ('decision-zones-false-breakouts','annotated_data','illustrative',$j${"en":{"icon":"🧭","eyebrow":"Breakouts need a boundary check","title":"A move outside a zone can return","altText":"An illustrative chart shows price moving above a zone and closing back inside it.","disclosure":"Illustrative chart only. A false breakout is evidence to investigate, not a guaranteed reversal.","payload":{"quoteTitle":"Zone and return","chart":{"accent":"advanced","candles":[{"open":100,"high":104,"low":98,"close":102,"label":"Zone"},{"open":102,"high":106,"low":101,"close":105,"label":"Test"},{"open":105,"high":110,"low":104,"close":106,"label":"Breach"},{"open":106,"high":107,"low":101,"close":102,"label":"Return"}],"markers":[{"number":1,"candleIndex":0,"position":"close"},{"number":2,"candleIndex":2,"position":"high"},{"number":3,"candleIndex":3,"position":"close"}]},"annotations":[{"number":1,"label":"Mark a zone","detail":"Nearby reactions form an area."},{"number":2,"label":"Notice the breach","detail":"A brief move above needs more context."},{"number":3,"label":"Record the return","detail":"A return changes the description, not the future."}]}},"id":{"icon":"🧭","eyebrow":"Breakout membutuhkan batas","title":"Pergerakan di luar zona dapat kembali","altText":"Grafik ilustratif menunjukkan harga sebentar di atas zona lalu kembali ke dalam.","disclosure":"Hanya ilustrasi. False breakout adalah bukti untuk diperiksa, bukan pembalikan yang dijamin.","payload":{"quoteTitle":"Zona dan kembali","chart":{"accent":"advanced","candles":[{"open":100,"high":104,"low":98,"close":102,"label":"Zona"},{"open":102,"high":106,"low":101,"close":105,"label":"Uji"},{"open":105,"high":110,"low":104,"close":106,"label":"Tembus"},{"open":106,"high":107,"low":101,"close":102,"label":"Kembali"}],"markers":[{"number":1,"candleIndex":0,"position":"close"},{"number":2,"candleIndex":2,"position":"high"},{"number":3,"candleIndex":3,"position":"close"}]},"annotations":[{"number":1,"label":"Tandai zona","detail":"Reaksi berdekatan membentuk area."},{"number":2,"label":"Perhatikan penembusan","detail":"Pergerakan singkat membutuhkan konteks."},{"number":3,"label":"Catat kembalinya harga","detail":"Kembalinya harga mengubah deskripsi, bukan masa depan."}]}}}$j$::jsonb),
 ('decision-timeframe-comparison','comparison','illustrative',$j${"en":{"icon":"🔭","eyebrow":"Change the lens, not the facts","title":"Five minutes and one week tell different parts of the story","altText":"A comparison shows short timeframe detail and longer timeframe context.","disclosure":"Illustrative comparison. Aggregation changes visible detail; it does not guarantee a forecast.","payload":{"leftTitle":"Short timeframe","rightTitle":"Longer timeframe","rows":[{"left":"More candles and intraday detail","right":"Fewer candles and broader context"},{"left":"A move may look dramatic","right":"The same move may sit in a normal range"},{"left":"Describes detail","right":"Describes wider structure"}]}},"id":{"icon":"🔭","eyebrow":"Ganti lensa, bukan fakta","title":"Lima menit dan satu minggu menceritakan bagian berbeda","altText":"Perbandingan menunjukkan detail timeframe pendek dan konteks timeframe panjang.","disclosure":"Hanya ilustrasi. Agregasi mengubah detail, bukan menjamin ramalan.","payload":{"leftTitle":"Timeframe pendek","rightTitle":"Timeframe lebih panjang","rows":[{"left":"Lebih banyak candle dan detail intraday","right":"Lebih sedikit candle dan konteks luas"},{"left":"Pergerakan bisa terlihat dramatis","right":"Pergerakan sama bisa dalam rentang normal"},{"left":"Menjelaskan detail","right":"Menjelaskan struktur luas"}]}}}$j$::jsonb),
 ('decision-risk-reward','worked_example','calculated',$j${"en":{"icon":"⚖️","eyebrow":"Plan the downside first","title":"A ratio does not turn a guess into a guarantee","altText":"A fictional Rp100,000 possible loss is compared with a fictional Rp200,000 possible gain.","disclosure":"Calculated illustration only: no probability, fees, taxes, or expected return is implied.","payload":{"inputs":[{"label":"Possible loss","value":"Rp100,000"},{"label":"Possible gain","value":"Rp200,000"},{"label":"Ratio","value":"1 : 2"}],"steps":["Name the possible loss.","Compare the possible gain.","Ask whether the loss disrupts essentials or a goal."],"outcome":"The ratio describes a scenario; it does not predict the outcome."}},"id":{"icon":"⚖️","eyebrow":"Rencanakan sisi buruk","title":"Rasio tidak mengubah tebakan menjadi jaminan","altText":"Kemungkinan rugi fiktif Rp100.000 dibandingkan dengan kemungkinan untung fiktif Rp200.000.","disclosure":"Hanya ilustrasi: tidak menyiratkan probabilitas, biaya, pajak, atau imbal hasil.","payload":{"inputs":[{"label":"Kemungkinan rugi","value":"Rp100.000"},{"label":"Kemungkinan untung","value":"Rp200.000"},{"label":"Rasio","value":"1 : 2"}],"steps":["Sebutkan kemungkinan rugi.","Bandingkan kemungkinan untung.","Tanyakan apakah kerugian mengganggu kebutuhan atau tujuan."],"outcome":"Rasio menggambarkan skenario; bukan memprediksi hasil."}}}$j$::jsonb),
 ('decision-position-sizing','worked_example','calculated',$j${"en":{"icon":"🧱","eyebrow":"Exposure is a choice","title":"A smaller position leaves more room for being wrong","altText":"A fictional Rp10,000,000 portfolio is compared with larger and smaller exposures.","disclosure":"Calculated illustration only. This is not a personal position-size recommendation.","payload":{"inputs":[{"label":"Illustrative portfolio","value":"Rp10,000,000"},{"label":"Larger exposure","value":"Rp1,000,000"},{"label":"Smaller exposure","value":"Rp200,000"}],"steps":["Protect money needed for essentials.","Choose tolerable exposure.","Write the condition that triggers reassessment."],"outcome":"Position size changes potential damage; confidence does not remove uncertainty."}},"id":{"icon":"🧱","eyebrow":"Eksposur adalah pilihan","title":"Posisi lebih kecil memberi ruang untuk salah","altText":"Portofolio fiktif Rp10.000.000 dibandingkan dengan eksposur lebih besar dan lebih kecil.","disclosure":"Hanya ilustrasi. Ini bukan rekomendasi ukuran posisi pribadi.","payload":{"inputs":[{"label":"Portofolio ilustratif","value":"Rp10.000.000"},{"label":"Eksposur lebih besar","value":"Rp1.000.000"},{"label":"Eksposur lebih kecil","value":"Rp200.000"}],"steps":["Lindungi uang untuk kebutuhan pokok.","Pilih eksposur yang dapat ditanggung.","Tuliskan kondisi untuk penilaian ulang."],"outcome":"Ukuran posisi mengubah dampak; keyakinan tidak menghapus ketidakpastian."}}}$j$::jsonb),
 ('decision-bias-and-narratives','process','illustrative',$j${"en":{"icon":"🧠","eyebrow":"Slow the story down","title":"Separate evidence from the story you want to be true","altText":"A three-step process states a belief, seeks disconfirming evidence, and checks a neutral official source.","disclosure":"Decision-hygiene process, not a prediction or recommendation.","payload":{"steps":[{"title":"1. State the belief","description":"Write the claim you are tempted to accept."},{"title":"2. Seek disconfirmation","description":"Name one observation that would weaken it."},{"title":"3. Check neutral evidence","description":"Use an official source and separate facts from interpretation."}]}},"id":{"icon":"🧠","eyebrow":"Perlambat ceritanya","title":"Pisahkan bukti dari cerita yang ingin kamu percayai","altText":"Proses tiga langkah menyebutkan keyakinan, mencari bukti penyangkal, dan memeriksa sumber resmi netral.","disclosure":"Proses menjaga keputusan, bukan prediksi atau rekomendasi.","payload":{"steps":[{"title":"1. Sebutkan keyakinan","description":"Tuliskan klaim yang ingin kamu terima."},{"title":"2. Cari bukti penyangkal","description":"Sebutkan pengamatan yang dapat melemahkannya."},{"title":"3. Periksa bukti netral","description":"Gunakan sumber resmi dan pisahkan fakta dari interpretasi."}]}}}$j$::jsonb),
 ('decision-thesis-invalidation','process','illustrative',$j${"en":{"icon":"🛑","eyebrow":"A thesis needs a boundary","title":"Write the invalidation rule before the outcome","altText":"A three-step process moves from thesis to observable condition to reassessment.","disclosure":"Illustrative reasoning workflow, not a personal stop, target, or trade instruction.","payload":{"steps":[{"title":"1. State the thesis","description":"Explain why the idea might make sense using evidence."},{"title":"2. Name the condition","description":"Write what new evidence would make it weaker."},{"title":"3. Reassess","description":"Pause and review when the condition appears."}]}},"id":{"icon":"🛑","eyebrow":"Tesis membutuhkan batas","title":"Tuliskan aturan pembatalan sebelum hasilnya terlihat","altText":"Proses tiga langkah bergerak dari tesis ke kondisi yang dapat diamati lalu penilaian ulang.","disclosure":"Alur penalaran ilustratif, bukan stop, target, atau instruksi transaksi.","payload":{"steps":[{"title":"1. Sebutkan tesis","description":"Jelaskan mengapa ide mungkin masuk akal berdasarkan bukti."},{"title":"2. Sebutkan kondisi","description":"Tuliskan bukti baru yang akan melemahkannya."},{"title":"3. Nilai ulang","description":"Berhenti dan tinjau saat kondisi muncul."}]}}}$j$::jsonb)
)
INSERT INTO public.lesson_visual_blocks (lesson_id,placement,block_type,display_order,data_status,content,is_published)
SELECT l.id,'concept',b.kind,10,b.status,b.content,TRUE FROM b JOIN public.lessons l ON l.slug=b.slug AND l.is_published
ON CONFLICT (lesson_id,placement,display_order) DO UPDATE SET block_type=EXCLUDED.block_type,data_status=EXCLUDED.data_status,content=EXCLUDED.content,is_published=TRUE,updated_at=NOW();

WITH m(slug,source_code) AS (VALUES
 ('decision-multicandle-context','CH08-OJK-CAPITAL'),('decision-volume-confirmation','CH08-IDX-TRADING'),('decision-zones-false-breakouts','CH08-OJK-CAPITAL'),('decision-timeframe-comparison','CH08-IDX-TRADING'),('decision-risk-reward','OJK-ADV-001'),('decision-position-sizing','OJK-ADV-001'),('decision-bias-and-narratives','OJK-003'),('decision-thesis-invalidation','OJK-ADV-001'))
INSERT INTO public.lesson_visual_block_sources (visual_block_id,source_id,citation_label)
SELECT b.id,s.id,s.source_code FROM m JOIN public.lessons l ON l.slug=m.slug JOIN public.lesson_visual_blocks b ON b.lesson_id=l.id AND b.placement='concept' AND b.display_order=10 JOIN public.sources s ON s.source_code=m.source_code
ON CONFLICT (visual_block_id,source_id) DO UPDATE SET citation_label=EXCLUDED.citation_label;

-- Three varied, bilingual applied checks per lesson. The same contract is
-- intentionally used for every lesson: observation, boundary, then action.
WITH q(slug,n,en_question,id_question,en_answer,id_answer,en_options,id_options,en_explanation,id_explanation) AS (VALUES
 ('decision-multicandle-context',1,'Four candles rise, pause, reject a higher level, then close near the starting zone. What is supported?','Empat candle naik, berhenti, menolak level lebih tinggi, lalu ditutup dekat zona awal. Apa yang didukung?','The sequence shows a changing reaction that needs context','Rangkaian menunjukkan reaksi yang berubah dan membutuhkan konteks',jsonb_build_array('The sequence shows a changing reaction that needs context','The next candle must rise','The rejection guarantees a reversal','One candle proves the whole trend'),jsonb_build_array('Rangkaian menunjukkan reaksi yang berubah dan membutuhkan konteks','Candle berikutnya pasti naik','Penolakan menjamin pembalikan','Satu candle membuktikan seluruh tren'),'The sequence describes past reactions; it does not guarantee the next move.','Rangkaian menggambarkan reaksi masa lalu; bukan jaminan pergerakan berikutnya.'),
 ('decision-multicandle-context',2,'A sequence of candles can add context without becoming what?','Rangkaian candle dapat menambah konteks tanpa menjadi apa?','A guaranteed forecast','Ramalan yang dijamin',jsonb_build_array('A guaranteed forecast','A historical observation','A description of reaction','A reason to inspect context'),jsonb_build_array('Ramalan yang dijamin','Pengamatan historis','Deskripsi reaksi','Alasan memeriksa konteks'),'More observations improve description, not certainty.','Lebih banyak pengamatan memperbaiki deskripsi, bukan kepastian.'),
 ('decision-multicandle-context',3,'What should be checked after describing a candle sequence?','Apa yang perlu diperiksa setelah mendeskripsikan rangkaian candle?','Later evidence and the surrounding zone','Bukti setelahnya dan zona sekitar',jsonb_build_array('Later evidence and the surrounding zone','A guaranteed next price','Only the candle colour','A universal buy rule'),jsonb_build_array('Bukti setelahnya dan zona sekitar','Harga berikutnya yang dijamin','Hanya warna candle','Aturan beli universal'),'Later evidence adds context without settling the future.','Bukti setelahnya menambah konteks tanpa menentukan masa depan.'),
 ('decision-volume-confirmation',1,'A price move has unusually high volume. What is the best next question?','Pergerakan harga memiliki volume sangat tinggi. Apa pertanyaan berikutnya?','What news, level, or event might explain the activity?','Berita, level, atau peristiwa apa yang mungkin menjelaskan aktivitas itu?',jsonb_build_array('What news, level, or event might explain the activity?','How can I copy it immediately?','Which price is guaranteed next?','Why does volume remove risk?'),jsonb_build_array('Berita, level, atau peristiwa apa yang mungkin menjelaskan aktivitas itu?','Bagaimana langsung menirunya?','Harga berikutnya mana yang dijamin?','Mengapa volume menghapus risiko?'),'Unusual activity invites investigation; it does not prove direction.','Aktivitas tidak biasa mengundang pemeriksaan; bukan bukti arah harga.'),
 ('decision-volume-confirmation',2,'High volume proves a price move will continue.','Volume tinggi membuktikan pergerakan harga akan berlanjut.','False','Salah',jsonb_build_array('True','False','Only in a rising market','Only with a famous ticker'),jsonb_build_array('Benar','Salah','Hanya di pasar naik','Hanya dengan ticker terkenal'),'Volume is context about past activity, not proof of the next outcome.','Volume adalah konteks aktivitas masa lalu, bukan bukti hasil berikutnya.'),
 ('decision-volume-confirmation',3,'What should stay separate when reading volume?','Apa yang harus tetap dipisahkan saat membaca volume?','The observed activity and the forecast','Aktivitas yang diamati dan ramalan',jsonb_build_array('The observed activity and the forecast','The ticker and the exchange','The candle and its date','The source and its title'),jsonb_build_array('Aktivitas yang diamati dan ramalan','Ticker dan bursa','Candle dan tanggalnya','Sumber dan judulnya'),'Separating observation from forecast prevents overclaiming.','Memisahkan pengamatan dari ramalan mencegah klaim berlebihan.'),
 ('decision-zones-false-breakouts',1,'Price briefly moves above a zone and closes back inside. What is careful?','Harga sebentar di atas zona lalu kembali masuk. Apa pembacaan hati-hati?','The breach and return are evidence to inspect, not a guaranteed reversal','Penembusan dan kembalinya harga adalah bukti untuk diperiksa, bukan pembalikan yang dijamin',jsonb_build_array('The breach and return are evidence to inspect, not a guaranteed reversal','The zone must hold forever','The next candle must fall','The exact zone price is known'),jsonb_build_array('Penembusan dan kembalinya harga adalah bukti untuk diperiksa, bukan pembalikan yang dijamin','Zona pasti bertahan selamanya','Candle berikutnya pasti turun','Harga zona tepat sudah diketahui'),'A false breakout describes what happened; it does not settle what happens next.','False breakout menjelaskan apa yang terjadi; bukan menentukan yang berikutnya.'),
 ('decision-zones-false-breakouts',2,'Support and resistance are better treated as what?','Support dan resistance lebih tepat diperlakukan sebagai apa?','Reaction areas','Area reaksi',jsonb_build_array('Reaction areas','Magical exact prices','Guaranteed floors','Company fair value'),jsonb_build_array('Area reaksi','Harga tepat yang ajaib','Lantai yang dijamin','Nilai wajar perusahaan'),'Nearby reactions can cluster across a range.','Reaksi berdekatan dapat berkumpul dalam suatu rentang.'),
 ('decision-zones-false-breakouts',3,'What should follow marking a reaction zone?','Apa yang dilakukan setelah menandai zona reaksi?','Observe the breach, return, and later evidence','Amati penembusan, kembalinya harga, dan bukti setelahnya',jsonb_build_array('Observe the breach, return, and later evidence','Assume a guaranteed bounce','Ignore the timeframe','Treat one touch as proof'),jsonb_build_array('Amati penembusan, kembalinya harga, dan bukti setelahnya','Anggap pantulan dijamin','Abaikan timeframe','Anggap satu sentuhan sebagai bukti'),'A zone must be updated with new evidence.','Zona perlu diperbarui dengan bukti baru.'),
 ('decision-timeframe-comparison',1,'Why can a five-minute move look dramatic while a weekly chart looks ordinary?','Mengapa pergerakan lima menit tampak dramatis sementara grafik mingguan biasa?','Each timeframe aggregates the same activity into different detail','Setiap timeframe mengagregasi aktivitas yang sama dengan detail berbeda',jsonb_build_array('Each timeframe aggregates the same activity into different detail','The weekly chart deletes volatility','The five-minute chart guarantees a forecast','One chart must be wrong'),jsonb_build_array('Setiap timeframe mengagregasi aktivitas yang sama dengan detail berbeda','Grafik mingguan menghapus volatilitas','Grafik lima menit menjamin ramalan','Salah satu grafik pasti salah'),'A timeframe changes the observation lens, not historical events.','Timeframe mengubah lensa pengamatan, bukan peristiwa historis.'),
 ('decision-timeframe-comparison',2,'A longer timeframe removes market risk.','Timeframe lebih panjang menghapus risiko pasar.','False','Salah',jsonb_build_array('True','False','Only for large companies','Only after a breakout'),jsonb_build_array('Benar','Salah','Hanya untuk perusahaan besar','Hanya setelah breakout'),'A wider view adds context but cannot remove uncertainty.','Pandangan lebih luas menambah konteks tetapi tidak menghapus ketidakpastian.'),
 ('decision-timeframe-comparison',3,'What should be named before comparing two similar patterns?','Apa yang harus disebutkan sebelum membandingkan dua pola serupa?','The timeframe and surrounding context','Timeframe dan konteks sekitar',jsonb_build_array('The timeframe and surrounding context','Only the candle colour','The pattern name alone','A prediction that both agree'),jsonb_build_array('Timeframe dan konteks sekitar','Hanya warna candle','Nama pola saja','Prediksi bahwa keduanya sama'),'The same shape can carry different context in another window.','Bentuk sama dapat memiliki konteks berbeda pada jendela lain.'),
 ('decision-risk-reward',1,'A fictional idea shows Rp100,000 possible loss and Rp200,000 possible gain. What does 1:2 describe?','Ide fiktif menunjukkan kemungkinan rugi Rp100.000 dan untung Rp200.000. Apa yang dijelaskan 1:2?','Scenario magnitudes, not probability or guarantee','Besaran skenario, bukan probabilitas atau jaminan',jsonb_build_array('Scenario magnitudes, not probability or guarantee','Guaranteed profit','Chance of success','A required personal trade'),jsonb_build_array('Besaran skenario, bukan probabilitas atau jaminan','Keuntungan dijamin','Peluang berhasil','Transaksi pribadi wajib'),'Risk/reward compares magnitudes; it does not predict probability.','Risiko/imbal hasil membandingkan besaran; bukan memprediksi probabilitas.'),
 ('decision-risk-reward',2,'A favourable ratio can still lose money.','Rasio yang tampak baik tetap dapat menghasilkan kerugian.','True','Benar',jsonb_build_array('True','False','Only when volume is low','Only outside Indonesia'),jsonb_build_array('Benar','Salah','Hanya saat volume rendah','Hanya di luar Indonesia'),'The ratio does not make the possible loss disappear.','Rasio tidak membuat kemungkinan rugi menghilang.'),
 ('decision-risk-reward',3,'What should be checked before accepting a possible loss?','Apa yang perlu diperiksa sebelum menerima kemungkinan rugi?','Whether it fits essentials and the financial plan','Apakah sesuai dengan kebutuhan pokok dan rencana keuangan',jsonb_build_array('Whether it fits essentials and the financial plan','Whether the story sounds exciting','Whether a friend agrees','Whether a ratio looks impressive'),jsonb_build_array('Apakah sesuai dengan kebutuhan pokok dan rencana keuangan','Apakah ceritanya menarik','Apakah teman setuju','Apakah rasionya terlihat mengesankan'),'A ratio cannot override personal financial boundaries.','Rasio tidak boleh mengalahkan batas keuangan pribadi.'),
 ('decision-position-sizing',1,'Why can a smaller position protect a plan?','Mengapa posisi lebih kecil dapat melindungi rencana?','It limits exposure if the thesis is wrong','Membatasi eksposur jika tesis salah',jsonb_build_array('It limits exposure if the thesis is wrong','It guarantees the thesis','It removes the need for a buffer','It turns volatility into income'),jsonb_build_array('Membatasi eksposur jika tesis salah','Menjamin tesis benar','Menghapus kebutuhan penyangga','Mengubah volatilitas menjadi pendapatan'),'Size changes potential damage, not the truth of the thesis.','Ukuran mengubah potensi dampak, bukan kebenaran tesis.'),
 ('decision-position-sizing',2,'Money needed for rent, food, debt, or near-term goals is available risk capital.','Uang untuk sewa, makan, utang, atau tujuan dekat adalah modal risiko.','False','Salah',jsonb_build_array('True','False','Only after saving','Only with diversification'),jsonb_build_array('Benar','Salah','Hanya setelah menabung','Hanya dengan diversifikasi'),'Essentials and near-term goals need protection.','Kebutuhan pokok dan tujuan dekat perlu dilindungi.'),
 ('decision-position-sizing',3,'What should come before choosing exposure?','Apa yang dilakukan sebelum memilih eksposur?','Protect essentials and define tolerable loss','Lindungi kebutuhan pokok dan tentukan kerugian yang dapat ditanggung',jsonb_build_array('Protect essentials and define tolerable loss','Choose the largest position','Copy the loudest opinion','Ignore the time horizon'),jsonb_build_array('Lindungi kebutuhan pokok dan tentukan kerugian yang dapat ditanggung','Pilih posisi terbesar','Tiru opini paling keras','Abaikan horizon waktu'),'Protect the plan first, then define exposure.','Lindungi rencana lebih dulu, lalu tentukan eksposur.'),
 ('decision-bias-and-narratives',1,'What is a useful response to confirmation bias?','Apa respons berguna terhadap bias konfirmasi?','Write one observation that would weaken the belief','Tuliskan satu pengamatan yang dapat melemahkan keyakinan',jsonb_build_array('Write one observation that would weaken the belief','Collect only agreeing posts','Treat confidence as evidence','Ignore neutral sources'),jsonb_build_array('Tuliskan satu pengamatan yang dapat melemahkan keyakinan','Kumpulkan hanya unggahan yang setuju','Anggap keyakinan sebagai bukti','Abaikan sumber netral'),'A disconfirming condition makes a belief testable.','Kondisi penyangkal membuat keyakinan dapat diuji.'),
 ('decision-bias-and-narratives',2,'An official source automatically proves your interpretation is correct.','Sumber resmi otomatis membuktikan interpretasimu benar.','False','Salah',jsonb_build_array('True','False','Only for charts','Only for OJK sources'),jsonb_build_array('Benar','Salah','Hanya untuk grafik','Hanya untuk sumber OJK'),'A source provides evidence; interpretation still requires reasoning.','Sumber memberi bukti; interpretasi tetap membutuhkan penalaran.'),
 ('decision-bias-and-narratives',3,'What should happen before deciding from a market story?','Apa yang dilakukan sebelum memutuskan berdasarkan cerita pasar?','State the story, seek disconfirmation, and check neutral evidence','Sebutkan cerita, cari bukti penyangkal, dan periksa bukti netral',jsonb_build_array('State the story, seek disconfirmation, and check neutral evidence','Collect only confirming evidence','Decide from confidence','Skip source checking'),jsonb_build_array('Sebutkan cerita, cari bukti penyangkal, dan periksa bukti netral','Kumpulkan hanya bukti yang setuju','Putuskan dari keyakinan','Lewati pemeriksaan sumber'),'Make the narrative visible before testing it.','Buat narasinya terlihat sebelum mengujinya.'),
 ('decision-thesis-invalidation',1,'What makes an invalidation rule useful?','Apa yang membuat aturan pembatalan berguna?','It names observable evidence that triggers reassessment','Menyebutkan bukti yang dapat diamati untuk memicu penilaian ulang',jsonb_build_array('It names observable evidence that triggers reassessment','It guarantees profit','It changes after every move','It protects a story from challenge'),jsonb_build_array('Menyebutkan bukti yang dapat diamati untuk memicu penilaian ulang','Menjamin keuntungan','Berubah setiap pergerakan','Melindungi cerita dari tantangan'),'An invalidation rule creates a boundary for updating a thesis.','Aturan pembatalan membuat batas untuk memperbarui tesis.'),
 ('decision-thesis-invalidation',2,'Changing a thesis after new evidence appears can be disciplined decision-making.','Mengubah tesis setelah bukti baru muncul dapat menjadi keputusan disiplin.','True','Benar',jsonb_build_array('True','False','Only after a profit','Only when a chart is flat'),jsonb_build_array('Benar','Salah','Hanya setelah untung','Hanya saat grafik datar'),'A thesis is a working explanation that should respond to evidence.','Tesis adalah penjelasan kerja yang merespons bukti.'),
 ('decision-thesis-invalidation',3,'What should be written before the outcome is known?','Apa yang perlu ditulis sebelum hasil diketahui?','The thesis and the evidence that would weaken it','Tesis dan bukti yang akan melemahkannya',jsonb_build_array('The thesis and the evidence that would weaken it','A guaranteed future price','A story explaining every outcome','A promise of profit'),jsonb_build_array('Tesis dan bukti yang akan melemahkannya','Harga masa depan yang dijamin','Cerita untuk menjelaskan semua hasil','Janji keuntungan'),'Writing the boundary early reduces hindsight stories.','Menulis batas lebih awal mengurangi cerita hindsight.')
)
INSERT INTO public.content_variants (lesson_id,variant_type,body,body_id,difficulty,topic_tag,is_active)
SELECT l.id,'question',jsonb_build_object('type','multiple_choice','difficulty','advanced','question',q.en_question,'options',q.en_options,'answer',q.en_answer,'explanation',q.en_explanation),jsonb_build_object('type','multiple_choice','difficulty','advanced','question',q.id_question,'options',q.id_options,'answer',q.id_answer,'explanation',q.id_explanation),'advanced','visual_applied',TRUE
FROM q JOIN public.lessons l ON l.slug=q.slug AND l.is_published;

WITH r(slug,en_q,id_q,en_options,id_options,en_answer,id_answer,en_explanation,id_explanation) AS (VALUES
 ('decision-multicandle-context','Why is a sequence more useful than one candle?','Mengapa rangkaian lebih berguna daripada satu candle?',jsonb_build_array('It shows developing context while remaining uncertain'),jsonb_build_array('Menunjukkan konteks berkembang tetapi tetap tidak pasti'),'It shows developing context while remaining uncertain','Menunjukkan konteks berkembang tetapi tetap tidak pasti','More observations improve description, not certainty.','Lebih banyak pengamatan memperbaiki deskripsi, bukan kepastian.'),
 ('decision-volume-confirmation','What does unusual volume add?','Apa yang ditambahkan volume tidak biasa?',jsonb_build_array('A reason to investigate context'),jsonb_build_array('Alasan memeriksa konteks'),'A reason to investigate context','Alasan memeriksa konteks','Volume is a clue about past activity.','Volume adalah petunjuk aktivitas masa lalu.'),
 ('decision-zones-false-breakouts','What should a return inside a zone be treated as?','Bagaimana kembalinya harga ke dalam zona diperlakukan?',jsonb_build_array('Evidence to inspect, not a guaranteed reversal'),jsonb_build_array('Bukti untuk diperiksa, bukan pembalikan yang dijamin'),'Evidence to inspect, not a guaranteed reversal','Bukti untuk diperiksa, bukan pembalikan yang dijamin','A false breakout describes a past breach and return.','False breakout menggambarkan penembusan dan kembalinya harga.'),
 ('decision-timeframe-comparison','Why compare more than one timeframe?','Mengapa membandingkan lebih dari satu timeframe?',jsonb_build_array('Each lens exposes different detail and context'),jsonb_build_array('Setiap lensa menunjukkan detail dan konteks berbeda'),'Each lens exposes different detail and context','Setiap lensa menunjukkan detail dan konteks berbeda','Timeframes change aggregation, not historical facts.','Timeframe mengubah agregasi, bukan fakta historis.'),
 ('decision-risk-reward','What does a risk/reward ratio not tell you?','Apa yang tidak diberitahukan rasio risiko/imbal hasil?',jsonb_build_array('Whether either outcome will happen'),jsonb_build_array('Apakah salah satu hasil akan terjadi'),'Whether either outcome will happen','Apakah salah satu hasil akan terjadi','A ratio is a comparison, not a probability.','Rasio adalah perbandingan, bukan probabilitas.'),
 ('decision-position-sizing','What does position size change?','Apa yang diubah ukuran posisi?',jsonb_build_array('The amount exposed if the idea is wrong'),jsonb_build_array('Jumlah yang terekspos jika ide salah'),'The amount exposed if the idea is wrong','Jumlah yang terekspos jika ide salah','Size changes potential damage, not uncertainty.','Ukuran mengubah potensi dampak, bukan ketidakpastian.'),
 ('decision-bias-and-narratives','What is one way to test confirmation bias?','Apa salah satu cara menguji bias konfirmasi?',jsonb_build_array('Write evidence that could weaken the belief'),jsonb_build_array('Tuliskan bukti yang dapat melemahkan keyakinan'),'Write evidence that could weaken the belief','Tuliskan bukti yang dapat melemahkan keyakinan','A testable belief allows disconfirming evidence.','Keyakinan yang dapat diuji memberi ruang untuk bukti penyangkal.'),
 ('decision-thesis-invalidation','What does an invalidation rule do?','Apa fungsi aturan pembatalan?',jsonb_build_array('Defines evidence that triggers reassessment'),jsonb_build_array('Menentukan bukti yang memicu penilaian ulang'),'Defines evidence that triggers reassessment','Menentukan bukti yang memicu penilaian ulang','It is a reasoning boundary, not a prediction.','Ini batas penalaran, bukan prediksi.')
)
INSERT INTO public.lesson_recall_questions (lesson_id,question_en,question_id,options_en,options_id,correct_option,explanation_en,explanation_id,is_active)
SELECT l.id,r.en_q,r.id_q,r.en_options,r.id_options,r.en_answer,r.en_explanation,r.id_explanation,TRUE FROM r JOIN public.lessons l ON l.slug=r.slug AND l.is_published
ON CONFLICT (lesson_id) DO UPDATE SET question_en=EXCLUDED.question_en,question_id=EXCLUDED.question_id,options_en=EXCLUDED.options_en,options_id=EXCLUDED.options_id,correct_option=EXCLUDED.correct_option,explanation_en=EXCLUDED.explanation_en,explanation_id=EXCLUDED.explanation_id,is_active=TRUE,updated_at=NOW();

DO $$
DECLARE lessons_count INT; visuals_count INT; applied_count INT; recalls_count INT; sources_count INT;
BEGIN
 SELECT COUNT(*) INTO lessons_count FROM public.lessons l JOIN public.topics t ON t.id=l.topic_id WHERE t.chapter='Decision Analysis Lab' AND l.is_published;
 SELECT COUNT(*) INTO visuals_count FROM public.lesson_visual_blocks b JOIN public.lessons l ON l.id=b.lesson_id JOIN public.topics t ON t.id=l.topic_id WHERE t.chapter='Decision Analysis Lab' AND l.is_published AND b.is_published;
 SELECT COUNT(*) INTO applied_count FROM public.content_variants v JOIN public.lessons l ON l.id=v.lesson_id JOIN public.topics t ON t.id=l.topic_id WHERE t.chapter='Decision Analysis Lab' AND l.is_published AND v.topic_tag='visual_applied' AND v.is_active;
 SELECT COUNT(*) INTO recalls_count FROM public.lesson_recall_questions r JOIN public.lessons l ON l.id=r.lesson_id JOIN public.topics t ON t.id=l.topic_id WHERE t.chapter='Decision Analysis Lab' AND l.is_published AND r.is_active;
 SELECT COUNT(DISTINCT l.id) INTO sources_count FROM public.lesson_sources x JOIN public.lessons l ON l.id=x.lesson_id JOIN public.topics t ON t.id=l.topic_id JOIN public.sources s ON s.id=x.source_id WHERE t.chapter='Decision Analysis Lab' AND l.is_published AND x.is_primary AND s.source_tier=1 AND s.status='verified';
 IF lessons_count<>8 OR visuals_count<>8 OR applied_count<>48 OR recalls_count<>8 OR sources_count<>8 THEN RAISE EXCEPTION 'KO-440 coverage mismatch: %, %, %, %, %',lessons_count,visuals_count,applied_count,recalls_count,sources_count; END IF;
END $$;
COMMIT;
