-- Migration: KO-CURR-002 - Renumber curriculum and add debt-management lessons
-- Branch: web-koinaku

BEGIN;

-- Part A: Renumber curriculum
-- Step 1: Move existing main-track lessons to a temporary range to avoid UNIQUE conflicts.
UPDATE lessons
SET lesson_number = lesson_number + 10000
WHERE slug IN (
  'money-basics-101',
  'value-and-purchasing-power',
  'inflation-101',
  'income-vs-wealth',
  'needs-vs-wants-101',
  'assets-vs-liabilities',
  'understanding-risk',
  'time-value-of-money',
  'too-good-to-be-true',
  'check-ojk-license',
  'phishing-social-engineering',
  'mlm-pyramid-red-flags',
  'interest-101',
  'compound-interest-101',
  'bank-vs-investment',
  'risk-return-101',
  'diversification-101',
  'reksa-dana-basics',
  'what-is-a-stock',
  'idx-basics-101',
  'reading-a-stock-page',
  'portfolio-thinking',
  'taxes-on-returns',
  'macro-indicators',
  'budgeting-101',
  'behavioral-bias-intro',
  'emergency-fund-101',
  'pay-yourself-first',
  'spending-traps',
  'debt-traps',
  'goal-setting-101',
  'building-financial-plan'
);

-- Step 2: Renumber Foundation Zero micro-lessons to 101-112.
UPDATE lessons SET lesson_number = 101 WHERE slug = 'fz-what-is-money';
UPDATE lessons SET lesson_number = 102 WHERE slug = 'fz-inflation';
UPDATE lessons SET lesson_number = 103 WHERE slug = 'fz-interest';
UPDATE lessons SET lesson_number = 104 WHERE slug = 'fz-income-vs-wealth';
UPDATE lessons SET lesson_number = 105 WHERE slug = 'fz-assets-vs-liabilities';
UPDATE lessons SET lesson_number = 106 WHERE slug = 'fz-risk';
UPDATE lessons SET lesson_number = 107 WHERE slug = 'fz-return';
UPDATE lessons SET lesson_number = 108 WHERE slug = 'fz-saving-vs-investing';
UPDATE lessons SET lesson_number = 109 WHERE slug = 'fz-emergency-fund';
UPDATE lessons SET lesson_number = 110 WHERE slug = 'fz-needs-vs-wants';
UPDATE lessons SET lesson_number = 111 WHERE slug = 'fz-debt';
UPDATE lessons SET lesson_number = 112 WHERE slug = 'fz-scam-red-flags';

-- Step 3: Renumber main-track lessons to target 1-36 in chapter order.
UPDATE lessons SET lesson_number = 1 WHERE slug = 'money-basics-101';
UPDATE lessons SET lesson_number = 2 WHERE slug = 'value-and-purchasing-power';
UPDATE lessons SET lesson_number = 3 WHERE slug = 'inflation-101';
UPDATE lessons SET lesson_number = 4 WHERE slug = 'income-vs-wealth';
UPDATE lessons SET lesson_number = 5 WHERE slug = 'needs-vs-wants-101';
UPDATE lessons SET lesson_number = 6 WHERE slug = 'assets-vs-liabilities';
UPDATE lessons SET lesson_number = 7 WHERE slug = 'understanding-risk';
UPDATE lessons SET lesson_number = 8 WHERE slug = 'time-value-of-money';
UPDATE lessons SET lesson_number = 9 WHERE slug = 'too-good-to-be-true';
UPDATE lessons SET lesson_number = 10 WHERE slug = 'check-ojk-license';
UPDATE lessons SET lesson_number = 11 WHERE slug = 'phishing-social-engineering';
UPDATE lessons SET lesson_number = 12 WHERE slug = 'mlm-pyramid-red-flags';
UPDATE lessons SET lesson_number = 13 WHERE slug = 'interest-101';
UPDATE lessons SET lesson_number = 14 WHERE slug = 'compound-interest-101';
UPDATE lessons SET lesson_number = 15 WHERE slug = 'bank-vs-investment';
UPDATE lessons SET lesson_number = 16 WHERE slug = 'risk-return-101';
UPDATE lessons SET lesson_number = 17 WHERE slug = 'diversification-101';
UPDATE lessons SET lesson_number = 18 WHERE slug = 'reksa-dana-basics';
UPDATE lessons SET lesson_number = 19 WHERE slug = 'what-is-a-stock';
UPDATE lessons SET lesson_number = 20 WHERE slug = 'idx-basics-101';
UPDATE lessons SET lesson_number = 21 WHERE slug = 'reading-a-stock-page';
UPDATE lessons SET lesson_number = 22 WHERE slug = 'portfolio-thinking';
UPDATE lessons SET lesson_number = 23 WHERE slug = 'taxes-on-returns';
UPDATE lessons SET lesson_number = 24 WHERE slug = 'macro-indicators';
UPDATE lessons SET lesson_number = 25 WHERE slug = 'budgeting-101';
UPDATE lessons SET lesson_number = 26 WHERE slug = 'behavioral-bias-intro';
UPDATE lessons SET lesson_number = 27 WHERE slug = 'emergency-fund-101';
UPDATE lessons SET lesson_number = 28 WHERE slug = 'pay-yourself-first';
UPDATE lessons SET lesson_number = 29 WHERE slug = 'spending-traps';
UPDATE lessons SET lesson_number = 30 WHERE slug = 'debt-traps';
UPDATE lessons SET lesson_number = 35 WHERE slug = 'goal-setting-101';
UPDATE lessons SET lesson_number = 36 WHERE slug = 'building-financial-plan';

-- Part C: Ensure BI-010 source exists.
INSERT INTO sources (id, source_code, title, local_title, source_tier, source_type, organization, url, isbn, publication_year, language, status, localization_notes) VALUES
  (gen_random_uuid(), 'BI-010', 'Peraturan Bank Indonesia No.14/2/PBI/2012 tentang Penyelenggaraan Kegiatan Alat Pembayaran Dengan Menggunakan Kartu', 'PBI 14/2/PBI/2012 — Kartu Kredit', 1, 'regulation', 'BI', 'https://www.bi.go.id/id/publikasi/peraturan/Pages/pbi_140212.aspx', NULL, 2012, 'id', 'verified', 'Use to explain credit-card interest caps, minimum eligibility, and consumer protection in Indonesia')
ON CONFLICT (source_code) DO NOTHING;

-- Part B: Insert four new debt-management lessons.
INSERT INTO lessons (id, slug, title, title_id, topic_id, lesson_number, difficulty, xp_reward, estimated_minutes, summary, concept_body, indonesian_example, why_this_matters, common_mistake, ai_assist_context, review_status, reviewed_by, reviewed_at, is_published) VALUES
  (gen_random_uuid(), 'good-debt-vs-bad-debt', $$Good Debt vs Bad Debt$$, $$Utang Baik vs Utang Buruk$$, (SELECT id FROM topics WHERE slug = 'debt_management'), 31, 'beginner', 55, 6, $$Some debt helps you earn more or own assets that grow in value; other debt only buys things that lose value and create monthly stress.$$, $$Debt is not automatically good or bad — it depends on what the money produces. Good debt is borrowed money that is likely to increase your future income or net worth. Examples include a low-cost education loan that leads to a better job, a KUR (Kredit Usaha Rakyat) loan that starts a profitable small business, or a mortgage on a rental property that generates income. Bad debt is borrowed money spent on things that lose value quickly and do not produce income, such as gadgets, clothes, or vacations paid with high-interest PayLater or credit cards.

The same loan can be good or bad depending on the purpose and your ability to repay. A motorbike loan is good if it lets you work as an ojek online driver and earn more than the installments. It is bad if it is only for weekend fun and strains your budget. OJK's personal financial management pocket guide recommends borrowing only for productive needs and always having a clear repayment plan before signing any loan agreement.$$, $$Sari borrows Rp 5,000,000 for an online coding bootcamp. After finishing, she gets a junior developer job that pays Rp 7,000,000 per month. The loan was good debt because it increased her earning power. Her friend Rina uses PayLater to buy a Rp 1,200,000 hoodie. She misses the due date and the total grows to Rp 1,500,000 after fees and interest. The hoodie was bad debt because it lost value immediately and created extra cost.$$, $$Knowing the difference helps you say yes to debt that builds future income and no to debt that only feeds short-term wants.$$, $$Thinking all debt is bad, or thinking all debt is fine as long as you can make the minimum payment.$$, $$Help the user classify a real or fictional borrowing decision as good debt or bad debt using Indonesian examples. Ask about the purpose of the loan, the expected return, and the repayment plan. Avoid recommending specific lenders or loan products.$$, 'approved', 'koin-curriculum-agent', NOW(), TRUE),
  (gen_random_uuid(), 'why-pay-later-is-bad', $$Why "Pay Later" Is Bad$$, $$Mengapa "Bayar Nanti" Itu Buruk$$, (SELECT id FROM topics WHERE slug = 'debt_management'), 32, 'beginner', 55, 6, $$PayLater and buy-now-pay-later plans make spending feel free, but late fees, interest, and impulse buying can turn a small purchase into a stressful debt.$$, $$Buy-now-pay-later (BNPL), often called PayLater in Indonesian apps, lets you split a purchase into small installments. This feels affordable, but it hides the full cost and encourages buying things you do not need. If you miss a due date, late fees and interest can make the item far more expensive than the original price. Many users end up with several PayLater bills at once and struggle to track them all.

Even licensed PayLater providers are required to follow OJK rules, but the product itself is designed to make spending easy. The danger is not the app; it is the habit of spending money you have not earned. The safest approach is to use PayLater only for planned needs that already fit your budget, not for wants triggered by flash sales or influencer posts. If you cannot pay the full price today, saving first is usually cheaper and less stressful.$$, $$Bayu buys a Rp 900,000 gaming headset using PayLater in three installments of Rp 300,000. He forgets the second due date and is charged a Rp 150,000 late fee plus interest. The headset now costs Rp 1,150,000, and he still has to pay his phone bill and campus meals. The small installment felt safe, but one missed payment turned it into a budget problem.$$, $$PayLater trains you to spend money you do not have. One missed payment can start a cycle of fees and stress.$$, $$Using PayLater for wants because "it is only Rp 50,000 per month" without reading the late fee and interest terms.$$, $$Explain why PayLater feels easy but can become expensive. Use a specific Indonesian e-commerce or app example. Ask the user to name the full cost, including late fees, before accepting any BNPL offer.$$, 'approved', 'koin-curriculum-agent', NOW(), TRUE),
  (gen_random_uuid(), 'credit-card-good-or-bad', $$Credit Cards: Good or Bad?$$, $$Kartu Kredit: Baik atau Buruk?$$, (SELECT id FROM topics WHERE slug = 'debt_management'), 33, 'beginner', 60, 6, $$A credit card is a tool. It rewards disciplined users with convenience and credit history, and punishes those who only pay the minimum.$$, $$A credit card is not free money. It is a short-term loan from a bank. In Indonesia, Bank Indonesia regulates credit cards through PBI No.14/2/PBI/2012. The rules cover maximum interest rates, minimum age and income requirements, credit limits, and consumer protection. These rules exist because revolving credit can be expensive when misused.

A credit card can be good when you pay the full balance every month. You build a positive SLIK credit record, enjoy a short grace period before payment, and may receive cashback or rewards. It can also help in a real emergency, such as buying a flight home when your debit card is not working. But a credit card becomes bad when you treat the limit as extra income, buy wants you cannot afford, or pay only the minimum. The remaining balance is charged interest every month, and the debt can last for years.$$, $$Citra uses her BCA credit card only for monthly groceries and fuel, then pays the full bill automatically from her tabungan. She never pays interest and earns small cashback. Her older brother Doni uses his credit card to buy a new phone and only pays the minimum each month. The remaining balance grows with interest, and after six months he has paid more in interest than the phone is worth.$$, $$At your first job, a credit card can help or hurt your financial life depending on whether you treat it as delayed cash or extra income.$$, $$Treating the credit limit as extra money instead of a short-term loan that must be repaid in full.$$, $$Walk the user through the BI rules on credit cards and ask them to decide whether a fictional young worker should get a card. Discuss full-payment discipline, minimum-payment traps, and emergency-only use.$$, 'approved', 'koin-curriculum-agent', NOW(), TRUE),
  (gen_random_uuid(), 'how-to-pay-debt-responsibly', $$How to Pay Debt Responsibly$$, $$Cara Membayar Utang dengan Bertanggung Jawab$$, (SELECT id FROM topics WHERE slug = 'debt_management'), 34, 'beginner', 60, 6, $$A clear repayment plan protects your budget, your credit record, and your peace of mind.$$, $$The first step in paying debt responsibly is to stop adding new debt. Then list every debt you have: the lender, the remaining balance, the interest rate, the minimum payment, and the due date. This simple list removes the fear of the unknown and lets you choose a strategy.

Two popular strategies are the avalanche method and the snowball method. Avalanche means paying the minimum on every debt, then putting all extra money toward the debt with the highest interest rate. This saves the most money over time. Snowball means paying the smallest balance first to build motivation, then moving to the next smallest. Both methods work, but avalanche is usually cheaper mathematically.

Always pay at least the minimum on every debt to avoid late fees and a damaged SLIK record. If you cannot make a payment, contact the lender immediately. Licensed banks and OJK-supervised lenders often have restructuring or rescheduling options. Ignoring the problem makes it worse because interest and penalties keep growing.$$, $$Raka has three debts: an online loan (pinjol) of Rp 2,000,000 at 36% per year, a credit card balance of Rp 5,000,000 at 24% per year, and a loan from his brother of Rp 1,000,000 at 0% interest. He pays the minimums on the credit card and brother loan, then puts all extra money toward the pinjol. Once the pinjol is gone, he attacks the credit card next. This avalanche approach saves him the most interest.$$, $$A plan turns panic into progress and keeps you from falling into deeper debt or damaging your SLIK record.$$, $$Paying only the minimum on high-interest debt while spending on wants, which makes the debt last for years.$$, $$Help the user create a simple debt list and choose between avalanche and snowball methods using their own or a fictional Indonesian example. Emphasize calling the lender early if a payment is missed.$$, 'approved', 'koin-curriculum-agent', NOW(), TRUE)
ON CONFLICT (slug) DO NOTHING;

-- Part D: Insert approved lesson_reviews for the four new lessons.
INSERT INTO lesson_reviews (id, lesson_id, reviewer_name, reviewer_role, review_date, factual_accuracy_status, source_verification_status, indonesia_context_status, compliance_status, notes, approved_to_publish) VALUES
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'koin-curriculum-agent', 'curriculum-agent', CURRENT_DATE, 'pass', 'pass', 'pass', 'pass', $$Approved as part of KO-CURR-002 debt-management expansion. Tier-1 source OJK-014 cited.$$, TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'koin-curriculum-agent', 'curriculum-agent', CURRENT_DATE, 'pass', 'pass', 'pass', 'pass', $$Approved as part of KO-CURR-002 debt-management expansion. Tier-1 sources OJK-009 and OJK-012 cited.$$, TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'koin-curriculum-agent', 'curriculum-agent', CURRENT_DATE, 'pass', 'pass', 'pass', 'pass', $$Approved as part of KO-CURR-002 debt-management expansion. Tier-1 sources BI-010 and OJK-012 cited.$$, TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'koin-curriculum-agent', 'curriculum-agent', CURRENT_DATE, 'pass', 'pass', 'pass', 'pass', $$Approved as part of KO-CURR-002 debt-management expansion. Tier-1 sources OJK-014 and OJK-012 cited.$$, TRUE)
ON CONFLICT (lesson_id) DO NOTHING;

-- Part C (continued): Link new lessons to sources.
INSERT INTO lesson_sources (id, lesson_id, source_id, relevance_type, is_primary) VALUES
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), (SELECT id FROM sources WHERE source_code = 'OJK-014'), 'primary', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), (SELECT id FROM sources WHERE source_code = 'OJK-009'), 'primary', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), (SELECT id FROM sources WHERE source_code = 'OJK-012'), 'supporting', FALSE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), (SELECT id FROM sources WHERE source_code = 'BI-010'), 'primary', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), (SELECT id FROM sources WHERE source_code = 'OJK-012'), 'supporting', FALSE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), (SELECT id FROM sources WHERE source_code = 'OJK-014'), 'primary', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), (SELECT id FROM sources WHERE source_code = 'OJK-012'), 'supporting', FALSE)
ON CONFLICT (lesson_id, source_id) DO NOTHING;

-- Part E: Insert content variants for the four new lessons.
DELETE FROM content_variants WHERE lesson_id IN (SELECT id FROM lessons WHERE slug IN ('good-debt-vs-bad-debt', 'why-pay-later-is-bad', 'credit-card-good-or-bad', 'how-to-pay-debt-responsibly'));
INSERT INTO content_variants (id, lesson_id, variant_type, body, difficulty, is_active) VALUES
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'example', $${"text": "Andi mengambil KUR Rp 10 juta untuk membeli gerobak kopi. Setiap bulan ia untung Rp 3 juta dan cicilan hanya Rp 800 ribu. Untuk Andi, pinjaman itu adalah utang baik karena menghasilkan pendapatan. Temannya Eko mengambil kredit motor Rp 15 juta hanya untuk nongkrong akhir pekan. Cicilan Rp 800 ribu per bulan hanya menguras uangnya tanpa penghasilan tambahan. Itu utang buruk."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'example', $${"text": "Diana meminjam Rp 4 juta untuk kursus sertifikasi perawat. Setelah lulus, gajinya naik dari Rp 3,5 juta menjadi Rp 6 juta per bulan. Pinjamannya termasuk utang baik karena meningkatkan penghasilannya. Bayu memakai cicilan 12 bulan untuk beli headset gaming. Headset itu tidak menghasilkan uang dan nilainya turun cepat. Itu utang buruk."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'example', $${"text": "Seorang pengusaha kos meminjam dari bank untuk membeli properti kedua yang disewakan. Penyewa membayar cicilan dan menyisakan laba. Itu utang baik. Seorang mahasiswa memakai PayLater untuk membeli sepatu branded yang tidak benar-benar dibutuhkan. Itu utang buruk karena hanya menambah beban bulanan."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "multiple_choice", "question": "Apa yang membuat sebuah utang disebut utang baik?", "options": ["Digunakan untuk hal yang meningkatkan pendapatan atau kekayaan di masa depan", "Memiliki bunga nol persen", "Diberikan oleh teman tanpa jaminan", "Digunakan untuk membeli barang branded"], "answer": "Digunakan untuk hal yang meningkatkan pendapatan atau kekayaan di masa depan", "explanation": "Utang baik menghasilkan nilai lebih besar di masa depan, misalnya pendidikan atau usaha yang menguntungkan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "true_false", "question": "Semua utang pasti buruk dan harus dihindari.", "answer": false, "explanation": "Tidak semua utang buruk. Pinjaman untuk pendidikan atau usaha produktif bisa menjadi utang baik jika direncanakan dengan baik.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "multiple_choice", "question": "Manakah contoh utang baik?", "options": ["Pinjaman KUR untuk usaha kecil yang menghasilkan laba", "PayLater untuk membeli hoodie", "Cicilan 0% untuk liburan ke Bali", "Pinjol untuk beli smartphone terbaru"], "answer": "Pinjaman KUR untuk usaha kecil yang menghasilkan laba", "explanation": "KUR untuk usaha yang menguntungkan bisa meningkatkan pendapatan, jadi termasuk utang baik.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "fill_blank", "question": "Utang yang digunakan untuk membeli sesuatu yang _____ penghasilan atau kekayaan masa depanmu biasanya disebut utang baik.", "answer": "meningkatkan", "explanation": "Utang baik berkontribusi pada pertumbuhan keuangan jangka panjang, bukan hanya memuaskan keinginan sesaat.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "multiple_choice", "question": "Rina meminjam Rp 1 juta untuk liburan akhir pekan. Jenis utang apa ini?", "options": ["Utang buruk", "Utang baik", "Utang investasi", "Utang produktif"], "answer": "Utang buruk", "explanation": "Liburan tidak menghasilkan pendapatan atau kekayaan, dan nilainya tidak kembali setelah dibelanjakan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "true_false", "question": "Kredit motor selalu termasuk utang buruk.", "answer": false, "explanation": "Kredit motor bisa jadi utang baik jika digunakan untuk bekerja dan menghasilkan pendapatan yang melebihi cicilan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "multiple_choice", "question": "Mengapa utang pendidikan kadang disebut utang baik?", "options": ["Karena bisa meningkatkan keterampilan dan pendapatan di masa depan", "Karena tidak perlu dibayar", "Karena bunga selalu rendah", "Karena diberikan oleh pemerintah"], "answer": "Karena bisa meningkatkan keterampilan dan pendapatan di masa depan", "explanation": "Pendidikan yang tepat dapat meningkatkan daya saing dan penghasilan, sehingga pinjamannya bisa dibayar kembali dari pendapatan lebih besar.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "fill_blank", "question": "Utang buruk sering digunakan untuk membeli barang yang cepat _____ nilainya.", "answer": "turun", "explanation": "Barang seperti pakaian, gadget, atau liburan cepat kehilangan nilai setelah dibeli.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "multiple_choice", "question": "Sari meminjam uang untuk memulai toko online. Jika usahanya menghasilkan lebih banyak dari biaya pinjaman, utangnya termasuk...", "options": ["Utang baik", "Utang buruk", "Utang konsumtif", "Utang macet"], "answer": "Utang baik", "explanation": "Ketika pinjaman menghasilkan pendapatan yang melebihi biayanya, utang itu mendukung pertumbuhan keuangan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'good-debt-vs-bad-debt'), 'question', $${"type": "true_false", "question": "Utang baik tidak perlu dilunasi karena menghasilkan uang.", "answer": false, "explanation": "Semua utang harus dilunasi sesuai jadwal. Yang membedakan utang baik adalah tujuannya yang produktif, bukan kewajiban membayarnya.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'example', $${"text": "Dina membuka Shopee dan melihat flash sale skincare Rp 450.000 dengan tawaran PayLater. Ia tidak merencanakan pembelian itu. Sebelum checkout, ia mengecek anggaran keinginannya dan menyadari sudah habus untuk tiket konser. Ia menutup aplikasi dan menyimpan skincare itu untuk bulan depan jika masih ingin."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'example', $${"text": "Andi membeli sepatu Rp 500.000 pakai PayLater karena tertarik dengan promo cashback. Ia lupa membayar tagihan dan kena denda Rp 100.000. Akhirnya sepatu yang seharusnya Rp 500.000 malah jadi Rp 600.000, melebihi anggaran yang ia miliki."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'example', $${"text": "Rina punya 3 tagihan PayLater sekaligus: elektronik, pakaian, dan kosmetik. Total cicilan bulanan Rp 700.000. Ia kesulitan mengingat jatuh tempo masing-masing dan akhirnya telat bayar salah satu. Denda menumpuk dan membuatnya menyesal membeli barang yang tidak terlalu penting."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "multiple_choice", "question": "Mengapa PayLater berbahaya untuk keinginan?", "options": ["Menyembunyikan biaya penuh dan mendorong pembelian impulsif", "Selalu ilegal", "Tidak pernah ada bunga", "Hanya bisa dipakai untuk kebutuhan"], "answer": "Menyembunyikan biaya penuh dan mendorong pembelian impulsif", "explanation": "PayLater memecah pembayaran sehingga terasa murah, padahal total bisa membengkak dan sering memicu pembelian yang tidak direncanakan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "true_false", "question": "PayLater tidak ada biaya tambahan asal bayar tepat waktu.", "answer": false, "explanation": "Meski sering ada promo bunga 0%, beberapa PayLater tetap mengenakan biaya administrasi atau denda jika telat. Selalu baca ketentuan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "multiple_choice", "question": "Bayu membeli headset Rp 900.000 dan kena denda Rp 150.000 karena telat bayar. Berapa total yang harus ia bayar?", "options": ["Rp 1.050.000", "Rp 900.000", "Rp 150.000", "Rp 750.000"], "answer": "Rp 1.050.000", "explanation": "Total biaya adalah harga barang ditambah denda keterlambatan, belum termasuk bunga jika ada.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "fill_blank", "question": "PayLater membuat pengeluaran terasa mudah karena menyembunyikan _____ sebenarnya.", "answer": "biaya", "explanation": "Cicilan kecil membuat barang tampak murah, padahal total yang harus dibayar bisa lebih besar.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "multiple_choice", "question": "Apa yang sebaiknya dilakukan sebelum menggunakan PayLater?", "options": ["Memastikan pembelian sudah masuk anggaran dan membaca ketentuan biaya", "Langsung checkout karena promo hanya beberapa jam", "Meminjamkan akun ke teman", "Mengabaikan tanggal jatuh tempo"], "answer": "Memastikan pembelian sudah masuk anggaran dan membaca ketentuan biaya", "explanation": "PayLater aman hanya jika kamu sudah merencanakan pembayaran dan memahami denda serta bunga.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "true_false", "question": "Semua layanan PayLater di Indonesia ilegal.", "answer": false, "explanation": "Banyak PayLater berizin OJK, tetapi pengguna tetap harus waspada dan hanya memakai layanan yang terdaftar.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "multiple_choice", "question": "Jebakan PayLater yang paling umum adalah...", "options": ["Pembelian impulsif yang tidak masuk anggaran", "Diskon 100%", "Bunga negatif", "Tabungan otomatis"], "answer": "Pembelian impulsif yang tidak masuk anggaran", "explanation": "Kemudahan checkout membuat orang sering membeli barang yang sebenarnya tidak terlalu dibutuhkan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "multiple_choice", "question": "Apa yang terjadi jika kamu hanya membayar minimum pada PayLater?", "options": ["Sisa tagihan dikenakan bunga dan bisa bertambah besar", "Tagihan langsung lunas", "Tidak ada biaya tambahan", "Limit PayLater tertutup otomatis"], "answer": "Sisa tagihan dikenakan bunga dan bisa bertambah besar", "explanation": "Membayar minimum membiarkan bunga bekerja pada sisa tagihan, sehingga utang tumbuh.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "fill_blank", "question": "OJK mengingatkan agar memastikan aplikasi pinjaman atau PayLater sudah _____ sebelum digunakan.", "answer": "berizin", "explanation": "Memakai layanan berizin OJK lebih aman karena ada aturan perlindungan konsumen yang mengikat.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'why-pay-later-is-bad'), 'question', $${"type": "true_false", "question": "PayLater paling aman jika digunakan untuk kebutuhan terencana yang sesuai anggaran.", "answer": true, "explanation": "PayLater sebaiknya menjadi alat pembayaran yang sudah direncanakan, bukan pemicu pembelian impulsif.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'example', $${"text": "Rina kehilangan dompet saat mudik dan kartu debitnya diblokir. Ia memakai kartu kredit untuk membeli tiket pesawat pulang. Begitu tiba di rumah, ia langsung membayar tagihan penuh dari tabungan. Kartu kredit itu membantu dalam keadaan darurat karena ia punya rencana pelunasan."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'example', $${"text": "Doni membeli laptop Rp 10 juta pakai kartu kredit dan memilih bayar minimum Rp 500 ribu per bulan. Bunga 2% per bulan mengenai sisa tagihan. Setelah setahun, ia sudah membayar Rp 6 juta tetapi masih punya utang sekitar Rp 8 juta karena bunga terus menumpuk."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'example', $${"text": "Setiap gajian, Andi mengatur autodebet penuh untuk tagihan kartu kreditnya. Ia memakai kartu hanya untuk belanja bulanan dan mendapat cashback Rp 100 ribu per bulan. Karena tidak pernah membayar bunga, kartu kredit justru menghemat pengeluarannya."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "multiple_choice", "question": "Kapan kartu kredit disebut baik?", "options": ["Jika tagihan penuh dibayar setiap bulan dan digunakan sesuai anggaran", "Jika limitnya besar", "Jika hanya membayar minimum", "Jika digunakan untuk membeli barang branded"], "answer": "Jika tagihan penuh dibayar setiap bulan dan digunakan sesuai anggaran", "explanation": "Kartu kredit menjadi alat bantu keuangan jika digunakan dengan disiplin dan tidak menimbulkan bunga.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "true_false", "question": "Limit kartu kredit adalah penghasilan tambahan yang bisa dibelanjakan bebas.", "answer": false, "explanation": "Limit kartu kredit adalah pinjaman dari bank yang harus dilunasi, bukan penghasilan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "multiple_choice", "question": "Apa yang diatur Bank Indonesia terkait kartu kredit?", "options": ["Bunga maksimum, usia minimum, dan perlindungan konsumen", "Harga barang yang boleh dibeli", "Jumlah reward cashback", "Nama bank yang boleh menerbitkan kartu"], "answer": "Bunga maksimum, usia minimum, dan perlindungan konsumen", "explanation": "PBI 14/2/2012 mengatur suku bunga, persyaratan pemegang, plafon, dan perlindungan konsumen kartu kredit.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "multiple_choice", "question": "Apa yang terjadi jika Doni hanya membayar minimum tagihan kartu kreditnya?", "options": ["Sisa tagihan dikenakan bunga dan utang bertambah", "Tagihan langsung lunas", "Ia mendapat reward tambahan", "Bank menghapuskan bunganya"], "answer": "Sisa tagihan dikenakan bunga dan utang bertambah", "explanation": "Pembayaran minimum membiarkan bunga menggerus sisa tagihan, sehingga utang tumbuh dari bulan ke bulan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "fill_blank", "question": "Untuk menghindari bunga kartu kredit, bayar tagihan _____ setiap bulan.", "answer": "penuh", "explanation": "Membayar tagihan penuh sebelum jatuh tempo menghindari bunga bergulir.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "true_false", "question": "Kartu kredit selalu mengenakan bunga sejak hari pembelian.", "answer": false, "explanation": "Jika tagihan dibayar penuh sebelum jatuh tempo, pemegang kartu biasanya tidak dikenakan bunga selama masa tenggang.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "multiple_choice", "question": "Kebiasaan mana yang membangun rekam kredit bagus?", "options": ["Membayar tagihan penuh dan tepat waktu", "Membayar minimum setiap bulan", "Melewati jatuh tempo sesekali", "Memakai seluruh limit setiap bulan"], "answer": "Membayar tagihan penuh dan tepat waktu", "explanation": "Pembayaran penuh dan tepat waktu tercatat di SLIK sebagai riwayat kredit positif.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "multiple_choice", "question": "Penggunaan kartu kredit yang aman untuk pekerja pertama adalah...", "options": ["Untuk kebutuhan terencana yang bisa dilunasi penuh", "Untuk membeli ponsel baru meski tabungan kosong", "Untuk meminjam uang kepada teman", "Untuk menarik tunai sebanyak-banyaknya"], "answer": "Untuk kebutuhan terencana yang bisa dilunasi penuh", "explanation": "Kartu kredit aman jika kamu sudah punya uang untuk melunasinya dan menggunakannya untuk kebutuhan, bukan keinginan impulsif.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "fill_blank", "question": "Bank Indonesia menetapkan aturan suku bunga kartu kredit untuk melindungi _____.", "answer": "konsumen", "explanation": "Regulasi BI bertujuan mencegah pemegang kartu terjebak bunga yang terlalu tinggi dan tidak transparan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'credit-card-good-or-bad'), 'question', $${"type": "true_false", "question": "Menggunakan kartu kredit untuk keadaan darurat selalu buruk.", "answer": false, "explanation": "Kartu kredit bisa menjadi solusi darurat yang berguna jika kamu punya rencana untuk membayar penuh segera setelahnya.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'example', $${"text": "Sari punya utang Rp 500 ribu ke teman, Rp 2 juta ke pinjol, dan Rp 3 juta ke kartu kredit. Ia memilih metode snowball: melunasi utang teman terlebih dahulu untuk merasa lega, lalu beralih ke pinjol. Motivasi dari kemenangan kecil membantunya tetap disiplin."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'example', $${"text": "Bayu kehilangan pekerjaan dan tidak bisa membayar cicilan KPR. Ia segera menghubungi bank untuk menjelaskan situasinya. Bank menawarkan opsi penangguhan cicilan selama tiga bulan. Karena ia tidak mengabaikan masalah, rekam kreditnya tetap terjaga dan ia punya waktu mencari pekerjaan baru."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'example', $${"text": "Dina menulis semua utangnya di buku: total, bunga, minimum, dan jatuh tempo. Ia menyadari pinjolnya punya bunga tertinggi. Setiap bulan ia membayar minimum dua utang lainnya dan menyisihkan Rp 800 ribu ekstra untuk pinjol. Dalam tiga bulan pinjolnya lunas."}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "multiple_choice", "question": "Langkah pertama membayar utang dengan bertanggung jawab adalah...", "options": ["Berhenti menambah utang baru dan membuat daftar semua utang", "Meminjam lagi untuk melunasi utang lama", "Berhenti membayar semua cicilan", "Membeli barang kebutuhan pakai kartu kredit"], "answer": "Berhenti menambah utang baru dan membuat daftar semua utang", "explanation": "Daftar utang memberikan gambaran jelas dan membantumu memilih strategi pelunasan.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "multiple_choice", "question": "Metode avalanche berarti...", "options": ["Fokus melunasi utang dengan bunga tertinggi terlebih dahulu", "Melunasi utang terkecil terlebih dahulu", "Membayar semua utang sekaligus", "Mengabaikan utang berbunga rendah"], "answer": "Fokus melunasi utang dengan bunga tertinggi terlebih dahulu", "explanation": "Avalanche menghemat bunga paling banyak karena utang paling mahal diselesaikan lebih dulu.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "true_false", "question": "Kamu boleh mengabaikan utang kecil dan fokus hanya pada utang terbesar.", "answer": false, "explanation": "Utang kecil yang telat bayar tetap bisa kena denda dan merusak rekam kredit. Bayar minimum semua utang terlebih dahulu.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "multiple_choice", "question": "Mengapa harus membayar minimum pada semua utang sebelum fokus pada satu utang?", "options": ["Untuk menghindari denda dan kerusakan rekam kredit", "Karena bank menghapus bunga jika kita membayar minimum", "Karena itu membuat utang lebih cepat lunas", "Karena tidak ada cara lain"], "answer": "Untuk menghindari denda dan kerusakan rekam kredit", "explanation": "Pembayaran minimum menjaga agar tidak ada keterlambatan yang merusak SLIK dan menambah biaya.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "fill_blank", "question": "Metode _____ menargetkan utang dengan bunga tertinggi terlebih dahulu.", "answer": "avalanche", "explanation": "Avalanche mengutamakan pelunasan utang berbunga tinggi untuk menghemat biaya bunga total.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "multiple_choice", "question": "Apa yang sebaiknya dilakukan jika kamu tidak bisa membayar cicilan?", "options": ["Segera hubungi pemberi pinjaman untuk mencari solusi", "Menunggu debt collector datang", "Berhenti membayar dan berharap utang hilang", "Meminjam dari pinjol lain untuk menutupi"], "answer": "Segera hubungi pemberi pinjaman untuk mencari solusi", "explanation": "Pemberi pinjaman berizin sering bisa menawarkan restrukturisasi atau penjadwalan ulang jika dihubungi sejak dini.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "true_false", "question": "Membayar hanya minimum pada utang berbunga tinggi adalah cara tercepat bebas utang.", "answer": false, "explanation": "Pembayaran minimum membiarkan bunga terus bertambah, sehingga utang berlangsung lebih lama dan lebih mahal.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "multiple_choice", "question": "Utang mana yang harus Raka lunasi pertama: pinjol bunga 36% per tahun atau utang kakak tanpa bunga?", "options": ["Pinjol bunga 36%", "Utang kakak", "Keduanya sekaligus", "Tergantung siapa yang menagih lebih keras"], "answer": "Pinjol bunga 36%", "explanation": "Utang dengan bunga tertinggi merusak keuangan paling cepat, jadi didahulukan dalam metode avalanche.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "fill_blank", "question": "Membuat _____ tertulis membantu mengubah panik utang menjadi kemajuan yang terukur.", "answer": "rencana", "explanation": "Rencana pelunasan memberikan arah, tenggat waktu, dan motivasi saat mengelola banyak utang.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE),
  (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'how-to-pay-debt-responsibly'), 'question', $${"type": "multiple_choice", "question": "Apa yang melindungi rekam kredit SLIK saat membayar utang?", "options": ["Membayar minimum tepat waktu dan tidak mengabaikan kewajiban", "Meminjam dari banyak sumber", "Membayar hanya utang terbesar", "Menutup semua rekening bank"], "answer": "Membayar minimum tepat waktu dan tidak mengabaikan kewajiban", "explanation": "Keteraturan pembayaran dan komunikasi dini dengan pemberi pinjaman menjaga rekam kredit tetap baik.", "difficulty": "beginner"}$$::jsonb, 'beginner', TRUE)
;

COMMIT;