-- KO-225 group 4 lesson translation batch 2

update public.lessons set summary_id = $text$Beberapa hutang membantu Anda memperoleh lebih banyak atau memiliki aset yang nilainya meningkat; hutang lainnya hanya membeli barang-barang yang kehilangan nilainya dan menimbulkan stres bulanan.$text$, concept_body_id = $text$Hutang tidak secara otomatis baik atau buruk – hal ini bergantung pada apa yang dihasilkan oleh uang tersebut. Hutang baik adalah uang pinjaman yang kemungkinan besar akan meningkatkan pendapatan atau kekayaan bersih Anda di masa depan. Contohnya termasuk pinjaman pendidikan berbiaya rendah yang menghasilkan pekerjaan yang lebih baik, pinjaman KUR (Kredit Usaha Rakyat) yang memulai usaha kecil yang menguntungkan, atau hipotek atas properti sewaan yang menghasilkan pendapatan. Hutang macet adalah uang pinjaman yang dibelanjakan untuk barang-barang yang cepat kehilangan nilainya dan tidak menghasilkan pendapatan, seperti gadget, pakaian, atau liburan yang dibayar dengan PayLater atau kartu kredit berbunga tinggi.

Pinjaman yang sama bisa baik atau buruk tergantung pada tujuan dan kemampuan Anda membayarnya kembali. Pinjaman sepeda motor bagus jika memungkinkan Anda bekerja sebagai driver ojek online dan menghasilkan lebih dari cicilan. Sayang sekali jika hanya untuk bersenang-senang di akhir pekan dan membebani anggaran Anda. Panduan saku pengelolaan keuangan pribadi OJK merekomendasikan peminjaman hanya untuk kebutuhan produktif dan selalu memiliki rencana pembayaran yang jelas sebelum menandatangani perjanjian pinjaman apa pun.$text$, why_this_matters_id = $text$Mengetahui perbedaannya membantu Anda mengatakan ya terhadap utang yang menghasilkan pendapatan masa depan dan tidak terhadap utang yang hanya memenuhi kebutuhan jangka pendek.$text$, common_mistake_id = $text$Menganggap semua utang itu buruk, atau menganggap semua utang baik-baik saja selama Anda bisa melakukan pembayaran minimum.$text$ where id = '921580a5-9e97-4c4d-b80f-191f238ca9b0';
update public.lessons set summary_id = $text$Jika Anda memutuskan untuk membeli kripto, gunakan bursa yang terdaftar di Bappebti, hindari orang asing yang melakukan P2P, lindungi dompet Anda, dan ingatlah bahwa pajak mungkin berlaku.$text$, concept_body_id = $text$Cara teraman untuk membeli kripto di Indonesia adalah melalui bursa yang terdaftar di Bappebti. Platform ini harus mengikuti aturan kenali pelanggan Anda (KYC), menyimpan catatan, dan memisahkan aset pelanggan dari dana perusahaan. Platform ternama Indonesia yang sudah menyatakan terdaftar di Bappebti antara lain Tokocrypto, Indodax, Pintu, dan Reku, namun sebaiknya selalu cek daftar terbaru di website Bappebti sebelum menyetor uang.

Hindari transaksi peer-to-peer (P2P) dengan orang asing di WhatsApp, Telegram, atau Instagram. Harga yang lebih rendah tidak sebanding dengan risiko penipuan. Setelah uang dikirim ke rekening pribadi, hampir tidak mungkin untuk dipulihkan. Untuk penyimpanan, bursa menyimpan kripto dalam “dompet panas” online, yang nyaman tetapi masih menjadi target peretas. "Dompet dingin" adalah perangkat fisik yang menyimpan kripto secara offline dan lebih sulit untuk diretas, namun kehilangan perangkat atau frase pemulihan berarti kehilangan akses selamanya.

Terakhir, kripto tidak bebas pajak. Di Indonesia, keuntungan perdagangan dan pendapatan terkait kripto dapat dikenakan pajak penghasilan (PPh) dan pajak pertambahan nilai (PPN) tergantung pada jenis transaksinya. Catat setiap pembelian, penjualan, dan transfer. Peraturan perpajakan dapat berubah, jadi periksalah panduan resmi Direktorat Jenderal Pajak untuk mengetahui peraturan terbaru.$text$, why_this_matters_id = $text$Menggunakan saluran terdaftar dan menyimpan catatan melindungi Anda dari penipuan, peretasan, dan masalah pajak yang tidak terduga.$text$, common_mistake_id = $text$Mengirim uang langsung ke penjual di WhatsApp atau Instagram untuk mendapatkan "harga lebih baik", lalu kalah karena penipuan.$text$ where id = '674331a1-1867-4346-bc17-62f2d6aab62b';
update public.lessons set summary_id = $text$Rencana pembayaran yang jelas melindungi anggaran Anda, catatan kredit Anda, dan ketenangan pikiran Anda.$text$, concept_body_id = $text$Langkah pertama dalam membayar utang secara bertanggung jawab adalah berhenti menambah utang baru. Kemudian daftarkan setiap hutang yang Anda miliki: pemberi pinjaman, sisa saldo, tingkat bunga, pembayaran minimum, dan tanggal jatuh tempo. Daftar sederhana ini menghilangkan rasa takut akan hal yang tidak diketahui dan memungkinkan Anda memilih strategi.

Dua strategi yang populer adalah metode longsoran salju dan metode bola salju. Longsoran berarti membayar minimum setiap utang, lalu memasukkan semua uang ekstra ke utang dengan tingkat bunga tertinggi. Ini menghemat uang paling banyak dari waktu ke waktu. Snowball berarti membayar saldo terkecil terlebih dahulu untuk membangun motivasi, kemudian melanjutkan ke saldo terkecil berikutnya. Kedua metode tersebut berhasil, tetapi longsoran salju biasanya lebih murah secara matematis.

Selalu membayar minimal minimum pada setiap hutang untuk menghindari denda keterlambatan dan rusaknya catatan SLIK. Jika Anda tidak dapat melakukan pembayaran, segera hubungi pemberi pinjaman. Bank yang memiliki izin dan pemberi pinjaman yang diawasi OJK sering kali memiliki opsi restrukturisasi atau penjadwalan ulang. Mengabaikan masalah ini akan memperburuk keadaan karena bunga dan denda terus bertambah.$text$, why_this_matters_id = $text$Sebuah rencana mengubah kepanikan menjadi kemajuan dan mencegah Anda terjerumus ke dalam hutang yang lebih dalam atau merusak catatan SLIK Anda.$text$, common_mistake_id = $text$Hanya membayar utang berbunga tinggi dalam jumlah minimum sambil membelanjakan kebutuhannya, yang membuat utang tersebut bertahan bertahun-tahun.$text$ where id = 'c2766d98-cb4a-4233-b919-3bff435cd80f';
update public.lessons set summary_id = $text$Pendapatan adalah uang yang masuk; kekayaan adalah apa yang Anda simpan dan kembangkan seiring waktu.$text$, concept_body_id = $text$Pendapatan adalah aliran uang yang Anda terima, seperti gaji, tunjangan, atau pembayaran lepas. Kekayaan adalah persediaan uang dan barang berharga yang sudah Anda miliki, dikurangi utang Anda. Seseorang dapat memperoleh penghasilan yang tinggi namun memiliki kekayaan yang rendah jika ia membelanjakan hampir semuanya. Orang lain bisa berpenghasilan lebih sedikit namun memiliki lebih banyak kekayaan jika mereka menabung dan berinvestasi secara konsisten.

Pendapatan mengukur kecepatan; kekayaan mengukur besarnya simpanan keuangan Anda. Kesehatan finansial jangka panjang lebih bergantung pada apa yang Anda simpan dibandingkan penghasilan Anda. Inilah sebabnya mengapa penganggaran, pengendalian utang, dan pembentukan kebiasaan menabung penting di setiap tingkat pendapatan. Anda dapat menganggap pendapatan sebagai air yang mengalir ke dalam ember dan kekayaan sebagai air yang sudah ada di dalamnya. Jika ember berlubang, aliran deras tidak akan mengisinya. Memperbaiki lubang, menabung lebih banyak, dan menghindari utang berbunga tinggi adalah hal-hal yang membangun kekayaan seiring berjalannya waktu. Kekayaan juga mencakup barang-barang yang bisa dijual, seperti sepeda motor atau keterampilan yang berharga, dikurangi hutang apa pun yang menyertainya. Inilah sebabnya mengapa dua orang dengan gaji yang sama bisa mendapatkan posisi keuangan yang sangat berbeda. Kesenjangan ini berasal dari pilihan, bukan hanya pendapatan.$text$, why_this_matters_id = $text$Pada usia 18 tahun, penghasilan Anda mungkin kecil, namun kebiasaan membangun kekayaan Anda bisa dimulai sekarang. Kekayaan dibangun oleh apa yang tidak Anda belanjakan.$text$, common_mistake_id = $text$Menilai kesuksesan finansial hanya dari pendapatan bulanan dan mengabaikan tabungan, hutang, dan kebiasaan belanja.$text$ where id = '1be1d991-71c2-4d37-a6db-6658ec89367a';
update public.lessons set summary_id = $text$Bunga adalah biaya meminjam uang atau imbalan karena menyimpannya.$text$, concept_body_id = $text$Bunga adalah uang tambahan yang Anda bayarkan saat meminjam, atau uang tambahan yang Anda terima saat Anda menabung atau meminjamkan. Ketika Anda menyimpan uang di bank, bank memberi Anda bunga karena bank dapat menggunakan uang Anda untuk memberikan pinjaman. Ketika Anda meminjam, Anda membayar bunga karena pemberi pinjaman tidak lagi menggunakan uang itu.

Bunga sederhana dihitung hanya berdasarkan jumlah awal. Misalnya, bunga tahunan 4% pada Rp 1.000.000 menghasilkan Rp 40.000 dalam satu tahun. Tingkat suku bunga penting karena mempengaruhi seberapa cepat pertumbuhan utang dan seberapa cepat pertumbuhan tabungan. Selalu periksa apakah tarifnya per tahun, per bulan, atau per hari sebelum membandingkan penawaran. Tarif bulanan yang terlihat kecil bisa menjadi sangat besar jika diubah menjadi tarif tahunan. Bunga majemuk atas utang sangat berbahaya karena jumlah utang Anda dapat bertambah meskipun Anda berhenti meminjam. Inilah sebabnya mengapa pinjaman berbunga tinggi bisa lepas kendali. Memahami bunga dari kedua sisi, sebagai penabung dan peminjam, membantu Anda menggunakannya dengan bijak dan menghindari jebakan.$text$, why_this_matters_id = $text$Bunga mempengaruhi kedua sisi uang Anda: apa yang Anda peroleh dari tabungan dan apa yang Anda bayarkan dari hutang. Memahaminya membantu Anda membandingkan produk dengan jujur.$text$, common_mistake_id = $text$Mengabaikan tingkat bunga tahunan atau bulanan, yang membuat pinjaman terlihat lebih murah dari yang sebenarnya.$text$ where id = 'a3dfa5b3-e967-439f-bf9a-a07d36d1f951';
update public.lessons set summary_id = $text$Memenuhi kebutuhan terlebih dahulu membuat keinginan menjadi lebih menyenangkan dan mengurangi stres.$text$, concept_body_id = $text$Kebutuhan adalah sesuatu yang harus Anda miliki untuk hidup, belajar, atau bekerja dengan aman. Contohnya termasuk makanan, tempat tinggal, transportasi, dan pulsa telepon dasar. Keinginan adalah sesuatu yang ingin Anda miliki tetapi Anda dapat hidup tanpanya, seperti pakaian baru, tiket konser, atau langganan streaming premium.

Batas antara kebutuhan dan keinginan tidak selalu jelas. Misalnya, ponsel basic adalah kebutuhan untuk kelas online, namun ponsel andalan terbaru adalah sebuah kebutuhan. Tujuannya bukan untuk menghilangkan keinginan. Tujuannya adalah untuk memenuhi kebutuhan terlebih dahulu, selanjutnya menabung, dan kemudian membelanjakan kebutuhan tanpa rasa bersalah atau hutang. Banyak orang yang merasa stres karena membeli kebutuhan terlebih dahulu, baru kemudian kesulitan membayar kebutuhannya. Membalik urutan akan menciptakan ruang bernapas dan membuat belanja lebih menyenangkan karena Anda tahu hal-hal penting sudah tercakup. Budaya dan media sosial sering kali mengaburkan batas ini dengan mengubah keinginan menjadi kebutuhan yang dirasakan. Telepon biasa menjadi sebuah kebutuhan ketika kelas berpindah secara online, namun warna atau merek baru tetap menjadi sebuah keinginan. Belajar memisahkan keduanya memberi Anda kendali atas uang Anda alih-alih membiarkan pengiklan memutuskannya untuk Anda.$text$, why_this_matters_id = $text$Mempelajari pembagian ini sejak dini membantu Anda menghindari kehabisan uang sebelum bulan berakhir dan mencegah hutang impulsif.$text$, common_mistake_id = $text$Menyebut setiap keinginan sebagai kebutuhan, lalu bertanya-tanya mengapa tidak ada uang tersisa untuk menabung atau keadaan darurat.$text$ where id = 'c08723e0-8b2f-4c86-b24a-3fbc90d78b8f';

