-- KO-225 group 5 exact duplicate translation batch 5

update public.content_variants set body = $json${"text":"Bank Indonesia targets inflation of around 2.5% plus or minus 1%. If inflation is 4% per year and our savings only have 2% interest, the real value of our money decreases."}$json$::jsonb where id = '342f25f7-d4b8-4080-8b81-7202aec2f5db';
update public.content_variants set body = $json${"text":"An artist gets an honorarium of IDR 100 million per job, but it's all spent on a luxurious lifestyle. His friend's honorary teacher earns IDR 3 million/month, but regularly saves and has IDR 20 million. Wealth is seen from what is left, not what comes in."}$json$::jsonb where id = '34c609f3-6b9d-4e19-a106-8dc5bf878a4c';
update public.content_variants set body = $json${"text":"A spending trap is a situation that makes us buy more than we planned or needed. For example, flash sales, influencer hype, and small daily purchases that feel cheap but add up."}$json$::jsonb where id = '3568f99c-9f97-4aae-b4e0-9c4ddc585671';
update public.content_variants set body = $json${"text":"A bowl of chicken noodles in Jakarta costs IDR 18,000, but in Rina's hometown it is only IDR 12,000. Rina's IDR 50,000 in Jakarta is enough for 2 bowls plus leftovers, in the village it's enough for 4 bowls. The purchasing power of money is different in two places."}$json$::jsonb where id = '357e7cb3-509d-498c-85af-b896fe444fd2';
update public.content_variants set body = $json${"text":"Good financial goals are SMART: Specific, Measurable, Achievable, Relevant, Time-bound. Vagues like 'saving more' are tricked into action."}$json$::jsonb where id = '37fb3d76-b5d2-401f-b4d7-a74ccb98db21';
update public.content_variants set body = $json${"text":"Emergency funds should be kept in a safe and liquid place, such as separate savings or short-term deposits, so they can be withdrawn quickly when needed."}$json$::jsonb where id = '39f1c2c0-9efa-4765-b31b-7bfe9388ec63';
update public.content_variants set body = $json${"text":"Kartika understands that diversification does not mean buying 20 shares at once. He chose 5 stocks from different sectors plus money market mutual funds. The quality of the spread is more important than the number of shares.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = '3afce518-9681-47cf-90e9-d0cb09027e76';
update public.content_variants set body = $json${"text":"Choose a bank for money that will be used immediately. Choose investments for money that can be allowed to grow over a long period of time."}$json$::jsonb where id = '3b1292d2-16da-4603-a2b9-12afb8a81b0a';
update public.content_variants set body = $json${"text":"Budi works as an online motorcycle taxi driver with an income that changes every month. Because his income is not fixed, he chose an emergency fund target of 6 months of expenses. Budi saves it in a money market mutual fund which can be cashed out in 2-3 working days.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = '3b16a7b1-202f-42b6-bb13-6cca8c93d7b1';
update public.content_variants set body = $json${"text":"Bimo heard that ABC shares rose 50% in a month. He bought without research. It turned out that the increase was just short speculation and the price fell 30%. Bimo learned that following trends without understanding is a big risk.","source_ids":["eca56a9e-df9b-432f-b360-c1ab6450a2ae"]}$json$::jsonb where id = '3b853258-889d-4033-9941-21c9dad21855';

