-- KO-225 group 5 exact duplicate translation batch 1

update public.content_variants set body = $json${"text":"Save emergency funds in a safe place that is easy to disburse, for example separate savings at a bank guaranteed by LPS, short-term deposits, or money market mutual funds. Avoid stocks, crypto, or other instruments whose prices can fall sharply, because during an emergency you need a stable value."}$json$::jsonb where id = '00520940-8cba-4a03-9b68-3e5ea52d44a2';
update public.content_variants set body = $json${"text":"Dividing big goals into monthly targets makes them less overwhelming. If targets are achieved, we can celebrate small progress."}$json$::jsonb where id = '018946ee-44fa-45ab-8867-093a7bd5aa5f';
update public.content_variants set body = $json${"text":"An online motorcycle taxi driver bought BBCA, BBRI, TLKM and UNVR shares. He didn't buy just one share even though his friend said \"you'll definitely make a profit.\" The choices spread across the banking, telecommunications and consumer sectors.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = '0306eb40-1b91-4df0-80b4-3ca263ca3eb7';
update public.content_variants set body = $json${"text":"A young investor with the goal of retiring in the next 30 years can tolerate market fluctuations. An investor who needs money for a down payment on a house in the next 2 years should choose a more stable instrument.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = '06a42cc3-7cd8-4acb-be04-ade4380541af';
update public.content_variants set body = $json${"text":"Bank Indonesia has set an inflation target of 2.5% ± 1% in 2025. If inflation is too high, prices of goods rise quickly and people find it difficult to plan spending. If it is too low, the economy could slow down.","source_ids":["097b62c4-9aae-4933-a870-ac74a526b8f1"]}$json$::jsonb where id = '092e3f71-0440-4583-9b13-6b4fc1a42b78';
update public.content_variants set body = $json${"text":"Dina has a credit card with interest of 2.5% per month. He only paid the minimum payment, so that the remaining debt continued to bear interest. A Rp. 5 million bill that is not paid in full can grow to Rp. 6.5 million in a few months."}$json$::jsonb where id = '09c3cf85-3540-443c-a2b2-098582d21cb5';
update public.content_variants set body = $json${"text":"Sari was invited to the skincare business. He had to buy a package of IDR 3,000,000 and recruit two friends. The main profit comes from recruit registration fees, not from product sales. This is a pyramid scheme, not a productive MLM."}$json$::jsonb where id = '0a60f6f6-6364-4531-90ef-7dd80f235544';
update public.content_variants set body = $json${"text":"The Composite Stock Price Index (IHSG) reflects price movements of large shares in Indonesia. If the JCI rises, it means that the majority of large stocks rise, although not all shares rise.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = '0ab1d22c-2d9f-44b3-afca-c3b0afa81acd';
update public.content_variants set body = $json${"text":"Raka bought a hoodie for IDR 1,200,000 using PayLater. He forgot to pay the bill on time and the bill ballooned to IDR 1,500,000 due to late fees. Small consumer debts can grow large if not regulated."}$json$::jsonb where id = '0c1953c1-7528-41a6-91b9-b7e67fa355b7';
update public.content_variants set body = $json${"text":"Diversification does not mean buying lots of stocks from the same sector. Buying GOTO, DCII, and other technology issuers remains high risk if the technology sector corrects.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = '0c2ab69e-ce56-4c33-8b0d-355f7fec8a89';

