-- KO-225 group 1 continuation batch 16

update public.content_variants set body = $json${"type":"fill_blank","answer":"liabilities","question":"If an item costs money continuously without generating income, it is more _____.","difficulty":"beginner","explanation":"Liabilities drain money, such as installments for consumer goods that do not generate income."}$json$::jsonb where id = 'a9fb4015-30fb-4b30-8263-036d78ee1e18';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"High income always means high wealth.","difficulty":"beginner","explanation":"If expenses are greater than income, people with high salaries may have low wealth or even debt."}$json$::jsonb where id = 'ad911e4e-6e17-4b37-8fb7-816d6aa91ccd';
update public.content_variants set body = $json${"type":"matching","pairs":[["Asset","Deposits that earn interest"],["Liabilities","Motorbike installments are just for style"],["Can do both","Motorbike used for work and traveling"]],"answer":{"Aset":"Deposits that earn interest","Liabilitas":"Motorbike installments are just for style","Bisa keduanya":"Motorbike used for work and traveling"},"question":"Match items with their categories.","difficulty":"beginner","explanation":"Categories depend on whether the item includes or costs money."}$json$::jsonb where id = 'ae6672c9-d83d-4d44-9bef-09da991009ce';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"50%","options":["20%","30%","50%","70%"],"question":"In the 50/30/20 rule, what percentage is allocated to needs?","difficulty":"beginner","parameters":{},"explanation":"The 50/30/20 rule uses 50% for needs, 30% for wants, and 20% for savings and debt."}$json$::jsonb where id = 'b0d984ed-7e7e-4c5d-9cde-a2d15cbaa86e';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Assets are always in the form of physical goods such as a house or car.","difficulty":"beginner","explanation":"Assets can be cash, deposits, shares, skills, or money-making businesses."}$json$::jsonb where id = 'b14308e1-0adc-4319-91f9-99bcf331bfa5';
update public.content_variants set body = $json${"type":"fill_blank","answer":"worse","question":"Risk is the possibility of an outcome that is _____ than expected.","difficulty":"beginner","explanation":"Risks relate to negative or inconsistent results that may occur."}$json$::jsonb where id = 'b321dd5b-9303-4609-91ac-0594aeb3bb96';
update public.content_variants set body = $json${"type":"fill_blank","answer":"guess","question":"Diversification is often called a 'free lunch' because it reduces risk without having to _____ which assets are best.","difficulty":"intermediate","explanation":"With diversification, we don't need to predict winners; we have many assets."}$json$::jsonb where id = 'b3899c41-a194-4219-bbe3-65731e03f561';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Stock prices rise if more people want to buy than sell.","difficulty":"intermediate","explanation":"Prices are determined by supply and demand. High demand drives prices up."}$json$::jsonb where id = 'b42a3a2d-4077-4aa1-941d-2717f94a89be';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Place to buy and sell shares in Indonesia","options":["Issuing rupiah currency","Place to buy and sell shares in Indonesia","Set bank interest rates","Distributes MSME credit"],"question":"What is the main function of the Indonesian Stock Exchange (IDX)?","difficulty":"beginner","parameters":{},"explanation":"IDX is a market where shares and other securities are traded in Indonesia."}$json$::jsonb where id = 'b4677ef1-5bea-4ef4-8a47-86f2726e9009';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"To avoid selling investments when you need money urgently","options":["To buy cheap shares","To avoid selling investments when you need money urgently","To pay taxes","To gamble on the market"],"question":"What is the function of an emergency fund in investing?","difficulty":"beginner","parameters":{},"explanation":"An emergency fund protects long-term investments from immediate needs."}$json$::jsonb where id = 'b7405533-24ce-4d87-af52-05c2c1301e99';

