-- KO-225 group 4 lesson translation batch 1

update public.lessons set summary_id = $text$Sebuah aset memasukkan uang ke dalam saku Anda; suatu kewajiban mengeluarkan uang.$text$, concept_body_id = $text$Aset adalah sesuatu yang Anda miliki yang dapat memasukkan uang ke dalam saku Anda atau meningkatkan nilainya seiring berjalannya waktu. Kewajiban adalah sesuatu yang harus Anda bayar atau sesuatu yang selalu mengeluarkan uang. Benda fisik yang sama dapat menjadi aset bagi seseorang dan menjadi liabilitas bagi orang lain, bergantung pada cara penggunaannya.

Misalnya, sepeda motor yang dibeli secara tunai dan digunakan untuk memperoleh penghasilan sebagai pengemudi ojek online merupakan aset karena membantu menghasilkan uang. Sepeda motor yang dibeli secara kredit hanya untuk bersenang-senang di akhir pekan menjadi beban karena memerlukan pembayaran pinjaman, bahan bakar, dan perawatan tanpa menghasilkan pendapatan. Bahkan sebuah rumah bisa menjadi aset jika menghasilkan pendapatan sewa, atau menjadi liabilitas jika pinjaman dan pemeliharaan bank KPR menguras uang Anda. Pertanyaan kuncinya adalah: apakah item ini menambah atau mengurangi uang masa depan saya? Pendidikan dan keterampilan juga bisa menjadi aset karena dapat meningkatkan penghasilan Anda di masa depan. Namun, mereka hanya menjadi aset jika menghasilkan kekuatan. Kursus atau gelar yang tidak meningkatkan prospek pekerjaan Anda dapat menjadi beban jika hal tersebut membuat Anda memiliki hutang pendidikan yang besar.$text$, why_this_matters_id = $text$Sebelum Anda membeli sesuatu yang besar, tanyakan apakah itu akan menambah uang Anda atau menghabiskannya. Kebiasaan ini melindungi Anda dari hutang yang disamarkan sebagai status.$text$, common_mistake_id = $text$Berpikir bahwa harta benda mahal seperti mobil atau motor otomatis menjadi aset, padahal sebagian besarnya membutuhkan uang.$text$ where id = '0c9d741a-7151-4bea-bb7f-152a185efa2a';
update public.lessons set summary_id = $text$Kartu kredit adalah sebuah alat. Ini memberi penghargaan kepada pengguna yang disiplin dengan kenyamanan dan riwayat kredit, dan menghukum mereka yang hanya membayar minimum.$text$, concept_body_id = $text$Kartu kredit bukanlah uang gratis. Ini adalah pinjaman jangka pendek dari bank. Di Indonesia, Bank Indonesia mengatur kartu kredit melalui PBI No.14/2/PBI/2012. Aturan tersebut mencakup suku bunga maksimum, persyaratan usia dan pendapatan minimum, batas kredit, dan perlindungan konsumen. Aturan-aturan ini ada karena kredit bergulir bisa mahal jika disalahgunakan.

Kartu kredit bisa menjadi pilihan yang baik jika Anda membayar seluruh saldo setiap bulan. Anda memiliki catatan kredit SLIK yang positif, menikmati masa tenggang singkat sebelum pembayaran, dan dapat menerima uang kembali atau hadiah. Ini juga dapat membantu dalam keadaan darurat, seperti membeli tiket pesawat pulang ketika kartu debit Anda tidak berfungsi. Namun kartu kredit menjadi buruk ketika Anda memperlakukan batas tersebut sebagai penghasilan tambahan, membeli kebutuhan yang tidak mampu Anda beli, atau hanya membayar jumlah minimum. Sisanya dikenakan bunga setiap bulan, dan utangnya bisa bertahan bertahun-tahun.$text$, why_this_matters_id = $text$Pada pekerjaan pertama Anda, kartu kredit dapat membantu atau merugikan kehidupan finansial Anda tergantung pada apakah Anda memperlakukannya sebagai uang tunai yang tertunda atau penghasilan tambahan.$text$, common_mistake_id = $text$Memperlakukan batas kredit sebagai uang tambahan, bukan pinjaman jangka pendek yang harus dilunasi.$text$ where id = '1f2e87b9-6b3d-407c-8dd5-69d0e1e75194';
update public.lessons set summary_id = $text$Harga mata uang kripto dapat berfluktuasi secara liar, dan para penipu menggunakan token palsu, penarikan permadani, dan dukungan selebriti untuk mencuri uang dari generasi muda Indonesia.$text$, concept_body_id = $text$Risiko kripto yang pertama adalah volatilitas. Adalah normal jika mata uang kripto naik atau turun sebesar 20% dalam satu hari. Artinya, seseorang yang berinvestasi sebesar Rp 5.000.000 dapat melihatnya menjadi Rp 4.000.000 — atau Rp 6.000.000 — dalam waktu 24 jam. Ini bukan bug; begitulah cara pasar bekerja. Bagi seseorang yang tidak memiliki dana darurat atau pendapatan stabil, ketidakstabilan ini dapat menyebabkan kepanikan dan pengambilan keputusan yang buruk.

Risiko kedua adalah penipuan. *Penarikan permadani* terjadi ketika pengembang membuat koin baru, menarik pembeli, lalu menghilang bersama uangnya. Token palsu menyalin nama koin terkenal untuk mengelabui pemula. Penipuan lainnya termasuk skema Ponzi yang menjanjikan jaminan pengembalian bulanan, dukungan selebriti palsu, dan tautan phishing yang mencuri kata sandi dompet. OJK dan Bappebti telah berulang kali memperingatkan masyarakat Indonesia: jika suatu tawaran menjanjikan keuntungan tetap yang tinggi, memaksa Anda untuk merekrut teman, atau berasal dari platform yang tidak terdaftar, maka hampir pasti tawaran tersebut merupakan penipuan. Di Indonesia, perdagangan kripto legal harus melalui bursa yang terdaftar di Bappebti; hal lain tidak terlindungi dan berisiko tinggi.$text$, why_this_matters_id = $text$Penipuan kripto sering kali menargetkan orang berusia 18-30 tahun melalui media sosial. Mempelajari tanda bahaya melindungi tabungan dan persahabatan Anda.$text$, common_mistake_id = $text$Membeli koin karena influencer, teman, atau grup Telegram menjanjikan jaminan keuntungan cepat.$text$ where id = '064e728e-dcd6-4773-85e3-77cb140e29b8';
update public.lessons set summary_id = $text$Membeli kripto untuk membaliknya dengan cepat sebagian besar merupakan spekulasi, bukan investasi. Berinvestasi membangun kekayaan melalui aset produktif; perjudian adalah hiburan yang biasanya merugi.$text$, concept_body_id = $text$Berinvestasi berarti membeli sesuatu yang diharapkan dapat menghasilkan pendapatan atau tumbuh karena adanya kegiatan ekonomi riil. Misalnya, reksa dana memiliki saham dan obligasi yang menghasilkan keuntungan dan bunga. Deposito menghasilkan bunga karena bank meminjamkan uangnya kepada bisnis dan pemilik rumah. Selama bertahun-tahun, aset produktif ini dapat membangun kekayaan secara perlahan.

Spekulasi berarti membeli sesuatu terutama karena Anda berharap harganya akan cepat naik. Membeli token kripto baru karena Anda memperkirakannya akan "berbulan" minggu depan adalah spekulasi. Anda tidak memperoleh dividen atau bunga; Anda bertaruh bahwa orang lain akan membayar lebih nanti. Spekulasi tidak selalu buruk, namun berisiko tinggi dan hanya melibatkan uang yang mampu Anda tanggung kerugiannya.

Perjudian berbeda dari keduanya. Saat Anda berjudi, permainannya dirancang agar rumah menang seiring waktu. Ini adalah hiburan, bukan cara untuk membangun kekayaan. Banyak permainan kripto, pasar prediksi, dan aplikasi perdagangan dengan leverage terasa seperti berinvestasi tetapi berperilaku seperti perjudian. Aturan yang baik: jika Anda tidak memahami asetnya, membutuhkan uang segera, atau merasa FOMO, menjauhlah.$text$, why_this_matters_id = $text$Banyak anak muda Indonesia memasuki dunia kripto dengan pemikiran bahwa mereka sedang berinvestasi, padahal sebenarnya mereka sedang berspekulasi atau berjudi. Mengetahui perbedaannya melindungi tujuan keuangan Anda.$text$, common_mistake_id = $text$Memasukkan uang yang Anda tidak mampu kehilangannya ke dalam kripto karena Anda takut ketinggalan (FOMO).$text$ where id = 'b6c47e7f-f014-47c8-804a-dfaa9d11e7d0';

