-- KO-225 group 5 continuation batch 17

update public.content_variants set body = $json${"text":"An MLM sells vitamins at a reasonable price. Members can sell products without having to recruit. Commissions are earned from product sales. This is closer to product-based MLM."}$json$::jsonb where id = 'bbcb7f2c-d5e4-4460-915a-f6e360377557';
update public.content_variants set body = $json${"text":"Characteristics of fraudulent investments: guaranteed high returns, no risk, time pressure, and invite-a-friend schemes. Legitimate investments do not promise guaranteed profits."}$json$::jsonb where id = 'bbd3ab75-8868-48c9-b2a1-7a795e2e9b12';
update public.content_variants set body = $json${"text":"Index mutual funds that follow IDX30 automatically provide diversification into 30 large stocks. This is suitable for beginners who don't have time to research one by one.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'bc066666-f10c-4937-8a5c-a176906aac55';
update public.content_variants set body_id = $json${"type":"categorization","answer":{"Needs":["Pembayaran sewa","Bahan makanan"],"Wants":["Berlangganan Netflix","Keanggotaan gimnasium","Sepatu kets baru"],"Savings":["Setoran dana darurat"],"Investments":["SIP bulanan","Pembelian saham"]},"options":{"items":["Pembayaran sewa","Berlangganan Netflix","SIP bulanan","Setoran dana darurat","Keanggotaan gimnasium","Bahan makanan","Sepatu kets baru","Pembelian saham"],"buckets":["Kebutuhan","ingin","Tabungan","Investasi"]},"question":"Kategorikan setiap item ke dalam kelompok anggaran yang sesuai:","difficulty":"intermediate","parameters":{},"explanation":"Kategorisasi yang benar: {\"Kebutuhan\": [\"Pembayaran sewa\", \"Bahan Makanan\"], \"Keinginan\": [\"Langganan Netflix\", \"Keanggotaan Gym\", \"Sepatu kets baru\"], \"Tabungan\": [\"Setoran dana darurat\"], \"Investasi\": [\"SIP Bulanan\", \"Pembelian saham\"]}"}$json$::jsonb where id = 'bc943cbf-8b9f-4f3a-a066-f5375ad04527';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"memulai sejak dini dan tetap konsisten","options":["memilih saham terbaik","memulai sejak dini dan tetap konsisten","mengatur waktu pasar dengan sempurna","memiliki informasi orang dalam"],"question":"Faktor terpenting dalam membangun kekayaan melalui investasi adalah ________.","difficulty":"advanced","parameters":{},"explanation":"Waktu di pasar dan kontribusi yang konsisten jauh lebih penting daripada pemilihan saham atau penentuan waktu pasar."}$json$::jsonb where id = 'bca757fe-0dbf-429f-a66e-8011dcefdbc2';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"lebih murah","options":["lebih mahal","lebih murah","tidak berubah harganya","liar"],"question":"Jika mata uang suatu negara terdepresiasi, barang ekspornya menjadi ________ bagi pembeli asing.","difficulty":"beginner","parameters":{},"explanation":"Depresiasi mata uang membuat barang-barang dalam negeri lebih murah bagi pembeli asing, sehingga berpotensi meningkatkan ekspor."}$json$::jsonb where id = 'bcad4066-696b-4f73-b17f-879725562858';
update public.content_variants set body = $json${"text":"An asset is something that puts money in our pockets or can increase in value. A liability is something that takes money out of our pocket."}$json$::jsonb where id = 'bcafcc6d-6e7a-4e10-b972-48b21c47eb71';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"tidak menunjukkan","options":["jaminan","tidak menunjukkan","adalah satu-satunya prediktor","selalu melebihi"],"question":"Saat mengevaluasi investasi, kinerja masa lalu ________ hasil di masa depan.","difficulty":"beginner","parameters":{},"explanation":"Penafian standar: kinerja masa lalu tidak menjamin hasil di masa depan. Pasar pada dasarnya tidak menentu."}$json$::jsonb where id = 'bcb77a9f-b482-4317-87c5-96258187a01d';
update public.content_variants set body = $json${"text":"Two important factors of compound interest: timing and interest rates. Starting early gives money longer to grow."}$json$::jsonb where id = 'bd45826f-22ec-461f-a4b9-0976a301a93e';
update public.content_variants set body = $json${"text":"The best defense is to pause before buying. Ask: is this a necessity? Do I have money without disturbing savings? Do I still want to buy tomorrow?"}$json$::jsonb where id = 'bd6482c2-ba77-4668-82f4-a7520f249904';

