-- KO-225 group 1 translation batch 9

update public.content_variants set body = $json${"type":"multiple_choice","answer":"Rp. 950 - Rp. 1,100","options":["Rp. 950 - Rp. 1,100","Rp. 1,000 - Rp. 1,050","Rp. 1,050 - Rp. 1,100","Rp. 950 - Rp. 1,050"],"question":"ABC shares open IDR 1,000, high IDR 1,100, low IDR 950, close IDR 1,050. What is the price range that day?","difficulty":"intermediate","explanation":"The price range is from low (lowest) to high (highest), namely Rp. 950 to Rp. 1,100."}$json$::jsonb where id = '4d26ddac-0efe-4b9c-92c5-805523b9b39c';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Investing is always better than keeping money in the bank for all purposes.","difficulty":"intermediate","explanation":"Investments have risks. For short-term goals and emergency funds, banks are safer."}$json$::jsonb where id = '4d3aa205-b342-4c2c-80b0-bfd7fc1ab667';
update public.content_variants set body = $json${"type":"ordering","answer":["Pay the boarding house","Buy credit and quota","Streaming subscription","Buy new shoes"],"options":["Pay the boarding house","Buy credit and quota","Streaming subscription","Buy new shoes"],"question":"Sort Sari expenses from the most urgent (need) to the most that can be postponed (want).","difficulty":"beginner","explanation":"Boarding house and credit are basic needs. Streaming and new shoes are desires that can be postponed."}$json$::jsonb where id = '4eebb4c3-d066-4f7f-83fc-847c43114681';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Diversification ensures that investments always produce profits.","difficulty":"beginner","parameters":{},"explanation":"Diversification reduces risk, but does not guarantee profits."}$json$::jsonb where id = '51c19eaf-3ede-4d9e-9fb6-c6b9d29b7e3f';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Short term deposits or separate savings","options":["Short term deposits or separate savings","Blue chip stocks","Large cap crypto","Property for rent"],"question":"The best place to save emergency funds is...","difficulty":"beginner","parameters":{},"explanation":"Emergency funds must be liquid and safe. Short deposits or separate savings are suitable because they are easy to withdraw and their value is stable."}$json$::jsonb where id = '52372ad6-2545-4c1e-b229-4bfeb60199b5';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Save IDR 2,000,000 for a laptop in 5 months","options":["Save IDR 2,000,000 for a laptop in 5 months","Save more","Don't spend money","Buy what you want"],"question":"Which is the best financial goal?","difficulty":"beginner","explanation":"Goals that are specific and have deadlines are easier to implement and measure."}$json$::jsonb where id = '5256c9be-535b-47bc-81a3-8ec1ae912001';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"The budget should be rigid and should not be adjusted even if income changes.","difficulty":"beginner","parameters":{},"explanation":"The budget should be flexible and adjusted to changing income and expenditure conditions."}$json$::jsonb where id = '52933b46-c41e-491a-bcb0-030fbed38bc8';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"BBCA shares, government bonds, and money market mutual funds","options":["All money in GOTO shares","BBCA shares, government bonds, and money market mutual funds","Bought 15 technology sector stocks","Store all money in a digital wallet"],"question":"Which comes closest to good diversification?","difficulty":"intermediate","parameters":{},"explanation":"Good diversification spreads funds across different types of assets and sectors, not just one type."}$json$::jsonb where id = '533508c3-bd87-4e5e-8b43-0c4bda64a797';
update public.content_variants set body = $json${"type":"ordering","answer":["Open a securities account in registered securities","Do company research","Determine the shares and number of lots","Monitor the portfolio regularly"],"options":["Open a securities account in registered securities","Do company research","Determine the shares and number of lots","Monitor the portfolio regularly"],"question":"Sequence the steps to buy shares on IDX safely.","difficulty":"intermediate","parameters":{},"explanation":"Start with a securities account, research the company, determine the lot, then monitor it periodically."}$json$::jsonb where id = '53e73e28-a176-4999-9d31-78368444f333';
update public.content_variants set body = $json${"type":"word_bank","answer":["take notes","review"],"options":["take notes","review"],"question":"Complete the following sentences with words from the word bank: \"Budgets only work if we routinely _____ spending and _____ budget.\"","difficulty":"beginner","parameters":{},"explanation":"Regular record keeping and review ensures the budget remains realistic."}$json$::jsonb where id = '5429e479-96e5-4ca8-9255-6fcd4a93fb7c';

