-- KO-225 group 5 continuation batch 27

update public.content_variants set body_id = $json${"type":"calculation","answer":"0.69","question":"Portofolio memiliki 50% saham (beta 1.2), 30% obligasi (beta 0.3), 20% uang tunai (beta 0). Apa itu portofolio beta?","difficulty":"beginner","parameters":{"hint":"Weight each asset's beta by its portfolio allocation."},"explanation":"Portofolio beta = (0,50 × 1,2) + (0,30 × 0,3) + (0,20 × 0) = 0,60 + 0,09 + 0 = 0,69."}$json$::jsonb where id = 'e62eb996-f99f-45aa-8611-b74696dae311';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["mempertaruhkan","kembali"],"options":["mempertaruhkan","kembali","diversifikasi","likuiditas"],"question":"Investor harus memahami trade-off antara ________ dan ________ yang diharapkan.","difficulty":"intermediate","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah : risk, return."}$json$::jsonb where id = 'e65eafa6-d8c6-4a91-90ba-7c721ba0e4b6';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"keadaan darurat","question":"Dana ________ adalah uang yang disisihkan khusus untuk pengeluaran tak terduga.","difficulty":"advanced","parameters":{},"explanation":"Dana darurat memberikan keamanan finansial selama keadaan tak terduga seperti kehilangan pekerjaan atau keadaan darurat medis."}$json$::jsonb where id = 'e69c7e48-f571-45d4-910d-32c92e7ed80d';
update public.content_variants set body = $json${"text":"A young family in Bandung has emergency funds in deposits, long-term investments in BBCA and BBRI shares, and savings for children's education in mixed mutual funds. Each goal has a different instrument.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee","c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'e6a5d8a7-d36b-4194-ab3a-4efccd31a0a2';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"jatuh","options":["bangkit","jatuh","tetap tidak berubah","menjadi lebih fluktuatif"],"question":"Ketika bank sentral menaikkan suku bunga, harga obligasi umumnya ________.","difficulty":"intermediate","parameters":{},"explanation":"Harga obligasi dan suku bunga memiliki hubungan terbalik. Suku bunga yang lebih tinggi berarti obligasi yang ada menjadi kurang menarik."}$json$::jsonb where id = 'e6bd6931-d5b6-48c2-ad64-030be1572c7a';
update public.content_variants set body = $json${"text":"Dewi sets aside IDR 5,000,000 per month: 40% into IDX30 index stock mutual funds, 30% into government bonds, 20% into deposits, and 10% into digital gold. When stocks fall, bonds and deposits help hold the value of the portfolio.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee","c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'e6be6e88-bbef-4404-bba3-ec6fbef28c38';
update public.content_variants set body = $json${"text":"When the price of rice rose, fried rice traders on the side of the road raised the selling price from IDR 12,000 to IDR 15,000. Raw material inflation spreads to selling prices to consumers.","source_ids":["e49fe239-c534-4bed-b0bd-a7950b9e35c4"]}$json$::jsonb where id = 'e6e5fcf4-dd2c-40e4-95ff-f993aaf9ac95';
update public.content_variants set body = $json${"text":"Waiting for payment has an opportunity cost. Deferred money cannot be used for immediate needs or earn interest during the waiting period."}$json$::jsonb where id = 'e6f09959-6b2d-47e7-9d30-86b59e9dd4ca';
update public.content_variants set body_id = $json${"type":"matching","answer":{"Deflation":"Penurunan harga secara umum","Inflation":"Kenaikan harga secara umum","Stagflation":"Inflasi tinggi + stagnasi","Hyperinflation":"Kenaikan harga yang sangat cepat"},"options":{"left":["Inflasi","Deflasi","Stagflasi","Hiperinflasi"],"right":["Kenaikan harga secara umum","Penurunan harga secara umum","Inflasi tinggi + stagnasi","Kenaikan harga yang sangat cepat"]},"question":"Cocokkan setiap kondisi perekonomian dengan definisinya:","difficulty":"intermediate","parameters":{},"explanation":"Pertandingan yang benar: Inflasi → Kenaikan harga secara umum, Deflasi → Penurunan harga secara umum, Stagflasi → Inflasi tinggi + stagnasi, Hiperinflasi → Kenaikan harga yang sangat cepat"}$json$::jsonb where id = 'e7705584-992a-462a-a7a7-49166ae21dff';
update public.content_variants set body_id = $json${"type":"calculation","answer":"69,770,000","question":"Jika Anda menabung Rp 1.000.000 setiap bulan dengan bunga majemuk 6% per bulan, berapa jumlah yang akan Anda miliki setelah 5 tahun?","difficulty":"beginner","parameters":{"hint":"Use FV annuity formula with monthly compounding."},"explanation":"Menggunakan nilai masa depan dari rumus anuitas: FV = PMT × [(1+r)^n - 1]/r. Dengan r = 0,5% bulanan, n = 60, PMT = 1.000.000. FV ≈ Rp 69,77M."}$json$::jsonb where id = 'e8861246-c5e8-4bdc-9949-277f1f130fb5';

