-- Migration 011: Social tables
-- Friendships, invites, cohorts, memberships, and weekly leaderboard snapshots.

CREATE TABLE friendships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  addressee_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','accepted','declined','blocked')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(requester_id, addressee_id),
  CHECK (requester_id != addressee_id)
);

COMMENT ON TABLE friendships IS 'Friend requests and friendships between users. RLS: users see rows where they are requester OR addressee.';

CREATE TABLE friend_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inviter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  invite_code TEXT UNIQUE NOT NULL DEFAULT substr(md5(random()::text), 1, 8),
  uses_count INTEGER DEFAULT 0,
  max_uses INTEGER DEFAULT 10,
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '30 days',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE friend_invites IS 'Friend invite codes generated by users. RLS: users read/create own invite codes only.';

CREATE TABLE cohorts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  created_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE cohorts IS 'Groups/cohorts users can join by invite code. Public read for invite-code lookup.';

CREATE TABLE cohort_memberships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cohort_id UUID NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cohort_id, user_id)
);

COMMENT ON TABLE cohort_memberships IS 'User memberships in cohorts. RLS: users read own memberships.';

CREATE TABLE weekly_leaderboard_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  xp_this_week INTEGER DEFAULT 0,
  koin_points_this_week INTEGER DEFAULT 0,
  rank_global INTEGER,
  rank_friends INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, week_start)
);

COMMENT ON TABLE weekly_leaderboard_snapshots IS 'Weekly XP and Koin Points totals per user. RLS: users read own rows; public read via safe leaderboard view.';

-- RLS: friendships - users can see and manage rows they participate in
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own friendships"
  ON friendships FOR ALL
  USING (auth.uid() = requester_id OR auth.uid() = addressee_id)
  WITH CHECK (auth.uid() = requester_id OR auth.uid() = addressee_id);

COMMENT ON POLICY "Users manage own friendships" ON friendships IS 'Authenticated users can only access friendship rows where they are requester or addressee.';

-- RLS: friend_invites - users read/create own
ALTER TABLE friend_invites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own friend_invites"
  ON friend_invites FOR SELECT
  USING (auth.uid() = inviter_id);

COMMENT ON POLICY "Users read own friend_invites" ON friend_invites IS 'Authenticated users can only read their own invite codes.';

CREATE POLICY "Users create own friend_invites"
  ON friend_invites FOR INSERT
  WITH CHECK (auth.uid() = inviter_id);

COMMENT ON POLICY "Users create own friend_invites" ON friend_invites IS 'Authenticated users can only create invite codes for themselves.';

-- RLS: cohorts - public read via SELECT policy (no user data restriction)
ALTER TABLE cohorts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read cohorts"
  ON cohorts FOR SELECT
  USING (TRUE);

COMMENT ON POLICY "Public read cohorts" ON cohorts IS 'Anyone can read cohorts for invite-code lookup.';

-- RLS: cohort_memberships - users read own
ALTER TABLE cohort_memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own cohort_memberships"
  ON cohort_memberships FOR SELECT
  USING (auth.uid() = user_id);

COMMENT ON POLICY "Users read own cohort_memberships" ON cohort_memberships IS 'Authenticated users can only read their own cohort membership rows.';

-- RLS: weekly_leaderboard_snapshots - users read own
ALTER TABLE weekly_leaderboard_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own weekly_leaderboard_snapshots"
  ON weekly_leaderboard_snapshots FOR SELECT
  USING (auth.uid() = user_id);

COMMENT ON POLICY "Users read own weekly_leaderboard_snapshots" ON weekly_leaderboard_snapshots IS 'Authenticated users can only read their own weekly leaderboard snapshot rows. Public read is exposed through a safe view.';
