-- KO-230..KO-239: Chapters 10 and 11. Practice data only; never live prices.
BEGIN;

INSERT INTO topics (id, slug, name, name_id, icon, color, display_order, chapter) VALUES
  (gen_random_uuid(), 'chart_literacy', 'Chart Literacy', 'Literasi Grafik', 'chart', 'primary', 100, 'Reading Trading Charts'),
  (gen_random_uuid(), 'decision_analysis', 'Decision Analysis', 'Analisis Keputusan', 'compass', 'secondary', 110, 'Decision Analysis Lab')
ON CONFLICT (slug) DO UPDATE SET chapter = EXCLUDED.chapter, color = EXCLUDED.color, display_order = EXCLUDED.display_order;

INSERT INTO sources (id, source_code, title, local_title, source_tier, source_type, organization, url, publication_year, language, status, localization_notes)
VALUES (
  gen_random_uuid(), 'OJK-CHART-001', 'OJK Financial Literacy Series: Capital Market', 'OJK Seri Literasi Keuangan: Pasar Modal',
  1, 'document', 'Otoritas Jasa Keuangan', 'https://sikapiuangmu.ojk.go.id/FrontEnd/LiterasiPerguruanTinggi/assets/pdf/Buku%203%20-%20Pasar%20Modal.pdf',
  2024, 'id', 'verified', 'Covers OHLC and candlestick-pattern education; Koinaku charts use fictional practice data.'
)
ON CONFLICT (source_code) DO NOTHING;

WITH seed(slug, chapter, lesson_number, difficulty, title, title_id, term, term_id, definition, definition_id, practice, practice_id) AS (
  VALUES
    ('chart-ohcl-basics', 'Reading Trading Charts', 113, 'beginner', 'OHLC: The Four Prices in One Candle', 'OHLC: Empat Harga dalam Satu Candle', 'OHLC', 'OHLC', 'Open, high, low, and close describe the first, highest, lowest, and last traded prices in one period.', 'Open, high, low, dan close menunjukkan harga pertama, tertinggi, terendah, dan terakhir dalam satu periode.', 'A practice candle opens at 100, reaches 112, falls to 96, and closes at 108. Those four values are its OHLC story.', 'Satu candle latihan dibuka di 100, mencapai 112, turun ke 96, lalu ditutup di 108. Empat angka itu adalah cerita OHLC-nya.'),
    ('chart-body-and-wick', 'Reading Trading Charts', 114, 'beginner', 'Candle Body and Wick', 'Body dan Wick Candle', 'candle body and wick', 'body dan wick candle', 'The body shows the distance between open and close; the wicks show the highest and lowest prices reached.', 'Body menunjukkan jarak antara open dan close; wick menunjukkan harga tertinggi dan terendah yang sempat tercapai.', 'A small body with a long lower wick means price travelled lower during the period but recovered before the close.', 'Body kecil dengan wick bawah panjang berarti harga sempat turun lalu pulih sebelum penutupan.'),
    ('chart-bullish-bearish-doji', 'Reading Trading Charts', 115, 'beginner', 'Bullish, Bearish, and Doji Candles', 'Candle Bullish, Bearish, dan Doji', 'bullish, bearish, and doji candles', 'candle bullish, bearish, dan doji', 'A bullish candle closes above its open, a bearish candle closes below it, and a doji closes near its open.', 'Candle bullish ditutup di atas open, candle bearish ditutup di bawah open, dan doji ditutup dekat dengan open.', 'A doji does not predict a reversal by itself; it simply shows a period where open and close were close together.', 'Doji tidak otomatis memprediksi pembalikan; doji hanya menunjukkan open dan close berada dekat.'),
    ('chart-long-wick-rejection', 'Reading Trading Charts', 116, 'beginner', 'Long Wicks and Price Rejection', 'Wick Panjang dan Penolakan Harga', 'long-wick rejection', 'penolakan harga dengan wick panjang', 'A long wick can show that price moved strongly in one direction but was pushed back before the close.', 'Wick panjang dapat menunjukkan harga bergerak kuat ke satu arah lalu terdorong kembali sebelum penutupan.', 'A long upper wick after a rise is a clue to study context, not a command to sell.', 'Wick atas panjang setelah kenaikan adalah petunjuk untuk memeriksa konteks, bukan perintah untuk menjual.'),
    ('chart-hammer-shooting-star', 'Reading Trading Charts', 117, 'intermediate', 'Hammer, Inverted Hammer, and Shooting Star', 'Hammer, Inverted Hammer, dan Shooting Star', 'hammer and shooting-star patterns', 'pola hammer dan shooting star', 'These candle shapes describe where the body and wick sit; their meaning depends on the surrounding trend and confirmation.', 'Bentuk candle ini menggambarkan posisi body dan wick; maknanya bergantung pada tren sekitar dan konfirmasi.', 'A hammer after a decline may show rejection of lower prices, but a learner still checks the next candles and risk before deciding.', 'Hammer setelah penurunan dapat menunjukkan penolakan harga rendah, tetapi tetap perlu memeriksa candle berikutnya dan risiko.'),
    ('chart-support-resistance', 'Reading Trading Charts', 118, 'intermediate', 'Support and Resistance Are Zones', 'Support dan Resistance adalah Zona', 'support and resistance zones', 'zona support dan resistance', 'Support and resistance are areas where price has repeatedly paused or reacted, not exact magical numbers.', 'Support dan resistance adalah area tempat harga berulang kali berhenti atau bereaksi, bukan angka ajaib yang pasti.', 'If price has reacted near 100 several times, treat 100 as a zone to observe rather than a guaranteed floor.', 'Jika harga beberapa kali bereaksi di sekitar 100, anggap 100 sebagai zona untuk diamati, bukan lantai yang pasti.'),
    ('chart-trend-and-timeframe', 'Reading Trading Charts', 119, 'intermediate', 'Trend and Timeframe Context', 'Konteks Tren dan Timeframe', 'trend and timeframe', 'tren dan timeframe', 'A chart can look different on a daily and weekly timeframe, so a pattern needs its timeframe stated.', 'Grafik dapat terlihat berbeda pada timeframe harian dan mingguan, jadi pola harus selalu menyebut timeframe-nya.', 'A one-day drop can happen inside a longer upward trend; viewing only one candle removes important context.', 'Penurunan satu hari dapat terjadi dalam tren naik yang lebih panjang; melihat satu candle saja menghilangkan konteks penting.'),
    ('chart-reading-limits', 'Reading Trading Charts', 120, 'intermediate', 'What a Chart Cannot Tell You', 'Hal yang Tidak Bisa Diberitahu Grafik', 'limits of chart reading', 'batas membaca grafik', 'Charts summarize historical price movement; they cannot guarantee a future price, company quality, or a suitable decision for you.', 'Grafik merangkum pergerakan harga masa lalu; grafik tidak dapat menjamin harga masa depan, kualitas perusahaan, atau keputusan yang cocok untukmu.', 'Before acting on a pattern, combine it with goals, risk tolerance, research, and an amount you can afford to lose.', 'Sebelum bertindak berdasarkan pola, gabungkan dengan tujuan, toleransi risiko, riset, dan dana yang sanggup kamu tanggung risikonya.'),
    ('decision-multicandle-context', 'Decision Analysis Lab', 121, 'intermediate', 'Read the Sequence, Not One Candle', 'Baca Rangkaian, Bukan Satu Candle', 'multi-candle context', 'konteks beberapa candle', 'A single candle is one observation; a sequence shows whether momentum, rejection, or range behaviour is developing.', 'Satu candle adalah satu pengamatan; rangkaian candle menunjukkan apakah momentum, penolakan, atau rentang harga sedang berkembang.', 'Three mixed candles near the same zone may mean uncertainty, so a disciplined learner avoids inventing a certain story.', 'Tiga candle campuran di zona yang sama dapat berarti ketidakpastian, jadi pelajar yang disiplin tidak mengarang cerita pasti.'),
    ('decision-volume-confirmation', 'Decision Analysis Lab', 122, 'intermediate', 'Volume Is Context, Not Proof', 'Volume adalah Konteks, Bukan Bukti', 'volume confirmation', 'konfirmasi volume', 'Volume shows how much was traded during a period. It can add context to a move but does not prove what happens next.', 'Volume menunjukkan seberapa banyak yang diperdagangkan dalam satu periode. Volume dapat menambah konteks tetapi tidak membuktikan langkah berikutnya.', 'A price move with unusual volume invites more questions about context; it is not an automatic signal to copy a trade.', 'Pergerakan harga dengan volume tidak biasa mengundang lebih banyak pertanyaan tentang konteks; itu bukan sinyal otomatis untuk meniru transaksi.'),
    ('decision-zones-false-breakouts', 'Decision Analysis Lab', 123, 'intermediate', 'Zones and False Breakouts', 'Zona dan False Breakout', 'false breakout', 'false breakout', 'A false breakout happens when price moves beyond a watched zone but returns inside it. It is a reminder to plan for uncertainty.', 'False breakout terjadi saat harga bergerak melewati zona yang diamati lalu kembali ke dalamnya. Ini mengingatkan kita untuk merencanakan ketidakpastian.', 'Instead of chasing the first move above a zone, a learner writes what evidence would change their view and what loss they can accept.', 'Alih-alih mengejar gerakan pertama di atas zona, pelajar menulis bukti apa yang mengubah pandangan dan kerugian yang dapat diterima.'),
    ('decision-timeframe-comparison', 'Decision Analysis Lab', 124, 'intermediate', 'Compare Timeframes Before a Story', 'Bandingkan Timeframe Sebelum Membuat Cerita', 'timeframe comparison', 'perbandingan timeframe', 'Short timeframes show detail; longer timeframes show broader context. Neither one removes risk.', 'Timeframe pendek menunjukkan detail; timeframe lebih panjang menunjukkan konteks yang lebih luas. Keduanya tidak menghilangkan risiko.', 'A five-minute move can look dramatic while the weekly chart remains inside a normal range.', 'Pergerakan lima menit dapat terlihat dramatis ketika grafik mingguan masih berada dalam rentang normal.'),
    ('decision-risk-reward', 'Decision Analysis Lab', 125, 'advanced', 'Risk/Reward Before a Trade Idea', 'Risiko/Imbal Hasil Sebelum Ide Transaksi', 'risk/reward planning', 'perencanaan risiko/imbalan', 'Risk/reward compares a possible loss with a possible gain before acting; it does not make either outcome certain.', 'Risiko/imbalan membandingkan kemungkinan rugi dengan kemungkinan untung sebelum bertindak; ini tidak membuat hasil apa pun menjadi pasti.', 'A learner can decide not to take an idea when the possible loss would disrupt an emergency fund or financial goal.', 'Pelajar dapat memilih tidak mengambil ide ketika kemungkinan rugi akan mengganggu dana darurat atau tujuan keuangan.'),
    ('decision-position-sizing', 'Decision Analysis Lab', 126, 'advanced', 'Position Size Protects Your Plan', 'Ukuran Posisi Melindungi Rencanamu', 'position sizing', 'ukuran posisi', 'Position size is how much of your available money is exposed to one idea. Smaller size limits the damage of being wrong.', 'Ukuran posisi adalah jumlah uang yang terpapar pada satu ide. Ukuran yang lebih kecil membatasi dampak ketika salah.', 'Having a strong opinion is not a reason to risk money needed for rent, food, debt, or savings goals.', 'Memiliki pendapat kuat bukan alasan untuk mempertaruhkan uang yang dibutuhkan untuk kos, makan, utang, atau tujuan tabungan.'),
    ('decision-bias-and-narratives', 'Decision Analysis Lab', 127, 'advanced', 'Confirmation Bias and Market Stories', 'Bias Konfirmasi dan Cerita Pasar', 'confirmation bias', 'bias konfirmasi', 'Confirmation bias is the habit of looking only for information that agrees with a belief while ignoring evidence against it.', 'Bias konfirmasi adalah kebiasaan mencari informasi yang mendukung keyakinan sambil mengabaikan bukti yang berlawanan.', 'Before deciding, write one fact that would prove your idea wrong and one neutral source you will check.', 'Sebelum memutuskan, tulis satu fakta yang dapat membuktikan ide kamu salah dan satu sumber netral yang akan diperiksa.'),
    ('decision-thesis-invalidation', 'Decision Analysis Lab', 128, 'advanced', 'A Thesis Needs an Invalidation Rule', 'Tesis Membutuhkan Aturan Pembatalan', 'thesis and invalidation rule', 'tesis dan aturan pembatalan', 'A thesis states why an idea may make sense; an invalidation rule states what evidence would make you stop or reassess.', 'Tesis menjelaskan mengapa suatu ide mungkin masuk akal; aturan pembatalan menjelaskan bukti yang membuatmu berhenti atau menilai ulang.', 'Writing a thesis before acting reduces hindsight stories and makes later reflection more useful.', 'Menulis tesis sebelum bertindak mengurangi cerita setelah kejadian dan membuat refleksi berikutnya lebih berguna.')
)
INSERT INTO lessons (id, slug, title, title_id, topic_id, lesson_number, difficulty, xp_reward, estimated_minutes, summary, summary_id, concept_body, concept_body_id, indonesian_example, why_this_matters, why_this_matters_id, common_mistake, common_mistake_id, review_status, reviewed_by, reviewed_at, is_published)
SELECT gen_random_uuid(), slug, title, title_id, (SELECT id FROM topics WHERE topics.chapter = seed.chapter), lesson_number, difficulty, 70, 6,
  definition, definition_id, definition || E'\n\n' || practice, definition_id || E'\n\n' || practice_id, practice_id,
  'Practice reading evidence and uncertainty before acting on a financial idea.', 'Berlatih membaca bukti dan ketidakpastian sebelum bertindak atas ide keuangan.',
  'Treating one pattern as a guaranteed buy or sell signal.', 'Menganggap satu pola sebagai sinyal beli atau jual yang pasti.',
  'approved', 'koin-curriculum-agent', NOW(), TRUE
FROM seed
ON CONFLICT (slug) DO NOTHING;

WITH seed(slug, chapter, term, term_id, definition, definition_id, practice, practice_id) AS (
  VALUES
    ('chart-ohcl-basics','Reading Trading Charts','OHLC','OHLC','Open, high, low, and close describe the four prices in one period.','Open, high, low, dan close menjelaskan empat harga dalam satu periode.','OHLC tells one period''s price range, not a forecast.','OHLC menunjukkan rentang harga satu periode, bukan ramalan.'),
    ('chart-body-and-wick','Reading Trading Charts','candle body and wick','body dan wick candle','The body is open-to-close; wicks are the high-to-low range.','Body adalah open-ke-close; wick adalah rentang high-ke-low.','A wick records movement, not a promise.','Wick mencatat pergerakan, bukan janji.'),
    ('chart-bullish-bearish-doji','Reading Trading Charts','bullish, bearish, and doji candles','candle bullish, bearish, dan doji','Bullish closes above open, bearish below, and doji near open.','Bullish ditutup di atas open, bearish di bawah, dan doji dekat open.','A doji alone does not guarantee reversal.','Doji sendiri tidak menjamin pembalikan.'),
    ('chart-long-wick-rejection','Reading Trading Charts','long-wick rejection','penolakan harga dengan wick panjang','A long wick can show price was pushed back before close.','Wick panjang dapat menunjukkan harga terdorong kembali sebelum close.','Rejection is a clue that still needs context.','Penolakan adalah petunjuk yang tetap membutuhkan konteks.'),
    ('chart-hammer-shooting-star','Reading Trading Charts','hammer and shooting-star patterns','pola hammer dan shooting star','Their meaning depends on trend and confirmation, not shape alone.','Maknanya bergantung pada tren dan konfirmasi, bukan bentuk saja.','Pattern names do not guarantee direction.','Nama pola tidak menjamin arah.'),
    ('chart-support-resistance','Reading Trading Charts','support and resistance zones','zona support dan resistance','They are reaction areas, not exact magical prices.','Ini adalah area reaksi, bukan harga ajaib yang pasti.','Zones help plan observation, not certainty.','Zona membantu merencanakan pengamatan, bukan kepastian.'),
    ('chart-trend-and-timeframe','Reading Trading Charts','trend and timeframe','tren dan timeframe','A pattern needs its timeframe and broader context.','Pola membutuhkan timeframe dan konteks yang lebih luas.','One candle cannot describe every timeframe.','Satu candle tidak dapat menjelaskan semua timeframe.'),
    ('chart-reading-limits','Reading Trading Charts','limits of chart reading','batas membaca grafik','Charts cannot guarantee future price or suitability.','Grafik tidak dapat menjamin harga masa depan atau kecocokan keputusan.','Research and risk limits remain necessary.','Riset dan batas risiko tetap diperlukan.'),
    ('decision-multicandle-context','Decision Analysis Lab','multi-candle context','konteks beberapa candle','A sequence gives more context than one candle.','Rangkaian memberi lebih banyak konteks daripada satu candle.','Uncertainty is a valid conclusion.','Ketidakpastian adalah kesimpulan yang valid.'),
    ('decision-volume-confirmation','Decision Analysis Lab','volume confirmation','konfirmasi volume','Volume adds context but does not prove the next move.','Volume menambah konteks tetapi tidak membuktikan langkah berikutnya.','Unusual volume should prompt questions, not copying.','Volume tidak biasa harus memicu pertanyaan, bukan meniru.'),
    ('decision-zones-false-breakouts','Decision Analysis Lab','false breakout','false breakout','Price can leave a zone and return inside it.','Harga dapat keluar dari zona lalu kembali ke dalamnya.','Plan for uncertainty instead of chasing the first move.','Rencanakan ketidakpastian alih-alih mengejar gerakan pertama.'),
    ('decision-timeframe-comparison','Decision Analysis Lab','timeframe comparison','perbandingan timeframe','Short and long charts show different context.','Grafik pendek dan panjang menunjukkan konteks berbeda.','Neither timeframe removes risk.','Tidak ada timeframe yang menghilangkan risiko.'),
    ('decision-risk-reward','Decision Analysis Lab','risk/reward planning','perencanaan risiko/imbalan','It compares possible loss and gain before acting.','Ini membandingkan kemungkinan rugi dan untung sebelum bertindak.','Possible gain is never guaranteed.','Kemungkinan untung tidak pernah dijamin.'),
    ('decision-position-sizing','Decision Analysis Lab','position sizing','ukuran posisi','It limits how much money one idea can expose.','Ini membatasi berapa banyak uang yang terpapar pada satu ide.','Do not risk money needed for essentials.','Jangan mempertaruhkan uang untuk kebutuhan pokok.'),
    ('decision-bias-and-narratives','Decision Analysis Lab','confirmation bias','bias konfirmasi','It is seeking only evidence that supports a belief.','Ini adalah mencari hanya bukti yang mendukung keyakinan.','Write down evidence that could disprove your view.','Tuliskan bukti yang dapat membantah pandanganmu.'),
    ('decision-thesis-invalidation','Decision Analysis Lab','thesis and invalidation rule','tesis dan aturan pembatalan','A thesis explains an idea and an invalidation rule explains when to reassess it.','Tesis menjelaskan ide dan aturan pembatalan menjelaskan kapan perlu menilai ulang.','Writing both improves reflection, not certainty.','Menulis keduanya memperbaiki refleksi, bukan kepastian.')
), inserted AS (
  SELECT l.id, l.difficulty, seed.* FROM seed JOIN lessons l ON l.slug = seed.slug
)
INSERT INTO content_variants (id, lesson_id, variant_type, body, body_id, difficulty, topic_tag, is_active)
SELECT gen_random_uuid(), id, 'explanation', jsonb_build_object('text', definition), jsonb_build_object('text', definition_id), difficulty, chapter, TRUE FROM inserted
UNION ALL
SELECT gen_random_uuid(), id, 'example', jsonb_build_object('text', practice), jsonb_build_object('text', practice_id), difficulty, chapter, TRUE FROM inserted
UNION ALL
SELECT gen_random_uuid(), id, 'question', jsonb_build_object('type','multiple_choice','question','Which description best fits ' || term || '?','options',jsonb_build_array(definition,'A guaranteed trade result','A company earnings report','A tax calculation'),'answer',definition,'explanation',definition,'difficulty',difficulty,'parameters',jsonb_build_object()), jsonb_build_object('type','multiple_choice','question','Deskripsi mana yang paling sesuai untuk ' || term_id || '?','options',jsonb_build_array(definition_id,'Hasil transaksi yang dijamin','Laporan laba perusahaan','Perhitungan pajak'),'answer',definition_id,'explanation',definition_id,'difficulty',difficulty,'parameters',jsonb_build_object()), difficulty, chapter, TRUE FROM inserted
UNION ALL
SELECT gen_random_uuid(), id, 'question', jsonb_build_object('type','true_false','question',term || ' guarantees a profitable trade.','answer',FALSE,'explanation',practice,'difficulty',difficulty,'parameters',jsonb_build_object()), jsonb_build_object('type','true_false','question',term_id || ' menjamin transaksi yang menguntungkan.','answer',FALSE,'explanation',practice_id,'difficulty',difficulty,'parameters',jsonb_build_object()), difficulty, chapter, TRUE FROM inserted
UNION ALL
SELECT gen_random_uuid(), id, 'question', jsonb_build_object('type','multiple_choice','question','What is the safer learning habit here?','options',jsonb_build_array(practice,'Treat one chart as a guarantee','Copy a stranger''s trade','Use money needed for rent'),'answer',practice,'explanation','Charts are practice evidence, not guarantees.','difficulty',difficulty,'parameters',jsonb_build_object()), jsonb_build_object('type','multiple_choice','question','Kebiasaan belajar mana yang lebih aman?','options',jsonb_build_array(practice_id,'Menganggap satu grafik sebagai jaminan','Meniru transaksi orang asing','Memakai uang untuk kos'),'answer',practice_id,'explanation','Grafik adalah bukti latihan, bukan jaminan.','difficulty',difficulty,'parameters',jsonb_build_object()), difficulty, chapter, TRUE FROM inserted;

-- Visual chart-question variants for every Chapter 10/11 lesson. The data is fictional and deterministic.
INSERT INTO content_variants (id, lesson_id, variant_type, body, body_id, difficulty, topic_tag, is_active)
SELECT gen_random_uuid(), l.id, 'question',
  jsonb_build_object('type','chart_interpretation','question','Which practice option closes above its open?','chart',jsonb_build_array(jsonb_build_object('open',100,'high',112,'low',96,'close',108,'label','Context')),'options',jsonb_build_array(
    jsonb_build_object('id','up','label','Option A','chart',jsonb_build_array(jsonb_build_object('open',100,'high',112,'low',96,'close',108,'label','A'))),
    jsonb_build_object('id','down','label','Option B','chart',jsonb_build_array(jsonb_build_object('open',108,'high',112,'low',96,'close',100,'label','B'))),
    jsonb_build_object('id','flat','label','Option C','chart',jsonb_build_array(jsonb_build_object('open',104,'high',112,'low',96,'close',104,'label','C')))
  ),'answer','up','explanation','A close above the open is bullish for that practice candle; it is not a forecast.','difficulty',l.difficulty,'parameters',jsonb_build_object()),
  jsonb_build_object('type','chart_interpretation','question','Pilihan latihan mana yang ditutup di atas harga open?','chart',jsonb_build_array(jsonb_build_object('open',100,'high',112,'low',96,'close',108,'label','Konteks')),'options',jsonb_build_array(
    jsonb_build_object('id','up','label','Pilihan A','chart',jsonb_build_array(jsonb_build_object('open',100,'high',112,'low',96,'close',108,'label','A'))),
    jsonb_build_object('id','down','label','Pilihan B','chart',jsonb_build_array(jsonb_build_object('open',108,'high',112,'low',96,'close',100,'label','B'))),
    jsonb_build_object('id','flat','label','Pilihan C','chart',jsonb_build_array(jsonb_build_object('open',104,'high',112,'low',96,'close',104,'label','C')))
  ),'answer','up','explanation','Close di atas open berarti bullish untuk candle latihan tersebut; ini bukan ramalan.','difficulty',l.difficulty,'parameters',jsonb_build_object()),
  l.difficulty, t.chapter, TRUE
FROM lessons l JOIN topics t ON t.id = l.topic_id
WHERE t.chapter IN ('Reading Trading Charts','Decision Analysis Lab')
  AND NOT EXISTS (SELECT 1 FROM content_variants cv WHERE cv.lesson_id = l.id AND cv.variant_type = 'question' AND cv.body->>'type' = 'chart_interpretation');

INSERT INTO lesson_sources (id, lesson_id, source_id, relevance_type, is_primary)
SELECT gen_random_uuid(), l.id, s.id, 'primary', TRUE
FROM lessons l CROSS JOIN sources s
WHERE l.slug IN ('chart-ohcl-basics','chart-body-and-wick','chart-bullish-bearish-doji','chart-long-wick-rejection','chart-hammer-shooting-star','chart-support-resistance','chart-trend-and-timeframe','chart-reading-limits','decision-multicandle-context','decision-volume-confirmation','decision-zones-false-breakouts','decision-timeframe-comparison','decision-risk-reward','decision-position-sizing','decision-bias-and-narratives','decision-thesis-invalidation')
  AND s.source_code = 'OJK-CHART-001'
ON CONFLICT (lesson_id, source_id) DO NOTHING;

INSERT INTO lesson_reviews (id, lesson_id, reviewer_name, reviewer_role, review_date, factual_accuracy_status, source_verification_status, indonesia_context_status, compliance_status, notes, approved_to_publish)
SELECT gen_random_uuid(), l.id, 'koin-curriculum-agent', 'curriculum-agent', CURRENT_DATE, 'pass', 'pass', 'pass', 'pass', 'Fictional chart practice only; no live-price prediction or recommendation.', TRUE
FROM lessons l
WHERE l.slug IN ('chart-ohcl-basics','chart-body-and-wick','chart-bullish-bearish-doji','chart-long-wick-rejection','chart-hammer-shooting-star','chart-support-resistance','chart-trend-and-timeframe','chart-reading-limits','decision-multicandle-context','decision-volume-confirmation','decision-zones-false-breakouts','decision-timeframe-comparison','decision-risk-reward','decision-position-sizing','decision-bias-and-narratives','decision-thesis-invalidation')
  AND NOT EXISTS (SELECT 1 FROM lesson_reviews lr WHERE lr.lesson_id = l.id);

-- Expand the existing late-curriculum mission contract through Chapters 10–11.
ALTER TABLE chapter_mission_attempts DROP CONSTRAINT IF EXISTS chapter_mission_attempts_chapter_number_check;
ALTER TABLE chapter_mission_attempts ADD CONSTRAINT chapter_mission_attempts_chapter_number_check CHECK (chapter_number BETWEEN 7 AND 11);

CREATE OR REPLACE FUNCTION complete_chapter_mission(p_chapter_number SMALLINT, p_answers JSONB)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user_id UUID := auth.uid(); v_attempt_number INTEGER; v_passed BOOLEAN; v_chapter_name TEXT; v_valid_answers INTEGER; v_correct_answers INTEGER;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF p_chapter_number NOT BETWEEN 7 AND 11 OR jsonb_typeof(p_answers) <> 'array' OR jsonb_array_length(p_answers) <> 3 THEN RAISE EXCEPTION 'A chapter mission needs exactly three answers'; END IF;
  v_chapter_name := CASE p_chapter_number WHEN 7 THEN 'Grow Your Money' WHEN 8 THEN 'Investing in Indonesia' WHEN 9 THEN 'Cryptocurrency 101' WHEN 10 THEN 'Reading Trading Charts' WHEN 11 THEN 'Decision Analysis Lab' END;
  IF EXISTS (SELECT 1 FROM lessons l JOIN topics t ON t.id = l.topic_id LEFT JOIN lesson_progress lp ON lp.user_id = v_user_id AND lp.lesson_id = l.id WHERE l.is_published AND t.chapter = v_chapter_name AND COALESCE(lp.status,'locked') <> 'completed') THEN RAISE EXCEPTION 'Complete every chapter lesson before starting its Money Mission'; END IF;
  WITH submitted AS (SELECT (entry->>'variant_id')::UUID AS variant_id, entry->'response' AS response FROM jsonb_array_elements(p_answers) AS entry), eligible AS (SELECT cv.id, cv.body->'answer' AS answer FROM content_variants cv JOIN lessons l ON l.id = cv.lesson_id JOIN topics t ON t.id = l.topic_id WHERE cv.is_active AND cv.variant_type = 'question' AND cv.body->>'type' IN ('multiple_choice','true_false') AND l.is_published AND t.chapter = v_chapter_name)
  SELECT COUNT(*)::INTEGER, COUNT(*) FILTER (WHERE eligible.answer = submitted.response)::INTEGER INTO v_valid_answers, v_correct_answers FROM submitted JOIN eligible ON eligible.id = submitted.variant_id;
  IF v_valid_answers <> 3 OR (SELECT COUNT(DISTINCT entry->>'variant_id') FROM jsonb_array_elements(p_answers) AS entry) <> 3 THEN RAISE EXCEPTION 'Mission answers must be three distinct questions from this chapter'; END IF;
  SELECT COALESCE(MAX(attempt_number),0)+1 INTO v_attempt_number FROM chapter_mission_attempts WHERE user_id=v_user_id AND chapter_number=p_chapter_number;
  v_passed := v_correct_answers = 3;
  INSERT INTO chapter_mission_attempts (user_id,chapter_number,attempt_number,score,max_score,passed,completed_at) VALUES (v_user_id,p_chapter_number,v_attempt_number,v_correct_answers,3,v_passed,CASE WHEN v_passed THEN NOW() ELSE NULL END);
  RETURN jsonb_build_object('attempt_number',v_attempt_number,'passed',v_passed,'score',v_correct_answers,'max_score',3);
END;
$$;

COMMIT;
