-- KO-322: every published Chapter 08 source must expose a bilingual summary
-- so the lesson player can render both Read source and See summary actions.

BEGIN;

WITH source_updates(source_code, synopsis, synopsis_id, relevance_blurb, relevance_blurb_id) AS (
  VALUES
    ('CH08-BI-INFLATION',
      'Bank Indonesia information explaining inflation as a change in the general level of prices and its role in monetary context.',
      'Informasi Bank Indonesia yang menjelaskan inflasi sebagai perubahan tingkat harga umum dan perannya dalam konteks moneter.',
      'Use this official indicator as dated macro context; it does not predict the return of a particular stock.',
      'Gunakan indikator resmi ini sebagai konteks makro bertanggal; indikator ini tidak memprediksi imbal hasil saham tertentu.'),
    ('CH08-BI-JISDOR',
      'Bank Indonesia reference information for JISDOR, a reference rate used to describe the Indonesian rupiah against the US dollar.',
      'Informasi referensi Bank Indonesia untuk JISDOR, yaitu kurs referensi untuk menggambarkan rupiah Indonesia terhadap dolar AS.',
      'The reference rate helps learners read currency context without treating one exchange-rate observation as a market forecast.',
      'Kurs referensi membantu pelajar membaca konteks mata uang tanpa menganggap satu pengamatan kurs sebagai ramalan pasar.'),
    ('CH08-BI-RATE',
      'Bank Indonesia information for the BI-Rate policy indicator and its role in the monetary-policy context.',
      'Informasi Bank Indonesia untuk indikator kebijakan BI-Rate dan perannya dalam konteks kebijakan moneter.',
      'This source anchors a rate observation in the official institution; the effect on an asset still depends on channels and timing.',
      'Sumber ini menempatkan pengamatan suku bunga pada institusi resmi; dampaknya pada aset tetap bergantung pada jalur dan waktu.'),
    ('CH08-DJP-DEADLINES',
      'DJP reference information for deadlines used when reporting tax obligations in Indonesia.',
      'Informasi referensi DJP tentang batas waktu yang digunakan saat melaporkan kewajiban pajak di Indonesia.',
      'Check the current official deadline instead of copying an old example or relying on an unverified reminder.',
      'Periksa batas waktu resmi terbaru, bukan menyalin contoh lama atau mengandalkan pengingat yang tidak terverifikasi.'),
    ('CH08-DJP-PPH21',
      'DJP guidance about withholding and reporting Income Tax Article 21 in Indonesia.',
      'Panduan DJP tentang pemotongan dan pelaporan Pajak Penghasilan Pasal 21 di Indonesia.',
      'The official guidance keeps a lesson example separate from the rules that apply to a person and reporting period.',
      'Panduan resmi membantu memisahkan contoh pelajaran dari aturan yang berlaku bagi seseorang dan periode pelaporan.'),
    ('CH08-DJP-SPT',
      'DJP guidance for reporting an annual income tax return, including the official route for checking current instructions.',
      'Panduan DJP untuk melaporkan SPT Tahunan Pajak Penghasilan, termasuk jalur resmi untuk memeriksa petunjuk terbaru.',
      'Use the current DJP route to verify a filing example, required information, and confirmation of submission.',
      'Gunakan jalur DJP terbaru untuk memverifikasi contoh pelaporan, informasi yang diperlukan, dan konfirmasi pengiriman.'),
    ('CH08-DJP-SPT-INDIVIDUAL',
      'DJP service information for an individual taxpayer reporting an annual income tax return.',
      'Informasi layanan DJP untuk wajib pajak orang pribadi yang melaporkan SPT Tahunan Pajak Penghasilan.',
      'This service page gives individual learners a current official starting point; personal facts and the applicable period still matter.',
      'Halaman layanan ini memberi titik awal resmi bagi pelajar orang pribadi; fakta pribadi dan periode yang berlaku tetap penting.'),
    ('CH08-DJPPR-ORI',
      'DJPPR information about Obligasi Negara Ritel, a retail government-security product offered under stated series terms.',
      'Informasi DJPPR tentang Obligasi Negara Ritel, produk surat berharga negara ritel yang ditawarkan dengan ketentuan seri tertentu.',
      'Read the named series and current terms before using an illustrative coupon or access example.',
      'Baca seri yang disebutkan dan ketentuan terbaru sebelum menggunakan contoh kupon atau akses ilustratif.'),
    ('CH08-IDX-ETF-LIST',
      'IDX reference list for exchange-traded funds listed on the Indonesia Stock Exchange.',
      'Daftar referensi IDX untuk exchange-traded fund yang tercatat di Bursa Efek Indonesia.',
      'The list supports checking a fund name and listing context; it is not a promise about price, liquidity, or suitability.',
      'Daftar ini membantu memeriksa nama fund dan konteks pencatatan; bukan janji tentang harga, likuiditas, atau kecocokan.'),
    ('CH08-IDX-ETF-OVERVIEW',
      'IDX overview explaining exchange-traded funds as exchange-traded products with a stated investment objective.',
      'Ikhtisar IDX yang menjelaskan exchange-traded fund sebagai produk yang diperdagangkan di bursa dengan tujuan investasi tertentu.',
      'Use the overview to understand the product structure, then check the current fund documents, costs, tracking, and risks.',
      'Gunakan ikhtisar untuk memahami struktur produk, lalu periksa dokumen fund, biaya, pelacakan, dan risiko terbaru.'),
    ('CH08-IDX-STOCKS',
      'IDX product information describing stocks as listed ownership instruments traded on the Indonesian Stock Exchange.',
      'Informasi produk IDX yang menjelaskan saham sebagai instrumen kepemilikan yang tercatat dan diperdagangkan di Bursa Efek Indonesia.',
      'This source grounds stock vocabulary and ownership concepts in the exchange that lists the instruments.',
      'Sumber ini mengaitkan istilah saham dan konsep kepemilikan dengan bursa yang mencatat instrumen tersebut.'),
    ('CH08-IDX-TRADING',
      'IDX reference information for trading hours and the exchange trading mechanism.',
      'Informasi referensi IDX tentang jam perdagangan dan mekanisme perdagangan bursa.',
      'Use the current exchange rules when checking lots, order timing, and what an illustrative order calculation does not guarantee.',
      'Gunakan aturan bursa terbaru saat memeriksa lot, waktu order, dan hal yang tidak dijamin oleh perhitungan order ilustratif.'),
    ('CH08-KEMENKEU-SBN',
      'Kementerian Keuangan education about retail government securities and the features learners should verify before deciding.',
      'Edukasi Kementerian Keuangan tentang surat berharga negara ritel dan fitur yang perlu diperiksa sebelum mengambil keputusan.',
      'The education page provides context; the named series, current terms, access route, tax, and risks still require checking.',
      'Halaman edukasi memberi konteks; seri, ketentuan terbaru, jalur akses, pajak, dan risiko tetap perlu diperiksa.'),
    ('CH08-KSEI-RDN',
      'KSEI operating-procedure information for the infrastructure and processes supporting Indonesian securities accounts.',
      'Informasi prosedur operasional KSEI untuk infrastruktur dan proses yang mendukung rekening efek di Indonesia.',
      'This is a primary institutional reference for separating an official account process from an unverified funding message.',
      'Ini adalah referensi institusional utama untuk membedakan proses rekening resmi dari pesan pendanaan yang tidak terverifikasi.'),
    ('CH08-OJK-CAPITAL',
      'OJK capital-market information covering the regulated Indonesian capital-market context and investor-facing guidance.',
      'Informasi pasar modal OJK yang mencakup konteks pasar modal Indonesia yang diatur dan panduan bagi investor.',
      'Use the regulator’s channel to check the framework around market products, licensing, and investor protection.',
      'Gunakan kanal regulator untuk memeriksa kerangka produk pasar, perizinan, dan perlindungan investor.'),
    ('CH08-OJK-FIND',
      'OJK Financial Institutions Directory for checking financial institutions and their official regulatory information.',
      'Direktori Lembaga Jasa Keuangan OJK untuk memeriksa lembaga keuangan dan informasi regulasi resminya.',
      'The directory is a verification step before trusting a provider, account instruction, or investment-related message.',
      'Direktori ini menjadi langkah verifikasi sebelum mempercayai penyedia, petunjuk rekening, atau pesan terkait investasi.'),
    ('CH08-OJK-RDN',
      'OJK guidance for opening securities and customer-fund accounts electronically through a registered provider.',
      'Pedoman OJK untuk membuka rekening efek dan rekening dana nasabah secara elektronik melalui penyedia terdaftar.',
      'Check the provider, account structure, and current instructions against official guidance before funding an account.',
      'Periksa penyedia, struktur rekening, dan petunjuk terbaru terhadap pedoman resmi sebelum mengisi dana.'),
    ('CH08-OJK-SBN-GUIDE',
      'OJK capital-market pocketbook introducing market products, their risks, and basic investor-protection concepts.',
      'Buku saku pasar modal OJK yang memperkenalkan produk pasar, risikonya, dan konsep dasar perlindungan investor.',
      'The pocketbook supports a risk-aware explanation; it does not turn a product description into a guaranteed return.',
      'Buku saku ini mendukung penjelasan yang sadar risiko; deskripsi produk bukan jaminan imbal hasil.')
)
UPDATE public.sources AS source
SET synopsis = COALESCE(NULLIF(source.synopsis, ''), updates.synopsis),
    synopsis_id = COALESCE(NULLIF(source.synopsis_id, ''), updates.synopsis_id),
    relevance_blurb = COALESCE(NULLIF(source.relevance_blurb, ''), updates.relevance_blurb),
    relevance_blurb_id = COALESCE(NULLIF(source.relevance_blurb_id, ''), updates.relevance_blurb_id)
FROM source_updates AS updates
WHERE source.source_code = updates.source_code;

COMMIT;
