-- Migration 044: Track whether market data is simulated or sourced from IDX.
-- Also backfill existing rows as simulated so the disclaimer is accurate.

BEGIN;

ALTER TABLE market_data
ADD COLUMN IF NOT EXISTS is_simulated BOOLEAN NOT NULL DEFAULT TRUE;

COMMENT ON COLUMN market_data.is_simulated IS 'TRUE when the row was generated by the synthetic drift simulator; FALSE when sourced from IDX public data.';

-- Backfill existing rows to simulated, since historical seed data was generated.
UPDATE market_data SET is_simulated = TRUE WHERE is_simulated IS NULL;

-- Update the synthetic seeder to mark its rows clearly.
CREATE OR REPLACE FUNCTION seed_next_market_data(
  p_trade_date DATE DEFAULT CURRENT_DATE
) RETURNS TABLE(symbol TEXT, close_price NUMERIC(12,2))
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_latest RECORD;
  v_change_pct NUMERIC(5,4);
  v_new_close NUMERIC(12,2);
  v_new_open NUMERIC(12,2);
  v_new_high NUMERIC(12,2);
  v_new_low NUMERIC(12,2);
BEGIN
  FOR v_latest IN
    SELECT DISTINCT ON (m.symbol)
      m.symbol,
      m.company_name,
      m.close_price,
      m.volume
    FROM market_data m
    ORDER BY m.symbol, m.trade_date DESC
  LOOP
    -- Skip if we already have data for this date.
    IF EXISTS (SELECT 1 FROM market_data WHERE market_data.symbol = v_latest.symbol AND market_data.trade_date = p_trade_date) THEN
      CONTINUE;
    END IF;

    -- Random daily change between -3% and +3% using a deterministic-ish seed.
    v_change_pct := ((random() * 0.06) - 0.03);
    v_new_close := ROUND(v_latest.close_price * (1 + v_change_pct));
    v_new_open := ROUND(v_latest.close_price * (1 + ((random() * 0.02) - 0.01)));
    v_new_high := GREATEST(v_new_open, v_new_close) * (1 + (random() * 0.01));
    v_new_low := LEAST(v_new_open, v_new_close) * (1 - (random() * 0.01));

    INSERT INTO market_data (symbol, company_name, trade_date, open_price, high_price, low_price, close_price, volume, source_url, is_simulated)
    VALUES (
      v_latest.symbol,
      v_latest.company_name,
      p_trade_date,
      v_new_open,
      ROUND(v_new_high),
      ROUND(v_new_low),
      v_new_close,
      v_latest.volume,
      'https://www.idx.co.id/id-id/data-pasar/ringkasan-perdagangan/ringkasan-saham/',
      TRUE
    );

    symbol := v_latest.symbol;
    close_price := v_new_close;
    RETURN NEXT;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION seed_next_market_data(DATE) TO authenticated, anon;

COMMIT;
