-- KO-225 group 5 exact duplicate translation batch 3

update public.content_variants set body = $json${"text":"Rina received an email that appeared to be from OVO asking for data verification. The sender's email address is ov0-support@gmail.com. Rina was suspicious because the domain was unofficial and deleted the email."}$json$::jsonb where id = '1516d4c8-f9a9-4968-84e2-42a446f9bb42';
update public.content_variants set body = $json${"text":"A budget is a plan for using money. The 50/30/20 rule divides income: 50% for needs, 30% for wants, and 20% for savings and paying off debt. In Indonesia, students or young workers can adjust this proportion according to the cost of living and family responsibilities. The most important thing is to record expenses and review the budget regularly.","ai_assist_context":"Help users create a simple budget with the 50/30/20 rule using examples of income and living costs in Indonesia."}$json$::jsonb where id = '16a15e36-a8f3-471a-8c40-a3b2260fcb0a';
update public.content_variants set body = $json${"text":"IDX is the Indonesian Stock Exchange. On IDX, 1 lot = 100 shares. Weekday trading with specific hours."}$json$::jsonb where id = '16ecd02c-a7df-4c04-bb0a-3b020331325a';
update public.content_variants set body = $json${"text":"GOTO stock prices change daily as many people buy and sell. If more people want to buy, the price goes up. If more want to sell, the price falls."}$json$::jsonb where id = '18c5bb40-f173-4049-ab99-eb977492ffc3';
update public.content_variants set body = $json${"text":"Dewa, a design freelancer, has a variable income. In busy months he saves 30% of his income, in slow months he uses these savings without taking on debt.","source_ids":["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}$json$::jsonb where id = '18eb5284-ee42-4d0c-9998-7127797cf8d3';
update public.content_variants set body = $json${"text":"Doni has IDR 100,000. In the school canteen, that money can buy 10 portions of fried rice. At the mall, the price of fried rice is IDR 35,000, so the money is only enough for 2 portions. Location and situation change purchasing power."}$json$::jsonb where id = '1bd65e9d-3dc2-4330-ad39-c629ba8c7202';
update public.content_variants set body = $json${"text":"Volume indicates liquidity. Stocks with high volume are easier to buy and sell without moving the price too much."}$json$::jsonb where id = '1c335ff0-57be-4df0-b9f5-1be6fbc63d83';
update public.content_variants set body = $json${"text":"Doni wants to buy 75 shares of TLKM. On the Indonesian Stock Exchange, shares are traded in lots consisting of 100 shares. Doni must buy a minimum of 1 lot or 100 shares."}$json$::jsonb where id = '1cdfd723-cfba-47ba-84d3-eace3c5c1d05';
update public.content_variants set body = $json${"text":"A mutual fund advertises returns of 10% per year. After final taxes on interest or dividends, the net return received by investors can be lower, for example 8.5%."}$json$::jsonb where id = '1d0a6089-7924-4db3-8916-a184fc92ce4b';
update public.content_variants set body = $json${"text":"Red flag pyramid: the main focus is recruiting, not selling products; having to buy expensive packages; promise of easy money; unsustainable multi-level schemes."}$json$::jsonb where id = '20bc940b-cee4-4dcf-bf4a-cbf6c8dd8e2d';

