-- KO-225 group 5 continuation batch 14

update public.content_variants set body_id = $json${"type":"matching","pairs":[["Makanan dasar","Membutuhkan"],["Konsol game terbaru","Ingin"],["Sewa untuk perumahan","Membutuhkan"],["Sepatu kets desainer","Ingin"]],"answer":{"Basic food":"Membutuhkan","Rent for housing":"Membutuhkan","Designer sneakers":"Ingin","Latest gaming console":"Ingin"},"question":"Cocokkan setiap item dengan apakah itu biasanya merupakan kebutuhan atau keinginan.","difficulty":"beginner","parameters":{},"explanation":"Kebutuhan merupakan hal yang penting untuk hidup. Keinginan adalah hal-hal yang kita inginkan tetapi kita dapat hidup tanpanya."}$json$::jsonb where id = 'ac5554b1-bdbf-4d20-8928-e0845a72c51e';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["kebutuhan","ingin"],"options":["kebutuhan","ingin","tabungan","dana darurat"],"question":"Perencanaan keuangan dimulai dengan membedakan ________ dari ________, kemudian membangun cadangan.","difficulty":"beginner","parameters":{},"explanation":"Kata-kata yang benar dari bank adalah: kebutuhan, keinginan."}$json$::jsonb where id = 'acc48124-1c81-4516-be68-8381be8a8d5e';
update public.content_variants set body_id = $json${"type":"comparison","answer":"Rekening tabungan dengan hasil tinggi","options":["Rekening tabungan dengan hasil tinggi","Portofolio saham","Keduanya sama-sama tepat","Dompet mata uang kripto"],"question":"Untuk dana darurat: apakah rekening tabungan dengan imbal hasil tinggi atau portofolio saham lebih tepat?","difficulty":"advanced","parameters":{},"explanation":"Dana darurat membutuhkan likuiditas dan pelestarian modal, yang mana rekening tabungan menyediakan lebih baik daripada saham yang bergejolak."}$json$::jsonb where id = 'acfde6d9-c8c0-4653-bbe3-d0516305f5f9';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"jatuh","options":["bangkit","jatuh","tetap tidak berubah","menjadi lebih fluktuatif"],"question":"Ketika bank sentral menaikkan suku bunga, harga obligasi umumnya ________.","difficulty":"intermediate","parameters":{},"explanation":"Harga obligasi dan suku bunga memiliki hubungan terbalik. Suku bunga yang lebih tinggi berarti obligasi yang ada menjadi kurang menarik."}$json$::jsonb where id = 'adfafc81-abd6-4730-8582-ed18e760b7d2';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["OJK","DUA"],"options":["OJK","DUA","BEI","SIPF"],"question":"Di Indonesia, ________ mengatur jasa keuangan sementara ________ mengatur kebijakan moneter.","difficulty":"advanced","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah: OJK, BI."}$json$::jsonb where id = 'ae7c445a-61c6-4d59-a2c8-efba41c8e77e';
update public.content_variants set body_id = $json${"type":"sentence_completion","answer":"berkurang","options":["meningkat","berkurang","tetap sama","menjadi tidak relevan"],"question":"Jika inflasi naik sementara suku bunga tetap, keuntungan riil dari tabungan adalah ________.","difficulty":"intermediate","parameters":{},"explanation":"Pengembalian riil = pengembalian nominal - inflasi. Jika inflasi meningkat dan return nominal tetap, return riil akan turun."}$json$::jsonb where id = 'af5d5732-90fe-4b87-b238-26d6739a0bcb';
update public.content_variants set body = $json${"text":"Every time his salary comes in, Doni immediately transfers IDR 300,000 to a separate savings account before buying credit or coffee. Only after that did he manage daily expenses. His savings grew without making any sacrifices."}$json$::jsonb where id = 'af6ecdf9-147a-4f50-a20f-101a2b8d664a';
update public.content_variants set body_id = $json${"type":"ordering","answer":["Tetapkan tujuan keuangan","Lacak pendapatan dan pengeluaran","Buat anggaran","Membangun dana darurat","Mulailah berinvestasi"],"options":["Tetapkan tujuan keuangan","Lacak pendapatan dan pengeluaran","Buat anggaran","Membangun dana darurat","Mulailah berinvestasi"],"question":"Pesanlah langkah-langkah berikut untuk membangun landasan keuangan yang kokoh:","difficulty":"beginner","parameters":{},"explanation":"Urutan yang benar adalah: Tetapkan tujuan keuangan → Lacak pendapatan dan pengeluaran → Buat anggaran → Bangun dana darurat → Mulai berinvestasi"}$json$::jsonb where id = 'affbfafa-5608-41af-86a0-31b144c9d5d5';
update public.content_variants set body = $json${"text":"Inflation is a general increase in the prices of goods and services over a certain period of time. Bank Indonesia targets inflation of around 2.5% ± 1% so that the economy remains stable. If bank savings provide interest lower than inflation, the purchasing power of money decreases. Therefore, understanding inflation is important before choosing a long-term savings or investment instrument.","ai_assist_context":"Explain inflation using BI targets and examples of food prices in Indonesia. Avoid specific investment product recommendations."}$json$::jsonb where id = 'b002ee98-a550-47ad-af12-2e5df8b0a0da';
update public.content_variants set body = $json${"text":"Diversification is a strategy to spread risk, not seek maximum profit. By choosing different types of assets and sectors, you reduce the impact if one investment fails. Remember: don't put all your eggs in one basket.","ai_assist_context":"Explain diversification as a way to reduce risk with the example of Indonesian stocks and instruments."}$json$::jsonb where id = 'b0d293ed-a2f6-44ee-8024-4c291b908efc';

