-- KO-225 group 5: reviewed translation of Indonesian-shaped duplicate payloads (batch 02).
update public.content_variants set body = $json${"text":"Maya distinguishes between needs and wants before shopping online. Needs: skincare is finished, dish soap, and vitamins. Wants: new shoes at a 50% discount. Maya buys the needs first, postponing the wants until her savings are enough.","source_ids":["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}$json$::jsonb where id = '3f64eb98-df19-4e00-b1dd-de9bd23050b8';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Check the license with OJK and discuss with an adult","options":["Transfer immediately","Check the license with OJK and discuss with an adult","Invite all friends to join","Borrow money to join"],"question":"What should you do if there is a suspicious investment offer?","difficulty":"beginner","parameters":{},"explanation":"Verifying the OJK license and consulting helps avoid fraudulent investments."}$json$::jsonb where id = '4264992d-c335-40c5-ab99-867504b5fe74';
update public.content_variants set body = $json${"type":"word_bank","answer":["OJK"],"options":["OJK","BI"],"question":"Complete the following sentence with a word from the word bank: \"Before investing money, make sure the company is registered and supervised by _____.\"","difficulty":"beginner","parameters":{},"explanation":"The Financial Services Authority (OJK) oversees financial products and companies in Indonesia."}$json$::jsonb where id = '5946e30e-bfc2-44b7-92b2-ef051668faa6';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Investments that promise high returns and are guaranteed safe without risk are usually trustworthy.","difficulty":"beginner","parameters":{},"explanation":"Offers with high returns and guarantees without risk are common traits of illegal investments. Always check the OJK license."}$json$::jsonb where id = '5de2b587-a0f8-43d3-9eef-e4758b9acfa3';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Selling good stocks too quickly out of fear of loss","options":["Selling good stocks too quickly out of fear of loss","Buying stocks with thorough research","Spreading investments across many sectors","Saving regularly every month"],"question":"Loss aversion is most evident when investors ...","difficulty":"intermediate","parameters":{},"explanation":"Loss aversion often causes investors to sell assets even though their fundamentals are still good."}$json$::jsonb where id = '6f1b6379-3409-4c08-ab8a-b1fc9f08e5ec';
update public.content_variants set body = $json${"text":"Money is a medium of exchange that must be managed wisely. The first step is to distinguish between needs (something that must be fulfilled for living and learning) and wants (something enjoyable but can be postponed). The second step is to be cautious of investment offers that promise high returns without risk. Always check the financial product license on the OJK website before deciding to invest.","ai_assist_context":"Help users understand the difference between needs and wants in the context of Indonesian students, and teach how to verify financial product licenses through OJK."}$json$::jsonb where id = '733bc7a1-db7b-41e0-b884-909606956be0';
update public.content_variants set body = $json${"type":"word_bank","answer":["Record income","Separate needs & wants","Set aside savings","Evaluate expenses"],"options":["Record income","Separate needs & wants","Set aside savings","Evaluate expenses"],"question":"Arrange the steps for healthy money management: ____","difficulty":"beginner","parameters":{},"explanation":"Record, separate, save, then evaluate is a cycle of healthy money management."}$json$::jsonb where id = '7eb56dbe-51e8-46f0-baca-a3ff3441b448';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Healthcare costs or urgent needs","options":["Buy a new gadget","Healthcare costs or urgent needs","Vacation to Bali","All answers are correct"],"question":"An emergency fund is important for?","difficulty":"beginner","parameters":{},"explanation":"An emergency fund is used for unexpected needs, not wants."}$json$::jsonb where id = '83f9de68-4479-45df-b70a-df1b88367a1e';
update public.content_variants set body = $json${"text":"Money has three main functions: medium of exchange, store of value, and unit of account. GoPay, OVO, or bank balances are considered digital money because they can be used for all three functions."}$json$::jsonb where id = '85b063c5-fa50-4b4e-bd8c-b932f6780689';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Money left after meeting needs should be saved for urgent needs.","difficulty":"beginner","parameters":{},"explanation":"Setting aside leftover money for an emergency fund is a good financial habit."}$json$::jsonb where id = '86053d43-11ff-4b24-be42-30c9f573809a';
