-- KO-247: guided fill-blank and expanded, standalone Daily Focus practice bank.
-- Keep this curriculum content local/private; lesson content_variants are not used.

BEGIN;

-- Every legacy fill-blank now has the same guided-choice affordance as lesson quiz.
UPDATE daily_focus_questions
SET body = jsonb_set(body, '{options}', jsonb_build_array(body->>'answer', 'budget', 'risk', 'cash flow'), true)
WHERE type = 'fill_blank' AND NOT (body ? 'options');

UPDATE daily_focus_questions
SET body = jsonb_set(body, '{locales,en,options}', jsonb_build_array(body->'locales'->'en'->>'answer', 'budget', 'risk', 'cash flow'), true)
WHERE type = 'fill_blank' AND body->'locales' ? 'en' AND NOT (body->'locales'->'en' ? 'options');

UPDATE daily_focus_questions
SET body = jsonb_set(body, '{locales,id,options}', jsonb_build_array(body->'locales'->'id'->>'answer', 'anggaran', 'risiko', 'arus kas'), true)
WHERE type = 'fill_blank' AND body->'locales' ? 'id' AND NOT (body->'locales'->'id' ? 'options');

INSERT INTO daily_focus_questions (id, chapter, topic, difficulty, type, body, is_active) VALUES
('DF4-001', 'Foundation 0', 'financial_decisions', 'intermediate', 'multiple_choice', $$
{"type":"multiple_choice","difficulty":"intermediate","question":"You receive a Rp 2,000,000 bonus. Which choice best turns it into a financial buffer?","options":["Put it in a separate emergency-fund account","Spend it before the month ends","Use pay-later to buy more than the bonus","Lend it without a repayment plan"],"answer":"Put it in a separate emergency-fund account","explanation":"A windfall can strengthen resilience when it is separated before spending pressure takes over.","locales":{"id":{"type":"multiple_choice","difficulty":"intermediate","question":"Kamu menerima bonus Rp2.000.000. Pilihan mana yang paling membantu membangun penyangga keuangan?","options":["Masukkan ke rekening dana darurat terpisah","Habiskan sebelum bulan berakhir","Gunakan pay-later untuk membeli lebih banyak","Pinjamkan tanpa rencana pengembalian"],"answer":"Masukkan ke rekening dana darurat terpisah","explanation":"Bonus bisa memperkuat ketahanan keuangan jika dipisahkan sebelum muncul dorongan untuk berbelanja."}}
}$$::jsonb, true),
('DF4-002', 'Foundation 0', 'financial_decisions', 'intermediate', 'true_false', $$
{"type":"true_false","difficulty":"intermediate","question":"A higher salary can improve cash flow but still fail to build wealth if spending rises just as fast.","answer":true,"explanation":"Wealth grows from the gap between what comes in and what is retained in assets, not income alone.","locales":{"id":{"type":"true_false","difficulty":"intermediate","question":"Gaji yang lebih tinggi bisa memperbaiki arus kas, tetapi tetap tidak membangun kekayaan jika pengeluaran naik sama cepatnya.","answer":true,"explanation":"Kekayaan tumbuh dari selisih antara uang yang masuk dan yang disimpan menjadi aset, bukan dari pendapatan saja."}}
}$$::jsonb, true),
('DF4-003', 'Money Life Skills', 'financial_decisions', 'intermediate', 'fill_blank', $$
{"type":"fill_blank","difficulty":"intermediate","question":"Before accepting a new monthly subscription, compare its recurring _____ with a goal you are funding.","options":["cost","return","tax","discount"],"answer":"cost","explanation":"Recurring costs compound into large annual commitments, so compare them with a goal before subscribing.","locales":{"id":{"type":"fill_blank","difficulty":"intermediate","question":"Sebelum mengambil langganan bulanan baru, bandingkan _____ berulangnya dengan tujuan keuanganmu.","options":["biaya","imbal hasil","pajak","diskon"],"answer":"biaya","explanation":"Biaya berulang bisa menjadi komitmen tahunan yang besar, jadi bandingkan dulu dengan tujuanmu."}}
}$$::jsonb, true),
('DF4-004', 'Money Life Skills', 'financial_decisions', 'intermediate', 'word_bank', $$
{"type":"word_bank","difficulty":"intermediate","question":"A sinking fund sets aside money before a predictable _____ arrives.","options":["expense","profit","discount","salary"],"answer":["expense"],"explanation":"Saving gradually for annual fees or repairs prevents a predictable bill from becoming emergency debt.","locales":{"id":{"type":"word_bank","difficulty":"intermediate","question":"Sinking fund menyisihkan uang sebelum _____ yang sudah diperkirakan datang.","options":["pengeluaran","keuntungan","diskon","gaji"],"answer":["pengeluaran"],"explanation":"Menabung bertahap untuk biaya tahunan atau perbaikan mencegah tagihan rutin berubah menjadi utang darurat."}}
}$$::jsonb, true),
('DF4-005', 'Plan Your Money', 'financial_decisions', 'intermediate', 'select_all', $$
{"type":"select_all","difficulty":"intermediate","question":"Select ALL questions worth asking before a large purchase.","options":["Is it planned and affordable?","What goal would this delay?","What is the total cost including fees?","Will a countdown timer make the decision for me?"],"answer":["Is it planned and affordable?","What goal would this delay?","What is the total cost including fees?"],"explanation":"A short pause exposes trade-offs, total cost, and whether the purchase fits the plan.","locales":{"id":{"type":"select_all","difficulty":"intermediate","question":"Pilih SEMUA pertanyaan yang layak ditanyakan sebelum pembelian besar.","options":["Apakah pembelian ini terencana dan terjangkau?","Tujuan apa yang mungkin tertunda?","Berapa total biaya termasuk biaya tambahan?","Apakah penghitung waktu harus menentukan keputusan saya?"],"answer":["Apakah pembelian ini terencana dan terjangkau?","Tujuan apa yang mungkin tertunda?","Berapa total biaya termasuk biaya tambahan?"],"explanation":"Jeda singkat membantu melihat trade-off, total biaya, dan kecocokan dengan rencana."}}
}$$::jsonb, true),
('DF4-006', 'Plan Your Money', 'financial_decisions', 'intermediate', 'ordering', $$
{"type":"ordering","difficulty":"intermediate","question":"Order the steps for turning an irregular annual bill into a monthly plan.","options":["Estimate the annual total","Divide it across the months","Open or label a separate fund","Transfer the monthly amount","Pay from that fund when due"],"answer":["Estimate the annual total","Divide it across the months","Open or label a separate fund","Transfer the monthly amount","Pay from that fund when due"],"explanation":"Planning before the due date turns a surprise-looking bill into a manageable routine.","locales":{"id":{"type":"ordering","difficulty":"intermediate","question":"Urutkan langkah mengubah tagihan tahunan yang tidak rutin menjadi rencana bulanan.","options":["Perkirakan total tahunan","Bagi total ke beberapa bulan","Buka atau beri label rekening terpisah","Transfer jumlah bulanan","Bayar dari dana itu saat jatuh tempo"],"answer":["Perkirakan total tahunan","Bagi total ke beberapa bulan","Buka atau beri label rekening terpisah","Transfer jumlah bulanan","Bayar dari dana itu saat jatuh tempo"],"explanation":"Perencanaan sebelum jatuh tempo membuat tagihan yang terlihat mendadak menjadi rutinitas yang terkelola."}}
}$$::jsonb, true),
('DF4-007', 'Grow Your Money', 'financial_decisions', 'advanced', 'matching', $$
{"type":"matching","difficulty":"advanced","question":"Match the decision habit with the behaviour it encourages.","pairs":[["Diversify","Avoid one outcome dominating the portfolio"],["Rebalance","Return risk weights to the plan"],["Automate","Reduce reliance on willpower"],["Verify fees","Compare the return you actually keep"]],"answer":{"Diversify":"Avoid one outcome dominating the portfolio","Rebalance":"Return risk weights to the plan","Automate":"Reduce reliance on willpower","Verify fees":"Compare the return you actually keep"},"explanation":"Good systems make sensible behaviour easier before emotions take over.","locales":{"id":{"type":"matching","difficulty":"advanced","question":"Pasangkan kebiasaan keputusan dengan perilaku yang didorongnya.","pairs":[["Diversifikasi","Mencegah satu hasil mendominasi portofolio"],["Rebalancing","Mengembalikan bobot risiko ke rencana"],["Otomatiskan","Mengurangi ketergantungan pada kemauan"],["Periksa biaya","Membandingkan imbal yang benar-benar tersisa"]],"answer":{"Diversifikasi":"Mencegah satu hasil mendominasi portofolio","Rebalancing":"Mengembalikan bobot risiko ke rencana","Otomatiskan":"Mengurangi ketergantungan pada kemauan","Periksa biaya":"Membandingkan imbal yang benar-benar tersisa"},"explanation":"Sistem yang baik membuat perilaku yang masuk akal lebih mudah sebelum emosi mengambil alih."}}
}$$::jsonb, true),
('DF4-008', 'Grow Your Money', 'financial_decisions', 'advanced', 'multiple_choice', $$
{"type":"multiple_choice","difficulty":"advanced","question":"Two funds track the same market. Fund A charges 0.2% yearly and Fund B charges 1.5%. What should you compare next?","options":["Whether their holdings and tracking quality are genuinely comparable","Only the fund with the higher fee","Which logo looks more professional","Whether either fund guarantees profit"],"answer":"Whether their holdings and tracking quality are genuinely comparable","explanation":"A fee comparison matters only after confirming the products provide a comparable exposure and service.","locales":{"id":{"type":"multiple_choice","difficulty":"advanced","question":"Dua reksa dana mengikuti pasar yang sama. Dana A mengenakan 0,2% per tahun dan Dana B 1,5%. Apa yang perlu dibandingkan berikutnya?","options":["Apakah isi dan kualitas pelacakannya benar-benar sebanding","Hanya dana dengan biaya lebih tinggi","Logo mana yang terlihat lebih profesional","Apakah salah satunya menjamin keuntungan"],"answer":"Apakah isi dan kualitas pelacakannya benar-benar sebanding","explanation":"Perbandingan biaya baru bermakna setelah memastikan produk memberi eksposur dan layanan yang sebanding."}}
}$$::jsonb, true),
('DF4-009', 'Protect Yourself', 'financial_decisions', 'intermediate', 'true_false', $$
{"type":"true_false","difficulty":"intermediate","question":"A familiar brand name is not proof that a payment link or investment offer is genuine.","answer":true,"explanation":"Impersonation attacks borrow trusted logos; verify through the official app or website instead of the message link.","locales":{"id":{"type":"true_false","difficulty":"intermediate","question":"Nama merek yang dikenal bukan bukti bahwa tautan pembayaran atau tawaran investasi itu asli.","answer":true,"explanation":"Penipu meniru logo tepercaya; verifikasi melalui aplikasi atau situs resmi, bukan tautan dalam pesan."}}
}$$::jsonb, true),
('DF4-010', 'Protect Yourself', 'financial_decisions', 'intermediate', 'select_all', $$
{"type":"select_all","difficulty":"intermediate","question":"Select ALL safe habits for protecting a new brokerage account.","options":["Use a unique password","Enable two-factor authentication","Verify the broker through the official regulator","Share an OTP with support if they sound urgent"],"answer":["Use a unique password","Enable two-factor authentication","Verify the broker through the official regulator"],"explanation":"Account security combines unique credentials, a second factor, and regulated counterparties.","locales":{"id":{"type":"select_all","difficulty":"intermediate","question":"Pilih SEMUA kebiasaan aman untuk melindungi rekening efek baru.","options":["Gunakan kata sandi unik","Aktifkan autentikasi dua faktor","Verifikasi pialang melalui regulator resmi","Bagikan OTP kepada dukungan jika terdengar mendesak"],"answer":["Gunakan kata sandi unik","Aktifkan autentikasi dua faktor","Verifikasi pialang melalui regulator resmi"],"explanation":"Keamanan rekening menggabungkan kredensial unik, faktor kedua, dan pihak yang teregulasi."}}
}$$::jsonb, true),
('DF4-011', 'Decision Analysis', 'financial_decisions', 'advanced', 'word_bank', $$
{"type":"word_bank","difficulty":"advanced","question":"A written investing _____ states why you own an asset and what would change your mind.","options":["thesis","receipt","discount","rumour"],"answer":["thesis"],"explanation":"Writing the thesis before the outcome helps separate a process from hindsight or social pressure.","locales":{"id":{"type":"word_bank","difficulty":"advanced","question":"_____ investasi tertulis menjelaskan alasan memiliki aset dan apa yang akan mengubah keputusanmu.","options":["tesis","struk","diskon","rumor"],"answer":["tesis"],"explanation":"Menulis tesis sebelum hasil terlihat membantu memisahkan proses dari bias setelah kejadian atau tekanan sosial."}}
}$$::jsonb, true),
('DF4-012', 'Decision Analysis', 'financial_decisions', 'advanced', 'ordering', $$
{"type":"ordering","difficulty":"advanced","question":"Order a disciplined review after an investment falls sharply.","options":["Check whether the original thesis changed","Separate market noise from new evidence","Decide whether the position still fits the plan","Record the decision and reason"],"answer":["Check whether the original thesis changed","Separate market noise from new evidence","Decide whether the position still fits the plan","Record the decision and reason"],"explanation":"A review tests the thesis and portfolio role, rather than reacting only to a frightening price move.","locales":{"id":{"type":"ordering","difficulty":"advanced","question":"Urutkan tinjauan disiplin setelah investasi turun tajam.","options":["Periksa apakah tesis awal berubah","Pisahkan kebisingan pasar dari bukti baru","Putuskan apakah posisi masih sesuai rencana","Catat keputusan dan alasannya"],"answer":["Periksa apakah tesis awal berubah","Pisahkan kebisingan pasar dari bukti baru","Putuskan apakah posisi masih sesuai rencana","Catat keputusan dan alasannya"],"explanation":"Tinjauan menguji tesis dan peran aset dalam portofolio, bukan hanya bereaksi terhadap harga yang menakutkan."}}
}$$::jsonb, true);

COMMIT;
