-- KO-225 group 1 translation batch 5

update public.content_variants set body = $json${"type":"multiple_choice","answer":"Gold or shares","options":["Ordinary savings","Gold or shares","Money on the pillow","Empty digital wallet"],"question":"Over the long term, what investments are generally used to hedge against inflation?","difficulty":"intermediate","parameters":{},"explanation":"Assets such as gold and shares have the potential to grow beyond inflation in the long term."}$json$::jsonb where id = '2432d7cf-2a80-4da3-b08f-cc669e75314e';
update public.content_variants set body = $json${"type":"fill_blank","answer":"Effect","question":"The abbreviation IDX is the Indonesian _____ Exchange.","difficulty":"beginner","parameters":{},"explanation":"IDX is the abbreviation of the Indonesian Stock Exchange."}$json$::jsonb where id = '24e86c49-5a5d-4995-a5cf-09873cdda83b';
update public.content_variants set body = $json${"type":"fill_blank","answer":"2,5","question":"Bank Indonesia targets inflation of around _____ percent per year so that the economy remains stable.","difficulty":"beginner","parameters":{},"explanation":"Bank Indonesia targets inflation of around 2.5% plus or minus 1% to maintain economic stability."}$json$::jsonb where id = '2510f83e-e377-470a-a970-b370dc5b28af';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"3–6 months","options":["1 month","3–6 months","12 months","No need for emergency funds"],"question":"How much routine spending is generally recommended for an emergency fund?","difficulty":"beginner","parameters":{},"explanation":"The rule of thumb is to reserve 3–6 months of regular expenses, adjusted for income stability and dependents."}$json$::jsonb where id = '2611aa7e-6067-4c10-a1ec-37f9f9c0c97d';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"500 sheets","options":["5 sheets","50 sheets","500 sheets","5000 sheets"],"question":"If an investor buys 5 lots of BBCA shares, how many total shares does he own?","difficulty":"beginner","parameters":{},"explanation":"On IDX, 1 lot is equal to 100 shares. So 5 lots equals 500 shares."}$json$::jsonb where id = '2726df68-f041-4288-ae22-0a49a95f7cac';
update public.content_variants set body = $json${"type":"word_bank","answer":["diversification","asset type"],"options":["diversification","asset type"],"question":"Complete the following sentence with words from the word bank: \"To reduce risk, a young investor should do _____ by spreading money over several _____.\"","difficulty":"intermediate","parameters":{},"explanation":"Diversification spreads investments across different types of assets to reduce the impact of a single loss."}$json$::jsonb where id = '277dcd33-a07a-4092-8027-1fca0daace03';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"High returns usually mean high risk","options":["High risk always produces high profits","High returns usually mean high risk","Low risk always beats inflation","Risk and return are unrelated"],"question":"Which statement is correct regarding the relationship of risk and return?","difficulty":"intermediate","parameters":{},"explanation":"Investors generally demand higher potential returns to compensate for greater risk."}$json$::jsonb where id = '28508b9d-a741-4421-9ec3-41fd5cedfda1';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Reduces overall risk","options":["Guarantees big profits","Reduces overall risk","Follow stock trends","Avoid taxes"],"question":"The main goal of diversification is...","difficulty":"intermediate","parameters":{},"explanation":"Diversification spreads risk so that a loss on one asset is less impactful."}$json$::jsonb where id = '2991cc26-7ee0-419a-adc3-6081b1e43d2d';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Returns of 20% per month are guaranteed without risk","options":["Returns of 20% per month are guaranteed without risk","Bank deposits interest 4% per year","Stock mutual funds fluctuate","Savings have no interest"],"question":"Which statement is most suspicious?","difficulty":"beginner","explanation":"No investment is guaranteed to be without risk, especially since the returns are very high."}$json$::jsonb where id = '2a712c0a-c4a2-42ea-9bf4-36de52ec661b';
update public.content_variants set body = $json${"type":"fill_blank","answer":"2,5","question":"Bank Indonesia targets inflation of around _____ percent plus or minus one percent.","difficulty":"beginner","parameters":{},"explanation":"Bank Indonesia targets inflation of around 2.5% ± 1% to maintain economic stability."}$json$::jsonb where id = '2aa8eac1-7bb6-4fb3-97ff-078917a13761';

