-- KO-225 group 1 translation batch 8

update public.content_variants set body = $json${"type":"multiple_choice","answer":"Purchasing power decreases","options":["Purchasing power increases","Purchasing power decreases","Purchasing power remains the same","Inflation has no effect"],"question":"What effect does inflation have on the purchasing power of money?","difficulty":"beginner","parameters":{},"explanation":"Inflation causes the price of goods to rise, so the same money can buy less."}$json$::jsonb where id = '416516f6-b2c2-4436-9ca9-a253a7d235d9';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"If the price of goods rises, the purchasing power of the money we own also rises.","difficulty":"beginner","explanation":"When prices rise, the same money can buy fewer goods, so purchasing power decreases."}$json$::jsonb where id = '41c19172-9e63-4cfc-867a-34bd33e0eaaf';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Emergency funds should be saved in shares so that the returns are higher.","difficulty":"beginner","parameters":{},"explanation":"Stocks are at risk of fluctuating. Emergency funds need stability and liquidity, so choose safe instruments such as savings or deposits."}$json$::jsonb where id = '41daebf5-ca5b-49a6-b92f-68a7f0e4fb62';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Bring provisions and limit delivery orders","options":["Impulse shopping every payday","Bring provisions and limit delivery orders","Using paylater for all desires","Not recording expenses"],"question":"Which habits best support a healthy budget?","difficulty":"beginner","parameters":{},"explanation":"Limiting unnecessary expenses and bringing provisions helps keep your budget healthy."}$json$::jsonb where id = '41f06dbb-5b4d-4ac5-a10e-297058fba75d';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"50%","options":["20%","30%","50%","80%"],"question":"According to the 50/30/20 rule, what percentage of money should ideally be spent on needs?","difficulty":"beginner","parameters":{},"explanation":"50/30/20 rule: 50% needs, 30% wants, 20% savings or debt."}$json$::jsonb where id = '43a2499e-61bb-43bf-b1b6-5b00848493ad';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Buying shares means lending money to the company.","difficulty":"beginner","parameters":{},"explanation":"Buying shares means becoming the owner of a small part of the company, not lending money."}$json$::jsonb where id = '44a59b78-bcae-4f97-8d5b-7861eb41ac0d';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Good financial goals should be specific and have a deadline.","difficulty":"beginner","explanation":"SMART goals are easier to achieve because they are clear in number, purpose and time."}$json$::jsonb where id = '45e4c67c-a8c8-4d0b-9525-9144ef5fd8ca';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Rp. 900,000","options":["Rp. 900,000","IDR 1,100,000","Rp. 800,000","IDR 1,000,000"],"question":"Doni received a gross dividend of IDR 1,000,000 and 10% tax. What is the net dividend?","difficulty":"advanced","explanation":"10% tax on IDR 1,000,000 is IDR 100,000, so the net is IDR 900,000."}$json$::jsonb where id = '45e594d4-6e4b-4c70-b9b6-38535e8c05bc';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"A financial plan only needs to be made once in a lifetime.","difficulty":"advanced","explanation":"Financial plans must be evaluated and adjusted periodically."}$json$::jsonb where id = '48141c0a-a344-4e4a-8c60-6b2f586c4337';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Desires are expenses that must be met for daily living.","difficulty":"beginner","parameters":{},"explanation":"Desires are pleasant things but can be postponed, unlike needs."}$json$::jsonb where id = '4964f7dd-37e5-4f5b-bd08-e9f415d61ba8';

