-- KO-225 group 1 translation batch 7

update public.content_variants set body = $json${"type":"fill_blank","answer":"asset","question":"Diversification helps reduce the impact if one _____ investment declines.","difficulty":"intermediate","parameters":{},"explanation":"By spreading it across many assets, a loss on one asset doesn't destroy the entire portfolio."}$json$::jsonb where id = '393628c2-d324-402b-a4c8-05854510f174';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Receiving money sooner is always better than receiving it later.","difficulty":"beginner","explanation":"In general money is now worth more, but there are exceptions such as high interest on loans that must be paid back more quickly."}$json$::jsonb where id = '3b2d0410-d796-43f3-b0b4-1d097c272635';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Buying multiple stocks from the same sector is enough for diversification.","difficulty":"intermediate","parameters":{},"explanation":"True diversification requires a spread across sectors and asset types, not just lots of stocks in one sector."}$json$::jsonb where id = '3dbbb15a-d612-463f-ac58-97c985f64241';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because compound interest works better in the long run","options":["Because the market always goes up every day","Because compound interest works better in the long run","Because administration costs are cheaper","Because there is no risk"],"question":"Why is investment timing important?","difficulty":"beginner","parameters":{},"explanation":"The longer the investment period, the greater the compound interest effect."}$json$::jsonb where id = '3ec90d06-7ff0-4ca7-8c25-b16c4cbe8e5b';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"3%","options":["3%","5%","8%","13%"],"question":"If inflation is 5% and investment returns are 8%, what is the rough real return?","difficulty":"intermediate","parameters":{},"explanation":"Real return = nominal return - inflation = 8% - 5% = 3%."}$json$::jsonb where id = '3f836bc5-d7ef-4240-9f04-4e3242f18889';
update public.content_variants set body = $json${"type":"word_bank","answer":["share","company"],"options":["share","company"],"question":"Complete the following sentence with words from the word bank: \"On IDX, investors purchase a _____ that represents partial ownership of a _____.\"","difficulty":"beginner","parameters":{},"explanation":"Shares are proof of partial ownership of a listed company."}$json$::jsonb where id = '40031ab2-8d1b-4fed-bba1-e6839c55b950';
update public.content_variants set body = $json${"type":"fill_blank","answer":"diversification","question":"Spreading investments across different types of assets to reduce risk is called _____.","difficulty":"intermediate","parameters":{},"explanation":"Diversification helps reduce risk by not putting all funds in one instrument."}$json$::jsonb where id = '4056d096-2923-42bb-a7e7-b024f88678e8';
update public.content_variants set body = $json${"type":"fill_blank","answer":"debt repayment","question":"In the 50/30/20 rule, the 20% figure is used for savings and _____.","difficulty":"beginner","parameters":{},"explanation":"20% of income should be allocated to savings and paying off debt."}$json$::jsonb where id = '40cc4611-6a45-4d7c-920f-d09ee3b4dda2';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Desires must always be fulfilled first in order to live happily.","difficulty":"beginner","explanation":"Basic needs must come first. New desires are considered after needs and savings are met."}$json$::jsonb where id = '4116fa98-88ef-4d3b-bf58-4599b64aa35d';
update public.content_variants set body = $json${"type":"word_bank","answer":["need","desire"],"options":["need","desire"],"question":"Complete the following sentences with words from the word bank: \"The 50/30/20 rule divides income into _____ (50%), _____ (30%), and savings/debt (20%).\"","difficulty":"beginner","parameters":{},"explanation":"The 50/30/20 rule divides income between needs, wants, as well as savings and paying off debt."}$json$::jsonb where id = '41388bcd-578f-4dc3-9f34-15c62cd35ac0';

