-- KO-225 group 1 batch 02: high-confidence duplicated Indonesian questions

update public.content_variants set body = $json${"type":"multiple_choice","answer":"The combination of all assets owned","options":["The combination of all assets owned","One of the best stocks","Savings in one bank","Owned debt"],"question":"What is meant by portfolio?","difficulty":"intermediate","explanation":"The portfolio includes savings, deposits, shares, mutual funds and other assets that we own."}$json$::jsonb where id = '048d7456-8a6a-432e-b502-9354b98c3419';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Diversification ensures the portfolio always makes a profit every month.","difficulty":"intermediate","parameters":{},"explanation":"Diversification reduces risk, not guarantees profits. The portfolio can still go down."}$json$::jsonb where id = '07d7a1ad-953c-48a1-afa5-f1bdcb4886a9';
update public.content_variants set body = $json${"type":"case_study","answer":"OTP and passwords should not be provided via links. Always verify through official channels.","caseText":"Bayu received a WhatsApp message: 'Your BCA account is blocked, immediately click the link to reactivate it. Link asks for OTP.'","followUp":{"answer":"Contact the official BCA call center and don't click on the link","options":["Contact the official BCA call center and don't click on the link","Click the link and enter the OTP","Reply to messages with questions","Share the link with family"],"question":"What should Bayu do?","explanation":"Official banks do not ask for OTP via the link. Contact the official call center for confirmation."},"question":"Read the following cases and choose the best response.","difficulty":"beginner","explanation":"Phishing often uses urgency and threats to get us to act quickly without thinking."}$json$::jsonb where id = '0833677f-feb9-49cb-87f1-9696a4871c83';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Study first and start with money that will not be used in the short term","options":["Go straight into debt to buy shares","Study first and start with money that will not be used in the short term","Follow influencers' advice without research","Putting all the money in one friend's stock"],"question":"Should someone who is just starting to invest?","difficulty":"beginner","parameters":{},"explanation":"Beginners should learn and use cold money so as not to panic when the market goes down."}$json$::jsonb where id = '0859abed-d81b-454a-91d2-dbf4d68d262b';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"100","options":["10","50","100","1000"],"question":"How many shares are in 1 lot on IDX?","difficulty":"beginner","parameters":{},"explanation":"On the Indonesian Stock Exchange, 1 lot = 100 shares."}$json$::jsonb where id = '09f41247-1e1b-4fb6-a84a-e2e66c1344f1';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Big discounts always mean we save money.","difficulty":"beginner","explanation":"Discounts save only if we really need the item. If not, we end up spending money on unnecessary items."}$json$::jsonb where id = '0aed0cee-d947-4177-a3c2-0b283472b636';
update public.content_variants set body = $json${"type":"word_bank","answer":["egg","basket"],"options":["egg","basket"],"question":"Complete: \"Don't store all _____ in one _____.\"","difficulty":"intermediate","parameters":{},"explanation":"This proverb reminds us not to concentrate risks in one place."}$json$::jsonb where id = '0afe08f9-472e-4856-844f-b094376536fe';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Spot spending leaks and improve habits","options":["Spent the remaining money","Spot spending leaks and improve habits","Compare salaries with friends","Looking for a new loan"],"question":"The purpose of each month's budget evaluation is?","difficulty":"beginner","parameters":{},"explanation":"Evaluation helps us see where money is leaking and fix it."}$json$::jsonb where id = '0bafde3f-9fab-4d2c-bd97-cab6714e5fef';
update public.content_variants set body = $json${"type":"ordering","answer":["Determine financial goals","Select several types of assets","Divide funds according to proportion","Monitor and adjust every 6 months"],"options":["Determine financial goals","Select several types of assets","Divide funds according to proportion","Monitor and adjust every 6 months"],"question":"Sequence simple diversification steps.","difficulty":"intermediate","parameters":{},"explanation":"Starting from the goal, choose assets, allocate funds, then evaluate regularly."}$json$::jsonb where id = '0c482b93-bbef-4266-bd57-e12b6b3b46e4';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Portfolio composition should be the same for everyone regardless of financial goals.","difficulty":"intermediate","explanation":"Portfolios should be tailored to individual goals, time horizons and risk tolerance."}$json$::jsonb where id = '0cf7b56f-09c6-42bb-86b9-fdd31d191361';

