-- KO-348: ensure the two Money Basics comparison cards are present.
BEGIN;
WITH blocks(slug, content) AS (VALUES
('assets-vs-liabilities',$json${"en":{"icon":"⚖️","eyebrow":"Balance sheet","title":"What you own and what you owe are different columns","altText":"A two-column comparison separates owned value from obligations.","disclosure":"Illustrative snapshot only — values and categories depend on your situation.","payload":{"leftTitle":"Assets ✅","rightTitle":"Liabilities 📌","rows":[{"left":"Cash you own","right":"Bill you must pay"},{"left":"Savings balance","right":"Loan balance"},{"left":"Can add to your net position","right":"Reduces your net position"}]}},"id":{"icon":"⚖️","eyebrow":"Neraca sederhana","title":"Yang dimiliki dan yang terutang adalah kolom berbeda","altText":"Perbandingan dua kolom memisahkan nilai yang dimiliki dari kewajiban.","disclosure":"Potret ilustratif saja — nilai dan kategori bergantung pada kondisi Anda.","payload":{"leftTitle":"Aset ✅","rightTitle":"Liabilitas 📌","rows":[{"left":"Kas yang dimiliki","right":"Tagihan yang harus dibayar"},{"left":"Saldo tabungan","right":"Saldo pinjaman"},{"left":"Dapat menambah posisi bersih","right":"Mengurangi posisi bersih"}]}}}$json$::jsonb),
('income-vs-wealth',$json${"en":{"icon":"📊","eyebrow":"Flow and snapshot","title":"Income moves; wealth is a position","altText":"A comparison distinguishes money received over a month from assets minus liabilities at a point in time.","disclosure":"Illustrative example only — neither number alone describes financial wellbeing.","payload":{"leftTitle":"Income 💼","rightTitle":"Wealth 🧰","rows":[{"left":"Received over time","right":"Measured at a point in time"},{"left":"Rp6m this month","right":"Assets minus liabilities"},{"left":"Can change next month","right":"Can change as assets or debt change"}]}},"id":{"icon":"📊","eyebrow":"Arus dan potret","title":"Pendapatan bergerak; kekayaan adalah posisi","altText":"Perbandingan membedakan uang yang diterima selama sebulan dari aset dikurangi liabilitas pada suatu waktu.","disclosure":"Contoh ilustratif saja — satu angka tidak menggambarkan kesejahteraan keuangan.","payload":{"leftTitle":"Pendapatan 💼","rightTitle":"Kekayaan 🧰","rows":[{"left":"Diterima selama waktu","right":"Diukur pada satu waktu"},{"left":"Rp6 juta bulan ini","right":"Aset dikurangi liabilitas"},{"left":"Dapat berubah bulan depan","right":"Berubah saat aset atau utang berubah"}]}}}$json$::jsonb)
)
INSERT INTO public.lesson_visual_blocks (lesson_id, placement, block_type, content, data_status, display_order, is_published)
SELECT lesson.id, 'concept', 'comparison', blocks.content, 'illustrative', 10, TRUE
FROM blocks JOIN public.lessons lesson ON lesson.slug=blocks.slug
WHERE lesson.is_published
ON CONFLICT (lesson_id, placement, display_order) DO UPDATE SET block_type=EXCLUDED.block_type, content=EXCLUDED.content, data_status=EXCLUDED.data_status, is_published=TRUE;
COMMIT;
