-- KO-225 group 5 exact duplicate translation batch 4

update public.content_variants set body = $json${"text":"Eko bought the same credit motorbike just for weekend trips. He paid the installments, petrol and parking, but the motorbike didn't make any money. For Eko, the motorbike is more of a liability because he keeps spending money."}$json$::jsonb where id = '232bba1b-735e-46e5-9f7d-7a5980cc170b';
update public.content_variants set body = $json${"text":"SIPF (Securities Investor Protection Fund) provides protection to investors who store securities on IDX. If a securities company experiences problems, investors are protected according to applicable regulations, as long as the securities are listed.","source_ids":["5fa2799e-2b92-46e8-b68a-c9d64847410c"]}$json$::jsonb where id = '239bcc43-06ab-4657-98fc-2f331fe0d6df';
update public.content_variants set body = $json${"text":"Inflation is a general increase in the prices of goods and services over a certain period of time. Light and stable inflation is normal, but high inflation erodes purchasing power."}$json$::jsonb where id = '263d6a44-1604-4eab-b977-729f589f31b0';
update public.content_variants set body = $json${"text":"The same item can be an asset or a liability depending on how it is used. A motorbike for work can be an asset, a motorbike just for style can be a liability."}$json$::jsonb where id = '2ab4a387-b4b1-4136-ae68-2b0541631348';
update public.content_variants set body = $json${"text":"Rina, a fresh graduate in Bandung, has a net income of IDR 5,000,000 per month and regular expenses of IDR 4,000,000. He is targeting a 6 month emergency fund, namely IDR 24,000,000. Rina saves IDR 8,000,000 in separate savings and IDR 16,000,000 in a 1 month term deposit so that it can be easily withdrawn.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = '2da95141-a69e-4880-8e6d-5760fd9a0968';
update public.content_variants set body = $json${"text":"Risk is the possibility of an outcome occurring that is worse than expected. All options have risks, including keeping money in a cushion that risks loss or inflation."}$json$::jsonb where id = '2e46bf32-c5bd-4d05-af5d-d4c661e2309f';
update public.content_variants set body = $json${"text":"Mrs. Siti makes a weekly shopping list before going to the market. By registering, he is not tempted to buy things he doesn't need and saves IDR 100,000 per week.","source_ids":["7f4b83f2-8f1d-415c-9d4f-64e6284bef04"]}$json$::jsonb where id = '3020cf7e-2f44-45a6-9050-ec77526afd6f';
update public.content_variants set body = $json${"text":"Rina wants to open a securities account at a securities company. He checked the OJK website to ensure the company was registered as a capital market organizer. After being verified, he just registered."}$json$::jsonb where id = '31059c8c-324c-44e8-83e7-21944bf08e91';
update public.content_variants set body = $json${"text":"Doni chose to take an online motorbike taxi during heavy rain. The risk is that the trip will be longer and more expensive. The reward is that he gets home faster and safer than riding his own motorbike."}$json$::jsonb where id = '31a8e682-45c4-4d0e-8960-4b0f45034868';
update public.content_variants set body = $json${"text":"Ani wants to invest in shares but doesn't know how to choose a company. He bought a stock mutual fund managed by an investment manager licensed by the OJK. The money is combined with the money of many other investors to buy many shares at once."}$json$::jsonb where id = '31fa35b0-4e3b-4d48-bc67-8f0d934366e9';

