-- KO-225 group 1 translation batch 12

update public.content_variants set body = $json${"type":"word_bank","answer":["Buy lots of stocks from different sectors"],"options":["Buy lots of stocks from different sectors","Keep all your money in one stock","Saving on a pillow","Follow trends without research"],"question":"How to reduce stock-specific risks: ____","difficulty":"beginner","parameters":{},"explanation":"Diversification between sectors reduces the risk if one company or sector is sluggish."}$json$::jsonb where id = '703fb839-48a6-4090-a77b-b1834ec1ee85';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"More afraid of loss than happy to gain","options":["More afraid of loss than happy to gain","Likes to lose money","Don't care about losses","Always buy stocks that are going down"],"question":"Loss aversion is the tendency to...","difficulty":"advanced","explanation":"Loss aversion makes us feel the pain of loss more than the joy of gain."}$json$::jsonb where id = '7085ba9a-3231-4e53-9a05-00cf3ffabecf';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Rp. 400,000","options":["Rp. 400,000","Rp. 600,000","IDR 1,000,000","Rp. 200,000"],"question":"Ani's salary is IDR 2,000,000. How much is ideally allocated to savings/debt according to 50/30/20?","difficulty":"beginner","explanation":"20% of IDR 2,000,000 is IDR 400,000 for savings and paying off debt."}$json$::jsonb where id = '716d8b2d-2a06-43c8-9746-8e57e971d156';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Rp. 200,000","options":["Rp. 200,000","Rp. 400,000","Rp. 100,000","Rp. 500,000"],"question":"Doni has a salary of IDR 2,000,000 and wants to save 10% at the start. How much should you set aside first?","difficulty":"beginner","explanation":"10% of IDR 2,000,000 is IDR 200,000."}$json$::jsonb where id = '71e6c081-07ca-495b-8f47-91c54dafa6c3';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"High risk, high potential return","options":["High risk, low return","Low risk, high return","High risk, high potential return","No connection"],"question":"The general relationship between risk and return is?","difficulty":"beginner","parameters":{},"explanation":"Generally, the higher the potential return, the higher the risk."}$json$::jsonb where id = '72198eb1-4fc6-489d-b5ef-fb100b44e65a';
update public.content_variants set body = $json${"type":"fill_blank","answer":"high flowering","question":"Before investing, make sure emergency funds are available and _____ debt is under control.","difficulty":"advanced","explanation":"High-interest debt can wipe out investment profits, so it needs to be controlled first."}$json$::jsonb where id = '723db299-1994-4dbf-8a1b-f1290c9bd2d3';
update public.content_variants set body = $json${"type":"fill_blank","answer":"24 hours","question":"Before buying an item because of an influencer, it's best to wait _____ for the FOMO emotion to subside.","difficulty":"beginner","explanation":"A gap of 24 hours or more helps us differentiate between real needs and emotional urges."}$json$::jsonb where id = '73e56048-a46e-4f13-b13d-4a519842663c';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"IDR 1,000,000","options":["IDR 500,000","IDR 1,000,000","IDR 1,500,000","IDR 2,500,000"],"question":"If Rina's salary is IDR 5,000,000, what is her ideal savings using the 50/30/20 rule?","difficulty":"beginner","parameters":{},"explanation":"20% of IDR 5,000,000 is IDR 1,000,000."}$json$::jsonb where id = '7440ebee-0f27-4ae0-a9b5-1818f84a9fea';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"1 lot","options":["1 lot","0.5 lots","10 lots","There are no minimums"],"question":"What is the minimum lot that can be purchased for one share on IDX?","difficulty":"intermediate","explanation":"At IDX, the minimum purchase of shares is 1 lot containing 100 shares."}$json$::jsonb where id = '77a8ad22-3dcc-4d89-8a40-4cdeefa47771';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Diversification ensures that investments always produce profits.","difficulty":"intermediate","explanation":"Diversification reduces risk, but does not guarantee profits."}$json$::jsonb where id = '78cd98cc-c86c-47ec-904b-c6183b85bbdb';

