-- KO-225 group 5 continuation batch 19

update public.content_variants set body = $json${"text":"The composition of the portfolio should be appropriate to the goals and time horizon. Short-term goals need safe assets; Long-term goals can withstand fluctuations."}$json$::jsonb where id = 'c2df85fa-c1e4-4f5e-929f-16e40a1ae249';
update public.content_variants set body = $json${"text":"Sari receives an allowance of IDR 1,500,000 per month. Boarding house IDR 700,000, credit and quota IDR 150,000, food in the canteen IDR 400,000 are necessities. A streaming subscription of IDR 50,000 and new shoes IDR 300,000 is a wish. If pocket money runs out, needs must come first."}$json$::jsonb where id = 'c38f8c51-b540-4787-adc4-f7339a86823d';
update public.content_variants set body_id = $json${"type":"ordering","answer":["Pahami tingkat inflasi","Periksa tingkat bunga tabungan","Hitung keuntungan riil","Pertimbangkan alternatif lain","Sesuaikan strategi tabungan"],"options":["Pahami tingkat inflasi","Periksa tingkat bunga tabungan","Hitung keuntungan riil","Pertimbangkan alternatif lain","Sesuaikan strategi tabungan"],"question":"Urutan langkah-langkah untuk melindungi tabungan dari inflasi:","difficulty":"advanced","parameters":{},"explanation":"Urutan yang benar adalah: Pahami tingkat inflasi → Periksa tingkat bunga tabungan → Hitung keuntungan riil → Pertimbangkan alternatif → Sesuaikan strategi tabungan"}$json$::jsonb where id = 'c3c231a3-c380-4588-8bc3-0e2902dab358';
update public.content_variants set body = $json${"text":"Risk and return go hand in hand: high profit potential usually comes with high risk. Compound interest means profits are generated not only from the initial capital, but also from previous profits. Diversification, or spreading investments across different assets, helps reduce the risk if one investment loses money. Time is the best partner for young investors.","ai_assist_context":"Explain the relationship between risk and return, compound interest, and diversification with the example of rupiah. Do not provide specific product recommendations."}$json$::jsonb where id = 'c419d1ae-2c5e-4c3d-9a56-6fbc91532625';
update public.content_variants set body_id = $json${"type":"definition_match","answer":{"Crash":"Penurunan drastis harga saham secara tiba-tiba sebesar 20% atau lebih","Correction":"Penurunan 10% atau lebih dari puncaknya baru-baru ini","Bear Market":"Suatu kondisi pasar dimana harga sedang turun atau diperkirakan akan turun","Bull Market":"Suatu kondisi pasar dimana harga sedang naik atau diperkirakan akan naik"},"options":{"terms":["Pasar Banteng","Pasar Beruang","Koreksi","Menabrak"],"definitions":["Suatu kondisi pasar dimana harga sedang naik atau diperkirakan akan naik","Suatu kondisi pasar dimana harga sedang turun atau diperkirakan akan turun","Penurunan 10% atau lebih dari puncaknya baru-baru ini","Penurunan drastis harga saham secara tiba-tiba sebesar 20% atau lebih"]},"question":"Cocokkan setiap istilah pasar dengan deskripsinya:","difficulty":"intermediate","parameters":{},"explanation":"Pertandingan yang benar: Bull Market = Kondisi pasar di mana harga sedang naik atau diperkirakan akan naik, Bear Market = Kondisi pasar di mana harga akan turun atau diperkirakan akan turun, Correction = Penurunan sebesar 10% atau lebih dari harga puncak baru-baru ini, Crash = Penurunan harga saham secara tiba-tiba dan drastis sebesar 20% atau lebih"}$json$::jsonb where id = 'c4256d11-e9b0-4890-b1b9-cfd5b3bc0dd6';
update public.content_variants set body_id = $json${"type":"multiple_choice","answer":"Inflasi","options":["Deflasi","Inflasi","Minat","Investasi"],"question":"Semangkuk mie ayam harganya Rp 12.000 tahun lalu dan Rp 13.000 tahun ini. Ini contohnya apa?","difficulty":"beginner","parameters":{},"explanation":"Kenaikan harga secara umum dari waktu ke waktu disebut inflasi."}$json$::jsonb where id = 'c46290c4-d62e-4d4a-9778-0f75552005ec';
update public.content_variants set body_id = $json${"type":"spot_mistake","answer":["Tidak ada sistem penganggaran","Pembelanjaan terfragmentasi di seluruh platform","Tidak ada pelacakan biaya","Mengandalkan pengecekan saldo secara reaktif"],"options":["Tidak ada sistem penganggaran","Pembelanjaan terfragmentasi di seluruh platform","Tidak ada pelacakan biaya","Mengandalkan pengecekan saldo secara reaktif","Tidak ada kesalahan","Hanya satu kesalahan kecil"],"question":"Bacalah pernyataan berikut dan kenali kesalahan finansialnya:\n\nSaya tidak perlu membuat anggaran karena saya selalu dapat memeriksa saldo e-wallet saya. Saya mempunyai 5 dompet elektronik yang berbeda dan saya tidak yakin berapa jumlah total pembelanjaan saya setiap bulannya.","difficulty":"advanced","parameters":{"mistake_count":4},"explanation":"Tanpa pelacakan dan penganggaran, pengeluaran dengan mudah melebihi pendapatan tanpa kesadaran."}$json$::jsonb where id = 'c4b8bb23-6262-4aa6-91ba-4d30516abbae';
update public.content_variants set body_id = $json${"type":"fill_blank","answer":"BEI","question":"________ adalah bursa efek Indonesia tempat perusahaan mencatatkan sahamnya.","difficulty":"intermediate","parameters":{},"explanation":"Bursa Efek Indonesia (IDX) adalah bursa efek nasional Indonesia."}$json$::jsonb where id = 'c50e6ef4-0064-40f8-93c3-542f0ea45cdb';
update public.content_variants set body_id = $json${"type":"calculation","answer":"8%","question":"Anda memiliki Rp 50 juta untuk berinvestasi. Anda mengalokasikan 60% untuk saham (pengembalian yang diharapkan 10%) dan 40% untuk obligasi (pengembalian yang diharapkan 5%). Berapa return portofolio yang diharapkan?","difficulty":"intermediate","parameters":{"hint":"Multiply each allocation by its return and sum the results."},"explanation":"Pengembalian tertimbang = (0,60 × 10%) + (0,40 × 5%) = 6% + 2% = 8%."}$json$::jsonb where id = 'c566327d-c6a6-447c-aa05-a6e1a8128e98';
update public.content_variants set body_id = $json${"type":"calculation","answer":"1,600,000","question":"Anda mendapat penghasilan Rp 8 juta setiap bulannya. Mengikuti aturan 50/30/20, berapa jumlah yang harus ditabung dan berhutang?","difficulty":"beginner","parameters":{"hint":"Calculate 20% of the monthly income."},"explanation":"20% dari 8.000.000 = 0,20 × 8.000.000 = Rp 1.600.000."}$json$::jsonb where id = 'c63927bf-27c1-43bd-a836-574993dde006';

