-- KO-313 / KO-315: restore the two-check English Chapter 08 pool and raise
-- multiple-choice distractor quality. The Indonesian payloads are kept in
-- parity for runtime safety; Indonesian editorial review remains separate.

BEGIN;

WITH option_updates(slug, options_en, options_id) AS (
  VALUES
    ('what-is-a-stock',
      jsonb_build_array('A small ownership stake, with no guaranteed profit.', 'A loan to the company with a scheduled repayment date.', 'A controlling position that lets you set company policy.', 'A fixed claim on cash flows regardless of company results.'),
      jsonb_build_array('Bagian kecil dari kepemilikan, tanpa keuntungan yang dijamin.', 'Pinjaman kepada perusahaan dengan jadwal pembayaran kembali.', 'Kepemilikan pengendali yang memungkinkanmu menetapkan kebijakan perusahaan.', 'Klaim tetap atas arus kas terlepas dari hasil perusahaan.')),
    ('idx-basics-101',
      jsonb_build_array('Rp 760,000 gross for 200 shares, before fees and current order rules.', 'Rp 7,600,000 because a lot contains 1,000 shares.', 'Rp 380,000 because the lot count replaces the share price.', 'Rp 76,000 because fees are included in the displayed price.'),
      jsonb_build_array('Rp 760.000 kotor untuk 200 saham, sebelum biaya dan aturan order terbaru.', 'Rp 7.600.000 karena satu lot berisi 1.000 saham.', 'Rp 380.000 karena jumlah lot menggantikan harga saham.', 'Rp 76.000 karena biaya sudah termasuk dalam harga yang ditampilkan.')),
    ('reading-a-stock-page',
      jsonb_build_array('More shares changed hands in that observation window; other evidence is still needed.', 'The company is definitely profitable because volume is high.', 'The next price move is guaranteed because many shares traded.', 'The stock is undervalued because volume exceeds 8 million.'),
      jsonb_build_array('Lebih banyak saham berpindah tangan pada periode pengamatan itu; bukti lain tetap diperlukan.', 'Perusahaan pasti menguntungkan karena volumenya tinggi.', 'Pergerakan harga berikutnya dijamin karena banyak saham diperdagangkan.', 'Saham itu undervalued karena volumenya melebihi 8 juta.')),
    ('portfolio-thinking',
      jsonb_build_array('The goal, time horizon, liquidity needs, and risk capacity.', 'The same asset mix for everyone with the same starting cash.', 'The stock with the highest recent return.', 'The asset that is most popular on social media.'),
      jsonb_build_array('Tujuan, jangka waktu, kebutuhan likuiditas, dan kapasitas risiko.', 'Komposisi aset yang sama untuk semua orang dengan modal awal yang sama.', 'Saham dengan imbal hasil terbaru paling tinggi.', 'Aset yang paling populer di media sosial.')),
    ('taxes-on-returns',
      jsonb_build_array('The amount kept can differ after the applicable tax treatment.', 'A headline return is the same as the final amount in every instrument.', 'Tax treatment is identical across instruments and taxpayers.', 'A gross return tells you the exact cash you will receive.'),
      jsonb_build_array('Jumlah yang diterima bisa berbeda setelah perlakuan pajak yang berlaku.', 'Angka imbal hasil utama sama dengan jumlah akhir pada setiap instrumen.', 'Perlakuan pajak sama untuk semua instrumen dan wajib pajak.', 'Imbal hasil kotor memberi tahu jumlah kas yang pasti diterima.')),
    ('macro-indicators',
      jsonb_build_array('It can explain one channel while leaving a stock outcome and timing uncertain.', 'It identifies the exact day to buy a stock.', 'It proves all stocks will move in the same direction.', 'It guarantees that purchasing power will rise.'),
      jsonb_build_array('Indikator dapat menjelaskan satu jalur dampak, sementara hasil dan waktu pergerakan saham tetap tidak pasti.', 'Indikator menentukan hari yang tepat untuk membeli saham.', 'Indikator membuktikan semua saham akan bergerak searah.', 'Indikator menjamin daya beli akan naik.')),
    ('etfs-investing-with-one-click',
      jsonb_build_array('Its stated basket or index, holdings, costs, tracking, and risks.', 'Only the ETF name and the largest holding.', 'A promise that every holding will rise together.', 'The number of holdings, without checking what they contain.'),
      jsonb_build_array('Keranjang atau indeks, kepemilikan, biaya, pelacakan, dan risikonya.', 'Hanya nama ETF dan kepemilikan terbesar.', 'Janji bahwa semua kepemilikan akan naik bersama.', 'Jumlah kepemilikan tanpa memeriksa isinya.')),
    ('bonds-sbn-safe-investing-with-the-government',
      jsonb_build_array('Issuer, coupon rule, term, access route, and the date of the current source.', 'The coupon alone, because it determines every risk.', 'The government name alone, because it removes market risk.', 'The product colour and headline, because they show suitability.'),
      jsonb_build_array('Penerbit, aturan kupon, tenor, jalur akses, dan tanggal sumber terbaru.', 'Kupon saja karena menentukan semua risiko.', 'Nama pemerintah saja karena menghapus risiko pasar.', 'Warna dan judul produk karena menunjukkan kecocokan.')),
    ('tax-basics-npwp-pph-21-and-filing-taxes',
      jsonb_build_array('Check your situation, the relevant period, and the current DJP rule.', 'Copy the example’s rate if the income amount looks similar.', 'Ignore your records because the example is already official.', 'Use the oldest form available to avoid changing instructions.'),
      jsonb_build_array('Periksa situasimu, periode terkait, dan aturan DJP terbaru.', 'Salin tarif contoh jika jumlah penghasilannya terlihat sama.', 'Abaikan catatan karena contoh tersebut sudah resmi.', 'Gunakan formulir tertua agar tidak menghadapi petunjuk yang berubah.')),
    ('brokerage-account-setup-opening-your-rdn',
      jsonb_build_array('Verify the provider and account structure in current official records.', 'Choose the app with the most features because it is safest.', 'Transfer to a personal account if the message uses the provider logo.', 'Assume a popular provider has the same terms as every other provider.'),
      jsonb_build_array('Verifikasi penyedia dan struktur rekening dalam catatan resmi terbaru.', 'Pilih aplikasi dengan fitur terbanyak karena paling aman.', 'Transfer ke rekening pribadi jika pesan memakai logo penyedia.', 'Anggap penyedia populer memiliki ketentuan yang sama dengan semua penyedia lain.')),
    ('stock-analysis-basics-fundamental-vs-technical',
      jsonb_build_array('Study the business, dated evidence, and uncertainty before a conclusion.', 'Treat one ratio as a complete and guaranteed signal.', 'Predict tomorrow’s price from one headline.', 'Use a chart alone to decide whether a business is financially healthy.'),
      jsonb_build_array('Pelajari bisnis, bukti bertanggal, dan ketidakpastian sebelum menarik kesimpulan.', 'Anggap satu rasio sebagai sinyal lengkap yang dijamin.', 'Prediksi harga besok dari satu judul berita.', 'Gunakan grafik saja untuk menentukan kesehatan keuangan bisnis.')),
    ('etfs-investing-with-one-click-part-2',
      jsonb_build_array('An amount paid before costs; current product data is still needed for any conclusion.', 'A guaranteed return equal to the product’s next market price.', 'Proof that a lower fee removes tracking and liquidity risk.', 'A forecast of the ETF’s value because the arithmetic uses 100 units.'),
      jsonb_build_array('Jumlah pembayaran sebelum biaya; data produk terbaru tetap diperlukan untuk kesimpulan apa pun.', 'Imbal hasil yang dijamin sama dengan harga pasar produk berikutnya.', 'Bukti bahwa biaya rendah menghapus risiko pelacakan dan likuiditas.', 'Prediksi nilai ETF karena perhitungannya memakai 100 unit.')),
    ('bonds-sbn-safe-investing-with-the-government-part-2',
      jsonb_build_array('It shows gross arithmetic for the stated example; current series terms determine the actual result.', 'It proves the next offer will pay the same amount.', 'It shows government bonds have no price or inflation risk.', 'It means tax and payment schedules cannot change.'),
      jsonb_build_array('Perhitungan menunjukkan aritmetika kotor untuk contoh tersebut; ketentuan seri terbaru menentukan hasil sebenarnya.', 'Perhitungan membuktikan penawaran berikutnya akan membayar jumlah yang sama.', 'Perhitungan menunjukkan obligasi pemerintah tidak memiliki risiko harga atau inflasi.', 'Perhitungan berarti pajak dan jadwal pembayaran tidak dapat berubah.')),
    ('tax-basics-npwp-pph-21-and-filing-taxes-part-2',
      jsonb_build_array('Save the submission receipt after checking the current route and confirmation.', 'Treat a saved draft as proof that the SPT was submitted.', 'Copy another person’s form and deadline if the income looks similar.', 'Skip the receipt because monthly withholding completes every filing step.'),
      jsonb_build_array('Simpan bukti penerimaan setelah memeriksa jalur dan konfirmasi terbaru.', 'Anggap draf yang tersimpan sebagai bukti SPT sudah dilaporkan.', 'Salin formulir dan tenggat orang lain jika penghasilannya terlihat sama.', 'Lewati bukti penerimaan karena pemotongan bulanan menyelesaikan semua langkah pelaporan.')),
    ('brokerage-account-setup-opening-your-rdn-part-2',
      jsonb_build_array('The official receiving account and current provider instructions through a trusted channel.', 'A payment request sent from an unverified personal account.', 'A projected return that justifies sending funds quickly.', 'A screenshot without checking the provider domain or account details.'),
      jsonb_build_array('Rekening tujuan resmi dan petunjuk terbaru penyedia melalui kanal tepercaya.', 'Permintaan pembayaran dari rekening pribadi yang tidak terverifikasi.', 'Proyeksi imbal hasil yang membenarkan pengiriman dana dengan cepat.', 'Tangkapan layar tanpa memeriksa domain penyedia atau detail rekening.')),
    ('stock-analysis-basics-fundamental-vs-technical-part-2',
      jsonb_build_array('Recent observed price or volume context for a stated period.', 'A guaranteed future direction based on the latest candle.', 'Whether the trade suits every learner regardless of goals.', 'A company’s complete financial health from price movement alone.'),
      jsonb_build_array('Konteks harga atau volume yang teramati untuk periode tertentu.', 'Arah masa depan yang dijamin berdasarkan candle terbaru.', 'Kecocokan transaksi untuk semua pelajar tanpa melihat tujuan.', 'Kesehatan keuangan perusahaan secara lengkap hanya dari pergerakan harga.'))
), updated AS (
  UPDATE public.content_variants AS variant
  SET body = jsonb_set(variant.body, '{options}', option_updates.options_en, TRUE),
      body_id = CASE WHEN variant.body_id IS NULL THEN NULL ELSE jsonb_set(variant.body_id, '{options}', option_updates.options_id, TRUE) END
  FROM option_updates
  JOIN public.lessons AS lesson ON lesson.slug = option_updates.slug
  WHERE variant.lesson_id = lesson.id
    AND variant.variant_type = 'question'
    AND variant.topic_tag = 'visual_applied'
    AND variant.is_active = TRUE
  RETURNING variant.id
)
SELECT count(*) AS updated_visual_questions FROM updated;

WITH additions(slug, question_en, options_en, answer_en, explanation_en, question_id, options_id, answer_id, explanation_id) AS (
  VALUES
    ('what-is-a-stock', 'Which statement best distinguishes a stock from a fixed loan?', jsonb_build_array('A shareholder has variable ownership exposure rather than a scheduled repayment claim.', 'A shareholder receives a fixed repayment date from the company.', 'A stockholder is an employee with authority over company policy.', 'The company must repurchase the shares at the original price.'), 'A shareholder has variable ownership exposure rather than a scheduled repayment claim.', 'Stocks represent ownership and can change in value; they do not promise a fixed repayment schedule.', 'Pernyataan mana yang paling membedakan saham dari pinjaman tetap?', jsonb_build_array('Pemegang saham memiliki eksposur kepemilikan yang berubah, bukan klaim pembayaran terjadwal.', 'Pemegang saham menerima tanggal pembayaran kembali yang tetap dari perusahaan.', 'Pemegang saham adalah karyawan yang berwenang atas kebijakan perusahaan.', 'Perusahaan wajib membeli kembali saham pada harga awal.'), 'Pemegang saham memiliki eksposur kepemilikan yang berubah, bukan klaim pembayaran terjadwal.', 'Saham menunjukkan kepemilikan dan nilainya dapat berubah; saham tidak menjanjikan jadwal pembayaran tetap.'),
    ('idx-basics-101', 'Before submitting an illustrative two-lot order, what should be checked beyond the multiplication?', jsonb_build_array('The current market rule, available cash, fees, symbol, and order details.', 'Only whether the arithmetic produces a round number.', 'The company’s popularity, because it determines whether the order is valid.', 'Whether the lot size guarantees that the order will execute.'), 'The current market rule, available cash, fees, symbol, and order details.', 'Lot arithmetic gives quantity and gross value; it does not replace order, cash, fee, or market-rule checks.', 'Sebelum mengirim order ilustratif dua lot, apa yang perlu diperiksa selain perkalian?', jsonb_build_array('Aturan pasar terbaru, kas tersedia, biaya, simbol, dan detail order.', 'Hanya apakah hasil perhitungannya berupa angka bulat.', 'Popularitas perusahaan karena menentukan validitas order.', 'Apakah ukuran lot menjamin order akan terlaksana.'), 'Aturan pasar terbaru, kas tersedia, biaya, simbol, dan detail order.', 'Perhitungan lot memberi jumlah dan nilai kotor; bukan pengganti pemeriksaan order, kas, biaya, atau aturan pasar.'),
    ('reading-a-stock-page', 'Which pairing keeps a quote observation separate from an unsupported conclusion?', jsonb_build_array('Volume describes shares traded; it does not establish profitability or value.', 'Volume proves management quality because active trading attracts informed buyers.', 'A high close proves the next session will continue upward.', 'A large market cap proves the current price is suitable for every goal.'), 'Volume describes shares traded; it does not establish profitability or value.', 'A quote field describes an observed market fact; business quality, valuation, and suitability require other evidence.', 'Pasangan mana yang memisahkan pengamatan kutipan dari kesimpulan yang belum didukung?', jsonb_build_array('Volume menjelaskan saham yang diperdagangkan; volume tidak membuktikan profitabilitas atau nilai.', 'Volume membuktikan kualitas manajemen karena perdagangan aktif menarik pembeli yang berpengetahuan.', 'Penutupan tinggi membuktikan sesi berikutnya akan terus naik.', 'Kapitalisasi besar membuktikan harga saat ini cocok untuk semua tujuan.'), 'Volume menjelaskan saham yang diperdagangkan; volume tidak membuktikan profitabilitas atau nilai.', 'Kolom kutipan menggambarkan fakta pasar yang teramati; kualitas bisnis, valuasi, dan kecocokan membutuhkan bukti lain.'),
    ('portfolio-thinking', 'Why can two assets still leave a portfolio concentrated?', jsonb_build_array('Both assets may respond to the same economic or company-specific risk.', 'Two assets always provide enough diversification for every goal.', 'The higher-priced asset automatically balances the lower-priced asset.', 'A familiar company removes concentration risk from the whole portfolio.'), 'Both assets may respond to the same economic or company-specific risk.', 'Counting holdings is not enough; the exposures and risks can still overlap.', 'Mengapa dua aset tetap dapat membuat portofolio terkonsentrasi?', jsonb_build_array('Kedua aset bisa merespons risiko ekonomi atau risiko perusahaan yang sama.', 'Dua aset selalu memberi diversifikasi yang cukup untuk semua tujuan.', 'Aset dengan harga lebih tinggi otomatis menyeimbangkan aset yang lebih rendah.', 'Perusahaan yang dikenal menghapus risiko konsentrasi dari seluruh portofolio.'), 'Kedua aset bisa merespons risiko ekonomi atau risiko perusahaan yang sama.', 'Menghitung jumlah kepemilikan saja tidak cukup; eksposur dan risikonya masih bisa tumpang tindih.'),
    ('taxes-on-returns', 'An 8% headline return is shown without a tax treatment. What is the strongest next step?', jsonb_build_array('Identify the instrument, current rule, gross or net basis, and relevant taxpayer situation.', 'Treat 8% as the exact cash amount every investor will keep.', 'Compare it only with the highest historical return.', 'Assume the same tax treatment applies to every instrument.'), 'Identify the instrument, current rule, gross or net basis, and relevant taxpayer situation.', 'A net comparison needs the instrument, applicable rule, and basis of the stated return.', 'Imbal hasil utama 8% ditampilkan tanpa perlakuan pajak. Apa langkah berikutnya yang paling kuat?', jsonb_build_array('Identifikasi instrumen, aturan terbaru, dasar kotor atau bersih, dan situasi wajib pajak terkait.', 'Anggap 8% sebagai jumlah kas yang pasti diterima setiap investor.', 'Bandingkan hanya dengan imbal hasil historis tertinggi.', 'Anggap perlakuan pajak yang sama berlaku untuk semua instrumen.'), 'Identifikasi instrumen, aturan terbaru, dasar kotor atau bersih, dan situasi wajib pajak terkait.', 'Perbandingan bersih memerlukan instrumen, aturan yang berlaku, dan dasar angka imbal hasil.'),
    ('macro-indicators', 'A new inflation reading is higher. What is the most disciplined response?', jsonb_build_array('Record the date, ask which channel may be affected, and seek other evidence before concluding.', 'Sell every stock because higher inflation fixes the market direction.', 'Buy the same stock immediately because macro data is a timing signal.', 'Ignore the reading because macro indicators never affect financial decisions.'), 'Record the date, ask which channel may be affected, and seek other evidence before concluding.', 'One indicator can sharpen a question; it does not settle the asset-level outcome.', 'Angka inflasi terbaru lebih tinggi. Apa respons yang paling disiplin?', jsonb_build_array('Catat tanggalnya, tanyakan jalur dampak yang mungkin, dan cari bukti lain sebelum menyimpulkan.', 'Jual semua saham karena inflasi tinggi menetapkan arah pasar.', 'Segera beli saham yang sama karena data makro adalah sinyal waktu.', 'Abaikan angka itu karena indikator makro tidak pernah memengaruhi keputusan keuangan.'), 'Catat tanggalnya, tanyakan jalur dampak yang mungkin, dan cari bukti lain sebelum menyimpulkan.', 'Satu indikator dapat memperjelas pertanyaan; bukan menentukan hasil pada tingkat aset.'),
    ('etfs-investing-with-one-click', 'An ETF tracks a broad index. What does that fact alone not establish?', jsonb_build_array('That its price, tracking, liquidity, or suitability is guaranteed.', 'That the product has a stated basket and index objective.', 'That its holdings should be checked against the current product information.', 'That its risks may differ from an individual share.'), 'That its price, tracking, liquidity, or suitability is guaranteed.', 'A broad basket describes exposure; it does not remove market, tracking, liquidity, or goal-fit questions.', 'ETF melacak indeks yang luas. Apa yang tidak dapat ditetapkan oleh fakta itu saja?', jsonb_build_array('Bahwa harga, pelacakan, likuiditas, atau kecocokannya dijamin.', 'Bahwa produk memiliki keranjang dan tujuan indeks yang dinyatakan.', 'Bahwa kepemilikannya perlu diperiksa terhadap informasi produk terbaru.', 'Bahwa risikonya dapat berbeda dari satu saham individual.'), 'Bahwa harga, pelacakan, likuiditas, atau kecocokannya dijamin.', 'Keranjang luas menjelaskan eksposur; bukan menghapus pertanyaan tentang pasar, pelacakan, likuiditas, atau kecocokan tujuan.'),
    ('bonds-sbn-safe-investing-with-the-government', 'Why record the source date beside an SBN coupon example?', jsonb_build_array('Series terms, rates, tax, and access conditions can be time-sensitive.', 'The date converts a historical example into a guaranteed future coupon.', 'The source date proves there is no interest-rate or liquidity risk.', 'The date is only needed when the issuer is not the government.'), 'Series terms, rates, tax, and access conditions can be time-sensitive.', 'A date helps separate a reviewed example from current series terms that must be checked again.', 'Mengapa tanggal sumber perlu dicatat di samping contoh kupon SBN?', jsonb_build_array('Ketentuan seri, tarif, pajak, dan akses dapat sensitif terhadap waktu.', 'Tanggal mengubah contoh historis menjadi kupon masa depan yang dijamin.', 'Tanggal sumber membuktikan tidak ada risiko suku bunga atau likuiditas.', 'Tanggal hanya diperlukan jika penerbitnya bukan pemerintah.'), 'Ketentuan seri, tarif, pajak, dan akses dapat sensitif terhadap waktu.', 'Tanggal membantu memisahkan contoh yang ditinjau dari ketentuan seri terbaru yang perlu diperiksa lagi.'),
    ('tax-basics-npwp-pph-21-and-filing-taxes', 'Why keep income and withholding records even if tax was withheld monthly?', jsonb_build_array('The annual SPT reconciles relevant records and the current reporting requirement.', 'Monthly withholding means no annual record can ever be needed.', 'A record is useful only when someone else files the SPT.', 'The withholding slip replaces every current DJP instruction.'), 'The annual SPT reconciles relevant records and the current reporting requirement.', 'Withholding evidence is part of a record set; it does not remove the need to follow the current filing route.', 'Mengapa catatan penghasilan dan pemotongan tetap disimpan meski pajak dipotong setiap bulan?', jsonb_build_array('SPT tahunan mencocokkan catatan terkait dan kewajiban pelaporan terbaru.', 'Pemotongan bulanan berarti catatan tahunan tidak pernah diperlukan.', 'Catatan hanya berguna jika orang lain melaporkan SPT.', 'Bukti pemotongan menggantikan semua petunjuk DJP terbaru.'), 'SPT tahunan mencocokkan catatan terkait dan kewajiban pelaporan terbaru.', 'Bukti pemotongan adalah bagian dari catatan; bukan alasan untuk mengabaikan jalur pelaporan terbaru.'),
    ('brokerage-account-setup-opening-your-rdn', 'Which evidence makes a provider claim safe to repeat?', jsonb_build_array('A named provider, a current official source, a review date, and a stated scope.', 'A popular app ranking without a source or date.', 'A fee screenshot from an unknown account.', 'A friend’s experience treated as a universal process.'), 'A named provider, a current official source, a review date, and a stated scope.', 'Provider claims need a source and boundary; one experience cannot establish a universal rule.', 'Bukti apa yang membuat klaim tentang penyedia aman untuk diulang?', jsonb_build_array('Nama penyedia, sumber resmi terbaru, tanggal pemeriksaan, dan cakupan yang dinyatakan.', 'Peringkat aplikasi populer tanpa sumber atau tanggal.', 'Tangkapan layar biaya dari akun yang tidak dikenal.', 'Pengalaman teman yang dianggap sebagai proses universal.'), 'Nama penyedia, sumber resmi terbaru, tanggal pemeriksaan, dan cakupan yang dinyatakan.', 'Klaim penyedia memerlukan sumber dan batas; satu pengalaman tidak menetapkan aturan universal.'),
    ('stock-analysis-basics-fundamental-vs-technical', 'Revenue rises while cash flow falls and debt rises. What is the strongest first response?', jsonb_build_array('Investigate cash conversion, debt, and valuation before relying on price momentum.', 'Treat rising revenue as proof that every risk has fallen.', 'Use the latest price candle as a complete financial diagnosis.', 'Choose the company because the headline is positive.'), 'Investigate cash conversion, debt, and valuation before relying on price momentum.', 'A fundamental review tests several business signals rather than accepting one positive headline.', 'Pendapatan naik sementara arus kas turun dan utang naik. Apa respons awal yang paling kuat?', jsonb_build_array('Periksa konversi kas, utang, dan valuasi sebelum mengandalkan momentum harga.', 'Anggap kenaikan pendapatan membuktikan semua risiko menurun.', 'Gunakan candle harga terbaru sebagai diagnosis keuangan lengkap.', 'Pilih perusahaan karena judul beritanya positif.'), 'Periksa konversi kas, utang, dan valuasi sebelum mengandalkan momentum harga.', 'Tinjauan fundamental menguji beberapa sinyal bisnis, bukan menerima satu judul positif.'),
    ('etfs-investing-with-one-click-part-2', 'Two ETFs track similar baskets but one has lower fees. What is the strongest conclusion?', jsonb_build_array('Lower fees are one factor; tracking, liquidity, price, and goal fit still need comparison.', 'The lower-fee ETF must have the higher future return.', 'Similar baskets make liquidity and tracking irrelevant.', 'The fee alone tells you which product suits every investor.'), 'Lower fees are one factor; tracking, liquidity, price, and goal fit still need comparison.', 'A fee comparison is useful but incomplete; it cannot settle risk or suitability.', 'Dua ETF melacak keranjang yang mirip tetapi salah satunya memiliki biaya lebih rendah. Apa kesimpulan terkuat?', jsonb_build_array('Biaya rendah adalah satu faktor; pelacakan, likuiditas, harga, dan kecocokan tujuan tetap perlu dibandingkan.', 'ETF dengan biaya lebih rendah pasti memberi imbal hasil masa depan lebih tinggi.', 'Keranjang yang mirip membuat likuiditas dan pelacakan tidak relevan.', 'Biaya saja memberi tahu produk yang cocok untuk semua investor.'), 'Biaya rendah adalah satu faktor; pelacakan, likuiditas, harga, dan kecocokan tujuan tetap perlu dibandingkan.', 'Perbandingan biaya berguna tetapi tidak lengkap; tidak dapat menentukan risiko atau kecocokan.'),
    ('bonds-sbn-safe-investing-with-the-government-part-2', 'What must accompany an illustrative SBN coupon calculation before relying on it?', jsonb_build_array('The named series, source date, current terms, tax treatment, and payment schedule.', 'A larger principal amount, because that makes the example current.', 'A promise that the next SBN offer will use the same rate.', 'Only the issuer name, because all government series share terms.'), 'The named series, source date, current terms, tax treatment, and payment schedule.', 'The arithmetic is only a teaching example until the current series documents are checked.', 'Apa yang harus menyertai perhitungan kupon SBN ilustratif sebelum diandalkan?', jsonb_build_array('Seri yang disebut, tanggal sumber, ketentuan terbaru, perlakuan pajak, dan jadwal pembayaran.', 'Jumlah pokok yang lebih besar karena membuat contoh menjadi terbaru.', 'Janji bahwa penawaran SBN berikutnya memakai tarif yang sama.', 'Hanya nama penerbit karena semua seri pemerintah memiliki ketentuan yang sama.'), 'Seri yang disebut, tanggal sumber, ketentuan terbaru, perlakuan pajak, dan jadwal pembayaran.', 'Aritmetika hanya contoh pembelajaran sampai dokumen seri terbaru diperiksa.'),
    ('tax-basics-npwp-pph-21-and-filing-taxes-part-2', 'Which sequence best reduces a filing mistake?', jsonb_build_array('Gather records, identify the current route, check the deadline, submit, and save confirmation.', 'Submit first, then find the form and deadline if the system accepts it.', 'Copy a previous form, change the name, and skip the current instructions.', 'Wait for another person’s result before checking your own taxpayer details.'), 'Gather records, identify the current route, check the deadline, submit, and save confirmation.', 'The sequence keeps records, current instructions, deadline, submission, and evidence connected.', 'Urutan mana yang paling mengurangi kesalahan pelaporan?', jsonb_build_array('Kumpulkan catatan, identifikasi jalur terbaru, periksa tenggat, kirim, dan simpan konfirmasi.', 'Kirim dulu, lalu cari formulir dan tenggat jika sistem menerimanya.', 'Salin formulir lama, ganti nama, dan lewati petunjuk terbaru.', 'Tunggu hasil orang lain sebelum memeriksa detail wajib pajak sendiri.'), 'Kumpulkan catatan, identifikasi jalur terbaru, periksa tenggat, kirim, dan simpan konfirmasi.', 'Urutan tersebut menghubungkan catatan, petunjuk terbaru, tenggat, pelaporan, dan bukti.'),
    ('brokerage-account-setup-opening-your-rdn-part-2', 'What makes a provider-specific funding instruction trustworthy enough to follow?', jsonb_build_array('It names the provider, comes through a verified official channel, and matches current account details.', 'It arrives quickly and promises a bonus for immediate transfer.', 'It uses a provider logo even when the account is personal.', 'It matches a screenshot from a different provider.'), 'It names the provider, comes through a verified official channel, and matches current account details.', 'Funding instructions need a trusted source and an account-level check, not only branding.', 'Apa yang membuat petunjuk pengisian dana khusus penyedia cukup tepercaya untuk diikuti?', jsonb_build_array('Petunjuk menyebut penyedia, berasal dari kanal resmi terverifikasi, dan cocok dengan detail rekening terbaru.', 'Petunjuk datang cepat dan menjanjikan bonus untuk transfer segera.', 'Petunjuk memakai logo penyedia meskipun rekeningnya pribadi.', 'Petunjuk cocok dengan tangkapan layar dari penyedia lain.'), 'Petunjuk menyebut penyedia, berasal dari kanal resmi terverifikasi, dan cocok dengan detail rekening terbaru.', 'Petunjuk dana memerlukan sumber tepercaya dan pemeriksaan tingkat rekening, bukan hanya merek.'),
    ('stock-analysis-basics-fundamental-vs-technical-part-2', 'A five-period chart shows three closes above their opens. What can you conclude?', jsonb_build_array('That observation describes those periods; it does not establish the next move or suitability.', 'That the next period has a greater-than-guaranteed chance of rising.', 'That the company’s financial health is proven by the candles.', 'That the chart is a suitable plan for every investor.'), 'That observation describes those periods; it does not establish the next move or suitability.', 'A chart can organise dated observations, but it cannot prove a forecast or personal fit.', 'Grafik lima periode menunjukkan tiga penutupan di atas pembukaannya. Apa yang dapat disimpulkan?', jsonb_build_array('Pengamatan itu menggambarkan periode tersebut; bukan arah berikutnya atau kecocokan.', 'Periode berikutnya memiliki peluang naik yang lebih besar dan dijamin.', 'Kesehatan keuangan perusahaan terbukti dari candle.', 'Grafik tersebut adalah rencana yang cocok untuk semua investor.'), 'Pengamatan itu menggambarkan periode tersebut; bukan arah berikutnya atau kecocokan.', 'Grafik dapat menyusun pengamatan bertanggal, tetapi tidak membuktikan prediksi atau kecocokan pribadi.')
), inserted AS (
  INSERT INTO public.content_variants (lesson_id, variant_type, body, body_id, difficulty, topic_tag, is_active)
  SELECT lesson.id,
    'question',
    jsonb_build_object('type', 'multiple_choice', 'question', additions.question_en, 'options', additions.options_en, 'answer', additions.answer_en, 'difficulty', 'intermediate', 'explanation', additions.explanation_en),
    jsonb_build_object('type', 'multiple_choice', 'question', additions.question_id, 'options', additions.options_id, 'answer', additions.answer_id, 'difficulty', 'intermediate', 'explanation', additions.explanation_id),
    'intermediate', 'visual_applied', TRUE
  FROM additions
  JOIN public.lessons AS lesson ON lesson.slug = additions.slug
  WHERE NOT EXISTS (
    SELECT 1 FROM public.content_variants AS existing
    WHERE existing.lesson_id = lesson.id
      AND existing.variant_type = 'question'
      AND existing.topic_tag = 'visual_applied'
      AND existing.body->>'question' = additions.question_en
  )
  RETURNING id
)
SELECT count(*) AS inserted_visual_questions FROM inserted;

COMMIT;
