-- KO-225 group 5: translate neutral-looking Indonesian payloads whose body/body_id
-- equality still leaked Indonesian into the English pool.
update public.content_variants set body = $json${"type":"fill_blank","answer":"rule","question":"A way to fight FOMO is to create an investment _____ before emotions take over.","difficulty":"intermediate","parameters":{},"explanation":"A rule created while calm helps you resist impulsive decisions when FOMO appears."}$json$::jsonb where id = '28b57497-aac8-4839-8ef5-48019e239738';
update public.content_variants set body = $json${"type":"fill_blank","answer":"OJK","question":"Before investing, always check the financial product's licence on the ____ website.","difficulty":"beginner","parameters":{},"explanation":"The Financial Services Authority (OJK) supervises financial products in Indonesia."}$json$::jsonb where id = '6c3d2d55-120f-49dd-a100-f2bca61614ec';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"A legitimate bank will ask for your ATM PIN through WhatsApp to keep your account secure.","difficulty":"beginner","explanation":"Legitimate banks never ask customers for their PIN, password, or one-time password (OTP)."}$json$::jsonb where id = '5cc92861-76c4-4d7b-8467-cbd2751d0ebb';
update public.content_variants set body = $json${"type":"fill_blank","answer":"unit of account","question":"Money's function as a _____ lets us compare the prices of different goods easily.","difficulty":"beginner","parameters":{},"explanation":"A unit of account lets us express the value of goods in rupiah, making prices easier to compare."}$json$::jsonb where id = '6f90ed04-f80c-478d-a14c-f1c6b8ae4ec8';
update public.content_variants set body = $json${"type":"fill_blank","answer":"OJK","question":"Before investing, first check the company's licence on the _____ website.","difficulty":"beginner","parameters":{},"explanation":"The Financial Services Authority (OJK) regulates and supervises financial products in Indonesia."}$json$::jsonb where id = '455b7871-3f75-42d6-bc27-f8dafdef2518';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"A GoPay or OVO balance does not count as money because it is not made of banknotes.","difficulty":"beginner","explanation":"An electronic balance is still accepted as a medium of exchange and unit of account, so it is a form of digital money."}$json$::jsonb where id = '1be59258-3ac0-41ec-acf5-2317e09bee81';
update public.content_variants set body = $json${"type":"fill_blank","answer":"2.5","question":"Bank Indonesia's inflation target is approximately ____% ± 1%.","difficulty":"intermediate","parameters":{},"explanation":"Bank Indonesia sets an inflation target of approximately 2.5% ± 1%."}$json$::jsonb where id = 'e5e33ab5-9d50-4cf5-bf86-446a7caf0d0c';
