-- KO-429: raise Chapter 10 — Reading Trading Charts quiz quality.
-- Keep the existing chart payloads; replace definition-level prompts and
-- giveaway distractors with chart-evidence and uncertainty reasoning.
-- All figures remain illustrative and are not trading instructions.

CREATE TEMP TABLE ko429_revised AS
WITH revised(slug, old_en, old_id, question_en, question_id, options_en, options_id, answer_en, answer_id, explanation_en, explanation_id) AS (
  VALUES
  ('chart-ohcl-basics', 'Which price tells you where the period ended?', 'Harga mana yang menunjukkan di mana periode berakhir?', 'A candle opens at 100, trades from 94 to 116, and closes at 109. Which conclusion is directly supported?', 'Sebuah candle dibuka di 100, bergerak antara 94 dan 116, lalu ditutup di 109. Kesimpulan mana yang langsung didukung?', jsonb_build_array('Buyers finished the period above the open; the candle alone does not establish a future trend', 'The next period must close higher', 'The high of 116 was the closing price', 'The candle proves the company is strong'), jsonb_build_array('Pembeli mengakhiri periode di atas open; candle saja tidak menentukan tren berikutnya', 'Periode berikutnya pasti ditutup lebih tinggi', 'High 116 adalah harga penutupan', 'Candle membuktikan perusahaan itu kuat'), 'Buyers finished the period above the open; the candle alone does not establish a future trend', 'Pembeli mengakhiri periode di atas open; candle saja tidak menentukan tren berikutnya', 'The close above the open describes this period''s net direction, but it does not forecast the next period or explain the company.', 'Close di atas open menggambarkan arah bersih periode ini, tetapi tidak meramalkan periode berikutnya atau menjelaskan perusahaan.'),
  ('chart-ohcl-basics', 'The distance from 94 to 116 on the candle represents what?', 'Jarak dari 94 ke 116 pada candle mewakili apa?', 'A candle has a 22-point high-low range and a 9-point open-close body. What does that contrast show?', 'Sebuah candle memiliki rentang high-low 22 poin dan body open-close 9 poin. Apa yang ditunjukkan perbandingan ini?', jsonb_build_array('Price explored a wider range than the net change between open and close', 'The body contains every traded price', 'The range predicts the next period''s exact range', 'The close must have been the high'), jsonb_build_array('Harga menjelajahi rentang lebih luas daripada perubahan bersih open ke close', 'Body berisi semua harga yang diperdagangkan', 'Rentang meramalkan rentang persis periode berikutnya', 'Close pasti sama dengan high'), 'Price explored a wider range than the net change between open and close', 'Harga menjelajahi rentang lebih luas daripada perubahan bersih open ke close', 'The wick-to-wick range records intraperiod exploration, while the body records only the open-to-close result.', 'Rentang dari wick ke wick mencatat pergerakan dalam periode, sedangkan body hanya mencatat hasil open ke close.'),
  ('chart-ohcl-basics', 'Looking at the practice candle, what was the highest price reached?', 'Melihat candle latihan, berapa harga tertinggi yang tercapai?', 'Two candles both close at 109. One opens at 100 and the other at 115. What is the safest comparison?', 'Dua candle sama-sama ditutup di 109. Satu dibuka di 100 dan lainnya di 115. Perbandingan paling aman apa?', jsonb_build_array('They have different open-to-close stories despite the same closing price', 'They show the same direction because their closes match', 'Both must have had the same high and low', 'The second candle proves a reversal'), jsonb_build_array('Keduanya memiliki cerita open-ke-close berbeda meski harga close sama', 'Keduanya menunjukkan arah sama karena close-nya sama', 'Keduanya pasti memiliki high dan low sama', 'Candle kedua membuktikan pembalikan'), 'They have different open-to-close stories despite the same closing price', 'Keduanya memiliki cerita open-ke-close berbeda meski harga close sama', 'A closing price is one coordinate; comparing it with each candle''s open reveals the period''s direction.', 'Harga close adalah satu koordinat; membandingkannya dengan open tiap candle menunjukkan arah periode.'),

  ('chart-body-and-wick', 'What does the upper wick show?', 'Apa yang ditunjukkan oleh wick atas?', 'A candle reaches 120 but closes at 114 after opening at 100. What can you conclude with the highest confidence?', 'Sebuah candle mencapai 120 tetapi ditutup di 114 setelah dibuka di 100. Apa kesimpulan yang paling kuat?', jsonb_build_array('Price traded at 120 but did not hold that high by the close', '120 was the closing price', 'No sellers entered near 120', 'A reversal is guaranteed next'), jsonb_build_array('Harga diperdagangkan di 120 tetapi tidak bertahan di level itu saat close', '120 adalah harga close', 'Tidak ada penjual di dekat 120', 'Pembalikan berikutnya dijamin'), 'Price traded at 120 but did not hold that high by the close', 'Harga diperdagangkan di 120 tetapi tidak bertahan di level itu saat close', 'The upper wick proves the high was visited and not retained at the close; it does not predict what follows.', 'Wick atas membuktikan high sempat dicapai tetapi tidak bertahan saat close; ini tidak meramalkan kelanjutannya.'),
  ('chart-body-and-wick', 'In the Up candle, the body runs from which prices?', 'Pada candle Naik, body berada di rentang harga mana?', 'The body spans 100 to 114 while the full range spans 92 to 120. Which description is accurate?', 'Body berada dari 100 sampai 114 sedangkan rentang penuh dari 92 sampai 120. Deskripsi mana yang tepat?', jsonb_build_array('The body shows the open-close result; the wicks show excursions beyond it', 'The body shows every price traded during the period', 'The wicks are future price estimates', 'The full range is the company''s intrinsic value'), jsonb_build_array('Body menunjukkan hasil open-close; wick menunjukkan pergerakan di luarnya', 'Body menunjukkan semua harga yang diperdagangkan selama periode', 'Wick adalah perkiraan harga masa depan', 'Rentang penuh adalah nilai intrinsik perusahaan'), 'The body shows the open-close result; the wicks show excursions beyond it', 'Body menunjukkan hasil open-close; wick menunjukkan pergerakan di luarnya', 'Separating body from wicks prevents a net move from being confused with the full intraperiod range.', 'Memisahkan body dan wick mencegah perubahan bersih disamakan dengan seluruh rentang periode.'),
  ('chart-body-and-wick', 'A long lower wick with a small body suggests what?', 'Wick bawah panjang dengan body kecil mengindikasikan apa?', 'A long lower wick ends in a small body. What is the most responsible next interpretation?', 'Wick bawah panjang berakhir dengan body kecil. Interpretasi lanjutan yang paling bertanggung jawab apa?', jsonb_build_array('Price was pushed lower and recovered before the close; inspect context before judging it', 'Buyers will always win next', 'The trend is confirmed without another candle', 'Open and close must be identical'), jsonb_build_array('Harga sempat ditekan turun lalu pulih sebelum close; periksa konteks sebelum menilainya', 'Pembeli selalu menang berikutnya', 'Tren sudah terkonfirmasi tanpa candle lain', 'Open dan close pasti identik'), 'Price was pushed lower and recovered before the close; inspect context before judging it', 'Harga sempat ditekan turun lalu pulih sebelum close; periksa konteks sebelum menilainya', 'The shape records rejection within the period. Its significance depends on the preceding trend, level, and subsequent evidence.', 'Bentuk ini mencatat penolakan dalam periode. Maknanya bergantung pada tren sebelumnya, level, dan bukti setelahnya.'),

  ('chart-bullish-bearish-doji', 'Which candle closes above its open?', 'Candle mana yang ditutup di atas open-nya?', 'A bullish candle closes above its open. What does that label establish—and what does it not establish?', 'Candle bullish ditutup di atas open-nya. Apa yang ditetapkan label itu—dan apa yang tidak?', jsonb_build_array('Net direction for that period, not a guaranteed next move', 'A guaranteed future rise', 'Company quality independent of price', 'That every buyer made a profit'), jsonb_build_array('Arah bersih periode itu, bukan langkah berikutnya yang dijamin', 'Kenaikan masa depan yang dijamin', 'Kualitas perusahaan terlepas dari harga', 'Semua pembeli mendapat keuntungan'), 'Net direction for that period, not a guaranteed next move', 'Arah bersih periode itu, bukan langkah berikutnya yang dijamin', 'Bullish describes open versus close for the displayed period; it is not a forecast or suitability judgement.', 'Bullish menggambarkan perbandingan open dan close pada periode tersebut; bukan ramalan atau penilaian kecocokan.'),
  ('chart-bullish-bearish-doji', 'What does a doji mainly show?', 'Apa yang utama ditunjukkan oleh doji?', 'A doji appears after a rising sequence. Which reading best respects the evidence?', 'Doji muncul setelah rangkaian kenaikan. Pembacaan mana yang paling menghormati bukti?', jsonb_build_array('The period ended near its open; the prior rise and later confirmation still matter', 'A reversal is guaranteed', 'Buyers won decisively', 'Sellers won decisively'), jsonb_build_array('Periode berakhir dekat open; kenaikan sebelumnya dan konfirmasi berikutnya tetap penting', 'Pembalikan dijamin', 'Pembeli menang dengan tegas', 'Penjual menang dengan tegas'), 'The period ended near its open; the prior rise and later confirmation still matter', 'Periode berakhir dekat open; kenaikan sebelumnya dan konfirmasi berikutnya tetap penting', 'A doji shows limited net change in that period. Its meaning is conditional on surrounding structure and later evidence.', 'Doji menunjukkan perubahan bersih yang terbatas pada periode itu. Maknanya bergantung pada struktur sekitar dan bukti berikutnya.'),
  ('chart-bullish-bearish-doji', 'Why should you not rely only on the bullish or bearish colour?', 'Mengapa tidak boleh mengandalkan warna bullish atau bearish saja?', 'When comparing bullish, bearish, and doji candles, which additional evidence most improves the interpretation?', 'Saat membandingkan candle bullish, bearish, dan doji, bukti tambahan mana yang paling meningkatkan interpretasi?', jsonb_build_array('The preceding trend, timeframe, and what happens after the candle', 'The candle colour alone', 'A promise that the next candle must agree', 'The name of the pattern without its prices'), jsonb_build_array('Tren sebelumnya, timeframe, dan apa yang terjadi setelah candle', 'Warna candle saja', 'Janji bahwa candle berikutnya pasti sama', 'Nama pola tanpa harganya'), 'The preceding trend, timeframe, and what happens after the candle', 'Tren sebelumnya, timeframe, dan apa yang terjadi setelah candle', 'Context turns a candle label into an observation rather than an isolated prediction.', 'Konteks mengubah label candle menjadi pengamatan, bukan prediksi yang berdiri sendiri.'),

  ('chart-long-wick-rejection', 'In the sequence, what created the long upper wick?', 'Dalam rangkaian, apa yang menciptakan wick atas panjang?', 'A candle reaches 120 but closes at 108 after opening at 106. Which explanation fits the candle evidence?', 'Sebuah candle mencapai 120 tetapi ditutup di 108 setelah dibuka di 106. Penjelasan mana yang sesuai dengan bukti candle?', jsonb_build_array('Price explored higher levels but selling pressure returned it before the close', 'The close was above the high', 'No sellers entered at the high', 'The next period must reverse'), jsonb_build_array('Harga menjelajahi level lebih tinggi tetapi tekanan jual mengembalikannya sebelum close', 'Close berada di atas high', 'Tidak ada penjual di high', 'Periode berikutnya pasti berbalik'), 'Price explored higher levels but selling pressure returned it before the close', 'Harga menjelajahi level lebih tinggi tetapi tekanan jual mengembalikannya sebelum close', 'The wick records rejection within this period; it does not identify a certain future direction.', 'Wick mencatat penolakan dalam periode ini; tidak menentukan arah masa depan.'),
  ('chart-long-wick-rejection', 'A long upper wick after a rise is best read as what?', 'Wick atas panjang setelah kenaikan paling baik dibaca sebagai apa?', 'A rise, long upper wick, and later pullback are visible. What does that sequence support?', 'Terlihat kenaikan, wick atas panjang, lalu pullback. Apa yang didukung rangkaian ini?', jsonb_build_array('Selling appeared near the high and the later candle provided follow-through evidence', 'The wick alone commanded an immediate sale', 'The price must keep rising', 'A reversal was guaranteed at the first wick'), jsonb_build_array('Tekanan jual muncul dekat high dan candle berikutnya memberi bukti lanjutan', 'Wick saja memerintahkan penjualan segera', 'Harga pasti terus naik', 'Pembalikan dijamin pada wick pertama'), 'Selling appeared near the high and the later candle provided follow-through evidence', 'Tekanan jual muncul dekat high dan candle berikutnya memberi bukti lanjutan', 'The later pullback adds context; the conclusion remains an observation about the sequence, not a trade instruction.', 'Pullback berikutnya menambah konteks; kesimpulannya tetap pengamatan rangkaian, bukan instruksi transaksi.'),
  ('chart-long-wick-rejection', 'What happened after the long wick formed?', 'Apa yang terjadi setelah wick panjang terbentuk?', 'If the long upper wick appears in isolation, what is the best learner response?', 'Jika wick atas panjang muncul tanpa konteks lain, respons pelajar yang paling tepat apa?', jsonb_build_array('Record it as a clue and inspect timeframe, levels, and subsequent candles', 'Treat it as proof of reversal', 'Ignore all other evidence', 'Assume the wick becomes the next body'), jsonb_build_array('Catat sebagai petunjuk dan periksa timeframe, level, serta candle berikutnya', 'Anggap sebagai bukti pembalikan', 'Abaikan semua bukti lain', 'Anggap wick menjadi body berikutnya'), 'Record it as a clue and inspect timeframe, levels, and subsequent candles', 'Catat sebagai petunjuk dan periksa timeframe, level, serta candle berikutnya', 'A single shape is incomplete evidence. Good chart reading keeps the observation separate from the decision.', 'Satu bentuk adalah bukti yang belum lengkap. Membaca grafik dengan baik memisahkan pengamatan dari keputusan.'),

  ('chart-hammer-shooting-star', 'A hammer has a small body and a long wick in which direction?', 'Hammer memiliki body kecil dan wick panjang ke arah mana?', 'When comparing a hammer with a shooting star, which feature is most useful for classification?', 'Saat membandingkan hammer dengan shooting star, fitur mana yang paling berguna untuk klasifikasi?', jsonb_build_array('The side of the body where the long wick extends', 'The pattern name alone', 'The colour without open and close', 'A guaranteed next move'), jsonb_build_array('Sisi body tempat wick panjang memanjang', 'Nama pola saja', 'Warna tanpa open dan close', 'Langkah berikutnya yang dijamin'), 'The side of the body where the long wick extends', 'Sisi body tempat wick panjang memanjang', 'The geometry distinguishes the shapes; interpretation still needs trend and confirmation.', 'Geometri membedakan bentuk; interpretasinya tetap membutuhkan tren dan konfirmasi.'),
  ('chart-hammer-shooting-star', 'Which statement about these patterns is correct?', 'Pernyataan mana tentang pola-pola ini yang benar?', 'A named candle pattern is visible after an uncertain market phase. What should the learner check next?', 'Pola candle terlihat setelah fase pasar yang tidak pasti. Apa yang perlu diperiksa pelajar berikutnya?', jsonb_build_array('The preceding trend, nearby levels, timeframe, and later price action', 'A universal buy or sell rule for the pattern', 'Only the candle colour', 'Whether the name sounds bullish'), jsonb_build_array('Tren sebelumnya, level terdekat, timeframe, dan pergerakan harga setelahnya', 'Aturan beli atau jual universal untuk pola itu', 'Hanya warna candle', 'Apakah namanya terdengar bullish'), 'The preceding trend, nearby levels, timeframe, and later price action', 'Tren sebelumnya, level terdekat, timeframe, dan pergerakan harga setelahnya', 'Patterns are vocabulary for describing evidence. Context determines how much weight to give that evidence.', 'Pola adalah kosakata untuk mendeskripsikan bukti. Konteks menentukan seberapa besar bobot bukti itu.'),
  ('chart-hammer-shooting-star', 'An inverted hammer has a long upper wick and a small body near which end?', 'Inverted hammer memiliki wick atas panjang dan body kecil di dekat ujung mana?', 'An inverted hammer has a small body near the low and a long upper wick. Which claim is still too strong?', 'Inverted hammer memiliki body kecil dekat low dan wick atas panjang. Klaim mana yang masih terlalu kuat?', jsonb_build_array('It guarantees a bullish reversal', 'It records an intraperiod test of higher prices', 'Its body is located near the lower end', 'Its meaning depends on surrounding context'), jsonb_build_array('Ini menjamin pembalikan bullish', 'Ini mencatat pengujian harga lebih tinggi dalam periode', 'Body-nya berada dekat ujung bawah', 'Maknanya bergantung pada konteks sekitar'), 'It guarantees a bullish reversal', 'Ini menjamin pembalikan bullish', 'The shape can describe a rejection attempt, but no single candle guarantees a future reversal.', 'Bentuknya dapat menggambarkan upaya penolakan, tetapi tidak ada candle yang menjamin pembalikan.'),

  ('chart-support-resistance', 'Why is support described as a zone rather than a single price?', 'Mengapa support dijelaskan sebagai zona bukan harga tunggal?', 'Several nearby lows cluster in the same area. Why is a zone a better description than one exact support price?', 'Beberapa low yang berdekatan berkumpul di area yang sama. Mengapa zona lebih tepat daripada satu harga support yang persis?', jsonb_build_array('Reactions occur across a nearby range rather than at one perfectly repeatable number', 'One touch proves the exact floor', 'A zone guarantees a bounce', 'The zone is the company''s fair value'), jsonb_build_array('Reaksi terjadi di rentang berdekatan, bukan pada satu angka yang selalu sama persis', 'Satu sentuhan membuktikan lantai tepat', 'Zona menjamin pantulan', 'Zona adalah nilai wajar perusahaan'), 'Reactions occur across a nearby range rather than at one perfectly repeatable number', 'Reaksi terjadi di rentang berdekatan, bukan pada satu angka yang selalu sama persis', 'Repeated nearby reactions support an area-based interpretation and acknowledge price variability.', 'Reaksi berulang yang berdekatan mendukung interpretasi berbasis area dan mengakui variasi harga.'),
  ('chart-support-resistance', 'In the chart, resistance is where price has repeatedly done what?', 'Pada grafik, resistance adalah area di mana harga berulang kali melakukan apa?', 'The highs near one area repeatedly fail to hold. Which observation best describes that area?', 'High di dekat satu area berulang kali gagal bertahan. Pengamatan mana yang paling tepat menggambarkan area itu?', jsonb_build_array('Rising price has repeatedly reversed lower near the area', 'Price must break higher next', 'Every candle stayed flat there', 'Sellers were absent there'), jsonb_build_array('Harga yang naik berulang kali berbalik turun dekat area tersebut', 'Harga pasti menembus naik berikutnya', 'Setiap candle tetap datar di sana', 'Tidak ada penjual di sana'), 'Rising price has repeatedly reversed lower near the area', 'Harga yang naik berulang kali berbalik turun dekat area tersebut', 'Resistance describes a historical reaction area; it is not a promise about the next test.', 'Resistance menggambarkan area reaksi historis; bukan janji tentang pengujian berikutnya.'),
  ('chart-support-resistance', 'If price briefly moves below a support zone then returns, what does that suggest?', 'Jika harga sebentar bergerak di bawah zona support lalu kembali, apa yang disarankan?', 'Price briefly dips below a support zone and closes back inside it. What is the most careful reading?', 'Harga sempat turun di bawah zona support lalu ditutup kembali di dalamnya. Pembacaan paling hati-hati apa?', jsonb_build_array('The area has variability; the breach is evidence to inspect, not proof of a guaranteed bounce', 'Support always holds exactly', 'The zone is permanently invalid', 'Price must fall on the next candle'), jsonb_build_array('Area memiliki variasi; breach adalah bukti untuk diperiksa, bukan jaminan pantulan', 'Support selalu bertahan tepat', 'Zona selamanya tidak valid', 'Harga pasti turun pada candle berikutnya'), 'The area has variability; the breach is evidence to inspect, not proof of a guaranteed bounce', 'Area memiliki variasi; breach adalah bukti untuk diperiksa, bukan jaminan pantulan', 'A brief breach and recovery can inform the zone assessment, but it does not settle the future direction.', 'Breach singkat lalu pemulihan dapat memberi informasi tentang zona, tetapi tidak menentukan arah masa depan.'),

  ('chart-trend-and-timeframe', 'The daily chart shows a smoother trend because each candle covers what?', 'Grafik harian menunjukkan tren yang lebih halus karena setiap candle mencakup apa?', 'A daily chart looks smoother than an hourly chart for the same period. What is the key trade-off?', 'Grafik harian terlihat lebih halus daripada grafik per jam untuk periode sama. Apa trade-off utamanya?', jsonb_build_array('It compresses a full day into each candle, reducing visible intraday detail', 'It removes all volatility from the market', 'It guarantees a more accurate forecast', 'It contains only one trade per day'), jsonb_build_array('Grafik memadatkan satu hari penuh dalam tiap candle sehingga detail intraday lebih sedikit', 'Grafik menghapus semua volatilitas pasar', 'Grafik menjamin ramalan lebih akurat', 'Grafik hanya berisi satu transaksi per hari'), 'It compresses a full day into each candle, reducing visible intraday detail', 'Grafik memadatkan satu hari penuh dalam tiap candle sehingga detail intraday lebih sedikit', 'Aggregation can make a trend look smoother while hiding shorter-term movement; it does not remove the movement itself.', 'Agregasi dapat membuat tren tampak lebih halus sambil menyembunyikan pergerakan pendek; bukan menghapus pergerakannya.'),
  ('chart-trend-and-timeframe', 'Why does the hourly chart look noisier for the same period?', 'Mengapa grafik per jam terlihat lebih berisik untuk periode yang sama?', 'Why can two timeframes show different-looking trends for the same dates?', 'Mengapa dua timeframe dapat menunjukkan tren yang tampak berbeda pada tanggal yang sama?', jsonb_build_array('Each timeframe aggregates the same activity differently and exposes different detail', 'One timeframe must contain incorrect prices', 'The longer timeframe hides every price movement', 'The trend necessarily changed when the timeframe changed'), jsonb_build_array('Setiap timeframe mengagregasi aktivitas yang sama secara berbeda dan menampilkan detail berbeda', 'Salah satu timeframe pasti berisi harga salah', 'Timeframe lebih panjang menyembunyikan semua pergerakan harga', 'Tren pasti berubah saat timeframe berubah'), 'Each timeframe aggregates the same activity differently and exposes different detail', 'Setiap timeframe mengagregasi aktivitas yang sama secara berbeda dan menampilkan detail berbeda', 'Timeframe is an observation lens. A different lens changes visible detail, not the underlying historical events.', 'Timeframe adalah lensa pengamatan. Lensa berbeda mengubah detail yang terlihat, bukan peristiwa historisnya.'),
  ('chart-trend-and-timeframe', 'A pattern should always be read with what information?', 'Pola harus selalu dibaca dengan informasi apa?', 'A similar candle appears on hourly and daily charts. What must be stated before comparing its significance?', 'Candle serupa muncul pada grafik per jam dan harian. Apa yang harus disebutkan sebelum membandingkan maknanya?', jsonb_build_array('The timeframe, surrounding trend, and the evidence being compared', 'Only the candle colour', 'The pattern name without its dates', 'A prediction that both charts will agree'), jsonb_build_array('Timeframe, tren sekitar, dan bukti yang dibandingkan', 'Hanya warna candle', 'Nama pola tanpa tanggalnya', 'Prediksi bahwa kedua grafik pasti sama'), 'The timeframe, surrounding trend, and the evidence being compared', 'Timeframe, tren sekitar, dan bukti yang dibandingkan', 'The same shape can carry different context when the aggregation window and surrounding structure change.', 'Bentuk sama dapat memiliki konteks berbeda saat jendela agregasi dan struktur sekitarnya berubah.'),

  ('chart-reading-limits', 'Why should chart reading be combined with goals and risk limits?', 'Mengapa membaca grafik harus dikombinasikan dengan tujuan dan batas risiko?', 'A chart shows a possible setup. Why should goals and risk limits still be checked?', 'Grafik menunjukkan kemungkinan setup. Mengapa tujuan dan batas risiko tetap harus diperiksa?', jsonb_build_array('Price history does not determine whether a decision fits the learner''s situation', 'A chart replaces personal planning', 'A pattern guarantees a profitable outcome', 'A chart contains complete business research'), jsonb_build_array('Riwayat harga tidak menentukan apakah keputusan cocok dengan situasi pelajar', 'Grafik menggantikan perencanaan pribadi', 'Pola menjamin hasil menguntungkan', 'Grafik berisi riset bisnis lengkap'), 'Price history does not determine whether a decision fits the learner''s situation', 'Riwayat harga tidak menentukan apakah keputusan cocok dengan situasi pelajar', 'Chart evidence and personal suitability answer different questions; both need separate consideration.', 'Bukti grafik dan kecocokan pribadi menjawab pertanyaan berbeda; keduanya perlu dipertimbangkan terpisah.'),
  ('chart-reading-limits', 'Which of these can a price chart show?', 'Manakah dari berikut ini yang bisa ditunjukkan grafik harga?', 'Which statement stays within what a historical price chart can actually support?', 'Pernyataan mana yang tetap berada dalam batas yang dapat didukung grafik harga historis?', jsonb_build_array('It can show past open, high, low, and close data', 'It can guarantee a future price', 'It can judge management quality', 'It can decide whether an investment suits every learner'), jsonb_build_array('Grafik dapat menunjukkan data open, high, low, dan close masa lalu', 'Grafik dapat menjamin harga masa depan', 'Grafik dapat menilai kualitas manajemen', 'Grafik dapat menentukan investasi cocok untuk setiap pelajar'), 'It can show past open, high, low, and close data', 'Grafik dapat menunjukkan data open, high, low, dan close masa lalu', 'A price chart is historical market evidence. Fundamental quality and personal suitability require other sources and reasoning.', 'Grafik harga adalah bukti pasar historis. Kualitas fundamental dan kecocokan pribadi membutuhkan sumber serta penalaran lain.'),
  ('chart-reading-limits', 'A chart pattern alone cannot tell you what?', 'Pola grafik saja tidak dapat memberitahumu apa?', 'After spotting a pattern, which question remains outside the chart itself?', 'Setelah menemukan pola, pertanyaan mana yang tetap berada di luar grafik itu sendiri?', jsonb_build_array('Whether the investment fits the learner''s goals, risk capacity, and circumstances', 'Where price reacted in the displayed history', 'How wide the displayed period''s range was', 'What the displayed candle''s close was'), jsonb_build_array('Apakah investasi cocok dengan tujuan, kapasitas risiko, dan keadaan pelajar', 'Di mana harga bereaksi dalam riwayat yang ditampilkan', 'Seberapa lebar rentang periode yang ditampilkan', 'Berapa harga close candle yang ditampilkan'), 'Whether the investment fits the learner''s goals, risk capacity, and circumstances', 'Apakah investasi cocok dengan tujuan, kapasitas risiko, dan keadaan pelajar', 'Suitability is a personal decision boundary, not a property that can be read from a price pattern alone.', 'Kecocokan adalah batas keputusan pribadi, bukan sesuatu yang dapat dibaca dari pola harga saja.')
)
SELECT * FROM revised;

DO $$
DECLARE
  expected INTEGER := 24;
  matched INTEGER;
BEGIN
  SELECT COUNT(*) INTO matched
  FROM public.content_variants v
  JOIN public.lessons l ON l.id = v.lesson_id
  JOIN ko429_revised u ON u.slug = l.slug AND u.old_en = v.body->>'question'
  WHERE v.variant_type = 'question'
    AND v.topic_tag = 'visual_applied'
    AND v.is_active = TRUE;
  IF matched <> expected THEN
    RAISE EXCEPTION 'KO-429 expected % exact English source rows before update, found %', expected, matched;
  END IF;
END $$;

UPDATE public.content_variants v
SET body = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(v.body, '{question}', to_jsonb(u.question_en)), '{options}', u.options_en), '{answer}', to_jsonb(u.answer_en)), '{explanation}', to_jsonb(u.explanation_en)), '{difficulty}', '"intermediate"'::jsonb),
    body_id = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(v.body_id, '{question}', to_jsonb(u.question_id)), '{options}', u.options_id), '{answer}', to_jsonb(u.answer_id)), '{explanation}', to_jsonb(u.explanation_id)), '{difficulty}', '"intermediate"'::jsonb)
FROM ko429_revised u
JOIN public.lessons l ON l.slug = u.slug
WHERE v.lesson_id = l.id
  AND v.variant_type = 'question'
  AND v.topic_tag = 'visual_applied'
  AND v.is_active = TRUE
  AND v.body->>'question' = u.old_en;

DO $$
DECLARE
  expected INTEGER := 24;
  changed INTEGER;
BEGIN
  SELECT COUNT(*) INTO changed
  FROM public.content_variants v
  JOIN ko429_revised u ON u.question_en = v.body->>'question'
  AND v.variant_type = 'question'
  AND v.topic_tag = 'visual_applied'
  AND v.is_active = TRUE
  AND v.body->>'difficulty' = 'intermediate';
  IF changed <> expected THEN
    RAISE EXCEPTION 'KO-429 expected % rewritten English payloads, found %', expected, changed;
  END IF;
END $$;
