-- KO-225: final exact pairs. Keep body_id in Bahasa Indonesia and restore
-- English source payloads for variants that were authored in Indonesian.
update public.content_variants set body_id = $json${"type":"comparison","answer":"Deposito bank berlisensi OJK","options":["Deposito bank berlisensi OJK","Platform P2P tidak berlisensi","Keduanya sama amannya","Tidak dapat ditentukan"],"question":"Mana yang umumnya lebih aman: menyimpan Rp 50 juta di deposito bank berlisensi OJK atau berinvestasi di platform P2P tidak berlisensi yang menjanjikan pengembalian 15%?","difficulty":"intermediate","parameters":{},"explanation":"Deposito berlisensi diatur dan diasuransikan. Platform tidak berlisensi memiliki risiko penipuan dan tidak ada perlindungan investor."}$json$::jsonb where id = 'f8167651-7bca-4d55-80d8-a6d9ddeb991b';
update public.content_variants set body = $json${"type":"word_bank","answer":["buying","missing out"],"options":["buying","missing out"],"question":"Complete: \"FOMO makes us _____ assets because we fear _____.\"","difficulty":"intermediate","parameters":{},"explanation":"FOMO is the fear of missing out that can drive purchases without proper research."}$json$::jsonb where id = 'e9182774-5f10-4cc4-ae60-868f151211a9';
update public.content_variants set body = $json${"text":"Recognising bias helps us make calmer decisions. Return to the original goal, do research, and avoid major decisions while emotional.","source_ids":["ec6ef517-82a4-4a35-826f-9b2cc0486896"]}$json$::jsonb where id = 'ee457d87-7f28-45ae-a77f-a6feb12bb534';
update public.content_variants set body = $json${"text":"When Bank Indonesia raises the BI Rate, banking shares such as BBCA and BBRI often move more actively. For an informed investor, this is volatility linked to monetary policy, not a sign that the company is failing.","source_ids":["097b62c4-9aae-4933-a870-ac74a526b8f1","c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'ec780bc8-bf48-4a33-8669-91ac88c3bf34';
update public.content_variants set body = $json${"text":"Dimas sets a rule: check his portfolio only once a week and sell only if the reason for buying changes. This simple rule helps him avoid overreacting when a share falls 5%.","source_ids":["5fa2799e-2b92-46e8-b68a-c9d64847410c"]}$json$::jsonb where id = 'ee7a5725-c524-4f03-a619-a8dd3a1ad4cf';
update public.content_variants set body = $json${"text":"Bank Indonesia often announces an interest rate (BI Rate) that can affect banking shares such as BBCA and BBRI. This change adds market volatility, especially in the financial sector.","source_ids":["097b62c4-9aae-4933-a870-ac74a526b8f1","c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'eecc47e1-f6fd-4c13-a6f4-f48f1450dd07';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Volatility is always the same as a realised loss.","difficulty":"intermediate","parameters":{},"explanation":"Volatility is price fluctuation. A realised loss occurs when you sell below your purchase price."}$json$::jsonb where id = 'eed421e3-dcfa-445f-bb2a-1bf2ef99bfcc';
update public.content_variants set body = $json${"text":"Andi has been investing for only three months but already thinks he can beat the market. He day-trades IDR 10,000,000 and loses 15% in one month because of overconfidence and transaction costs.","source_ids":["47189cc8-8e51-4890-ace4-3f30b913f5ee"]}$json$::jsonb where id = 'f4e3039b-130f-445b-9809-9a6bca1fbe89';
