-- KO-225 group 1 continuation batch 22

update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"The principle of paying yourself used to mean saving after all your desires were fulfilled.","difficulty":"beginner","explanation":"Pay yourself first instead of saving at the start, before you run out of money for what you want."}$json$::jsonb where id = 'fafffa70-d17f-41b8-ad3a-8d5753a6d26d';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"All online loan applications on the internet are definitely licensed by the OJK.","difficulty":"beginner","explanation":"Many lending applications are illegal. Always check the OJK list before using financial services."}$json$::jsonb where id = 'fb081e0e-c665-48b5-ac02-9826b4423ee6';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"High stock volume means the stock is definitely profitable.","difficulty":"intermediate","explanation":"High volume only indicates high trading activity, not a guarantee of profits."}$json$::jsonb where id = 'fb676a8c-34ec-4d02-ad5a-8f155b5af3fc';
update public.content_variants set body = $json${"type":"word_bank","answer":["time","long"],"options":["time","long"],"question":"Complete the following sentence with words from the word bank: \"Young investors have a _____ advantage because they can allow investments to grow more _____.\"","difficulty":"intermediate","parameters":{},"explanation":"Time is a young investor's partner because compound interest works better in the long run."}$json$::jsonb where id = 'fb78ce7d-4e8f-4a7c-8fe3-35502950b4f9';
update public.content_variants set body = $json${"type":"ordering","answer":["Deflation","Light inflation","High inflation","Hyperinflation"],"options":["Hyperinflation","Deflation","Light inflation","High inflation"],"question":"In order from mildest to most extreme:","difficulty":"advanced","parameters":{},"explanation":"Deflation (falling prices), mild inflation, high inflation, hyperinflation (very extreme)."}$json$::jsonb where id = 'fd7cb77c-dd6f-42a3-bb74-9731d788765a';
update public.content_variants set body = $json${"type":"case_study","answer":"Diversification protects Andi from single stock risks.","caseText":"Andi has IDR 5,000,000 and wants to start investing. His friend suggested buying shares in a technology company because it was going viral. Andi wants to be safe but still have the potential to grow.","followUp":{"answer":"Choose a mutual fund that has many stocks to be diversified","options":["Choose a mutual fund that has many stocks to be diversified","Buy all the shares of the viral company","Wait until you have IDR 50 million","Borrow money to buy more viral shares"],"question":"What is the best advice for Andi?","explanation":"Mutual funds spread the risk over many shares, so that a loss on one share is not too big."},"question":"Read the following cases and choose the best response.","difficulty":"intermediate","explanation":"Diversification reduces risk without having to pick one winner. Mutual funds are a simple way to diversify."}$json$::jsonb where id = 'fda2044a-e6ac-423d-a03f-dcb703d5d8f8';
update public.content_variants set body = $json${"type":"fill_blank","answer":"asset type","question":"Diversification means spreading investments across different _____ and instruments.","difficulty":"intermediate","parameters":{},"explanation":"Diversification spreads funds across different types of assets or sectors to reduce risk."}$json$::jsonb where id = 'ff45cb29-ccca-46ae-808e-a687ec75acdc';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Diversification means putting all your money in one of the most promising instruments.","difficulty":"beginner","parameters":{},"explanation":"Diversification is spreading investments across various instruments to reduce risk."}$json$::jsonb where id = 'ff58c4d0-b09f-428d-bd86-d38bcf89c95a';

