-- KO-225 group 1 continuation batch 15

update public.content_variants set body = $json${"type":"fill_blank","answer":"100","question":"If we buy 1 lot of BBCA shares, we have _____ shares.","difficulty":"intermediate","explanation":"On IDX, 1 lot is equal to 100 shares."}$json$::jsonb where id = '9e49b14e-f6ff-47d8-9d81-c546e30d414c';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"If inflation is 5% per year, savings with interest of 3% per year will still increase in purchasing power.","difficulty":"intermediate","parameters":{},"explanation":"Purchasing power decreases because inflation (5%) is higher than savings interest (3%)."}$json$::jsonb where id = '9f5216b3-399b-4411-b11e-d36d7ef9d300';
update public.content_variants set body = $json${"type":"fill_blank","answer":"self","question":"The principle of \"pay ____ first\" means setting aside savings before shopping.","difficulty":"beginner","parameters":{},"explanation":"Paying yourself first means prioritizing savings before other expenses."}$json$::jsonb where id = 'a0584ac5-f28e-4ab6-ad24-6954b586f3fa';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"If the sector goes down, all stocks are affected","options":["Cheaper administration costs","If the sector goes down, all stocks are affected","Taxes are always lower","Guaranteed bigger dividends"],"question":"What are the risks of buying multiple stocks from the same sector?","difficulty":"intermediate","parameters":{},"explanation":"Stocks in the same sector tend to move in the same direction, so sector diversification is important."}$json$::jsonb where id = 'a0bc6f99-aea4-4e50-97b5-283ad3d70bca';
update public.content_variants set body = $json${"type":"fill_blank","answer":"100","question":"On IDX, 1 lot of shares is equal to _____ shares.","difficulty":"intermediate","explanation":"1 lot on the Indonesian Stock Exchange consists of 100 shares."}$json$::jsonb where id = 'a2095697-000e-4d07-9d3c-b2d515cc381a';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because we are used to living with the money we have left","options":["Because we are used to living with the money we have left","Because bank interest is higher at the beginning of the month","Because there is always a lot of money left over","Because desires are less at the beginning of the month"],"question":"Why is saving at the beginning of the month more effective than saving from the rest?","difficulty":"beginner","explanation":"If savings are taken out first, expenses will adjust to the remaining money."}$json$::jsonb where id = 'a24c92f8-c473-406a-b84f-b525e4066968';
update public.content_variants set body = $json${"type":"case_study","answer":"The main risk is not getting the money back. Rina can minimize risk by borrowing a small amount or asking for collateral.","caseText":"Rina was asked to lend Rp. 500,000 to a friend she had only met a few times. The friend promised to pay next week, but Rina heard that he often postponed the debt.","followUp":{"answer":"Friends don't pay back","options":["Friends don't pay back","Rina lost time","Rina lost the opportunity to use the money","Friends borrow again"],"question":"What are the main risks Rina faces?","explanation":"Credit risk is a counterparty not fulfilling a payment promise."},"question":"Read the following cases and choose the best response.","difficulty":"beginner","explanation":"Risk is the possibility of a bad outcome. Lending money to someone who frequently delays means the risk of default is high."}$json$::jsonb where id = 'a346f094-7c26-4d27-bf36-e08311a6a357';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"All types of mutual funds have the same risks.","difficulty":"intermediate","explanation":"Money market, fixed income, and stock mutual funds have different risk profiles."}$json$::jsonb where id = 'a58c565c-08d3-40cd-afde-fd297e6f8623';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Creating a budget means not spending any money on entertainment at all.","difficulty":"beginner","parameters":{},"explanation":"A 50/30/20 budget sets aside 30% for wants, including entertainment, as long as it stays within limits."}$json$::jsonb where id = 'a7d13902-c344-4980-b51e-29c9e1e73d05';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"The higher the potential profit of an investment, the higher the risk.","difficulty":"beginner","parameters":{},"explanation":"Risk and return go hand in hand; High profits usually come with high risks."}$json$::jsonb where id = 'a8cf2f45-a350-4bc0-b12b-f01e7b5d0644';

