-- KO-225 group 5: reviewed translation of Indonesian-shaped duplicate payloads (batch 03).
update public.content_variants set body = $json${"type":"ordering","answer":["Pay tuition fees","Food and transport","Emergency savings","Concert tickets"],"options":["Emergency savings","Food and transport","Concert tickets","Pay tuition fees"],"question":"Order the priority of using pocket money from most important:","difficulty":"beginner","parameters":{},"explanation":"The main priority is educational needs, food/transport, savings, then desires."}$json$::jsonb where id = '9af6e436-69d3-4617-89bd-18d8a614169d';
update public.content_variants set body = $json${"text":"Siti saw an ad on social media offering a 15% monthly return with guaranteed safe capital. Before sending money, Siti checked the organizer's license on the OJK website. It turned out the company was not registered. Siti chose to report to OJK and did not invest her money.","source_ids":["9ddb5412-52b8-4461-b2e5-a5443ac63ca8"]}$json$::jsonb where id = 'a26ab9c1-df86-4203-a72a-553bb17270cb';
update public.content_variants set body = $json${"type":"ordering","answer":["Pay for needs","Set aside savings","Fulfill desires if there's leftover","Check investment license before investing"],"options":["Pay for needs","Set aside savings","Fulfill desires if there's leftover","Check investment license before investing"],"question":"Order the following steps from most important to last.","difficulty":"beginner","parameters":{},"explanation":"Prioritize needs, then savings, then desires. Invest only after verifying the license."}$json$::jsonb where id = 'a35de4b3-882f-449e-80a4-a37df7854815';
update public.content_variants set body = $json${"type":"word_bank","answer":["needs","wants"],"options":["needs","wants"],"question":"Complete the following sentence with words from the word bank: \"Before buying a new item, ask yourself: is this a _____ or a _____?\"","difficulty":"beginner","parameters":{},"explanation":"Distinguishing between needs and wants is the first step in managing money."}$json$::jsonb where id = 'ab75d712-0dbe-47fc-9e36-752ac747a93c';
update public.content_variants set body = $json${"text":"A trader in a traditional market was offered a scheme of \"double your money back in a week\" by an acquaintance. He remembered OJK's message: high returns without risk are not normal. He refused and reminded his neighbors.","source_ids":["9ddb5412-52b8-4461-b2e5-a5443ac63ca8"]}$json$::jsonb where id = 'be2049b6-2415-4392-bd3b-021a893cbe3e';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Promises high returns without risk","options":["Promises high returns without risk","Registered and supervised by OJK","Provides regular financial reports","Product is easy to understand"],"question":"What is a common characteristic of illegal investment offers to be wary of?","difficulty":"beginner","parameters":{},"explanation":"Illegal investment offers often promise high returns and claim no risk. Always check the license on the OJK website."}$json$::jsonb where id = 'c9880606-0acc-45e2-8bd6-b9b18096fc38';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Investments that promise high returns and are \"guaranteed\" safe without risk are usually trustworthy.","difficulty":"beginner","parameters":{},"explanation":"Offers with high returns and guarantees without risk are common traits of illegal investments. Always check the OJK license."}$json$::jsonb where id = 'd4801a9c-2e38-4160-b5cb-dabf5ebafba0';
update public.content_variants set body = $json${"text":"A group of students in Yogyakarta created a joint financial record for a campus event. They separated the budget for food, transport, supplies, and a 10% reserve. The remaining money was transparently returned to each member.","source_ids":["ad0e8258-4e0a-4378-b257-4fd3628c6953"]}$json$::jsonb where id = 'da9dceab-2602-4ce0-b3b0-55d492a92737';
update public.content_variants set body = $json${"text":"Lia compared the price of instant noodles on e-commerce and a nearby shop. Although online was slightly cheaper, the shipping cost made it more expensive. Lia bought from the shop to save money and support local businesses.","source_ids":["53eef1ac-2553-48d9-92a0-af6159d7d369"]}$json$::jsonb where id = 'db641749-3168-48e7-afba-e4494b0bc5fd';
update public.content_variants set body = $json${"type":"ordering","answer":["Record income","Separate needs and wants","Set aside savings","Use the remainder for wants in a measured way"],"options":["Record income","Separate needs and wants","Set aside savings","Use the remainder for wants in a measured way"],"question":"Order the steps to manage pocket money wisely.","difficulty":"beginner","parameters":{},"explanation":"Record income, understand priorities, set aside savings, then use the remainder for wants."}$json$::jsonb where id = 'dbe23cdc-4a80-4950-afd2-34e28d57a603';
