-- KO-225 group 1 continuation batch 17

update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Risk only exists in investments, not in everyday life.","difficulty":"beginner","explanation":"Risks are everywhere: lending money, driving a vehicle, choosing a major, even saving money at home."}$json$::jsonb where id = 'b74b89ec-80be-4d76-8c7b-999ab614c2ad';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Emergency funds should be set aside after all desires are fulfilled.","difficulty":"beginner","parameters":{},"explanation":"Emergency funds should be set aside at the beginning, before desires."}$json$::jsonb where id = 'b9fdd286-3669-4b08-8349-73ae6f21a667';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because it can be used immediately or saved","options":["Because it can be used immediately or saved","Because the nominal value is bigger","Because future money is worthless","Because the price of goods will definitely fall"],"question":"Why is Rp. 500,000 received today better than Rp. 500,000 received in three months?","difficulty":"beginner","explanation":"Money can now be used for needs or to earn interest, so it has more value."}$json$::jsonb where id = 'ba535b49-7d41-4e2e-8e13-ad85d8fe7368';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"09.00–15.00 WIB","options":["08.00–14.00 WIB","09.00–15.00 WIB","10.00–16.00 WIB","24 hours"],"question":"Stock trading hours on IDX are?","difficulty":"beginner","parameters":{},"explanation":"IDX trading hours are 09.00–15.00 WIB."}$json$::jsonb where id = 'bad176ea-3d32-48bf-9512-b18610f65521';
update public.content_variants set body = $json${"type":"ordering","answer":["Visit the OJK website","Search for the company/app name","Make sure it is registered with permission","Transfer funds if verified"],"options":["Visit the OJK website","Search for the company/app name","Make sure it is registered with permission","Transfer funds if verified"],"question":"Sort out safe steps before investing.","difficulty":"beginner","explanation":"Verification of OJK permission must be carried out before spending money."}$json$::jsonb where id = 'bcd11556-0f6a-42ac-9cf1-291282f5821b';
update public.content_variants set body = $json${"type":"matching","pairs":[["Money market mutual funds","Low risk, suitable short term"],["Fixed income mutual funds","Medium risk, contains bonds"],["Stock mutual funds","High risk, high potential return"]],"answer":{"Reksa dana saham":"High risk, high potential return","Reksa dana pasar uang":"Low risk, suitable short term","Reksa dana pendapatan tetap":"Medium risk, contains bonds"},"question":"Match the types of mutual funds with their characteristics.","difficulty":"intermediate","explanation":"Each type of mutual fund has a different risk and return profile."}$json$::jsonb where id = 'bddcc2d8-e274-4031-a285-e4ae85f3cea2';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"10%","options":["8%","10%","12%","15%"],"question":"If the price of a used motorbike rises from IDR 8 million to IDR 8.8 million in a year, what is the inflation rate for the price of the motorbike?","difficulty":"intermediate","parameters":{},"explanation":"The increase of IDR 800,000 from IDR 8 million is 10%."}$json$::jsonb where id = 'bf4b3b83-7685-433c-b574-39d1941cd5c2';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Returns are calculated from capital and previous returns","options":["Returns are calculated only from the initial capital","Returns are calculated from capital and previous returns","The interest received is fixed every year","Has no risk at all"],"question":"Which statement best describes compound interest?","difficulty":"intermediate","parameters":{},"explanation":"Compound interest produces returns from the initial capital and from returns previously obtained."}$json$::jsonb where id = 'c0287659-5b95-4f84-a39d-a1c675bff63a';
update public.content_variants set body = $json${"type":"case_study","answer":"Raka had to stop new purchases and focus on paying off his debt so that it didn't get bigger.","caseText":"Raka bought a hoodie for IDR 1,200,000 using PayLater and was late in paying. The bill ballooned to IDR 1,500,000. The salary is IDR 2,500,000 per month.","followUp":{"answer":"Stop new purchases and pay PayLater bills ASAP","options":["Stop new purchases and pay PayLater bills ASAP","Buy something else to feel better","Pay the minimum and continue the lifestyle","Borrow from a friend to pay the minimum"],"question":"What is the most important first step for Raka?","explanation":"Stopping new borrowing and paying off consumer debt prevents additional interest and penalties."},"question":"Read the following cases and choose the best response.","difficulty":"beginner","explanation":"Consumer debt with high interest can grow quickly. The solution is to stop adding and pay faster."}$json$::jsonb where id = 'c11fe616-3261-4ddb-b05c-000818220a07';
update public.content_variants set body = $json${"type":"ordering","answer":["Determine financial goals and timeframe","Get to know your own risk tolerance","Select the appropriate instrument","Review portfolio regularly"],"options":["Determine financial goals and timeframe","Get to know your own risk tolerance","Select the appropriate instrument","Review portfolio regularly"],"question":"Sort the principles of choosing investments according to the risk profile.","difficulty":"intermediate","parameters":{},"explanation":"Start from your goals, understand your risk, choose an instrument, then review your portfolio regularly."}$json$::jsonb where id = 'c202c54b-3a8d-41fc-a817-9c1291e30b91';

