-- KO-352: Foundation 00 visual learning, applied checks, recall prompts, and mascot moments.
--
-- All numerical examples are illustrative or calculated teaching scenarios.
-- They are not market data, personal financial advice, or return promises.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Reviewed primary sources
-- ---------------------------------------------------------------------------
INSERT INTO public.sources (
  source_code, title, local_title, source_tier, source_type, organization, url,
  language, last_checked_at, status, trust_notes, localization_notes, synopsis,
  synopsis_id, relevance_blurb, relevance_blurb_id
)
VALUES
  (
    'FZ-BI-INFLATION', 'Bank Indonesia inflation explainer', 'Penjelasan inflasi Bank Indonesia',
    1, 'website', 'Bank Indonesia',
    'https://www.bi.go.id/id/fungsi-utama/moneter/inflasi/Default.aspx', 'id', '2026-08-07', 'verified',
    'Primary Bank Indonesia explainer for the meaning, measurement, and economic effects of inflation.',
    'Indonesian primary source; the lesson gives a bilingual educational summary.',
    'Bank Indonesia explains inflation as a sustained rise in the general price level, rather than a one-off change in one item.',
    'Bank Indonesia menjelaskan inflasi sebagai kenaikan harga secara umum dan berkelanjutan, bukan perubahan satu barang saja.',
    'Supports the Foundation lesson on purchasing power and inflation.',
    'Mendukung pelajaran Foundation tentang daya beli dan inflasi.'
  ),
  (
    'FZ-OJK-PLANNING', 'OJK financial planning guide', 'Panduan perencanaan keuangan OJK',
    1, 'report', 'OJK',
    'https://sikapiuangmu.ojk.go.id/FrontEnd/images/FileDownload/208_Buku%209%20PERENCANAAN%20KEUANGAN-ilovepdf-compressed.pdf', 'id', '2026-08-07', 'verified',
    'Official OJK Sikapi Uangmu educational guide covering planning, budgeting, emergency funds, debt, and financial goals.',
    'Indonesian primary guide; examples in this chapter are illustrative and not prescriptions.',
    'OJK presents financial planning as aligning income, spending, protection, savings, debt, and goals with a person’s circumstances.',
    'OJK menyajikan perencanaan keuangan sebagai penyelarasan pendapatan, pengeluaran, perlindungan, tabungan, utang, dan tujuan dengan kondisi seseorang.',
    'Supports Foundation concepts including income, wealth, assets, liabilities, saving, emergency funds, needs, wants, and debt.',
    'Mendukung konsep Foundation seperti pendapatan, kekayaan, aset, liabilitas, menabung, dana darurat, kebutuhan, keinginan, dan utang.'
  ),
  (
    'FZ-OJK-WASPADA', 'OJK Waspada Investasi FAQ', 'FAQ OJK Waspada Investasi',
    1, 'website', 'OJK', 'https://www.ojk.go.id/waspada-investasi/id/FAQ.aspx',
    'id', '2026-08-07', 'verified',
    'Official OJK FAQ for recognising, checking, and reporting suspicious investment offers.',
    'Indonesian primary source; use official OJK channels to check a real offer.',
    'The OJK FAQ describes warning signs and reporting routes for suspicious investment offers.',
    'FAQ OJK menjelaskan tanda peringatan dan jalur pelaporan untuk penawaran investasi mencurigakan.',
    'Supports the Foundation scam-red-flags lesson and its safe next-step guidance.',
    'Mendukung pelajaran tanda bahaya penipuan Foundation serta panduan langkah aman berikutnya.'
  )
ON CONFLICT (source_code) DO UPDATE SET
  title = EXCLUDED.title, local_title = EXCLUDED.local_title, source_tier = EXCLUDED.source_tier,
  source_type = EXCLUDED.source_type, organization = EXCLUDED.organization, url = EXCLUDED.url,
  language = EXCLUDED.language, last_checked_at = EXCLUDED.last_checked_at, status = EXCLUDED.status,
  trust_notes = EXCLUDED.trust_notes, localization_notes = EXCLUDED.localization_notes,
  synopsis = EXCLUDED.synopsis, synopsis_id = EXCLUDED.synopsis_id,
  relevance_blurb = EXCLUDED.relevance_blurb, relevance_blurb_id = EXCLUDED.relevance_blurb_id;

WITH links(slug, source_code, citation_label) AS (
  VALUES
    ('fz-what-is-money', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-inflation', 'FZ-BI-INFLATION', 'Bank Indonesia: inflation explainer'),
    ('fz-interest', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-income-vs-wealth', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-assets-vs-liabilities', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-risk', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-return', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-saving-vs-investing', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-emergency-fund', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-needs-vs-wants', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-debt', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-scam-red-flags', 'FZ-OJK-WASPADA', 'OJK: Waspada Investasi FAQ')
)
INSERT INTO public.lesson_sources (lesson_id, source_id, relevance_type, citation_label, is_primary, display_order)
SELECT lesson.id, source.id, 'primary', links.citation_label, TRUE, 5
FROM links JOIN public.lessons lesson ON lesson.slug = links.slug
JOIN public.sources source ON source.source_code = links.source_code
WHERE lesson.is_published = TRUE
ON CONFLICT (lesson_id, source_id) DO UPDATE SET
  relevance_type = EXCLUDED.relevance_type, citation_label = EXCLUDED.citation_label,
  is_primary = EXCLUDED.is_primary, display_order = EXCLUDED.display_order;

-- ---------------------------------------------------------------------------
-- 2. One bilingual visual block per published Foundation lesson.
-- Mascots appear in six friendly, non-sensitive teaching moments only.
-- ---------------------------------------------------------------------------
WITH blocks(slug, placement, block_type, data_status, content) AS (
  VALUES
    ('fz-what-is-money', 'concept', 'annotated_data', 'illustrative', $json${"en":{"eyebrow":"Money map","title":"Money helps you choose, trade, and plan","disclosure":"Illustrative learning example — the labels describe everyday uses, not financial advice.","altText":"Three labelled cards show money used to buy something now, exchange value with another person, and set aside value for a later goal.","mascot":{"role":"coach","altText":"Koin the bull coach points toward a simple money map."},"payload":{"quoteTitle":"A simple money map","fields":[{"label":"Buy now","value":"🍜 Lunch","note":"Pay for a need or want today."},{"label":"Exchange","value":"🤝 Trade","note":"A shared way to value goods and work."},{"label":"Plan later","value":"🎯 Goal","note":"Set aside money for a future choice."}],"annotations":[{"number":1,"label":"Medium of exchange","detail":"Money makes trading simpler than bartering."},{"number":2,"label":"Unit of account","detail":"Prices give things a common measure."},{"number":3,"label":"Store of value","detail":"Saving supports later choices, though purchasing power can change."}]}},"id":{"eyebrow":"Peta uang","title":"Uang membantu memilih, bertukar, dan merencanakan","disclosure":"Contoh pembelajaran ilustratif — label menggambarkan penggunaan sehari-hari, bukan nasihat keuangan.","altText":"Tiga kartu berlabel menunjukkan uang untuk membeli sekarang, menukar nilai dengan orang lain, dan menyimpan nilai untuk tujuan nanti.","mascot":{"role":"coach","altText":"Koin si banteng pelatih menunjuk ke peta uang sederhana."},"payload":{"quoteTitle":"Peta uang sederhana","fields":[{"label":"Beli sekarang","value":"🍜 Makan siang","note":"Bayar kebutuhan atau keinginan hari ini."},{"label":"Bertukar","value":"🤝 Tukar nilai","note":"Cara bersama untuk menilai barang dan kerja."},{"label":"Rencanakan nanti","value":"🎯 Tujuan","note":"Sisihkan uang untuk pilihan masa depan."}],"annotations":[{"number":1,"label":"Alat tukar","detail":"Uang membuat pertukaran lebih mudah daripada barter."},{"number":2,"label":"Satuan hitung","detail":"Harga memberi ukuran yang sama untuk berbagai barang."},{"number":3,"label":"Penyimpan nilai","detail":"Menabung membantu pilihan nanti, walau daya beli dapat berubah."}]}}}$json$::jsonb),
    ('fz-inflation', 'concept', 'worked_example', 'calculated', $json${"en":{"eyebrow":"Purchasing power","title":"The same Rp100k can buy less over time","disclosure":"Calculated illustration only — real prices and inflation vary by item, place, and time.","altText":"A before-and-after example compares a Rp100,000 food budget that buys five items before a general price increase and four items after.","mascot":{"role":"explore","altText":"Koin the bull explorer compares two shopping baskets."},"payload":{"inputs":[{"label":"Before","value":"5 items × Rp20k = Rp100k"},{"label":"After","value":"5 items × Rp25k = Rp125k"}],"steps":["The basket costs Rp25k more after a general price rise.","With the same Rp100k, the shopper can now buy four items instead of five."],"outcome":"Inflation can reduce purchasing power: the same money reaches fewer goods or services."}},"id":{"eyebrow":"Daya beli","title":"Rp100 ribu yang sama bisa membeli lebih sedikit","disclosure":"Ilustrasi perhitungan saja — harga dan inflasi nyata berbeda menurut barang, tempat, dan waktu.","altText":"Contoh sebelum dan sesudah membandingkan anggaran makanan Rp100.000 yang membeli lima barang sebelum kenaikan harga umum dan empat barang sesudahnya.","mascot":{"role":"explore","altText":"Koin si banteng penjelajah membandingkan dua keranjang belanja."},"payload":{"inputs":[{"label":"Sebelum","value":"5 barang × Rp20 ribu = Rp100 ribu"},{"label":"Sesudah","value":"5 barang × Rp25 ribu = Rp125 ribu"}],"steps":["Keranjang menjadi Rp25 ribu lebih mahal setelah kenaikan harga umum.","Dengan Rp100 ribu yang sama, pembeli kini hanya dapat membeli empat barang, bukan lima."],"outcome":"Inflasi dapat mengurangi daya beli: uang yang sama menjangkau lebih sedikit barang atau jasa."}}}$json$::jsonb),
    ('fz-interest', 'concept', 'process', 'calculated', $json${"en":{"eyebrow":"Interest in motion","title":"Principal × rate × time","disclosure":"Calculated illustration only; real products have terms, fees, taxes, and compounding rules.","altText":"A three-step process shows Rp1,000,000 principal, a 6 percent annual rate, and one year resulting in Rp60,000 simple interest.","mascot":{"role":"coach","altText":"Koin the bull coach explains a three-step interest calculation."},"payload":{"steps":[{"title":"1. Start with principal","description":"Rp1,000,000 is the starting amount."},{"title":"2. Apply the annual rate","description":"6% of Rp1,000,000 is Rp60,000."},{"title":"3. Match the time","description":"For one year of simple interest, the illustration ends at Rp1,060,000."}]}},"id":{"eyebrow":"Bunga bergerak","title":"Pokok × suku bunga × waktu","disclosure":"Ilustrasi perhitungan saja; produk nyata memiliki syarat, biaya, pajak, dan aturan bunga majemuk.","altText":"Proses tiga langkah menunjukkan pokok Rp1.000.000, suku bunga tahunan 6 persen, dan satu tahun menghasilkan bunga sederhana Rp60.000.","mascot":{"role":"coach","altText":"Koin si banteng pelatih menjelaskan perhitungan bunga tiga langkah."},"payload":{"steps":[{"title":"1. Mulai dari pokok","description":"Rp1.000.000 adalah jumlah awal."},{"title":"2. Terapkan suku bunga tahunan","description":"6% dari Rp1.000.000 adalah Rp60.000."},{"title":"3. Cocokkan waktunya","description":"Untuk satu tahun bunga sederhana, ilustrasinya berakhir di Rp1.060.000."}]}}}$json$::jsonb),
    ('fz-income-vs-wealth', 'concept', 'comparison', 'illustrative', $json${"en":{"eyebrow":"Two different snapshots","title":"Income is a flow; wealth is a position","disclosure":"Illustrative example only — neither number alone tells the full financial picture.","altText":"A comparison table contrasts monthly income received with net wealth calculated from what someone owns minus what they owe.","mascot":{"role":"think","altText":"Koin the bull thinker studies two financial snapshots."},"payload":{"leftTitle":"Income 💼","rightTitle":"Wealth 🧰","rows":[{"left":"Money received over a period","right":"What you own minus what you owe at a point in time"},{"left":"Rp6m this month","right":"Assets Rp20m − debt Rp8m = Rp12m net wealth"},{"left":"Can change next month","right":"Can grow, shrink, or be negative"}]}},"id":{"eyebrow":"Dua potret berbeda","title":"Pendapatan adalah arus; kekayaan adalah posisi","disclosure":"Contoh ilustratif saja — satu angka tidak menggambarkan kondisi keuangan secara lengkap.","altText":"Tabel perbandingan membedakan pendapatan bulanan yang diterima dengan kekayaan bersih dari harta dikurangi utang.","mascot":{"role":"think","altText":"Koin si banteng pemikir mempelajari dua potret keuangan."},"payload":{"leftTitle":"Pendapatan 💼","rightTitle":"Kekayaan 🧰","rows":[{"left":"Uang yang diterima dalam suatu periode","right":"Yang dimiliki dikurangi yang terutang pada satu waktu"},{"left":"Rp6 juta bulan ini","right":"Aset Rp20 juta − utang Rp8 juta = kekayaan bersih Rp12 juta"},{"left":"Dapat berubah bulan depan","right":"Dapat bertambah, menyusut, atau negatif"}]}}}$json$::jsonb),
    ('fz-assets-vs-liabilities', 'concept', 'comparison', 'illustrative', $json${"en":{"eyebrow":"Balance-sheet basics","title":"What you own and what you owe","disclosure":"Illustrative classification only; an item’s value and usefulness depend on context.","altText":"A comparison table lists cash and a laptop as assets, and a bill and loan balance as liabilities.","mascot":{"role":"think","altText":"Koin the bull thinker sorts items into owned and owed columns."},"payload":{"leftTitle":"Assets ✅","rightTitle":"Liabilities 📌","rows":[{"left":"Cash: something you own","right":"Unpaid bill: something you owe"},{"left":"Laptop: an owned item with value or use","right":"Loan balance: a repayment obligation"},{"left":"Add assets, then subtract liabilities","right":"The difference is a simple net-worth snapshot"}]}},"id":{"eyebrow":"Dasar neraca","title":"Apa yang dimiliki dan apa yang terutang","disclosure":"Klasifikasi ilustratif saja; nilai dan kegunaan suatu barang bergantung pada konteks.","altText":"Tabel perbandingan mencantumkan kas dan laptop sebagai aset, serta tagihan dan saldo pinjaman sebagai liabilitas.","mascot":{"role":"think","altText":"Koin si banteng pemikir menyortir barang ke kolom dimiliki dan terutang."},"payload":{"leftTitle":"Aset ✅","rightTitle":"Liabilitas 📌","rows":[{"left":"Kas: sesuatu yang dimiliki","right":"Tagihan belum dibayar: sesuatu yang terutang"},{"left":"Laptop: barang yang dimiliki dan bernilai atau berguna","right":"Saldo pinjaman: kewajiban pelunasan"},{"left":"Jumlahkan aset, lalu kurangi liabilitas","right":"Selisihnya adalah potret sederhana kekayaan bersih"}]}}}$json$::jsonb),
    ('fz-risk', 'concept', 'comparison', 'illustrative', $json${"en":{"eyebrow":"Trade-offs","title":"More uncertainty needs more thought","disclosure":"Illustrative comparison only — no outcome is guaranteed and suitability is personal.","altText":"A comparison table contrasts a predictable near-term cash need with an uncertain investment outcome and highlights time horizon and ability to absorb loss.","payload":{"leftTitle":"Near-term need","rightTitle":"Uncertain outcome","rows":[{"left":"Money needed next month","right":"Value may rise or fall"},{"left":"Prioritise access and stability","right":"Consider time horizon and loss capacity"},{"left":"Ask: can I still pay essentials?","right":"Ask: what could go wrong, and can I handle it?"}]}},"id":{"eyebrow":"Pertukaran","title":"Lebih banyak ketidakpastian perlu lebih banyak pertimbangan","disclosure":"Perbandingan ilustratif saja — tidak ada hasil yang dijamin dan kecocokan bersifat pribadi.","altText":"Tabel perbandingan membedakan kebutuhan kas jangka dekat yang dapat diprediksi dengan hasil investasi tidak pasti serta menyoroti jangka waktu dan kemampuan menanggung rugi.","payload":{"leftTitle":"Kebutuhan dekat","rightTitle":"Hasil tidak pasti","rows":[{"left":"Uang dibutuhkan bulan depan","right":"Nilai dapat naik atau turun"},{"left":"Utamakan akses dan stabilitas","right":"Pertimbangkan jangka waktu dan kemampuan menanggung rugi"},{"left":"Tanya: apakah kebutuhan pokok tetap terbayar?","right":"Tanya: apa yang bisa salah dan sanggupkah saya menghadapinya?"}]}}}$json$::jsonb),
    ('fz-return', 'concept', 'worked_example', 'calculated', $json${"en":{"eyebrow":"Return is a result","title":"Calculate the change, then remember uncertainty","disclosure":"Calculated illustration only — a past change does not promise a future return.","altText":"A worked example shows an amount moving from Rp1,000,000 to Rp1,080,000, a gain of Rp80,000 or 8 percent.","mascot":{"role":"celebrate","altText":"Koin the bull celebrates a completed practice calculation, not an investment promise."},"payload":{"inputs":[{"label":"Starting amount","value":"Rp1,000,000"},{"label":"Ending amount","value":"Rp1,080,000"}],"steps":["Subtract: Rp1,080,000 − Rp1,000,000 = Rp80,000 gain.","Divide the gain by the starting amount: Rp80,000 ÷ Rp1,000,000 = 8%."],"outcome":"Return describes a change in value. It can be positive, zero, or negative."}},"id":{"eyebrow":"Imbal hasil adalah hasil","title":"Hitung perubahan, lalu ingat ketidakpastian","disclosure":"Ilustrasi perhitungan saja — perubahan masa lalu tidak menjanjikan imbal hasil masa depan.","altText":"Contoh perhitungan menunjukkan jumlah berubah dari Rp1.000.000 menjadi Rp1.080.000, keuntungan Rp80.000 atau 8 persen.","mascot":{"role":"celebrate","altText":"Koin si banteng merayakan perhitungan latihan yang selesai, bukan janji investasi."},"payload":{"inputs":[{"label":"Jumlah awal","value":"Rp1.000.000"},{"label":"Jumlah akhir","value":"Rp1.080.000"}],"steps":["Kurangi: Rp1.080.000 − Rp1.000.000 = keuntungan Rp80.000.","Bagi keuntungan dengan jumlah awal: Rp80.000 ÷ Rp1.000.000 = 8%."],"outcome":"Imbal hasil menggambarkan perubahan nilai. Hasilnya dapat positif, nol, atau negatif."}}}$json$::jsonb),
    ('fz-saving-vs-investing', 'concept', 'comparison', 'illustrative', $json${"en":{"eyebrow":"Different jobs","title":"Saving and investing can serve different goals","disclosure":"Illustrative comparison only — choose based on your goal, timing, safety needs, and understanding.","altText":"A comparison table contrasts saving for an emergency with investing for a longer-term goal where value can fluctuate.","mascot":{"role":"coach","altText":"Koin the bull coach points to two goal paths: near-term saving and longer-term investing."},"payload":{"leftTitle":"Saving 🏦","rightTitle":"Investing 🌱","rows":[{"left":"Often for access and a near-term goal","right":"Often for a longer-term goal"},{"left":"Example: emergency buffer","right":"Example: a goal with time to absorb changes"},{"left":"Focus: availability and stability","right":"Focus: risk, potential return, and time horizon"}]}},"id":{"eyebrow":"Tugas berbeda","title":"Menabung dan berinvestasi dapat melayani tujuan berbeda","disclosure":"Perbandingan ilustratif saja — pilih berdasarkan tujuan, waktu, kebutuhan keamanan, dan pemahaman Anda.","altText":"Tabel perbandingan membedakan tabungan untuk keadaan darurat dengan investasi untuk tujuan jangka lebih panjang yang nilainya dapat berfluktuasi.","mascot":{"role":"coach","altText":"Koin si banteng pelatih menunjuk dua jalur tujuan: menabung dekat dan investasi lebih panjang."},"payload":{"leftTitle":"Menabung 🏦","rightTitle":"Berinvestasi 🌱","rows":[{"left":"Sering untuk akses dan tujuan dekat","right":"Sering untuk tujuan jangka lebih panjang"},{"left":"Contoh: dana darurat","right":"Contoh: tujuan dengan waktu menghadapi perubahan"},{"left":"Fokus: ketersediaan dan stabilitas","right":"Fokus: risiko, potensi imbal hasil, dan jangka waktu"}]}}}$json$::jsonb),
    ('fz-emergency-fund', 'concept', 'process', 'calculated', $json${"en":{"eyebrow":"Build a buffer","title":"Start small, make it repeatable","disclosure":"Illustrative planning example only — your appropriate buffer depends on your circumstances.","altText":"A three-step process shows listing Rp3,000,000 essential monthly costs, choosing a first Rp300,000 goal, and setting aside Rp75,000 each week.","mascot":{"role":"coach","altText":"Koin the bull coach holds a small emergency-fund jar."},"payload":{"steps":[{"title":"1. Name essentials","description":"Example: housing, food, transport, and bills total Rp3,000,000 a month."},{"title":"2. Pick a reachable first target","description":"A Rp300,000 starter buffer is more concrete than an undefined goal."},{"title":"3. Repeat a contribution","description":"Rp75,000 each week reaches Rp300,000 in four weeks, before any changes in expenses."}]}},"id":{"eyebrow":"Bangun penyangga","title":"Mulai kecil, buat berulang","disclosure":"Contoh perencanaan ilustratif saja — penyangga yang sesuai bergantung pada keadaan Anda.","altText":"Proses tiga langkah menunjukkan mencatat biaya pokok Rp3.000.000 per bulan, memilih tujuan awal Rp300.000, dan menyisihkan Rp75.000 setiap minggu.","mascot":{"role":"coach","altText":"Koin si banteng pelatih memegang toples dana darurat kecil."},"payload":{"steps":[{"title":"1. Sebutkan kebutuhan pokok","description":"Contoh: tempat tinggal, makanan, transportasi, dan tagihan berjumlah Rp3.000.000 per bulan."},{"title":"2. Pilih target awal yang terjangkau","description":"Penyangga awal Rp300.000 lebih konkret daripada tujuan yang tidak jelas."},{"title":"3. Ulangi setoran","description":"Rp75.000 tiap minggu mencapai Rp300.000 dalam empat minggu, sebelum perubahan pengeluaran."}]}}}$json$::jsonb),
    ('fz-needs-vs-wants', 'concept', 'comparison', 'illustrative', $json${"en":{"eyebrow":"Pause before paying","title":"A need supports essentials; a want adds choice","disclosure":"Illustrative reflection tool only — context can make the same item a need or a want.","altText":"A comparison table asks whether an expense supports essential living or is optional for the moment, and suggests pausing before deciding.","mascot":{"role":"think","altText":"Koin the bull thinker pauses before choosing an item."},"payload":{"leftTitle":"Need 🧭","rightTitle":"Want ✨","rows":[{"left":"Supports essential living, health, work, or safety","right":"Adds enjoyment, convenience, or preference"},{"left":"Ask: what happens if I delay it?","right":"Ask: can I enjoy it within my plan?"},{"left":"Context matters","right":"Context matters — no shame, just a clear choice"}]}},"id":{"eyebrow":"Berhenti sebelum membayar","title":"Kebutuhan mendukung yang pokok; keinginan menambah pilihan","disclosure":"Alat refleksi ilustratif saja — konteks dapat membuat barang yang sama menjadi kebutuhan atau keinginan.","altText":"Tabel perbandingan menanyakan apakah pengeluaran mendukung hidup pokok atau bersifat opsional saat ini, serta menyarankan berhenti sejenak sebelum memutuskan.","mascot":{"role":"think","altText":"Koin si banteng pemikir berhenti sejenak sebelum memilih barang."},"payload":{"leftTitle":"Kebutuhan 🧭","rightTitle":"Keinginan ✨","rows":[{"left":"Mendukung hidup pokok, kesehatan, kerja, atau keselamatan","right":"Menambah kesenangan, kenyamanan, atau preferensi"},{"left":"Tanya: apa akibatnya jika ditunda?","right":"Tanya: apakah saya dapat menikmatinya dalam rencana?"},{"left":"Konteks penting","right":"Konteks penting — tanpa rasa bersalah, hanya pilihan yang jelas"}]}}}$json$::jsonb),
    ('fz-debt', 'concept', 'annotated_data', 'illustrative', $json${"en":{"eyebrow":"Read the whole obligation","title":"Debt is more than the monthly payment","disclosure":"Illustrative checklist only — read the actual agreement and seek qualified help for personal decisions.","altText":"A four-field debt checklist shows principal, interest or fees, due date, and total repayment question.","payload":{"quoteTitle":"Before you borrow, inspect","fields":[{"label":"Amount borrowed","value":"Principal","note":"How much is received now?"},{"label":"Cost","value":"Interest + fees","note":"What is added to repayment?"},{"label":"Timing","value":"Due dates","note":"When must payments be made?"},{"label":"Total","value":"Repayment","note":"How much will leave your budget overall?"}],"annotations":[{"number":1,"label":"Do not stop at the instalment","detail":"A small monthly number can hide a larger total cost."},{"number":2,"label":"Check affordability","detail":"Keep essential costs and a buffer in view."}]}},"id":{"eyebrow":"Baca seluruh kewajiban","title":"Utang lebih dari cicilan bulanan","disclosure":"Daftar periksa ilustratif saja — baca perjanjian sebenarnya dan cari bantuan yang berkualifikasi untuk keputusan pribadi.","altText":"Daftar periksa utang empat bidang menunjukkan pokok, bunga atau biaya, tanggal jatuh tempo, dan pertanyaan total pembayaran.","payload":{"quoteTitle":"Sebelum berutang, periksa","fields":[{"label":"Jumlah dipinjam","value":"Pokok","note":"Berapa yang diterima sekarang?"},{"label":"Biaya","value":"Bunga + biaya","note":"Apa yang ditambahkan ke pembayaran?"},{"label":"Waktu","value":"Jatuh tempo","note":"Kapan pembayaran harus dilakukan?"},{"label":"Total","value":"Pelunasan","note":"Berapa total yang keluar dari anggaran?"}],"annotations":[{"number":1,"label":"Jangan berhenti pada cicilan","detail":"Angka bulanan kecil dapat menyembunyikan biaya total lebih besar."},{"number":2,"label":"Periksa kemampuan bayar","detail":"Tetap lihat biaya pokok dan penyangga."}]}}}$json$::jsonb),
    ('fz-scam-red-flags', 'concept', 'process', 'illustrative', $json${"en":{"eyebrow":"Pause, check, report","title":"A big promise deserves a careful check","disclosure":"Safety checklist only — use official OJK channels to check or report a real offer.","altText":"A three-step process shows pausing on a guaranteed-return claim, checking the offer through official channels, and not sending money or personal data under pressure.","payload":{"steps":[{"title":"1. Pause on pressure","description":"“Guaranteed profit”, urgency, and secrecy are reasons to slow down."},{"title":"2. Check independently","description":"Use official OJK information, not a link supplied by the promoter."},{"title":"3. Protect your details","description":"Do not send money, passwords, OTPs, or identity data because of a rushed message."}]}},"id":{"eyebrow":"Berhenti, cek, laporkan","title":"Janji besar pantas diperiksa dengan cermat","disclosure":"Daftar periksa keamanan saja — gunakan kanal resmi OJK untuk memeriksa atau melaporkan penawaran nyata.","altText":"Proses tiga langkah menunjukkan berhenti pada klaim keuntungan terjamin, memeriksa penawaran lewat kanal resmi, dan tidak mengirim uang atau data pribadi karena tekanan.","payload":{"steps":[{"title":"1. Berhenti saat ditekan","description":"“Untung pasti”, urgensi, dan kerahasiaan adalah alasan untuk memperlambat."},{"title":"2. Periksa secara mandiri","description":"Gunakan informasi resmi OJK, bukan tautan dari promotor."},{"title":"3. Lindungi data","description":"Jangan kirim uang, kata sandi, OTP, atau data identitas karena pesan yang mendesak."}]}}}$json$::jsonb)
)
INSERT INTO public.lesson_visual_blocks (lesson_id, placement, block_type, display_order, data_status, content, is_published)
SELECT lesson.id, blocks.placement, blocks.block_type, 10, blocks.data_status, blocks.content, TRUE
FROM blocks JOIN public.lessons lesson ON lesson.slug = blocks.slug
WHERE lesson.is_published = TRUE
ON CONFLICT (lesson_id, placement, display_order) DO UPDATE SET
  block_type = EXCLUDED.block_type, data_status = EXCLUDED.data_status, content = EXCLUDED.content,
  is_published = TRUE, updated_at = NOW();

WITH block_sources(slug, source_code, citation_label) AS (
  VALUES
    ('fz-inflation', 'FZ-BI-INFLATION', 'Bank Indonesia: inflation explainer'),
    ('fz-scam-red-flags', 'FZ-OJK-WASPADA', 'OJK: Waspada Investasi FAQ'),
    ('fz-what-is-money', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-interest', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-income-vs-wealth', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-assets-vs-liabilities', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-risk', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-return', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-saving-vs-investing', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-emergency-fund', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-needs-vs-wants', 'FZ-OJK-PLANNING', 'OJK: financial planning guide'),
    ('fz-debt', 'FZ-OJK-PLANNING', 'OJK: financial planning guide')
)
INSERT INTO public.lesson_visual_block_sources (visual_block_id, source_id, citation_label)
SELECT block.id, source.id, block_sources.citation_label
FROM block_sources JOIN public.lessons lesson ON lesson.slug = block_sources.slug
JOIN public.lesson_visual_blocks block ON block.lesson_id = lesson.id AND block.placement = 'concept' AND block.display_order = 10
JOIN public.sources source ON source.source_code = block_sources.source_code
ON CONFLICT (visual_block_id, source_id) DO UPDATE SET citation_label = EXCLUDED.citation_label;

-- ---------------------------------------------------------------------------
-- 3. Three bilingual visual-applied checks per lesson (36 total).
-- ---------------------------------------------------------------------------
WITH q(slug, question, options, answer, explanation, question_id, options_id, answer_id, explanation_id) AS (
  VALUES
    ('fz-what-is-money','🍜 Paying for lunch is which money job?','["Buy now","Store a password","Predict prices","Guarantee wealth"]'::jsonb,'Buy now','It uses money to exchange for something today.','🍜 Membayar makan siang adalah fungsi uang yang mana?','["Beli sekarang","Menyimpan kata sandi","Memprediksi harga","Menjamin kaya"]'::jsonb,'Beli sekarang','Uang dipakai untuk menukar sesuatu hari ini.'),
    ('fz-what-is-money','Which card best shows planning for later?','["Set aside for a goal","Swap a shirt","Pay today’s lunch","Borrow without checking"]'::jsonb,'Set aside for a goal','Saving for a future choice is the planning-for-later use.','Kartu mana paling menunjukkan rencana untuk nanti?','["Sisihkan untuk tujuan","Menukar baju","Membayar makan siang hari ini","Berutang tanpa mengecek"]'::jsonb,'Sisihkan untuk tujuan','Menyisihkan untuk pilihan masa depan adalah penggunaan untuk nanti.'),
    ('fz-what-is-money','Why do price labels help in the money map?','["They give a common measure","They guarantee a bargain","They remove every choice","They stop inflation"]'::jsonb,'They give a common measure','Prices help compare the value of different goods and work.','Mengapa label harga membantu di peta uang?','["Memberi ukuran yang sama","Menjamin murah","Menghapus semua pilihan","Menghentikan inflasi"]'::jsonb,'Memberi ukuran yang sama','Harga membantu membandingkan nilai berbagai barang dan kerja.'),
    ('fz-inflation','The basket rises from 5 × Rp20k to 5 × Rp25k. What is the new basket cost?','["Rp125k","Rp100k","Rp105k","Rp20k"]'::jsonb,'Rp125k','Five items at Rp25k each cost Rp125k.','Keranjang naik dari 5 × Rp20 ribu menjadi 5 × Rp25 ribu. Berapa biaya keranjang baru?','["Rp125 ribu","Rp100 ribu","Rp105 ribu","Rp20 ribu"]'::jsonb,'Rp125 ribu','Lima barang seharga Rp25 ribu masing-masing berjumlah Rp125 ribu.'),
    ('fz-inflation','With Rp100k after the illustrated price rise, how many Rp25k items fit?','["4","5","3","25"]'::jsonb,'4','Rp100k ÷ Rp25k equals four items.','Dengan Rp100 ribu setelah kenaikan harga ilustratif, berapa barang Rp25 ribu yang dapat dibeli?','["4","5","3","25"]'::jsonb,'4','Rp100 ribu ÷ Rp25 ribu sama dengan empat barang.'),
    ('fz-inflation','What does this example teach about inflation?','["Purchasing power can fall","Every price always doubles","Money disappears","Inflation guarantees a loss"]'::jsonb,'Purchasing power can fall','The same Rp100k reached fewer items in the illustration.','Apa yang diajarkan contoh ini tentang inflasi?','["Daya beli dapat turun","Semua harga selalu dua kali lipat","Uang menghilang","Inflasi menjamin rugi"]'::jsonb,'Daya beli dapat turun','Rp100 ribu yang sama menjangkau lebih sedikit barang dalam ilustrasi.'),
    ('fz-interest','What is 6% of Rp1,000,000 in the practice calculation?','["Rp60,000","Rp6,000","Rp600,000","Rp1,060,000"]'::jsonb,'Rp60,000','0.06 × Rp1,000,000 is Rp60,000.','Berapa 6% dari Rp1.000.000 dalam perhitungan latihan?','["Rp60.000","Rp6.000","Rp600.000","Rp1.060.000"]'::jsonb,'Rp60.000','0,06 × Rp1.000.000 adalah Rp60.000.'),
    ('fz-interest','In the visual, what is the principal?','["The starting amount","The fee only","The final total only","The time period"]'::jsonb,'The starting amount','Principal means the original amount before the illustrated interest.','Dalam visual, apa itu pokok?','["Jumlah awal","Hanya biaya","Hanya total akhir","Periode waktu"]'::jsonb,'Jumlah awal','Pokok adalah jumlah asli sebelum bunga ilustratif.'),
    ('fz-interest','Why should you check terms beyond the simple example?','["Real products can include fees and compounding","Interest is always identical","Time never matters","Rates guarantee outcomes"]'::jsonb,'Real products can include fees and compounding','The disclosure explains real terms can change the total.','Mengapa perlu memeriksa syarat di luar contoh sederhana?','["Produk nyata dapat memiliki biaya dan bunga majemuk","Bunga selalu sama","Waktu tidak pernah penting","Suku bunga menjamin hasil"]'::jsonb,'Produk nyata dapat memiliki biaya dan bunga majemuk','Pernyataan batas menjelaskan syarat nyata dapat mengubah total.'),
    ('fz-income-vs-wealth','Rp6m received this month is an example of what?','["Income","Wealth","A liability","A due date"]'::jsonb,'Income','Income is money received during a period.','Rp6 juta yang diterima bulan ini adalah contoh apa?','["Pendapatan","Kekayaan","Liabilitas","Tanggal jatuh tempo"]'::jsonb,'Pendapatan','Pendapatan adalah uang yang diterima dalam suatu periode.'),
    ('fz-income-vs-wealth','Assets Rp20m minus debt Rp8m equals what net wealth?','["Rp12m","Rp28m","Rp8m","Rp6m"]'::jsonb,'Rp12m','Rp20m − Rp8m = Rp12m.','Aset Rp20 juta dikurangi utang Rp8 juta menghasilkan kekayaan bersih berapa?','["Rp12 juta","Rp28 juta","Rp8 juta","Rp6 juta"]'::jsonb,'Rp12 juta','Rp20 juta − Rp8 juta = Rp12 juta.'),
    ('fz-income-vs-wealth','Which statement matches the comparison?','["Income can change next month","Wealth is always cash","Income is what you owe","Wealth guarantees security"]'::jsonb,'Income can change next month','Income is a flow over time, so it can vary.','Pernyataan mana yang cocok dengan perbandingan?','["Pendapatan dapat berubah bulan depan","Kekayaan selalu kas","Pendapatan adalah yang terutang","Kekayaan menjamin aman"]'::jsonb,'Pendapatan dapat berubah bulan depan','Pendapatan adalah arus seiring waktu sehingga dapat berbeda.'),
    ('fz-assets-vs-liabilities','Which item belongs in the asset column?','["Cash you own","An unpaid bill","A loan balance","A late fee"]'::jsonb,'Cash you own','Cash is something you own.','Barang mana masuk kolom aset?','["Kas yang dimiliki","Tagihan belum dibayar","Saldo pinjaman","Denda terlambat"]'::jsonb,'Kas yang dimiliki','Kas adalah sesuatu yang dimiliki.'),
    ('fz-assets-vs-liabilities','A loan balance is best described as what?','["A liability","An asset","Income","A return"]'::jsonb,'A liability','It is an obligation to repay.','Saldo pinjaman paling tepat disebut apa?','["Liabilitas","Aset","Pendapatan","Imbal hasil"]'::jsonb,'Liabilitas','Itu adalah kewajiban untuk membayar kembali.'),
    ('fz-assets-vs-liabilities','What is the simple net-worth step?','["Assets minus liabilities","Income plus fees","Debt minus cash","Price times time"]'::jsonb,'Assets minus liabilities','The visual’s snapshot subtracts what is owed from what is owned.','Apa langkah sederhana untuk kekayaan bersih?','["Aset dikurangi liabilitas","Pendapatan ditambah biaya","Utang dikurangi kas","Harga kali waktu"]'::jsonb,'Aset dikurangi liabilitas','Potret visual mengurangi yang terutang dari yang dimiliki.'),
    ('fz-risk','Money needed next month should make you think first about what?','["Access and stability","Guaranteed high return","A secret tip","Ignoring essentials"]'::jsonb,'Access and stability','Near-term needs leave less room for swings.','Uang yang dibutuhkan bulan depan sebaiknya membuat Anda memikirkan apa terlebih dahulu?','["Akses dan stabilitas","Imbal hasil tinggi terjamin","Tips rahasia","Mengabaikan kebutuhan pokok"]'::jsonb,'Akses dan stabilitas','Kebutuhan dekat memberi ruang lebih kecil untuk perubahan nilai.'),
    ('fz-risk','Which is the visual’s better risk question?','["Can I handle what could go wrong?","Can I guarantee profit?","Can I skip checking?","Can I borrow more? "]'::jsonb,'Can I handle what could go wrong?','Risk involves uncertainty and ability to absorb loss.','Mana pertanyaan risiko yang lebih baik dari visual?','["Sanggupkah saya menghadapi apa yang bisa salah?","Bisakah saya menjamin untung?","Bisakah saya tidak perlu cek?","Bisakah saya lebih banyak berutang?"]'::jsonb,'Sanggupkah saya menghadapi apa yang bisa salah?','Risiko melibatkan ketidakpastian dan kemampuan menanggung rugi.'),
    ('fz-risk','What does the comparison say about outcomes?','["They are not guaranteed","They always rise","They are all the same","They remove trade-offs"]'::jsonb,'They are not guaranteed','The disclosure states no outcome is guaranteed.','Apa yang dikatakan perbandingan tentang hasil?','["Tidak dijamin","Selalu naik","Semuanya sama","Menghapus pertukaran"]'::jsonb,'Tidak dijamin','Pernyataan batas mengatakan tidak ada hasil yang dijamin.'),
    ('fz-return','What is the gain from Rp1,000,000 to Rp1,080,000?','["Rp80,000","Rp8,000","Rp180,000","8 rupiah"]'::jsonb,'Rp80,000','Subtract the starting amount from the ending amount.','Berapa keuntungan dari Rp1.000.000 ke Rp1.080.000?','["Rp80.000","Rp8.000","Rp180.000","8 rupiah"]'::jsonb,'Rp80.000','Kurangi jumlah awal dari jumlah akhir.'),
    ('fz-return','Rp80,000 divided by Rp1,000,000 is what percentage?','["8%","80%","0.8%","108%"]'::jsonb,'8%','The calculated change is 0.08, or 8%.','Rp80.000 dibagi Rp1.000.000 adalah berapa persen?','["8%","80%","0,8%","108%"]'::jsonb,'8%','Perubahan yang dihitung adalah 0,08 atau 8%.'),
    ('fz-return','What should you remember after the practice gain?','["Future return is uncertain","It is a promise","Loss is impossible","The example is live data"]'::jsonb,'Future return is uncertain','A past or illustrative gain is not a future promise.','Apa yang perlu diingat setelah keuntungan latihan?','["Imbal hasil masa depan tidak pasti","Itu janji","Rugi tidak mungkin","Contoh adalah data langsung"]'::jsonb,'Imbal hasil masa depan tidak pasti','Keuntungan masa lalu atau ilustratif bukan janji masa depan.'),
    ('fz-saving-vs-investing','Which visual path fits an emergency buffer?','["Saving","Investing","Guaranteed trading","Borrowing more"]'::jsonb,'Saving','The comparison uses an emergency buffer as a saving example.','Jalur visual mana cocok untuk dana darurat?','["Menabung","Berinvestasi","Trading terjamin","Lebih banyak berutang"]'::jsonb,'Menabung','Perbandingan memakai dana darurat sebagai contoh menabung.'),
    ('fz-saving-vs-investing','Which factor matters for the investing side?','["Time horizon","A guaranteed price","A secret code","Skipping risk"]'::jsonb,'Time horizon','The visual links investing with risk, potential return, and time horizon.','Faktor mana penting untuk sisi investasi?','["Jangka waktu","Harga terjamin","Kode rahasia","Melewati risiko"]'::jsonb,'Jangka waktu','Visual menghubungkan investasi dengan risiko, potensi imbal hasil, dan jangka waktu.'),
    ('fz-saving-vs-investing','What is the key message of the two columns?','["They can serve different goals","One is always best","Both guarantee gains","Goals do not matter"]'::jsonb,'They can serve different goals','The right choice depends on goal, timing, needs, and understanding.','Apa pesan utama dua kolom?','["Keduanya dapat melayani tujuan berbeda","Satu selalu terbaik","Keduanya menjamin untung","Tujuan tidak penting"]'::jsonb,'Keduanya dapat melayani tujuan berbeda','Pilihan yang tepat bergantung pada tujuan, waktu, kebutuhan, dan pemahaman.'),
    ('fz-emergency-fund','The example’s first emergency target is what?','["Rp300,000","Rp3,000,000","Rp75,000","Rp30,000"]'::jsonb,'Rp300,000','The first target is deliberately smaller and reachable.','Target dana darurat pertama dalam contoh adalah apa?','["Rp300.000","Rp3.000.000","Rp75.000","Rp30.000"]'::jsonb,'Rp300.000','Target pertama sengaja lebih kecil dan dapat dijangkau.'),
    ('fz-emergency-fund','Rp75,000 each week reaches Rp300,000 in how many weeks?','["4","3","5","75"]'::jsonb,'4','Four contributions of Rp75,000 equal Rp300,000.','Rp75.000 setiap minggu mencapai Rp300.000 dalam berapa minggu?','["4","3","5","75"]'::jsonb,'4','Empat setoran Rp75.000 sama dengan Rp300.000.'),
    ('fz-emergency-fund','What is step one in the buffer process?','["Name essential costs","Pick a secret investment","Ignore bills","Spend the buffer"]'::jsonb,'Name essential costs','Knowing essentials makes a buffer goal more grounded.','Apa langkah pertama proses penyangga?','["Sebutkan biaya pokok","Pilih investasi rahasia","Abaikan tagihan","Habiskan penyangga"]'::jsonb,'Sebutkan biaya pokok','Mengetahui kebutuhan pokok membuat tujuan penyangga lebih nyata.'),
    ('fz-needs-vs-wants','Which question helps classify an expense?','["What happens if I delay it?","Will it impress people?","Can I hide it?","Will it guarantee wealth?"]'::jsonb,'What happens if I delay it?','The visual suggests pausing and considering the consequence of delay.','Pertanyaan mana membantu mengklasifikasikan pengeluaran?','["Apa akibatnya jika ditunda?","Apakah akan membuat orang terkesan?","Bisakah saya menyembunyikannya?","Apakah menjamin kaya?"]'::jsonb,'Apa akibatnya jika ditunda?','Visual menyarankan berhenti dan mempertimbangkan akibat menunda.'),
    ('fz-needs-vs-wants','What does the visual say about context?','["It matters","It never matters","It makes all items needs","It guarantees the answer"]'::jsonb,'It matters','The same item can be a need or a want depending on circumstances.','Apa yang dikatakan visual tentang konteks?','["Konteks penting","Konteks tidak pernah penting","Semua barang menjadi kebutuhan","Konteks menjamin jawaban"]'::jsonb,'Konteks penting','Barang yang sama dapat menjadi kebutuhan atau keinginan tergantung keadaan.'),
    ('fz-needs-vs-wants','A want in the visual is best described as what?','["An optional preference","A safety essential always","A debt payment","A guaranteed mistake"]'::jsonb,'An optional preference','A want can add enjoyment or convenience without being essential at that moment.','Keinginan dalam visual paling tepat digambarkan sebagai apa?','["Preferensi opsional","Selalu kebutuhan keselamatan","Pembayaran utang","Kesalahan yang dijamin"]'::jsonb,'Preferensi opsional','Keinginan dapat menambah kesenangan atau kenyamanan tanpa selalu penting saat itu.'),
    ('fz-debt','Which field shows how much you receive now?','["Principal","Due date","Total repayment","Fee only"]'::jsonb,'Principal','Principal is the amount borrowed at the start.','Bidang mana menunjukkan berapa yang Anda terima sekarang?','["Pokok","Jatuh tempo","Total pelunasan","Hanya biaya"]'::jsonb,'Pokok','Pokok adalah jumlah yang dipinjam pada awal.'),
    ('fz-debt','Why not judge debt only by the monthly instalment?','["Total cost can be larger","Dates do not matter","Fees disappear","Debt is always free"]'::jsonb,'Total cost can be larger','Interest and fees can make total repayment higher.','Mengapa tidak menilai utang hanya dari cicilan bulanan?','["Biaya total bisa lebih besar","Tanggal tidak penting","Biaya menghilang","Utang selalu gratis"]'::jsonb,'Biaya total bisa lebih besar','Bunga dan biaya dapat membuat total pelunasan lebih tinggi.'),
    ('fz-debt','What should stay in view before borrowing?','["Essential costs and a buffer","Only a promotion","A rushed message","Someone else’s budget"]'::jsonb,'Essential costs and a buffer','The checklist asks you to check affordability alongside essentials.','Apa yang perlu tetap dilihat sebelum berutang?','["Biaya pokok dan penyangga","Hanya promosi","Pesan mendesak","Anggaran orang lain"]'::jsonb,'Biaya pokok dan penyangga','Daftar periksa meminta Anda mengecek kemampuan bayar bersama kebutuhan pokok.'),
    ('fz-scam-red-flags','Which phrase is a reason to pause?','["Guaranteed profit","Read the official FAQ","Take time to check","Use an official channel"]'::jsonb,'Guaranteed profit','A guaranteed-return claim is a warning sign, not proof.','Frasa mana menjadi alasan untuk berhenti sejenak?','["Untung pasti","Baca FAQ resmi","Luangkan waktu mengecek","Gunakan kanal resmi"]'::jsonb,'Untung pasti','Klaim keuntungan terjamin adalah tanda bahaya, bukan bukti.'),
    ('fz-scam-red-flags','Where should you check a real offer?','["An official OJK channel","The promoter’s private link","A rushed group chat","An OTP message"]'::jsonb,'An official OJK channel','Check independently using official information.','Di mana Anda sebaiknya memeriksa penawaran nyata?','["Kanal resmi OJK","Tautan pribadi promotor","Grup chat mendesak","Pesan OTP"]'::jsonb,'Kanal resmi OJK','Periksa secara mandiri menggunakan informasi resmi.'),
    ('fz-scam-red-flags','What should you never send because of pressure?','["OTP or password","A question to OJK","Time to verify","A report through official channels"]'::jsonb,'OTP or password','Do not share credentials or one-time codes in a rushed message.','Apa yang tidak boleh Anda kirim karena tekanan?','["OTP atau kata sandi","Pertanyaan ke OJK","Waktu untuk verifikasi","Laporan lewat kanal resmi"]'::jsonb,'OTP atau kata sandi','Jangan bagikan kredensial atau kode sekali pakai karena pesan mendesak.')
)
INSERT INTO public.content_variants (lesson_id, variant_type, body, body_id, difficulty, topic_tag, is_active)
SELECT lesson.id, 'question',
  jsonb_build_object('type','multiple_choice','difficulty','beginner','question',q.question,'options',q.options,'answer',q.answer,'explanation',q.explanation),
  jsonb_build_object('type','multiple_choice','difficulty','beginner','question',q.question_id,'options',q.options_id,'answer',q.answer_id,'explanation',q.explanation_id),
  'beginner', 'visual_applied', TRUE
FROM q JOIN public.lessons lesson ON lesson.slug = q.slug
WHERE lesson.is_published = TRUE
  AND NOT EXISTS (SELECT 1 FROM public.content_variants cv WHERE cv.lesson_id = lesson.id AND cv.topic_tag = 'visual_applied');

-- One private recall prompt per lesson; the answer key stays server-side.
WITH recalls(slug, question_en, question_id, options_en, options_id, correct_option, explanation_en, explanation_id) AS (
  VALUES
    ('fz-what-is-money','Which money job helps with a future goal?','Fungsi uang mana membantu tujuan masa depan?','["Set aside value","Hide a password","Guarantee wealth"]'::jsonb,'["Menyimpan nilai","Menyembunyikan kata sandi","Menjamin kaya"]'::jsonb,'Set aside value','Saving supports a later choice.','Menabung mendukung pilihan di kemudian hari.'),
    ('fz-inflation','What can inflation reduce?','Apa yang dapat dikurangi inflasi?','["Purchasing power","The number of hours in a day","Every price to zero"]'::jsonb,'["Daya beli","Jumlah jam dalam sehari","Semua harga menjadi nol"]'::jsonb,'Purchasing power','The same money can reach fewer goods.','Uang yang sama dapat menjangkau lebih sedikit barang.'),
    ('fz-interest','What is the starting amount called?','Apa nama jumlah awal?','["Principal","Fee","Due date"]'::jsonb,'["Pokok","Biaya","Jatuh tempo"]'::jsonb,'Principal','Principal is the original amount.','Pokok adalah jumlah asli.'),
    ('fz-income-vs-wealth','Income is usually measured over what?','Pendapatan biasanya diukur selama apa?','["A period of time","One fixed lifetime number","A password"]'::jsonb,'["Suatu periode waktu","Satu angka tetap seumur hidup","Kata sandi"]'::jsonb,'A period of time','Income is a flow.','Pendapatan adalah arus.'),
    ('fz-assets-vs-liabilities','Net wealth starts with what subtraction?','Kekayaan bersih dimulai dari pengurangan apa?','["Assets minus liabilities","Fees minus time","Income minus lunch"]'::jsonb,'["Aset dikurangi liabilitas","Biaya dikurangi waktu","Pendapatan dikurangi makan siang"]'::jsonb,'Assets minus liabilities','Owned items less obligations gives a snapshot.','Yang dimiliki dikurangi kewajiban memberi potret.'),
    ('fz-risk','What should you ask about a possible loss?','Apa yang perlu ditanyakan tentang kemungkinan rugi?','["Can I handle it?","Is it guaranteed?","Can I ignore it?"]'::jsonb,'["Sanggupkah saya menanggungnya?","Apakah dijamin?","Bisakah saya mengabaikannya?"]'::jsonb,'Can I handle it?','Ability to absorb loss matters.','Kemampuan menanggung rugi itu penting.'),
    ('fz-return','Can a return be negative?','Apakah imbal hasil bisa negatif?','["Yes","Never","Only on weekends"]'::jsonb,'["Ya","Tidak pernah","Hanya pada akhir pekan"]'::jsonb,'Yes','Return describes a change in value, up or down.','Imbal hasil menggambarkan perubahan nilai, naik atau turun.'),
    ('fz-saving-vs-investing','An emergency buffer is shown under which path?','Dana darurat ditunjukkan pada jalur mana?','["Saving","Investing","Guaranteed trading"]'::jsonb,'["Menabung","Berinvestasi","Trading terjamin"]'::jsonb,'Saving','The visual uses it as a saving example.','Visual memakainya sebagai contoh menabung.'),
    ('fz-emergency-fund','What makes a starter buffer useful?','Apa yang membuat penyangga awal berguna?','["A repeatable contribution","A secret promise","Ignoring essentials"]'::jsonb,'["Setoran berulang","Janji rahasia","Mengabaikan kebutuhan pokok"]'::jsonb,'A repeatable contribution','Small repeatable steps can build a buffer.','Langkah kecil berulang dapat membangun penyangga.'),
    ('fz-needs-vs-wants','Can context change a need-versus-want decision?','Dapatkah konteks mengubah keputusan kebutuhan versus keinginan?','["Yes","Never","Only for prices"]'::jsonb,'["Ya","Tidak pernah","Hanya untuk harga"]'::jsonb,'Yes','The same item can have different roles in different circumstances.','Barang yang sama dapat memiliki peran berbeda dalam keadaan berbeda.'),
    ('fz-debt','What should you inspect besides the instalment?','Apa yang perlu diperiksa selain cicilan?','["Total repayment","Only a promotion","A lucky number"]'::jsonb,'["Total pelunasan","Hanya promosi","Angka keberuntungan"]'::jsonb,'Total repayment','Interest and fees affect total cost.','Bunga dan biaya memengaruhi biaya total.'),
    ('fz-scam-red-flags','What is a safe response to a rushed offer?','Apa respons aman terhadap penawaran mendesak?','["Pause and check officially","Send an OTP","Pay immediately"]'::jsonb,'["Berhenti dan cek secara resmi","Kirim OTP","Bayar segera"]'::jsonb,'Pause and check officially','Independent verification protects your money and data.','Verifikasi mandiri melindungi uang dan data Anda.')
)
INSERT INTO public.lesson_recall_questions (lesson_id, question_en, question_id, options_en, options_id, correct_option, explanation_en, explanation_id, is_active)
SELECT lesson.id, recalls.question_en, recalls.question_id, choices.options_en, choices.options_id,
  choices.correct_option, recalls.explanation_en, recalls.explanation_id, TRUE
FROM recalls JOIN public.lessons lesson ON lesson.slug = recalls.slug
CROSS JOIN LATERAL (
  SELECT
    jsonb_agg(jsonb_build_object('id', format('option_%s', en.ordinality), 'label', en.label) ORDER BY en.ordinality) AS options_en,
    jsonb_agg(jsonb_build_object('id', format('option_%s', id.ordinality), 'label', id.label) ORDER BY id.ordinality) AS options_id,
    format('option_%s', correct.ordinality) AS correct_option
  FROM jsonb_array_elements_text(recalls.options_en) WITH ORDINALITY AS en(label, ordinality)
  JOIN jsonb_array_elements_text(recalls.options_id) WITH ORDINALITY AS id(label, ordinality)
    ON id.ordinality = en.ordinality
  JOIN LATERAL (
    SELECT match.ordinality
    FROM jsonb_array_elements_text(recalls.options_en) WITH ORDINALITY AS match(label, ordinality)
    WHERE match.label = recalls.correct_option
    LIMIT 1
  ) AS correct ON TRUE
  GROUP BY correct.ordinality
) AS choices
WHERE lesson.is_published = TRUE
ON CONFLICT (lesson_id) DO UPDATE SET
  question_en = EXCLUDED.question_en, question_id = EXCLUDED.question_id, options_en = EXCLUDED.options_en,
  options_id = EXCLUDED.options_id, correct_option = EXCLUDED.correct_option,
  explanation_en = EXCLUDED.explanation_en, explanation_id = EXCLUDED.explanation_id,
  is_active = TRUE, updated_at = NOW();

COMMIT;
