-- KO-225 group 1 continuation batch 14

update public.content_variants set body = $json${"type":"ordering","answer":["Prices of goods rise","The purchasing power of money decreases","Savings interest may be lower than inflation","The real value of savings decreases"],"options":["Prices of goods rise","The purchasing power of money decreases","Savings interest may be lower than inflation","The real value of savings decreases"],"question":"Sequence the process of the influence of inflation on savings.","difficulty":"beginner","parameters":{},"explanation":"Inflation raises prices, reduces purchasing power, and can reduce the real value of savings if interest is low."}$json$::jsonb where id = '8a2ebd4e-fd31-4a76-b679-f8ae7234c8b2';
update public.content_variants set body = $json${"type":"case_study","answer":"Bayu makes decisions based on emotion, not analysis.","caseText":"Bayu saw all his friends buying GOTO shares because they went viral on TikTok. He is afraid of missing out on profits, but also afraid of losing money. He doesn't understand the company's business yet.","followUp":{"answer":"FOMO and loss aversion","options":["FOMO and loss aversion","No bias","Purely rational decision","Over-diversification"],"question":"What bias is dominant in Bayu?","explanation":"Bayu is consumed by trends (FOMO) and afraid of loss (loss aversion), which clouds research."},"question":"Read the following cases and choose the best response.","difficulty":"advanced","explanation":"Behavioral biases can ruin financial plans. Bayu should return to his goals and research before buying shares."}$json$::jsonb where id = '8a90d924-9613-4c7e-805f-94ff739d5290';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Budi","options":["Budi","Andy","Same rich","Can't compare"],"question":"Andi's salary is IDR 8 million, savings are zero. Budi's salary is IDR 4 million, savings IDR 15 million. Who is richer?","difficulty":"beginner","explanation":"Wealth is measured by net assets owned, not by salary."}$json$::jsonb where id = '8fa48ba3-ad69-441c-8d45-c2653dd4eafe';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Stock mutual funds compared to savings","options":["Stock mutual funds compared to savings","100% Savings","Storing cash","Online loans"],"question":"For the goals for the next 5 years, which is more appropriate?","difficulty":"intermediate","explanation":"In the medium to long term, investments such as stock mutual funds have more potential to beat inflation."}$json$::jsonb where id = '93c1fab6-6862-4230-9f4a-4a5176ed0063';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because the price of imported goods rises","options":["Because bank interest is rising","Because the price of imported goods rises","Because salaries go up","Because savings increase"],"question":"Why does a weakening rupiah trigger inflation?","difficulty":"intermediate","parameters":{},"explanation":"The weakening rupiah makes imported goods such as oil and medicine more expensive."}$json$::jsonb where id = '9416b819-47d0-4a3f-970a-a71a256a2446';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Become a small part owner of the company","options":["Become a small part owner of the company","Lending money to companies","Become a company employee","Receive a fixed salary from the company"],"question":"What does it mean to buy company shares?","difficulty":"intermediate","explanation":"Shares are proof of partial ownership of a company."}$json$::jsonb where id = '9547388d-b2da-4644-bd7c-7999be4b3d9f';
update public.content_variants set body = $json${"type":"fill_blank","answer":"tax","question":"Income from dividends and deposit interest can be subject to _____ according to the provisions.","difficulty":"advanced","explanation":"The government imposes taxes on several types of investment returns."}$json$::jsonb where id = '9736c4e3-1315-416f-9075-98accd997ccc';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Bank savings","options":["Bank savings","Individual shares","Crypto","Stock mutual funds"],"question":"Bayu needs IDR 2 million next month for tuition fees. The best place to store it is...","difficulty":"intermediate","explanation":"Money that is immediately needed must be safe and liquid, such as bank savings."}$json$::jsonb where id = '9a6f7929-23e5-4ead-9504-5fe9cdcb6f63';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Because interest is calculated from previous interest over a longer period of time","options":["Because interest is calculated from previous interest over a longer period of time","Because banks give bonuses for beginners","Because the interest remains the same every year","Because the initial money is always bigger"],"question":"Why does saving early earn you more with compound interest?","difficulty":"intermediate","explanation":"Time allows flowers to accumulate and produce new flowers, so growth accelerates."}$json$::jsonb where id = '9be07756-e5d4-4c6c-a720-68726f9e332a';
update public.content_variants set body = $json${"type":"true_false","answer":false,"question":"Buying 1 lot of BBCA shares means buying 10 shares.","difficulty":"beginner","parameters":{},"explanation":"1 lot of shares on IDX is equal to 100 shares."}$json$::jsonb where id = '9c7b568e-c3a3-4ee2-85e9-d2e8357a138d';

