-- KO-225 group 1 continuation batch 13

update public.content_variants set body = $json${"type":"multiple_choice","answer":"Stable instruments such as deposits or money markets","options":["Individual stocks are speculative","Stable instruments such as deposits or money markets","Crypto with high volatility","Not saving at all"],"question":"Investors who need money for a down payment on a house within 2 years should choose?","difficulty":"intermediate","parameters":{},"explanation":"For short-term goals, choose stable instruments so that the value is not eroded by the market."}$json$::jsonb where id = '7d470952-0eed-4014-9300-9f3a9fc09831';
update public.content_variants set body = $json${"type":"word_bank","answer":["Exchange","100"],"options":["Exchange","100"],"question":"Complete the following sentence with words from the word bank: \"Shares are traded at _____ Indonesian Securities, and 1 lot is equal to _____ shares.\"","difficulty":"beginner","parameters":{},"explanation":"Shares are traded on the Indonesian Stock Exchange, with 1 lot equivalent to 100 shares."}$json$::jsonb where id = '7e07fc74-99e9-457c-be4c-5dda6571214a';
update public.content_variants set body = $json${"type":"fill_blank","answer":"yield","question":"Compound interest means we get a return on the initial capital and from the previous _____.","difficulty":"intermediate","parameters":{},"explanation":"Compound interest produces accelerated growth because returns are calculated from the capital and returns already obtained."}$json$::jsonb where id = '81fbd35d-d86f-4a48-a401-0d826bd00984';
update public.content_variants set body = $json${"type":"fill_blank","answer":"closed","question":"The closing price of a stock is called _____.","difficulty":"intermediate","explanation":"Close is the last price the stock traded on that day."}$json$::jsonb where id = '8340025f-62e4-419c-ba73-5dffd40017d4';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Reduce the impact of losing one asset","options":["Reduce the impact of losing one asset","Guaranteed profits every year","Eliminates risk completely","Makes investing more complicated"],"question":"Which are the benefits of diversification?","difficulty":"intermediate","explanation":"Diversification spreads risk, but does not eliminate risk or guarantee profits."}$json$::jsonb where id = '838c46b9-b443-42bf-95af-66ee4f1e44a6';
update public.content_variants set body = $json${"type":"fill_blank","answer":"OJK permission","question":"If an offer is too good to be true, it's best to check _____ before spending any money.","difficulty":"beginner","explanation":"The Financial Services Authority oversees legal financial products in Indonesia."}$json$::jsonb where id = '839e3ffe-8295-4a56-99a4-b76172ff4119';
update public.content_variants set body = $json${"type":"fill_blank","answer":"need","question":"Lunch at the canteen is considered _____, while eating at an expensive cafe every day is considered desirable.","difficulty":"beginner","explanation":"Eating to survive and studying is a necessity, but choosing a luxurious place is a desire."}$json$::jsonb where id = '849b6a1e-03f5-49a1-9053-765c4a8c4add';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Internet credit and quota for assignments","options":["Internet credit and quota for assignments","Concert tickets","Latest game skins","Fresh coffee every day"],"question":"Which are included as needs for students?","difficulty":"beginner","explanation":"Credit and quota support learning activities, so they are a necessity."}$json$::jsonb where id = '84c3fd61-70a6-4d75-8926-e15953128dfa';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Losing the opportunity to use or save money during the waiting period","options":["Losing the opportunity to use or save money during the waiting period","The nominal amount is reduced automatically","Money is lost forever","The bank asks for an administration fee"],"question":"The opportunity cost of waiting for payment is...","difficulty":"beginner","explanation":"While waiting, the money cannot be used for needs or earn interest."}$json$::jsonb where id = '853ff6ac-d128-44a0-a6c2-f4b87163de33';
update public.content_variants set body = $json${"type":"matching","pairs":[["Income","Salary IDR 4 million per month"],["Riches","Savings IDR 15 million minus debt IDR 2 million"],["Expenditure","Pay boarding house IDR 800 thousand per month"]],"answer":{"Kekayaan":"Savings IDR 15 million minus debt IDR 2 million","Pendapatan":"Salary IDR 4 million per month","Pengeluaran":"Pay boarding house IDR 800 thousand per month"},"question":"Match the concept with the example.","difficulty":"beginner","explanation":"Distinguishing between money flow (income/expenses) and stock of holdings (wealth) helps us assess financial health."}$json$::jsonb where id = '86fcdf8a-3dc8-462a-8ed3-9f04d1bc9b2c';

