-- KO-225 group 5 continuation batch 20

update public.content_variants set body = $json${"text":"Bank savings offer low interest of around 2-4% per year, but the money is relatively safe. Equity mutual funds have the potential for higher returns, but their value may fall in the short term. This is a risk and return relationship."}$json$::jsonb where id = 'c64cb7dc-bd8b-4d9a-9f07-a6b83eac5fc7';
update public.content_variants set body = $json${"text":"Dina saw a flash sale on Shopee: buy 2 get 1 free skincare. He is interested even though his skincare hasn't run out yet and it's not a necessity. If he buys, he is spending money on unplanned items."}$json$::jsonb where id = 'c6e83d79-a1d5-441c-a83d-b4df525a5c1f';
update public.content_variants set body_id = $json${"type":"matching","answer":{"Advanced Investor":"Menggunakan derivatif, mengelola risiko","Beginner Investor":"Mempelajari dasar-dasar, menggunakan deposito","Intermediate Investor":"Memahami rasio, melakukan diversifikasi"},"options":{"left":["Investor Pemula","Investor Menengah","Investor Tingkat Lanjut"],"right":["Mempelajari dasar-dasar, menggunakan deposito","Memahami rasio, melakukan diversifikasi","Menggunakan derivatif, mengelola risiko"]},"question":"Cocokkan setiap level investor dengan karakteristiknya:","difficulty":"beginner","parameters":{},"explanation":"Kecocokan yang benar: Investor Pemula → Mempelajari dasar-dasar, menggunakan deposito, Investor Menengah → Memahami rasio, melakukan diversifikasi, Investor Tingkat Lanjut → Menggunakan derivatif, mengelola risiko"}$json$::jsonb where id = 'c6e95f1a-2ca8-4dd8-b945-283132c9320f';
update public.content_variants set body_id = $json${"type":"calculation","answer":"8%","question":"Anda memiliki Rp 50 juta untuk berinvestasi. Anda mengalokasikan 60% untuk saham (pengembalian yang diharapkan 10%) dan 40% untuk obligasi (pengembalian yang diharapkan 5%). Berapa return portofolio yang diharapkan?","difficulty":"advanced","parameters":{"hint":"Multiply each allocation by its return and sum the results."},"explanation":"Pengembalian tertimbang = (0,60 × 10%) + (0,40 × 5%) = 6% + 2% = 8%."}$json$::jsonb where id = 'c7f0c249-295f-4593-8aad-b6be8b6dc392';
update public.content_variants set body_id = $json${"type":"calculation","answer":"9","question":"Dengan menggunakan Aturan 72, berapa tahun yang diperlukan untuk melipatgandakan uang dengan pengembalian tahunan 8%?","difficulty":"intermediate","parameters":{"hint":"Divide 72 by the annual return percentage."},"explanation":"Aturan 72: Tahun berlipat ganda = 72 / tingkat bunga. 72/8 = 9 tahun."}$json$::jsonb where id = 'c83ff655-ef56-4d60-9996-de4c1186ad18';
update public.content_variants set body_id = $json${"type":"scenario","answer":"Minimalkan risiko","options":["Maksimalkan pengembalian","Minimalkan risiko","Seimbangkan risiko dan keuntungan","Ikuti orang banyak"],"question":"Kata orang tuamu, mereka membeli rumah seharga Rp 50 juta pada tahun 2000. Berapa harga rumah saat ini jika inflasi rata-rata 5%? Pilihan mana yang meminimalkan risiko sekaligus menjaga peluang?","difficulty":"beginner","parameters":{"scenario_text":"Your parents say they bought a house for Rp 50M in 2000. What would it cost today with 5% average inflation?"},"explanation":"Dalam skenario ini, meminimalkan risiko merupakan pendekatan yang paling seimbang dan terinformasi dalam pengambilan keputusan keuangan."}$json$::jsonb where id = 'c88ff84e-c976-4131-bc3a-6ee28ff8c364';
update public.content_variants set body_id = $json${"type":"matching","answer":{"Advanced Investor":"Menggunakan derivatif, mengelola risiko","Beginner Investor":"Mempelajari dasar-dasar, menggunakan deposito","Intermediate Investor":"Memahami rasio, melakukan diversifikasi"},"options":{"left":["Investor Pemula","Investor Menengah","Investor Tingkat Lanjut"],"right":["Mempelajari dasar-dasar, menggunakan deposito","Memahami rasio, melakukan diversifikasi","Menggunakan derivatif, mengelola risiko"]},"question":"Cocokkan setiap level investor dengan karakteristiknya:","difficulty":"beginner","parameters":{},"explanation":"Kecocokan yang benar: Investor Pemula → Mempelajari dasar-dasar, menggunakan deposito, Investor Menengah → Memahami rasio, melakukan diversifikasi, Investor Tingkat Lanjut → Menggunakan derivatif, mengelola risiko"}$json$::jsonb where id = 'c894ce04-0428-4b7c-b921-414b87336579';
update public.content_variants set body = $json${"text":"On IDX, stock transactions occur during stock exchange hours 09.00–15.00 WIB. Stock prices change every second according to demand and supply from investors.","source_ids":["c7c57d03-733f-4fe8-bd15-ce3a1cd4a760"]}$json$::jsonb where id = 'c9a41524-020c-4bcd-bc3e-6e8522639983';
update public.content_variants set body_id = $json${"type":"matching","answer":{"Sentiment Analysis":"Suasana hati dan emosi pasar","Technical Analysis":"Bagan dan pola","Fundamental Analysis":"Laporan keuangan","Quantitative Analysis":"Model matematika"},"options":{"left":["Analisis Teknis","Analisis Mendasar","Analisis Kuantitatif","Analisis Sentimen"],"right":["Bagan dan pola","Laporan keuangan","Model matematika","Suasana hati dan emosi pasar"]},"question":"Cocokkan setiap pendekatan analisis dengan fokusnya:","difficulty":"beginner","parameters":{},"explanation":"Kecocokan yang benar: Analisis Teknikal → Grafik dan pola, Analisis Fundamental → Laporan keuangan, Analisis Kuantitatif → Model matematika, Analisis Sentimen → Suasana hati dan emosi pasar"}$json$::jsonb where id = 'c9c656c2-44b6-4334-9716-2d39eb4dff96';
update public.content_variants set body = $json${"text":"Shares are proof of partial ownership of a company. Stock prices change due to demand and supply in the market."}$json$::jsonb where id = 'ca2c3c53-14f6-44c0-9c1f-930ebfe2f05c';

