-- KO-225 group 1 translation batch 11

update public.content_variants set body = $json${"type":"multiple_choice","answer":"IDR 700,000","options":["IDR 350,000","IDR 700,000","IDR 3,500,000","IDR 7,000,000"],"question":"If the TLKM share price is IDR 3,500 per share, how much does it cost to buy 2 lots?","difficulty":"beginner","parameters":{},"explanation":"2 lots = 200 shares. 200 × IDR 3,500 = IDR 700,000."}$json$::jsonb where id = '63380433-e391-450d-8c88-ad96a740dee3';
update public.content_variants set body = $json${"type":"ordering","answer":["Set goals","Prepare an emergency fund","Pay off high-interest debt","Choose investment instruments according to your goals"],"options":["Set goals","Prepare an emergency fund","Pay off high-interest debt","Choose investment instruments according to your goals"],"question":"Sequence the steps to create a basic financial plan.","difficulty":"advanced","explanation":"Start with your goals, protect them with emergency funds, free yourself from high-interest debt, then invest."}$json$::jsonb where id = '639c01b7-9667-4624-8aad-4c3daf4b570f';
update public.content_variants set body = $json${"type":"multiple_choice","answer":"Decrease in the purchasing power of money for goods and services","options":["Increase in money supply","Decrease in the purchasing power of money for goods and services","Increase in the rupiah exchange rate","General reduction in prices of goods"],"question":"What is meant by inflation?","difficulty":"beginner","parameters":{},"explanation":"Inflation is a general increase in the prices of goods and services that reduces the purchasing power of money."}$json$::jsonb where id = '64f0d2d9-1559-4469-9234-75cb9a6dab79';
update public.content_variants set body = $json${"type":"fill_blank","answer":"flower","question":"The money received now is more valuable because it can produce _____ if saved or invested.","difficulty":"beginner","explanation":"Interest is a reward for holding money, so that money now can grow even more in the future."}$json$::jsonb where id = '65a3eccb-6d57-4170-b943-d7b72b859c18';
update public.content_variants set body = $json${"type":"ordering","answer":["Record income","Divide expenses into categories","Set savings goals","End of month evaluation"],"options":["Set savings goals","Record income","End of month evaluation","Divide expenses into categories"],"question":"Sequence the steps to create a simple budget:","difficulty":"beginner","parameters":{},"explanation":"Record income, divide expenses, set savings goals, then evaluate."}$json$::jsonb where id = '65f19304-4b5e-4fe8-a1bf-41f827ab1683';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Compound interest makes money grow faster over time.","difficulty":"intermediate","explanation":"Interest is calculated on the balance that continues to increase, so growth is faster."}$json$::jsonb where id = '66a35cd7-db19-4bb2-a18c-f4e7b881ab8e';
update public.content_variants set body = $json${"type":"case_study","answer":"The first priority is basic protection and stopping the debt spiral.","caseText":"Ani, 19 years old, income IDR 2.5 million/month, no emergency fund, PayLater debt IDR 2 million.","followUp":{"answer":"Create a small emergency fund and cut out new purchases","options":["Create a small emergency fund and cut out new purchases","Direct investment in shares","Buy a new gadget for work","Apply for a new loan to pay off PayLater"],"question":"What is the most important first step?","explanation":"A small emergency fund prevents additional debt; stopping new purchases stops the debt spiral."},"question":"Read the following cases and choose the best sequence of steps.","difficulty":"advanced","explanation":"A financial plan starts from the foundation: emergency fund, debt, budget, protection, then investment."}$json$::jsonb where id = '689144f6-9f59-42bf-bcd5-fdb0ffa87f6b';
update public.content_variants set body = $json${"type":"true_false","answer":true,"question":"Bank savings are very low risk, so the interest is usually low.","difficulty":"intermediate","explanation":"Low risk is generally offset by low returns."}$json$::jsonb where id = '6a0ac6c3-d54a-4353-acf9-784cd1610ed2';
update public.content_variants set body = $json${"type":"fill_blank","answer":"debt","question":"Net worth is calculated from total assets minus total _____.","difficulty":"beginner","explanation":"Net worth = assets - debts. This shows how much treasure we really have."}$json$::jsonb where id = '6d8c020e-5b0b-4713-95c5-89dd53ddec9c';
update public.content_variants set body = $json${"type":"fill_blank","answer":"registration","question":"If the main profits come from fees _____ new members, the business is most likely a pyramid scheme.","difficulty":"beginner","explanation":"The pyramid relies on incoming money from new members to pay old members."}$json$::jsonb where id = '6dbae953-e5b8-40d1-9717-1436ed6b3849';

