-- KO-225 group 5 continuation batch 11

update public.content_variants set body = $json${"text":"Raka evaluates his subscriptions every 3 months: streaming, music, cloud, gym. He canceled two subscriptions that he rarely used and saved IDR 150,000 per month.","source_ids":["53eef1ac-2553-48d9-92a0-af6159d7d369"]}$json$::jsonb where id = '8c6d70a1-42be-4da9-a592-040626908bf7';
update public.content_variants set body = $json${"text":"Rina waits for the end of the month to set aside the remaining pocket money. However, at the end of every month the money always runs out for snacks and streaming. He switched to setting aside Rp. 200,000 at the beginning of the month, and apparently was able to adjust his spending."}$json$::jsonb where id = '8cecd791-b370-4bb8-b78d-8be968fdf07f';
update public.content_variants set body = $json${"text":"A budget is not a prohibition on spending money, but a spending plan. With a budget, we know where the money goes and can adjust it if there are important goals."}$json$::jsonb where id = '8e0c5c79-e511-4725-a91a-43b912b10a89';
update public.content_variants set body_id = $json${"type":"word_bank","answer":["bullish","kasar"],"options":["bullish","kasar","ke samping","tidak stabil"],"question":"Ketika investor ________, mereka memperkirakan harga akan naik; ketika ________, mereka mengharapkan penurunan.","difficulty":"intermediate","parameters":{},"explanation":"Kata-kata yang benar dari pihak bank adalah: bullish, bearish."}$json$::jsonb where id = '8ff715a0-85c8-46b4-9ffb-4ae7cf33c83e';
update public.content_variants set body = $json${"text":"Diversification is spreading money across various assets so that a loss in one asset does not have too big an impact on the whole."}$json$::jsonb where id = '92508623-cac8-48fe-b94f-e161fb0a5dcc';
update public.content_variants set body = $json${"text":"GOTO shares and BBCA shares have different characters. GOTO is a technology company that is still developing with high volatility. BBCA is a large bank with a history of more stable profits.","source_ids":["58e3fb2d-7dbc-4a08-ab1a-379af3fa5c38"]}$json$::jsonb where id = '94faa86c-1169-4fe7-8a40-00037b7e1098';
update public.content_variants set body = $json${"text":"If the offer is too good to be true, stop and check for OJK clearance. No investment produces big profits without risk."}$json$::jsonb where id = '96bd67e3-a4fe-4c20-ba09-44fa5ef396b7';
update public.content_variants set body = $json${"text":"When the rupiah exchange rate weakens against the US dollar, the price of imported gadgets such as smartphones or laptops can rise. High inflation causes the prices of chicken noodles and gasoline to rise. These two indicators affect purchasing power."}$json$::jsonb where id = '96fc07ba-5230-4650-9673-7b8817856b52';
update public.content_variants set body = $json${"text":"Rina works as an intern with a salary of IDR 2,500,000. He sets aside IDR 300,000 per month into a separate account. After a year, he had IDR 3,600,000 that he could use if he got sick or lost his job."}$json$::jsonb where id = '98bd93b2-dfe3-4845-b8fc-667d6c4faeb0';
update public.content_variants set body = $json${"text":"If Rina's goal is to buy a laptop in 1 year, most of the funds must be safe. If his goal is to retire in 30 years, he can add shares and stock mutual funds."}$json$::jsonb where id = '9cef2e89-e351-4b5a-98bd-bfe990f2b15e';

